libfoedus-core: foedus::thread::ThreadGroupRef Class Reference
foedus::thread::ThreadGroupRef Class Reference final
FOEDUS Components » Thread and Thread-Group
A view of Thread group object for other SOCs and master engine.
Detailed Description
A view of Thread group object for other SOCs and master engine.
Definition at line 106 of file thread_ref.hpp.
#include <thread_ref.hpp>
Public Member Functions
ThreadGroupRef ()
ThreadGroupRef (Engine *engine, ThreadGroupId group_id)
Engine * get_engine () const
ThreadGroupId get_group_id () const
ThreadRef * get_thread (ThreadLocalOrdinal ordinal)
Returns Thread object for the given ordinal in this group.
ThreadRef get_thread_ref (ThreadLocalOrdinal ordinal) const
Returns a copied instance.
Epoch get_min_in_commit_epoch () const
Returns the oldest in-commit epoch of the threads in this group.
Friends
std::ostream & operator<< (std::ostream &o, const ThreadGroupRef &v)
Constructor & Destructor Documentation
foedus::thread::ThreadGroupRef::ThreadGroupRef ()
Definition at line 103 of file thread_ref.cpp.
                                : engine_(nullptr), group_id_(0) {
 }
foedus::thread::ThreadGroupRef::ThreadGroupRef (Engine * engine, ThreadGroupId group_id)
Definition at line 106 of file thread_ref.cpp.
References foedus::thread::compose_thread_id(), foedus::Engine::get_options(), foedus::EngineOptions::thread_, and foedus::thread::ThreadOptions::thread_count_per_group_.
   : engine_(engine), group_id_(group_id) {
   uint16_t count = engine->get_options().thread_.thread_count_per_group_;
   for (uint16_t i = 0; i < count; ++i) {
     threads_.emplace_back(ThreadRef(engine, compose_thread_id(group_id, i)));
   }
 }
Member Function Documentation
Engine* foedus::thread::ThreadGroupRef::get_engine () const inline
Definition at line 111 of file thread_ref.hpp.
 { return engine_; }
ThreadGroupId foedus::thread::ThreadGroupRef::get_group_id () const inline
Definition at line 112 of file thread_ref.hpp.
Referenced by foedus::thread::operator<<().
 { return group_id_; }
Epoch foedus::thread::ThreadGroupRef::get_min_in_commit_epoch () const
Returns the oldest in-commit epoch of the threads in this group.
Empty in-commit epoch is skipped. If all of them are empty, returns an invalid epoch (meaning all of them will get the latest current epoch and are safe).
See also
foedus::xct::InCommitEpochGuard
Definition at line 132 of file thread_ref.cpp.
References foedus::INVALID_EPOCH, foedus::Epoch::is_valid(), foedus::assorted::memory_fence_acquire(), and foedus::Epoch::store_min().
Referenced by foedus::xct::XctManagerPimpl::handle_epoch_chime_wait_grace_period().
{
   assorted::memory_fence_acquire();
   Epoch ret = INVALID_EPOCH;
   for (const auto& t : threads_) {
     Epoch in_commit_epoch = t.get_control_block()->in_commit_epoch_;
     if (in_commit_epoch.is_valid()) {
       if (!ret.is_valid()) {
         ret = in_commit_epoch;
       } else {
         ret.store_min(in_commit_epoch);
       }
     }
   }
   return ret;
 }
ThreadRef* foedus::thread::ThreadGroupRef::get_thread (ThreadLocalOrdinal ordinal) inline
Returns Thread object for the given ordinal in this group.
Definition at line 115 of file thread_ref.hpp.
Referenced by foedus::thread::ThreadPoolPimpl::get_thread(), and foedus::thread::ThreadPoolPimpl::impersonate_on_numa_node().
 { return &threads_[ordinal]; }
ThreadRef foedus::thread::ThreadGroupRef::get_thread_ref (ThreadLocalOrdinal ordinal) const inline
Returns a copied instance.
ThreadRef itself is a reference object, so it's cheap.
Definition at line 117 of file thread_ref.hpp.
 { return threads_[ordinal]; }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const ThreadGroupRef & v) friend
Definition at line 160 of file thread_ref.cpp.
{
   o << "<ThreadGroupRef>";
   o << "<group_id_>" << static_cast<int>(v.get_group_id()) << "</group_id_>";
   o << "<threads_>";
   for (const ThreadRef& child_thread : v.threads_) {
     o << child_thread;
   }
   o << "</threads_>";
   o << "</ThreadGroup>";
   return o;
 }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/thread/thread_ref.hpp
/home/shino/foedus_code/foedus-core/src/foedus/thread/thread_ref.cpp