libfoedus-core: foedus::proc::ProcManagerPimpl Class Reference
foedus::proc::ProcManagerPimpl Class Reference final
FOEDUS Components » System and User Procedures
Pimpl object of ProcManager.
Detailed Description
Pimpl object of ProcManager.
A private pimpl object for ProcManager. Do not include this header from a client program unless you know what you are doing.
Definition at line 65 of file proc_manager_pimpl.hpp.
#include <proc_manager_pimpl.hpp>
Classes
struct SharedData
All shared data in this module.
Public Member Functions
ProcManagerPimpl ()=delete
ProcManagerPimpl (Engine *engine)
ErrorStack initialize_once () override
ErrorStack uninitialize_once () override
std::string describe_registered_procs () const
ErrorStack get_proc (const ProcName &name, Proc *out)
ErrorStack pre_register (const ProcAndName &proc_and_name)
ErrorStack local_register (const ProcAndName &proc_and_name)
ErrorStack emulated_register (const ProcAndName &proc_and_name)
SharedData * get_local_data ()
const SharedData * get_local_data () const
Public Member Functions inherited from foedus::DefaultInitializable
DefaultInitializable ()
virtual ~DefaultInitializable ()
DefaultInitializable (const DefaultInitializable &)=delete
DefaultInitializable & operator= (const DefaultInitializable &)=delete
ErrorStack initialize () override final
Typical implementation of Initializable::initialize() that provides initialize-once semantics.
ErrorStack uninitialize () override final
Typical implementation of Initializable::uninitialize() that provides uninitialize-once semantics.
bool is_initialized () const override final
Returns whether the object has been already initialized or not.
Public Member Functions inherited from foedus::Initializable
virtual ~Initializable ()
Static Public Member Functions
static LocalProcId find_by_name (const ProcName &name, SharedData *shared_data)
static LocalProcId insert (const ProcAndName &proc_and_name, SharedData *shared_data)
Public Attributes
Engine *const engine_
std::vector< ProcAndName > pre_registered_procs_
std::vector< SharedData > all_soc_procs_
Shared data of all SOCs.
Constructor & Destructor Documentation
foedus::proc::ProcManagerPimpl::ProcManagerPimpl () delete
foedus::proc::ProcManagerPimpl::ProcManagerPimpl (Engine * engine) inline explicit
Definition at line 78 of file proc_manager_pimpl.hpp.
 : engine_(engine) {}
Member Function Documentation
std::string foedus::proc::ProcManagerPimpl::describe_registered_procs () const
Definition at line 172 of file proc_manager_pimpl.cpp.
References foedus::proc::ProcManagerPimpl::SharedData::control_block_, foedus::proc::ProcManagerControlBlock::count_, engine_, get_local_data(), foedus::Engine::is_master(), and foedus::proc::ProcManagerPimpl::SharedData::procs_.
Referenced by foedus::proc::ProcManager::describe_registered_procs().
{
   if (engine_->is_master()) {
     return "<Master engine has no proc>";
   }
   std::stringstream str;
   const SharedData* data = get_local_data();
   str << "Proc Count=" << data->control_block_->count_ << ", (name,address)=[";
   for (LocalProcId i = 0; i < data->control_block_->count_; ++i) {
     if (i > 0) {
       str << ",";
     }
     str << "(" << data->procs_[i].first << "," << data->procs_[i].second << ")";
   }
   str << "]";
   return str.str();
 }
ErrorStack foedus::proc::ProcManagerPimpl::emulated_register (const ProcAndName & proc_and_name)
Definition at line 129 of file proc_manager_pimpl.cpp.
References engine_, ERROR_STACK, foedus::get_error_message(), foedus::Engine::get_options(), foedus::DefaultInitializable::is_initialized(), foedus::kChildEmulated, foedus::kErrorCodeProcRegisterTooEarly, foedus::kErrorCodeProcRegisterUnsupportedSocType, foedus::kRetOk, foedus::EngineOptions::soc_, and foedus::soc::SocOptions::soc_type_.
Referenced by foedus::proc::ProcManager::emulated_register().
{
   if (!is_initialized()) {
     LOG(ERROR) << "Incorrect use of emulated_register(): "
       << get_error_message(kErrorCodeProcRegisterTooEarly);
     return ERROR_STACK(kErrorCodeProcRegisterTooEarly);
   }
   EngineType soc_type = engine_->get_options().soc_.soc_type_;
   if (soc_type != kChildEmulated) {
     LOG(ERROR) << "Incorrect use of emulated_register(): "
       << get_error_message(kErrorCodeProcRegisterUnsupportedSocType);
     return ERROR_STACK(kErrorCodeProcRegisterUnsupportedSocType);
   }
   LOG(INFO) << "emulated-registered a user procedure: " << proc_and_name.first;
   return kRetOk;
 }
LocalProcId foedus::proc::ProcManagerPimpl::find_by_name (const ProcName & name, SharedData * shared_data) static
Definition at line 146 of file proc_manager_pimpl.cpp.
References foedus::proc::ProcManagerPimpl::SharedData::control_block_, foedus::proc::ProcManagerControlBlock::count_, foedus::proc::kLocalProcInvalid, foedus::assorted::memory_fence_acquire(), and foedus::proc::ProcManagerPimpl::SharedData::procs_.
Referenced by get_proc(), and insert().
{
   // so far just a seqnetial search.
   LocalProcId count = shared_data->control_block_->count_;
   assorted::memory_fence_acquire();
   for (LocalProcId i = 0; i < count; ++i) {
     if (shared_data->procs_[i].first == name) {
       return i;
     }
   }
   return kLocalProcInvalid;
 }
ProcManagerPimpl::SharedData * foedus::proc::ProcManagerPimpl::get_local_data ()
Definition at line 80 of file proc_manager_pimpl.cpp.
References all_soc_procs_, ASSERT_ND, engine_, foedus::Engine::get_soc_id(), and foedus::Engine::is_master().
Referenced by describe_registered_procs(), initialize_once(), local_register(), and uninitialize_once().
{
   ASSERT_ND(!engine_->is_master());
   return &all_soc_procs_[engine_->get_soc_id()];
 }
const ProcManagerPimpl::SharedData * foedus::proc::ProcManagerPimpl::get_local_data () const
Definition at line 84 of file proc_manager_pimpl.cpp.
References all_soc_procs_, ASSERT_ND, engine_, foedus::Engine::get_soc_id(), and foedus::Engine::is_master().
{
   ASSERT_ND(!engine_->is_master());
   return &all_soc_procs_[engine_->get_soc_id()];
 }
ErrorStack foedus::proc::ProcManagerPimpl::get_proc (const ProcName & name, Proc * out)
Definition at line 71 of file proc_manager_pimpl.cpp.
References all_soc_procs_, foedus::assorted::FixedString< MAXLEN, CHAR >::c_str(), engine_, ERROR_STACK_MSG, find_by_name(), foedus::Engine::get_soc_id(), foedus::kErrorCodeProcNotFound, foedus::proc::kLocalProcInvalid, and foedus::kRetOk.
Referenced by foedus::proc::ProcManager::get_proc().
{
   soc::SocId node = engine_->get_soc_id();
   LocalProcId id = find_by_name(name, &all_soc_procs_[node]);
   if (id == kLocalProcInvalid) {
     return ERROR_STACK_MSG(kErrorCodeProcNotFound, name.c_str());
   }
   *out = all_soc_procs_[node].procs_[id].second;
   return kRetOk;
 }
ErrorStack foedus::proc::ProcManagerPimpl::initialize_once () override virtual
Implements foedus::DefaultInitializable.
Definition at line 35 of file proc_manager_pimpl.cpp.
References all_soc_procs_, foedus::proc::ProcManagerPimpl::SharedData::control_block_, foedus::Engine::describe_short(), engine_, get_local_data(), foedus::soc::SharedMemoryRepo::get_node_memory_anchors(), foedus::Engine::get_options(), foedus::soc::SocManager::get_shared_memory_repo(), foedus::Engine::get_soc_manager(), foedus::thread::ThreadOptions::group_count_, foedus::proc::ProcManagerControlBlock::initialize(), foedus::Engine::is_master(), foedus::kRetOk, foedus::proc::ProcManagerPimpl::SharedData::name_sort_, foedus::soc::NodeMemoryAnchors::proc_manager_memory_, foedus::soc::NodeMemoryAnchors::proc_memory_, foedus::soc::NodeMemoryAnchors::proc_name_sort_memory_, foedus::proc::ProcManagerPimpl::SharedData::procs_, and foedus::EngineOptions::thread_.
{
   // attach shared memories of all SOCs
   all_soc_procs_.clear();
   soc::SocId soc_count = engine_->get_options().thread_.group_count_;
   soc::SharedMemoryRepo* memory_repo = engine_->get_soc_manager()->get_shared_memory_repo();
   for (soc::SocId node = 0; node < soc_count; ++node) {
     soc::NodeMemoryAnchors* anchors = memory_repo->get_node_memory_anchors(node);
     SharedData data;
     data.control_block_ = anchors->proc_manager_memory_;
     data.name_sort_ = anchors->proc_name_sort_memory_;
     data.procs_ = anchors->proc_memory_;
     all_soc_procs_.push_back(data);
   }
   if (!engine_->is_master()) {
     LOG(INFO) << "Initializing ProcManager(" << engine_->describe_short() << ")..";
     get_local_data()->control_block_->initialize();
   }
   // TODO(Hideaki) load shared libraries
   return kRetOk;
 }
LocalProcId foedus::proc::ProcManagerPimpl::insert (const ProcAndName & proc_and_name, SharedData * shared_data) static
Definition at line 158 of file proc_manager_pimpl.cpp.
References foedus::proc::ProcManagerPimpl::SharedData::control_block_, foedus::proc::ProcManagerControlBlock::count_, find_by_name(), foedus::proc::kLocalProcInvalid, foedus::proc::ProcManagerControlBlock::lock_, and foedus::proc::ProcManagerPimpl::SharedData::procs_.
Referenced by local_register().
{
   soc::SharedMutexScope lock_scope(&shared_data->control_block_->lock_);
   LocalProcId found = find_by_name(proc_and_name.first, shared_data);
   // TASK(Hideaki) max_proc_count check.
   if (found != kLocalProcInvalid) {
     return kLocalProcInvalid;
   }
   LocalProcId new_id = shared_data->control_block_->count_;
   shared_data->procs_[new_id] = proc_and_name;
   ++shared_data->control_block_->count_;
   // TASK(Hideaki) insert-sort to name_sort
   return new_id;
 }
ErrorStack foedus::proc::ProcManagerPimpl::local_register (const ProcAndName & proc_and_name)
Definition at line 109 of file proc_manager_pimpl.cpp.
References engine_, ERROR_STACK, foedus::get_error_message(), get_local_data(), insert(), foedus::DefaultInitializable::is_initialized(), foedus::Engine::is_master(), foedus::kErrorCodeProcProcAlreadyExists, foedus::kErrorCodeProcRegisterChildOnly, foedus::kErrorCodeProcRegisterTooEarly, foedus::proc::kLocalProcInvalid, and foedus::kRetOk.
Referenced by foedus::proc::ProcManager::local_register().
{
   if (!is_initialized()) {
     LOG(ERROR) << "Incorrect use of local_register(): "
       << get_error_message(kErrorCodeProcRegisterTooEarly);
     return ERROR_STACK(kErrorCodeProcRegisterTooEarly);
   }
   if (engine_->is_master()) {
     LOG(ERROR) << "Incorrect use of local_register(): "
       << get_error_message(kErrorCodeProcRegisterChildOnly);
     return ERROR_STACK(kErrorCodeProcRegisterChildOnly);
   }
   LocalProcId result = insert(proc_and_name, get_local_data());
   if (result == kLocalProcInvalid) {
     LOG(ERROR) << "A procedure of this name is already registered in this engine: "
       << proc_and_name.first;
     return ERROR_STACK(kErrorCodeProcProcAlreadyExists);
   }
   LOG(INFO) << "local-registered a user procedure: " << proc_and_name.first;
   return kRetOk;
 }
ErrorStack foedus::proc::ProcManagerPimpl::pre_register (const ProcAndName & proc_and_name)
Definition at line 89 of file proc_manager_pimpl.cpp.
References engine_, ERROR_STACK, foedus::get_error_message(), foedus::Engine::get_options(), foedus::DefaultInitializable::is_initialized(), foedus::Engine::is_master(), foedus::kChildEmulated, foedus::kChildForked, foedus::kErrorCodeProcPreRegisterTooLate, foedus::kErrorCodeProcRegisterMasterOnly, foedus::kErrorCodeProcRegisterUnsupportedSocType, foedus::kRetOk, pre_registered_procs_, foedus::EngineOptions::soc_, and foedus::soc::SocOptions::soc_type_.
Referenced by foedus::proc::ProcManager::pre_register().
{
   if (is_initialized()) {
     LOG(ERROR) << "Incorrect use of pre_register(): "
       << get_error_message(kErrorCodeProcPreRegisterTooLate);
     return ERROR_STACK(kErrorCodeProcPreRegisterTooLate);
   }
   if (!engine_->is_master()) {
     LOG(ERROR) << "Incorrect use of pre_register(): "
       << get_error_message(kErrorCodeProcRegisterMasterOnly);
     return ERROR_STACK(kErrorCodeProcRegisterMasterOnly);
   }
   EngineType soc_type = engine_->get_options().soc_.soc_type_;
   if (soc_type != kChildEmulated && soc_type != kChildForked) {
     return ERROR_STACK(kErrorCodeProcRegisterUnsupportedSocType);
   }
   pre_registered_procs_.push_back(proc_and_name);
   // This is BEFORE the init, so we shouldn't use GLOG
   // LOG(INFO) << "pre-registered a user procedure: " << proc_and_name.first;
   return kRetOk;
 }
ErrorStack foedus::proc::ProcManagerPimpl::uninitialize_once () override virtual
Implements foedus::DefaultInitializable.
Definition at line 58 of file proc_manager_pimpl.cpp.
References all_soc_procs_, foedus::proc::ProcManagerPimpl::SharedData::control_block_, foedus::Engine::describe_short(), engine_, get_local_data(), foedus::Engine::is_master(), foedus::kRetOk, SUMMARIZE_ERROR_BATCH, and foedus::proc::ProcManagerControlBlock::uninitialize().
{
   ErrorStackBatch batch;
   // TODO(Hideaki) unload shared libraries
   if (!engine_->is_master()) {
     LOG(INFO) << "Uninitializing ProcManager(" << engine_->describe_short() << ")..";
     get_local_data()->control_block_->uninitialize();
     return kRetOk;
   }
   all_soc_procs_.clear();
   return SUMMARIZE_ERROR_BATCH(batch);
 }
Member Data Documentation
std::vector< SharedData > foedus::proc::ProcManagerPimpl::all_soc_procs_
Shared data of all SOCs.
Index is SOC ID.
Definition at line 99 of file proc_manager_pimpl.hpp.
Referenced by get_local_data(), get_proc(), initialize_once(), and uninitialize_once().
Engine* const foedus::proc::ProcManagerPimpl::engine_
Definition at line 94 of file proc_manager_pimpl.hpp.
Referenced by describe_registered_procs(), emulated_register(), get_local_data(), get_proc(), initialize_once(), local_register(), pre_register(), and uninitialize_once().
std::vector< ProcAndName > foedus::proc::ProcManagerPimpl::pre_registered_procs_
Definition at line 95 of file proc_manager_pimpl.hpp.
Referenced by foedus::proc::ProcManager::get_pre_registered_procedures(), and pre_register().
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/proc/proc_manager_pimpl.hpp
/home/shino/foedus_code/foedus-core/src/foedus/proc/proc_manager_pimpl.cpp