libfoedus-core: foedus::xct::McsOwnerlessLockScope Class Reference
foedus::xct::McsOwnerlessLockScope Class Reference
Detailed Description
Definition at line 1157 of file xct_id.hpp.
#include <xct_id.hpp>
Public Member Functions
McsOwnerlessLockScope ()
McsOwnerlessLockScope (McsWwLock *lock, bool acquire_now=true, bool non_racy_acquire=false)
~McsOwnerlessLockScope ()
bool is_valid () const
bool is_locked_by_me () const
void acquire (bool non_racy_acquire)
Acquires the lock.
void release ()
Release the lock if acquired.
Constructor & Destructor Documentation
foedus::xct::McsOwnerlessLockScope::McsOwnerlessLockScope ()
Definition at line 90 of file xct_id.cpp.
 : lock_(nullptr), locked_by_me_(false) {}
foedus::xct::McsOwnerlessLockScope::McsOwnerlessLockScope (McsWwLock * lock, bool acquire_now = true, bool non_racy_acquire = false)
Definition at line 91 of file xct_id.cpp.
References acquire().
   : lock_(lock), locked_by_me_(false) {
   if (acquire_now) {
     acquire(non_racy_acquire);
   }
 }
foedus::xct::McsOwnerlessLockScope::~McsOwnerlessLockScope ()
Definition at line 100 of file xct_id.cpp.
References release().
{
   release();
   lock_ = nullptr;
   locked_by_me_ = false;
 }
Member Function Documentation
void foedus::xct::McsOwnerlessLockScope::acquire (bool non_racy_acquire)
Acquires the lock.
Does nothing if already acquired or !is_valid().
Definition at line 106 of file xct_id.cpp.
References is_locked_by_me(), is_valid(), foedus::xct::McsWwLock::ownerless_acquire_lock(), and foedus::xct::McsWwLock::ownerless_initial_lock().
Referenced by McsOwnerlessLockScope().
{
   if (is_valid()) {
     if (!is_locked_by_me()) {
       if (non_racy_acquire) {
         lock_->ownerless_initial_lock();
       } else {
         lock_->ownerless_acquire_lock();
       }
       locked_by_me_ = true;
     }
   }
 }
bool foedus::xct::McsOwnerlessLockScope::is_locked_by_me () const inline
Definition at line 1167 of file xct_id.hpp.
Referenced by acquire(), and release().
 { return locked_by_me_; }
bool foedus::xct::McsOwnerlessLockScope::is_valid () const inline
Definition at line 1166 of file xct_id.hpp.
Referenced by acquire(), and release().
 { return lock_; }
void foedus::xct::McsOwnerlessLockScope::release ()
Release the lock if acquired.
Does nothing if not or !is_valid().
Definition at line 119 of file xct_id.cpp.
References is_locked_by_me(), is_valid(), and foedus::xct::McsWwLock::ownerless_release_lock().
Referenced by ~McsOwnerlessLockScope().
{
   if (is_valid()) {
     if (is_locked_by_me()) {
       lock_->ownerless_release_lock();
       locked_by_me_ = false;
     }
   }
 }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/xct/xct_id.hpp
/home/shino/foedus_code/foedus-core/src/foedus/xct/xct_id.cpp