libfoedus-core: foedus::storage::sequential::SequentialRecordIterator Class Reference
foedus::storage::sequential::SequentialRecordIterator Class Reference final
FOEDUS Components » Storage Manager » Sequential Storage
Iterator for one SequentialRecordBatch, or a page.
Detailed Description
Iterator for one SequentialRecordBatch, or a page.
This class inlines per-record methods, but not per-page methods (eg initialization).
Definition at line 383 of file sequential_cursor.hpp.
#include <sequential_cursor.hpp>
Public Member Functions
SequentialRecordIterator ()
SequentialRecordIterator (const SequentialRecordBatch *batch, Epoch from_epoch, Epoch to_epoch)
void reset ()
bool is_valid () const __attribute__((always_inline))
void next () __attribute__((always_inline))
uint16_t get_cur_record_length () const __attribute__((always_inline))
Epoch get_cur_record_epoch () const __attribute__((always_inline))
void copy_cur_record (char *out, uint16_t out_size) const __attribute__((always_inline))
Copies the current record to the given buffer.
const char * get_cur_record_raw () const __attribute__((always_inline))
Directly returns a pointer to the current record.
const xct::RwLockableXctId * get_cur_record_owner_id () const __attribute__((always_inline))
bool in_epoch_range (Epoch epoch) const __attribute__((always_inline))
uint16_t get_stat_skipped_records () const
uint16_t get_record_count () const
const SequentialRecordBatch * get_raw_batch () const
Constructor & Destructor Documentation
foedus::storage::sequential::SequentialRecordIterator::SequentialRecordIterator ()
Definition at line 127 of file sequential_cursor.cpp.
References foedus::INVALID_EPOCH.
   : batch_(nullptr),
     from_epoch_(INVALID_EPOCH),
     to_epoch_(INVALID_EPOCH),
     record_count_(0) {
   cur_record_ = 0;
   cur_record_length_ = 0;
   cur_offset_ = 0;
   cur_record_epoch_ = INVALID_EPOCH;
   stat_skipped_records_ = 0;
 }
foedus::storage::sequential::SequentialRecordIterator::SequentialRecordIterator (const SequentialRecordBatch * batch, Epoch from_epoch, Epoch to_epoch)
Definition at line 139 of file sequential_cursor.cpp.
References ASSERT_ND, foedus::storage::sequential::SequentialRecordBatch::get_epoch_from_offset(), foedus::storage::sequential::SequentialRecordBatch::get_record_length(), in_epoch_range(), foedus::Epoch::is_valid(), and next().
   : batch_(batch),
     from_epoch_(from_epoch),
     to_epoch_(to_epoch),
     record_count_(batch->get_record_count()) {
   cur_record_ = 0;
   cur_record_length_ = batch_->get_record_length(0);
   cur_offset_ = 0;
   cur_record_epoch_ = batch->get_epoch_from_offset(0);
   ASSERT_ND(cur_record_epoch_.is_valid());
   stat_skipped_records_ = 0;
   if (!in_epoch_range(cur_record_epoch_)) {
     ++stat_skipped_records_;
     next();
   }
 }
Member Function Documentation
void foedus::storage::sequential::SequentialRecordIterator::copy_cur_record (char * out, uint16_t out_size) const inline
Copies the current record to the given buffer.
This is safe even after the cursor moves on, but it incurs one memcpy.
See also
get_cur_record_raw()
Definition at line 425 of file sequential_cursor.hpp.
References ASSERT_ND, get_cur_record_raw(), and is_valid().
{
     ASSERT_ND(is_valid());
     const char* raw = get_cur_record_raw();
     uint16_t copy_size = std::min<uint16_t>(out_size, cur_record_length_);
     std::memcpy(out, raw, copy_size);
   }
Epoch foedus::storage::sequential::SequentialRecordIterator::get_cur_record_epoch () const inline
Definition at line 416 of file sequential_cursor.hpp.
References ASSERT_ND, and is_valid().
{
     ASSERT_ND(is_valid());
     return cur_record_epoch_;
   }
uint16_t foedus::storage::sequential::SequentialRecordIterator::get_cur_record_length () const inline
Definition at line 412 of file sequential_cursor.hpp.
References ASSERT_ND, and is_valid().
{
     ASSERT_ND(is_valid());
     return cur_record_length_;
   }
const xct::RwLockableXctId* foedus::storage::sequential::SequentialRecordIterator::get_cur_record_owner_id () const inline
Definition at line 440 of file sequential_cursor.hpp.
References ASSERT_ND, foedus::storage::sequential::SequentialRecordBatch::get_owner_id_from_offset(), and is_valid().
{
     ASSERT_ND(is_valid());
     return batch_->get_owner_id_from_offset(cur_offset_);
   }
const char* foedus::storage::sequential::SequentialRecordIterator::get_cur_record_raw () const inline
Directly returns a pointer to the current record.
No memcpy, but note that the pointed address might become invalid once the cursor moves on. Use it with caution, like std::string::data().
See also
copy_cur_record()
Definition at line 436 of file sequential_cursor.hpp.
References ASSERT_ND, foedus::storage::sequential::SequentialRecordBatch::get_payload_from_offset(), and is_valid().
Referenced by copy_cur_record().
{
     ASSERT_ND(is_valid());
     return batch_->get_payload_from_offset(cur_offset_);
   }
const SequentialRecordBatch* foedus::storage::sequential::SequentialRecordIterator::get_raw_batch () const inline
Definition at line 453 of file sequential_cursor.hpp.
 { return batch_; }
uint16_t foedus::storage::sequential::SequentialRecordIterator::get_record_count () const inline
Returns
total number of records in this batch
Definition at line 451 of file sequential_cursor.hpp.
 { return record_count_; }
uint16_t foedus::storage::sequential::SequentialRecordIterator::get_stat_skipped_records () const inline
Returns
number of records we skipped so far due to from/to epoch
Definition at line 449 of file sequential_cursor.hpp.
 { return stat_skipped_records_; }
bool foedus::storage::sequential::SequentialRecordIterator::in_epoch_range (Epoch epoch) const inline
Definition at line 444 of file sequential_cursor.hpp.
Referenced by next(), and SequentialRecordIterator().
{
     return epoch >= from_epoch_ && epoch < to_epoch_;
   }
bool foedus::storage::sequential::SequentialRecordIterator::is_valid () const inline
Definition at line 392 of file sequential_cursor.hpp.
Referenced by copy_cur_record(), get_cur_record_epoch(), get_cur_record_length(), get_cur_record_owner_id(), and get_cur_record_raw().
 { return cur_record_ < record_count_; }
void foedus::storage::sequential::SequentialRecordIterator::next () inline
Definition at line 393 of file sequential_cursor.hpp.
References foedus::assorted::align8(), ASSERT_ND, foedus::storage::sequential::SequentialRecordBatch::get_epoch_from_offset(), foedus::storage::sequential::SequentialRecordBatch::get_record_length(), in_epoch_range(), foedus::Epoch::is_valid(), LIKELY, and UNLIKELY.
Referenced by SequentialRecordIterator().
{
     while (true) {
       if (UNLIKELY(cur_record_ + 1U >= record_count_)) {
         cur_record_ = record_count_;
         break;
       }
       ++cur_record_;
       cur_offset_ += assorted::align8(cur_record_length_) + sizeof(xct::RwLockableXctId);
       cur_record_length_ = batch_->get_record_length(cur_record_);
       cur_record_epoch_ = batch_->get_epoch_from_offset(cur_offset_);
       ASSERT_ND(cur_record_epoch_.is_valid());
       if (LIKELY(in_epoch_range(cur_record_epoch_))) {
         break;
       }
       // we have to skip this record
       ++stat_skipped_records_;
     }
   }
void foedus::storage::sequential::SequentialRecordIterator::reset () inline
Definition at line 388 of file sequential_cursor.hpp.
Referenced by foedus::storage::sequential::SequentialCursor::next_batch().
                       {
     std::memset(this, 0, sizeof(SequentialRecordIterator));
   }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/storage/sequential/sequential_cursor.hpp
/home/shino/foedus_code/foedus-core/src/foedus/storage/sequential/sequential_cursor.cpp