libfoedus-core: foedus::xct::McsMockAdaptor< RW_BLOCK > Class Template Reference
foedus::xct::McsMockAdaptor< RW_BLOCK > Class Template Reference
Implements McsAdaptorConcept.
Detailed Description
template<typename RW_BLOCK>
class foedus::xct::McsMockAdaptor< RW_BLOCK >
Implements McsAdaptorConcept.
Note
completely header-only
Definition at line 305 of file xct_mcs_adapter_impl.hpp.
#include <xct_mcs_adapter_impl.hpp>
Public Types
typedef RW_BLOCK ThisRwBlock
Public Member Functions
McsMockAdaptor (thread::ThreadId id, McsMockContext< RW_BLOCK > *context)
~McsMockAdaptor ()
McsBlockIndex issue_new_block ()
void cancel_new_block (McsBlockIndex the_block)
McsBlockIndex get_cur_block () const
thread::ThreadId get_my_id () const
thread::ThreadGroupId get_my_numa_node () const
std::atomic< bool > * me_waiting ()
McsWwBlock * get_ww_my_block (McsBlockIndex index)
RW_BLOCK * get_rw_my_block (McsBlockIndex index)
McsMockThread< RW_BLOCK > * get_other_thread (thread::ThreadId id)
std::atomic< bool > * other_waiting (thread::ThreadId id)
McsBlockIndex get_other_cur_block (thread::ThreadId id)
McsWwBlock * get_ww_other_block (thread::ThreadId id, McsBlockIndex index)
RW_BLOCK * get_rw_other_block (thread::ThreadId id, McsBlockIndex index)
RW_BLOCK * get_rw_other_block (uint32_t block_int)
RW_BLOCK * dereference_rw_tail_block (uint32_t tail_int)
McsRwExtendedBlock * get_rw_other_async_block (thread::ThreadId id, xct::McsRwLock *lock)
void add_rw_async_mapping (xct::McsRwLock *lock, xct::McsBlockIndex block_index)
void remove_rw_async_mapping (xct::McsRwLock *lock)
Member Typedef Documentation
template<typename RW_BLOCK > typedef RW_BLOCK foedus::xct::McsMockAdaptor< RW_BLOCK >::ThisRwBlock
Definition at line 307 of file xct_mcs_adapter_impl.hpp.
Constructor & Destructor Documentation
template<typename RW_BLOCK > foedus::xct::McsMockAdaptor< RW_BLOCK >::McsMockAdaptor (thread::ThreadId id, McsMockContext< RW_BLOCK > * context) inline
Definition at line 309 of file xct_mcs_adapter_impl.hpp.
     : id_(id),
       numa_node_(thread::decompose_numa_node(id)),
       local_ordinal_(thread::decompose_numa_local_ordinal(id)),
       context_(context),
       me_(context->nodes_[numa_node_].threads_.data() + local_ordinal_) {}
template<typename RW_BLOCK > foedus::xct::McsMockAdaptor< RW_BLOCK >::~McsMockAdaptor () inline
Definition at line 315 of file xct_mcs_adapter_impl.hpp.
 {}
Member Function Documentation
template<typename RW_BLOCK > void foedus::xct::McsMockAdaptor< RW_BLOCK >::add_rw_async_mapping (xct::McsRwLock * lock, xct::McsBlockIndex block_index) inline
Definition at line 385 of file xct_mcs_adapter_impl.hpp.
References ASSERT_ND, foedus::xct::kNullUniversalLockId, and foedus::xct::rw_lock_to_universal_lock_id().
{
     ASSERT_ND(lock);
     ASSERT_ND(block_index);
     auto ulockid = xct::rw_lock_to_universal_lock_id(context_->page_memory_resolver_, lock);
 #ifndef NDEBUG
     for (uint32_t i = 0; i < me_->mcs_rw_async_mapping_current_; ++i) {
       if (me_->mcs_rw_async_mappings_[i].lock_id_ == ulockid) {
         ASSERT_ND(false);
       }
     }
 #endif
     // TLS, no concurrency control needed
     auto index = me_->mcs_rw_async_mapping_current_++;
     ASSERT_ND(me_->mcs_rw_async_mappings_[index].lock_id_ == kNullUniversalLockId);
     me_->mcs_rw_async_mappings_[index].lock_id_ = ulockid;
     me_->mcs_rw_async_mappings_[index].block_index_ = block_index;
   }
template<typename RW_BLOCK > void foedus::xct::McsMockAdaptor< RW_BLOCK >::cancel_new_block (McsBlockIndex the_block) inline
Definition at line 322 of file xct_mcs_adapter_impl.hpp.
References ASSERT_ND.
{
     ASSERT_ND(me_->mcs_block_current_ == the_block);
     --me_->mcs_block_current_;
   }
template<typename RW_BLOCK > RW_BLOCK* foedus::xct::McsMockAdaptor< RW_BLOCK >::dereference_rw_tail_block (uint32_t tail_int) inline
Definition at line 371 of file xct_mcs_adapter_impl.hpp.
References foedus::xct::McsMockAdaptor< RW_BLOCK >::get_rw_other_block(), foedus::xct::McsRwLock::get_tail_waiter(), foedus::xct::McsRwLock::get_tail_waiter_block(), and foedus::xct::McsRwLock::tail_.
{
     McsRwLock tail_tmp;
     tail_tmp.tail_ = tail_int;
     uint32_t tail_id = tail_tmp.get_tail_waiter();
     uint32_t tail_block = tail_tmp.get_tail_waiter_block();
     return get_rw_other_block(tail_id, tail_block);
   }
template<typename RW_BLOCK > McsBlockIndex foedus::xct::McsMockAdaptor< RW_BLOCK >::get_cur_block () const inline
Definition at line 326 of file xct_mcs_adapter_impl.hpp.
 { return me_->mcs_block_current_; }
template<typename RW_BLOCK > thread::ThreadId foedus::xct::McsMockAdaptor< RW_BLOCK >::get_my_id () const inline
Definition at line 327 of file xct_mcs_adapter_impl.hpp.
 { return id_; }
template<typename RW_BLOCK > thread::ThreadGroupId foedus::xct::McsMockAdaptor< RW_BLOCK >::get_my_numa_node () const inline
Definition at line 328 of file xct_mcs_adapter_impl.hpp.
 { return numa_node_; }
template<typename RW_BLOCK > McsBlockIndex foedus::xct::McsMockAdaptor< RW_BLOCK >::get_other_cur_block (thread::ThreadId id) inline
Definition at line 351 of file xct_mcs_adapter_impl.hpp.
References foedus::xct::McsMockAdaptor< RW_BLOCK >::get_other_thread(), and foedus::xct::McsMockThread< RW_BLOCK >::mcs_block_current_.
{
     McsMockThread<RW_BLOCK>* other = get_other_thread(id);
     return other->mcs_block_current_;
   }
template<typename RW_BLOCK > McsMockThread<RW_BLOCK>* foedus::xct::McsMockAdaptor< RW_BLOCK >::get_other_thread (thread::ThreadId id) inline
Definition at line 340 of file xct_mcs_adapter_impl.hpp.
References ASSERT_ND, foedus::thread::decompose_numa_local_ordinal(), and foedus::thread::decompose_numa_node().
Referenced by foedus::xct::McsMockAdaptor< RW_BLOCK >::get_other_cur_block(), foedus::xct::McsMockAdaptor< RW_BLOCK >::get_rw_other_async_block(), foedus::xct::McsMockAdaptor< RW_BLOCK >::get_rw_other_block(), foedus::xct::McsMockAdaptor< RW_BLOCK >::get_ww_other_block(), and foedus::xct::McsMockAdaptor< RW_BLOCK >::other_waiting().
{
     thread::ThreadGroupId node = thread::decompose_numa_node(id);
     ASSERT_ND(node < context_->nodes_.size());
     thread::ThreadLocalOrdinal ordinal = thread::decompose_numa_local_ordinal(id);
     ASSERT_ND(ordinal < context_->nodes_[node].threads_.size());
     return context_->nodes_[node].threads_.data() + ordinal;
   }
template<typename RW_BLOCK > RW_BLOCK* foedus::xct::McsMockAdaptor< RW_BLOCK >::get_rw_my_block (McsBlockIndex index) inline
Definition at line 335 of file xct_mcs_adapter_impl.hpp.
References ASSERT_ND.
{
     ASSERT_ND(index <= me_->mcs_block_current_);
     return me_->mcs_rw_blocks_.data() + index;
   }
template<typename RW_BLOCK > McsRwExtendedBlock* foedus::xct::McsMockAdaptor< RW_BLOCK >::get_rw_other_async_block (thread::ThreadId id, xct::McsRwLock * lock) inline
Definition at line 378 of file xct_mcs_adapter_impl.hpp.
References ASSERT_ND, foedus::xct::McsMockThread< RW_BLOCK >::get_mcs_rw_async_block_index(), foedus::xct::McsMockAdaptor< RW_BLOCK >::get_other_thread(), and foedus::xct::McsMockAdaptor< RW_BLOCK >::get_rw_other_block().
{
     McsMockThread<RW_BLOCK>* other = get_other_thread(id);
     McsBlockIndex block
       = other->get_mcs_rw_async_block_index(context_->page_memory_resolver_, lock);
     ASSERT_ND(block);
     return get_rw_other_block(id, block);
   }
template<typename RW_BLOCK > RW_BLOCK* foedus::xct::McsMockAdaptor< RW_BLOCK >::get_rw_other_block (thread::ThreadId id, McsBlockIndex index) inline
Definition at line 360 of file xct_mcs_adapter_impl.hpp.
References ASSERT_ND, foedus::xct::McsMockAdaptor< RW_BLOCK >::get_other_thread(), and foedus::xct::McsMockThread< RW_BLOCK >::mcs_rw_blocks_.
Referenced by foedus::xct::McsMockAdaptor< RW_BLOCK >::dereference_rw_tail_block(), and foedus::xct::McsMockAdaptor< RW_BLOCK >::get_rw_other_async_block().
{
     McsMockThread<RW_BLOCK>* other = get_other_thread(id);
     ASSERT_ND(index <= other->mcs_block_current_);
     return other->mcs_rw_blocks_.data() + index;
   }
template<typename RW_BLOCK > RW_BLOCK* foedus::xct::McsMockAdaptor< RW_BLOCK >::get_rw_other_block (uint32_t block_int) inline
Definition at line 365 of file xct_mcs_adapter_impl.hpp.
References ASSERT_ND, foedus::xct::McsMockAdaptor< RW_BLOCK >::get_other_thread(), and foedus::xct::McsMockThread< RW_BLOCK >::mcs_rw_blocks_.
{
     McsMockThread<RW_BLOCK>* other = get_other_thread(block_int >> 16);
     McsBlockIndex index = block_int & 0xFFFFU;
     ASSERT_ND(index <= other->mcs_block_current_);
     return other->mcs_rw_blocks_.data() + index;
   }
template<typename RW_BLOCK > McsWwBlock* foedus::xct::McsMockAdaptor< RW_BLOCK >::get_ww_my_block (McsBlockIndex index) inline
Definition at line 331 of file xct_mcs_adapter_impl.hpp.
References ASSERT_ND.
{
     ASSERT_ND(index <= me_->mcs_block_current_);
     return me_->mcs_ww_blocks_.data() + index;
   }
template<typename RW_BLOCK > McsWwBlock* foedus::xct::McsMockAdaptor< RW_BLOCK >::get_ww_other_block (thread::ThreadId id, McsBlockIndex index) inline
Definition at line 355 of file xct_mcs_adapter_impl.hpp.
References ASSERT_ND, foedus::xct::McsMockAdaptor< RW_BLOCK >::get_other_thread(), and foedus::xct::McsMockThread< RW_BLOCK >::mcs_ww_blocks_.
{
     McsMockThread<RW_BLOCK>* other = get_other_thread(id);
     ASSERT_ND(index <= other->mcs_block_current_);
     return other->mcs_ww_blocks_.data() + index;
   }
template<typename RW_BLOCK > McsBlockIndex foedus::xct::McsMockAdaptor< RW_BLOCK >::issue_new_block () inline
Definition at line 317 of file xct_mcs_adapter_impl.hpp.
References ASSERT_ND.
{
     // if this assertion fires, probably we are retrying something too many times
     ASSERT_ND(me_->mcs_block_current_ < 0xFFFFU);
     return ++me_->mcs_block_current_;
   }
template<typename RW_BLOCK > std::atomic<bool>* foedus::xct::McsMockAdaptor< RW_BLOCK >::me_waiting () inline
Definition at line 329 of file xct_mcs_adapter_impl.hpp.
 { return &me_->mcs_waiting_; }
template<typename RW_BLOCK > std::atomic<bool>* foedus::xct::McsMockAdaptor< RW_BLOCK >::other_waiting (thread::ThreadId id) inline
Definition at line 347 of file xct_mcs_adapter_impl.hpp.
References foedus::xct::McsMockAdaptor< RW_BLOCK >::get_other_thread(), and foedus::xct::McsMockThread< RW_BLOCK >::mcs_waiting_.
{
     McsMockThread<RW_BLOCK>* other = get_other_thread(id);
     return &(other->mcs_waiting_);
   }
template<typename RW_BLOCK > void foedus::xct::McsMockAdaptor< RW_BLOCK >::remove_rw_async_mapping (xct::McsRwLock * lock) inline
Definition at line 402 of file xct_mcs_adapter_impl.hpp.
References ASSERT_ND, foedus::xct::kNullUniversalLockId, and foedus::xct::rw_lock_to_universal_lock_id().
{
     ASSERT_ND(me_->mcs_rw_async_mapping_current_);
     auto lock_id = xct::rw_lock_to_universal_lock_id(context_->page_memory_resolver_, lock);
     for (uint32_t i = 0; i < me_->mcs_rw_async_mapping_current_; ++i) {
       if (me_->mcs_rw_async_mappings_[i].lock_id_ == lock_id) {
         me_->mcs_rw_async_mappings_[i].lock_id_ = kNullUniversalLockId;
         --me_->mcs_rw_async_mapping_current_;
         return;
       }
     }
     ASSERT_ND(false);
   }
The documentation for this class was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/xct/xct_mcs_adapter_impl.hpp