libfoedus-core: foedus::debugging::DebuggingSupports Class Reference
foedus::debugging::DebuggingSupports Class Reference final
FOEDUS Components | FOEDUS Programming Idioms » Debug-Support functionalities
APIs to support debugging functionalities.
Detailed Description
APIs to support debugging functionalities.
Definition at line 35 of file debugging_supports.hpp.
#include <debugging_supports.hpp>
Classes
struct PapiCounters
Public Member Functions
DebuggingSupports ()=delete
DebuggingSupports (Engine *engine)
ErrorStack initialize_once () override
ErrorStack uninitialize_once () override
void set_debug_log_to_stderr (bool value)
Whether to write debug logs to stderr rather than log file.
void set_debug_log_stderr_threshold (DebuggingOptions::DebugLogLevel level)
Debug logs at or above this level will be copied to stderr.
void set_debug_log_min_threshold (DebuggingOptions::DebugLogLevel level)
Debug logs below this level will be completely ignored.
void set_verbose_log_level (int verbose)
Verbose debug logs (VLOG(m)) at or less than this number will be shown.
void set_verbose_module (const std::string &module, int verbose)
Per-module verbose level.
ErrorStack start_profile (const std::string &output_file)
Start running a CPU profiler (gperftools/PAPI).
void stop_profile ()
Stop CPU profiling.
void start_papi_counters ()
Start collecting performance counters via PAPI if it's available.
void stop_papi_counters ()
Stop collecting performance counters via PAPI.
const PapiCounters & get_papi_counters () const
Returns the profiled PAPI counters.
Public Member Functions inherited from foedus::DefaultInitializable
DefaultInitializable ()
virtual ~DefaultInitializable ()
DefaultInitializable (const DefaultInitializable &)=delete
DefaultInitializable & operator= (const DefaultInitializable &)=delete
ErrorStack initialize () override final
Typical implementation of Initializable::initialize() that provides initialize-once semantics.
ErrorStack uninitialize () override final
Typical implementation of Initializable::uninitialize() that provides uninitialize-once semantics.
bool is_initialized () const override final
Returns whether the object has been already initialized or not.
Public Member Functions inherited from foedus::Initializable
virtual ~Initializable ()
Static Public Member Functions
static std::vector< std::string > describe_papi_counters (const PapiCounters &counters)
Returns a human-readable explanation of PAPI counters.
Constructor & Destructor Documentation
foedus::debugging::DebuggingSupports::DebuggingSupports () delete
foedus::debugging::DebuggingSupports::DebuggingSupports (Engine * engine) inline explicit
Definition at line 43 of file debugging_supports.hpp.
 : engine_(engine) {}
Member Function Documentation
std::vector< std::string > foedus::debugging::DebuggingSupports::describe_papi_counters (const PapiCounters & counters) static
Returns a human-readable explanation of PAPI counters.
One string for one counter to avoid returning too long string.
Definition at line 220 of file debugging_supports.cpp.
{
   std::vector<std::string> ret;
   ret.emplace_back("libpapi was not linked. No PAPI profile is collected");
   return ret;
 }
const PapiCounters& foedus::debugging::DebuggingSupports::get_papi_counters () const inline
Returns the profiled PAPI counters.
must be called after stop_profile(). You must call start_profile() with papi_counters=true.
Definition at line 88 of file debugging_supports.hpp.
 { return papi_counters_; }
ErrorStack foedus::debugging::DebuggingSupports::initialize_once () override virtual
Implements foedus::DefaultInitializable.
Definition at line 117 of file debugging_supports.cpp.
References foedus::Engine::is_emulated_child(), and foedus::kRetOk.
{
   // glog is already initialized by master, so emulated child does nothing
   if (engine_->is_emulated_child()) {
     return kRetOk;
   }
   initialize_glog();  // initialize glog at the beginning. we can use glog since now
   std::memset(&papi_counters_, 0, sizeof(papi_counters_));
   papi_enabled_ = false;
   return kRetOk;
 }
void foedus::debugging::DebuggingSupports::set_debug_log_min_threshold (DebuggingOptions::DebugLogLevel level)
Debug logs below this level will be completely ignored.
Default is kDebugLogInfo. There is an API to change this setting at runtime.
Definition at line 143 of file debugging_supports.cpp.
{
   FLAGS_minloglevel = static_cast<int>(level);
   LOG(INFO) << "Changed glog's FLAGS_minloglevel to " << level;
 }
void foedus::debugging::DebuggingSupports::set_debug_log_stderr_threshold (DebuggingOptions::DebugLogLevel level)
Debug logs at or above this level will be copied to stderr.
Default is kDebugLogInfo. There is an API to change this setting at runtime.
Definition at line 139 of file debugging_supports.cpp.
{
   FLAGS_stderrthreshold = static_cast<int>(level);
   LOG(INFO) << "Changed glog's FLAGS_stderrthreshold to " << level;
 }
void foedus::debugging::DebuggingSupports::set_debug_log_to_stderr (bool value)
Whether to write debug logs to stderr rather than log file.
Default is false. There is an API to change this setting at runtime.
Definition at line 135 of file debugging_supports.cpp.
{
   FLAGS_logtostderr = value;
   LOG(INFO) << "Changed glog's FLAGS_logtostderr to " << value;
 }
void foedus::debugging::DebuggingSupports::set_verbose_log_level (int verbose)
Verbose debug logs (VLOG(m)) at or less than this number will be shown.
Default is 0. There is an API to change this setting at runtime.
Definition at line 147 of file debugging_supports.cpp.
{
   FLAGS_v = verbose;
   LOG(INFO) << "Changed glog's FLAGS_v to " << verbose;
 }
void foedus::debugging::DebuggingSupports::set_verbose_module (const std::string & module, int verbose)
Per-module verbose level.
The value has to contain a comma-separated list of 'module name'='log level'. 'module name' is a glob pattern (e.g., gfs* for all modules whose name starts with "gfs"), matched against the filename base (that is, name ignoring .cc/.h./-inl.h) Default is "". There is an API to change this setting at runtime.
Definition at line 151 of file debugging_supports.cpp.
{
   // Watch out for this bug, if we get a crash here:
   // https://code.google.com/p/google-glog/issues/detail?id=172
   google::SetVLOGLevel(module.c_str(), verbose);
   LOG(INFO) << "Invoked google::SetVLOGLevel for " << module << ", level=" << verbose;
 }
void foedus::debugging::DebuggingSupports::start_papi_counters ()
Start collecting performance counters via PAPI if it's available.
Definition at line 216 of file debugging_supports.cpp.
{
   LOG(WARNING) << "libpapi was not linked. No PAPI profile is collected.";
 }
ErrorStack foedus::debugging::DebuggingSupports::start_profile (const std::string & output_file)
Start running a CPU profiler (gperftools/PAPI).
Parameters
[in] output_file path to output the profile result.
This feature is enabled only when you link to libprofiler.so. For example, use it like this:
CHECK_ERROR(engine.get_debug()->start_profile("hoge.prof"));
for (int i = 0; i < 1000000; ++i) do_something();
engine.get_debug()->stop_profile("hoge.prof");
Then, after the execution,
 pprof --pdf your_binary hoge.prof > hoge.pdf
 okular hoge.pdf
Definition at line 229 of file debugging_supports.cpp.
References ERROR_STACK, foedus::kErrorCodeDbgGperftools, foedus::kRetOk, and foedus::assorted::os_error().
{
 #ifdef HAVE_GOOGLEPERFTOOLS
   int ret = ::ProfilerStart(output_file.c_str());
   if (ret == 0) {
     LOG(ERROR) << "ProfilerStart() returned zero (an error). os_error=" << assorted::os_error();
     return ERROR_STACK(kErrorCodeDbgGperftools);
   }
 #else  // HAVE_GOOGLEPERFTOOLS
   LOG(WARNING) << "Google perftools was not linked. No profile is provided. " << output_file;
 #endif  // HAVE_GOOGLEPERFTOOLS
   return kRetOk;
 }
void foedus::debugging::DebuggingSupports::stop_papi_counters ()
Stop collecting performance counters via PAPI.
Definition at line 219 of file debugging_supports.cpp.
 {}
void foedus::debugging::DebuggingSupports::stop_profile ()
Stop CPU profiling.
Definition at line 242 of file debugging_supports.cpp.
{
 #ifdef HAVE_GOOGLEPERFTOOLS
   ::ProfilerStop();
 #endif  // HAVE_GOOGLEPERFTOOLS
 }
ErrorStack foedus::debugging::DebuggingSupports::uninitialize_once () override virtual
Implements foedus::DefaultInitializable.
Definition at line 127 of file debugging_supports.cpp.
References foedus::Engine::is_emulated_child(), and foedus::kRetOk.
{
   if (engine_->is_emulated_child()) {
     return kRetOk;
   }
   uninitialize_glog();  // release glog at the end. we can't use glog since now
   return kRetOk;
 }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/debugging/debugging_supports.hpp
/home/shino/foedus_code/foedus-core/src/foedus/debugging/debugging_supports.cpp