libfoedus-core: foedus::fs::Path Class Reference
foedus::fs::Path Class Reference
FOEDUS Programming Idioms » Filesystem wrapper
Analogue of boost::filesystem::path.
Detailed Description
Analogue of boost::filesystem::path.
Unlike boost::filesystem::path, this always brings a full path. As soon as this object is instantiated, we convert it to an absolute path with absolute().
Todo:
Support Windows. MUCH later.
Definition at line 37 of file path.hpp.
#include <path.hpp>
Public Member Functions
Path ()
Path (const Path &p)
Path (const std::string &s)
This one resolves ~ at beginning.
Path & operator= (const Path &p)
Path & operator= (const std::string &s)
Path & operator+= (const Path &p)
Path & operator+= (const std::string &s)
void append_separator_if_needed ()
Path & operator/= (const Path &p)
Path & operator/= (const std::string &s)
const std::string & native () const
const char * c_str () const
const std::string & string () const
int compare (const Path &p) const noexcept
int compare (const std::string &s) const
Path parent_path () const
std::vector< Path > child_paths () const
Path filename () const
bool root () const
bool empty () const
bool has_parent_path () const
bool has_filename () const
Static Public Attributes
static const char kPreferredSeparator = '/'
Friends
std::ostream & operator<< (std::ostream &o, const Path &v)
Constructor & Destructor Documentation
foedus::fs::Path::Path () inline
Definition at line 41 of file path.hpp.
Referenced by compare(), filename(), and parent_path().
 {}
foedus::fs::Path::Path (const Path & p) inline
Definition at line 42 of file path.hpp.
 : pathname_(p.pathname_) {}
foedus::fs::Path::Path (const std::string & s) explicit
This one resolves ~ at beginning.
Definition at line 29 of file path.cpp.
References foedus::fs::current_path(), foedus::fs::home_path(), kPreferredSeparator, and string().
{
   if (s.size() > 0 && s.at(0) == '~'
     && (s.size() == 1 || s.at(1) == '/')) {
     // starts with ~/ or ~ alone: resolve it as home folder
     pathname_ = home_path().pathname_;
     pathname_.append(s.substr(1));
   } else {
     if (s.empty() || s.at(0) == kPreferredSeparator) {
       pathname_ = s;
     } else {
       Path tmp = current_path();
       tmp /= s;
       pathname_ = tmp.string();
     }
   }
 }
Member Function Documentation
void foedus::fs::Path::append_separator_if_needed () inline
Definition at line 51 of file path.hpp.
References kPreferredSeparator.
Referenced by operator/=().
{
     if (!pathname_.empty() && pathname_.at(pathname_.size() - 1) != kPreferredSeparator) {
       pathname_ += kPreferredSeparator;
     }
   }
const char* foedus::fs::Path::c_str () const inline
Definition at line 64 of file path.hpp.
Referenced by foedus::fs::atomic_rename(), child_paths(), foedus::fs::create_directory(), foedus::fs::file_size(), foedus::fs::fsync(), foedus::externalize::Externalizable::load_from_file(), foedus::fs::DirectIoFile::open(), foedus::fs::space(), and foedus::fs::status().
 { return pathname_.c_str(); }
std::vector< Path > foedus::fs::Path::child_paths () const
Definition at line 64 of file path.cpp.
References c_str(), and foedus::fs::is_directory().
Referenced by foedus::fs::remove_all().
{
   std::vector< Path > children;
   if (is_directory(*this)) {
     DIR *d = ::opendir(c_str());
     if (d) {
       for (dirent *e = ::readdir(d); e != nullptr; e = ::readdir(d)) {
         if (e->d_name == std::string(".") || e->d_name == std::string("..")) {
           continue;
         }
         Path child(*this);
         child /= std::string(e->d_name);
         children.emplace_back(child);
       }
       ::closedir(d);
     }
   }
   return children;
 }
int foedus::fs::Path::compare (const Path & p) const inline noexcept
Definition at line 67 of file path.hpp.
Referenced by foedus::fs::operator!=(), foedus::fs::operator<(), and foedus::fs::operator==().
 { return pathname_.compare(p.pathname_); }
int foedus::fs::Path::compare (const std::string & s) const inline
Definition at line 68 of file path.hpp.
References compare(), and Path().
Referenced by compare().
 { return compare(Path(s)); }
bool foedus::fs::Path::empty () const inline
Definition at line 75 of file path.hpp.
Referenced by foedus::fs::create_directories(), and has_parent_path().
 { return pathname_.empty(); }  // name consistent with std containers
Path foedus::fs::Path::filename () const
Definition at line 46 of file path.cpp.
References kPreferredSeparator, and Path().
{
   size_t pos = pathname_.find_last_of(kPreferredSeparator);
   if (pos == pathname_.size()) {
     return Path(pathname_);
   } else {
     return Path(pathname_.c_str() + pos);
   }
 }
bool foedus::fs::Path::has_filename () const inline
Definition at line 77 of file path.hpp.
 { return !pathname_.empty(); }
bool foedus::fs::Path::has_parent_path () const inline
Definition at line 76 of file path.hpp.
References empty(), and parent_path().
 { return !parent_path().empty(); }
const std::string& foedus::fs::Path::native () const inline
Definition at line 63 of file path.hpp.
 { return pathname_; }
Path& foedus::fs::Path::operator+= (const Path & p) inline
Definition at line 48 of file path.hpp.
 {pathname_ += p.pathname_; return *this;}
Path& foedus::fs::Path::operator+= (const std::string & s) inline
Definition at line 49 of file path.hpp.
 {pathname_ += s; return *this;}
Path& foedus::fs::Path::operator/= (const Path & p) inline
Definition at line 56 of file path.hpp.
References operator/=().
Referenced by operator/=().
 { return operator/=(p.pathname_); }
Path& foedus::fs::Path::operator/= (const std::string & s) inline
Definition at line 57 of file path.hpp.
References append_separator_if_needed().
{
     append_separator_if_needed();
     pathname_ += s;
     return *this;
   }
Path& foedus::fs::Path::operator= (const Path & p) inline
Definition at line 46 of file path.hpp.
 { pathname_ = p.pathname_; return *this; }
Path& foedus::fs::Path::operator= (const std::string & s) inline
Definition at line 47 of file path.hpp.
 { pathname_ = s; return *this; }
Path foedus::fs::Path::parent_path () const
Definition at line 55 of file path.cpp.
References kPreferredSeparator, and Path().
Referenced by foedus::fs::create_directories(), foedus::fs::durable_atomic_rename(), foedus::fs::fsync(), has_parent_path(), foedus::fs::DirectIoFile::open(), and foedus::externalize::Externalizable::save_to_file().
{
   size_t pos = pathname_.find_last_of(kPreferredSeparator);
   if (pos == pathname_.size()) {
     return Path();
   } else {
     return Path(pathname_.substr(0, pos));
   }
 }
bool foedus::fs::Path::root () const inline
Definition at line 74 of file path.hpp.
References kPreferredSeparator.
 { return pathname_.size() == 1 && pathname_.at(0) == kPreferredSeparator; }
const std::string& foedus::fs::Path::string () const inline
Definition at line 65 of file path.hpp.
Referenced by foedus::fs::operator<<(), Path(), and foedus::snapshot::DumpFileSortedBuffer::to_string().
 { return pathname_; }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const Path & v) friend
Definition at line 84 of file path.cpp.
{
   o << v.string();
   return o;
 }
Member Data Documentation
const char foedus::fs::Path::kPreferredSeparator = '/' static
Definition at line 39 of file path.hpp.
Referenced by append_separator_if_needed(), filename(), parent_path(), Path(), and root().
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/fs/path.hpp
/home/shino/foedus_code/foedus-core/src/foedus/fs/path.cpp