libfoedus-core: foedus::storage::hash::HashIntermediatePage Class Reference
foedus::storage::hash::HashIntermediatePage Class Reference final
FOEDUS Components » Storage Manager » Hashtable Storage
Represents an intermediate page in Hashtable Storage.
Detailed Description
Represents an intermediate page in Hashtable Storage.
This is one of the page types in hash. An intermediate page is simply a list of pointers to child pages, which might be intermediate or data pages.
Page Layout
Common PageHeader HashRange (just for sanity check) DualPagePointer DualPagePointer ...
Each page simply contains kHashIntermediatePageFanout pointers to lower level.
Note
Let's not use the word 'leaf' in hash storage. We previously called intermediate pages whose get_level()==0 as leaves, but it's confusing. A leaf page usually means a last-level page that contains tuple data. Here, such a page still points to lower level (data pages). So, we should call it something like "level-0 intermediate" or just "level-0".
Definition at line 64 of file hash_page_impl.hpp.
#include <hash_page_impl.hpp>
Public Member Functions
HashIntermediatePage ()=delete
HashIntermediatePage (const HashIntermediatePage &other)=delete
HashIntermediatePage & operator= (const HashIntermediatePage &other)=delete
PageHeader & header ()
const PageHeader & header () const
VolatilePagePointer get_volatile_page_id () const
SnapshotPagePointer get_snapshot_page_id () const
DualPagePointer & get_pointer (uint16_t index)
const DualPagePointer & get_pointer (uint16_t index) const
DualPagePointer * get_pointer_address (uint16_t index)
const DualPagePointer * get_pointer_address (uint16_t index) const
void initialize_volatile_page (StorageId storage_id, VolatilePagePointer page_id, const HashIntermediatePage *parent, uint8_t level, HashBin start_bin)
Called only when this page is initialized.
void initialize_snapshot_page (StorageId storage_id, SnapshotPagePointer page_id, uint8_t level, HashBin start_bin)
void release_pages_recursive_parallel (Engine *engine)
void release_pages_recursive (const memory::GlobalVolatilePageResolver &page_resolver, memory::PageReleaseBatch *batch)
const HashBinRange & get_bin_range () const
uint8_t get_level () const
void assert_bin (HashBin bin) const __attribute__((always_inline))
void assert_range () const __attribute__((always_inline))
uint64_t get_dummy_padding_unused () const
Friends
std::ostream & operator<< (std::ostream &o, const HashIntermediatePage &v)
defined in hash_page_debug.cpp.
Constructor & Destructor Documentation
foedus::storage::hash::HashIntermediatePage::HashIntermediatePage () delete
foedus::storage::hash::HashIntermediatePage::HashIntermediatePage (const HashIntermediatePage & other) delete
Member Function Documentation
void foedus::storage::hash::HashIntermediatePage::assert_bin (HashBin bin) const inline
Definition at line 107 of file hash_page_impl.hpp.
References ASSERT_ND, and foedus::storage::hash::HashBinRange::contains().
{
     ASSERT_ND(bin_range_.contains(bin));
   }
void foedus::storage::hash::HashIntermediatePage::assert_range () const inline
Definition at line 110 of file hash_page_impl.hpp.
References ASSERT_ND, get_level(), foedus::storage::hash::kHashMaxBins, and foedus::storage::hash::HashBinRange::length().
Referenced by foedus::storage::hash::HashStoragePimpl::create().
{
     ASSERT_ND(bin_range_.length() == kHashMaxBins[get_level() + 1U]);
   }
const HashBinRange& foedus::storage::hash::HashIntermediatePage::get_bin_range () const inline
Definition at line 104 of file hash_page_impl.hpp.
Referenced by foedus::storage::hash::HashStoragePimpl::follow_page(), foedus::storage::hash::hash_data_volatile_page_init(), foedus::storage::hash::HashDataPage::initialize_volatile_page(), foedus::storage::hash::ComposedBinsMergedStream::open_path(), foedus::storage::hash::operator<<(), foedus::storage::hash::ComposedBinsMergedStream::process_a_bin(), and foedus::storage::hash::HashStoragePimpl::verify_single_thread_intermediate().
 { return bin_range_; }
uint64_t foedus::storage::hash::HashIntermediatePage::get_dummy_padding_unused () const inline
Definition at line 117 of file hash_page_impl.hpp.
 { return padding_; }
uint8_t foedus::storage::hash::HashIntermediatePage::get_level () const inline
Definition at line 105 of file hash_page_impl.hpp.
References foedus::storage::PageHeader::get_in_layer_level().
Referenced by assert_range(), foedus::storage::hash::HashComposer::construct_root(), foedus::storage::hash::HashStoragePimpl::debugout_single_thread_intermediate(), foedus::storage::hash::HashPartitioner::design_partition_task(), foedus::storage::hash::HashComposer::drop_volatiles(), foedus::storage::hash::HashStoragePimpl::follow_page(), foedus::storage::hash::HashStoragePimpl::follow_page_bin_head(), foedus::storage::hash::hash_data_volatile_page_init(), foedus::storage::hash::HashStoragePimpl::hcc_reset_all_temperature_stat_intermediate(), foedus::storage::hash::ComposedBinsMergedStream::init(), initialize_volatile_page(), foedus::storage::hash::HashDataPage::initialize_volatile_page(), foedus::storage::hash::HashStoragePimpl::locate_bin(), foedus::storage::hash::ComposedBinsMergedStream::open_path(), foedus::storage::hash::operator<<(), foedus::storage::hash::ComposedBinsMergedStream::process_a_bin(), release_pages_recursive(), release_pages_recursive_parallel(), foedus::storage::hash::HashStoragePimpl::verify_single_thread(), and foedus::storage::hash::HashStoragePimpl::verify_single_thread_intermediate().
 { return header_.get_in_layer_level(); }
DualPagePointer& foedus::storage::hash::HashIntermediatePage::get_pointer (uint16_t index) inline
Definition at line 80 of file hash_page_impl.hpp.
Referenced by foedus::storage::hash::HashStoragePimpl::debugout_single_thread_intermediate(), foedus::storage::hash::HashPartitioner::design_partition_task(), foedus::storage::hash::HashComposer::drop_volatiles(), foedus::storage::hash::HashStoragePimpl::follow_page(), foedus::storage::hash::HashStoragePimpl::hcc_reset_all_temperature_stat_intermediate(), foedus::storage::hash::ComposedBinsMergedStream::init(), foedus::storage::hash::HashStoragePimpl::locate_bin(), foedus::storage::hash::ComposedBinsMergedStream::open_path(), foedus::storage::hash::operator<<(), and foedus::storage::hash::HashStoragePimpl::verify_single_thread_intermediate().
 { return pointers_[index]; }
const DualPagePointer& foedus::storage::hash::HashIntermediatePage::get_pointer (uint16_t index) const inline
Definition at line 81 of file hash_page_impl.hpp.
 { return pointers_[index]; }
DualPagePointer* foedus::storage::hash::HashIntermediatePage::get_pointer_address (uint16_t index) inline
Definition at line 82 of file hash_page_impl.hpp.
Referenced by foedus::storage::hash::HashStoragePimpl::follow_page_bin_head(), and foedus::storage::hash::ComposedBinsMergedStream::process_a_bin().
 { return pointers_ + index; }
const DualPagePointer* foedus::storage::hash::HashIntermediatePage::get_pointer_address (uint16_t index) const inline
Definition at line 83 of file hash_page_impl.hpp.
 { return pointers_ + index; }
SnapshotPagePointer foedus::storage::hash::HashIntermediatePage::get_snapshot_page_id () const inline
Definition at line 76 of file hash_page_impl.hpp.
References ASSERT_ND, foedus::storage::PageHeader::page_id_, and foedus::storage::PageHeader::snapshot_.
{
     ASSERT_ND(header_.snapshot_);
     return static_cast<SnapshotPagePointer>(header_.page_id_);
   }
VolatilePagePointer foedus::storage::hash::HashIntermediatePage::get_volatile_page_id () const inline
Definition at line 72 of file hash_page_impl.hpp.
References ASSERT_ND, foedus::storage::PageHeader::page_id_, and foedus::storage::PageHeader::snapshot_.
{
     ASSERT_ND(!header_.snapshot_);
     return VolatilePagePointer(header_.page_id_);
   }
PageHeader& foedus::storage::hash::HashIntermediatePage::header () inline
Definition at line 70 of file hash_page_impl.hpp.
Referenced by foedus::storage::hash::HashComposer::construct_root(), foedus::storage::hash::HashComposeContext::execute(), foedus::storage::hash::HashStoragePimpl::follow_page(), foedus::storage::hash::HashStoragePimpl::follow_page_bin_head(), foedus::storage::hash::HashStoragePimpl::locate_bin(), foedus::storage::hash::ComposedBinsMergedStream::open_path(), foedus::storage::hash::operator<<(), foedus::storage::hash::ComposedBinsMergedStream::process_a_bin(), release_pages_recursive(), release_pages_recursive_parallel(), foedus::storage::hash::release_parallel(), foedus::storage::hash::resolve_intermediate_impl(), and foedus::storage::hash::HashStoragePimpl::verify_single_thread_intermediate().
 { return header_; }
const PageHeader& foedus::storage::hash::HashIntermediatePage::header () const inline
Definition at line 71 of file hash_page_impl.hpp.
 { return header_; }
void foedus::storage::hash::HashIntermediatePage::initialize_snapshot_page (StorageId storage_id, SnapshotPagePointer page_id, uint8_t level, HashBin start_bin)
Definition at line 58 of file hash_page_impl.cpp.
References foedus::storage::hash::HashBinRange::begin_, foedus::storage::hash::HashBinRange::end_, foedus::storage::PageHeader::init_snapshot(), foedus::storage::kHashIntermediatePageType, foedus::storage::hash::kHashMaxBins, foedus::storage::kPageSize, and foedus::storage::PageHeader::set_in_layer_level().
Referenced by foedus::storage::hash::HashComposer::construct_root(), and foedus::storage::hash::ComposedBinsMergedStream::open_path().
                      {
   std::memset(this, 0, kPageSize);
   header_.init_snapshot(page_id, storage_id, kHashIntermediatePageType);
   bin_range_.begin_ = start_bin;
   bin_range_.end_ = bin_range_.begin_ + kHashMaxBins[level + 1U];
   header_.set_in_layer_level(level);
 }
void foedus::storage::hash::HashIntermediatePage::initialize_volatile_page (StorageId storage_id, VolatilePagePointer page_id, const HashIntermediatePage * parent, uint8_t level, HashBin start_bin)
Called only when this page is initialized.
Definition at line 40 of file hash_page_impl.cpp.
References ASSERT_ND, foedus::storage::hash::HashBinRange::begin_, foedus::storage::hash::HashBinRange::contains(), foedus::storage::hash::HashBinRange::end_, get_level(), foedus::storage::PageHeader::init_volatile(), foedus::storage::kHashIntermediatePageType, foedus::storage::hash::kHashMaxBins, foedus::storage::kPageSize, and foedus::storage::PageHeader::set_in_layer_level().
Referenced by foedus::storage::hash::HashStoragePimpl::create(), and foedus::storage::hash::hash_intermediate_volatile_page_init().
                      {
   std::memset(this, 0, kPageSize);
   header_.init_volatile(page_id, storage_id, kHashIntermediatePageType);
   bin_range_.begin_ = start_bin;
   bin_range_.end_ = bin_range_.begin_ + kHashMaxBins[level + 1U];
   header_.set_in_layer_level(level);
   if (parent) {
     ASSERT_ND(parent->get_level() > 0);
     ASSERT_ND(level + 1U == parent->get_level());
     ASSERT_ND(parent->bin_range_.contains(bin_range_));
   }
 }
HashIntermediatePage& foedus::storage::hash::HashIntermediatePage::operator= (const HashIntermediatePage & other) delete
void foedus::storage::hash::HashIntermediatePage::release_pages_recursive (const memory::GlobalVolatilePageResolver & page_resolver, memory::PageReleaseBatch * batch)
Definition at line 302 of file hash_page_impl.cpp.
References ASSERT_ND, foedus::storage::VolatilePagePointer::clear(), foedus::storage::PageHeader::get_in_layer_level(), get_level(), foedus::storage::PageHeader::get_page_type(), header(), foedus::storage::hash::HashDataPage::header(), foedus::storage::VolatilePagePointer::is_null(), foedus::storage::kHashDataPageType, foedus::storage::hash::kHashIntermediatePageFanout, foedus::storage::kHashIntermediatePageType, foedus::storage::PageHeader::page_id_, foedus::memory::PageReleaseBatch::release(), release_pages_recursive(), foedus::storage::hash::HashDataPage::release_pages_recursive(), foedus::memory::GlobalVolatilePageResolver::resolve_offset(), foedus::storage::DualPagePointer::volatile_pointer_, and foedus::storage::VolatilePagePointer::word.
Referenced by release_pages_recursive(), release_pages_recursive_parallel(), and foedus::storage::hash::release_parallel().
{
   for (uint8_t i = 0; i < kHashIntermediatePageFanout; ++i) {
     VolatilePagePointer pointer = pointers_[i].volatile_pointer_;
     if (!pointer.is_null()) {
       Page* page = page_resolver.resolve_offset(pointer);
       if (get_level() == 0) {
         HashDataPage* child = reinterpret_cast<HashDataPage*>(page);
         ASSERT_ND(child->header().get_page_type() == kHashDataPageType);
         ASSERT_ND(child->header().get_in_layer_level() == 0);
         child->release_pages_recursive(page_resolver, batch);
       } else {
         HashIntermediatePage* child = reinterpret_cast<HashIntermediatePage*>(page);
         ASSERT_ND(child->header().get_page_type() == kHashIntermediatePageType);
         ASSERT_ND(child->get_level() + 1U == get_level());
         child->release_pages_recursive(page_resolver, batch);
       }
       pointer.clear();
     }
   }
   VolatilePagePointer volatile_id;
   volatile_id.word = header().page_id_;
   batch->release(volatile_id);
 }
void foedus::storage::hash::HashIntermediatePage::release_pages_recursive_parallel (Engine * engine)
Definition at line 271 of file hash_page_impl.cpp.
References foedus::memory::EngineMemory::get_global_volatile_page_resolver(), get_level(), foedus::Engine::get_memory_manager(), foedus::memory::EngineMemory::get_node_memory(), foedus::storage::VolatilePagePointer::get_numa_node(), foedus::storage::VolatilePagePointer::get_offset(), header(), foedus::storage::VolatilePagePointer::is_null(), foedus::storage::hash::kHashIntermediatePageFanout, foedus::storage::PageHeader::page_id_, foedus::memory::PageReleaseBatch::release_all(), foedus::memory::PagePool::release_one(), release_pages_recursive(), foedus::storage::hash::release_parallel(), foedus::storage::DualPagePointer::volatile_pointer_, and foedus::storage::VolatilePagePointer::word.
Referenced by foedus::storage::hash::HashStoragePimpl::drop().
{
   if (get_level() == 0) {
     // root page is a leaf page.. don't bother parallelize.
     const memory::GlobalVolatilePageResolver& page_resolver
       = engine->get_memory_manager()->get_global_volatile_page_resolver();
     memory::PageReleaseBatch release_batch(engine);
     release_pages_recursive(page_resolver, &release_batch);
     release_batch.release_all();
   } else {
     // so far, we spawn a thread for every single pointer.
     // it might be an oversubscription, but not a big issue.
     std::vector<std::thread> threads;
     for (uint8_t i = 0; i < kHashIntermediatePageFanout; ++i) {
       VolatilePagePointer pointer = pointers_[i].volatile_pointer_;
       if (!pointer.is_null()) {
         threads.emplace_back(release_parallel, engine, pointer);
       }
     }
     for (auto& t : threads) {
       t.join();
     }
     VolatilePagePointer volatile_id;
     volatile_id.word = header().page_id_;
     memory::PagePool* pool = engine->get_memory_manager()->get_node_memory(
       volatile_id.get_numa_node())->get_volatile_pool();
     pool->release_one(volatile_id.get_offset());
   }
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const HashIntermediatePage & v) friend
defined in hash_page_debug.cpp.
Definition at line 31 of file hash_page_debug.cpp.
{
   o << "<HashIntermediatePage>";
   o << std::endl << "  <vaddr>" << assorted::Hex(reinterpret_cast<uintptr_t>(&v), 16) << "</vaddr>";
   o << std::endl << "  " << v.header();
   o << std::endl << "  <level>" << static_cast<int>(v.get_level()) << "</level>";
   o << std::endl << "  " << v.get_bin_range();
   HashBin total_begin = v.get_bin_range().begin_;
   HashBin interval = kHashMaxBins[v.get_level()];
   for (uint16_t i = 0; i < kHashIntermediatePageFanout; ++i) {
     DualPagePointer pointer = v.get_pointer(i);
     if (pointer.is_both_null()) {
       continue;
     }
     o << std::endl << "  <Pointer index=\"" << static_cast<int>(i)
       << "\" bin_begin=\"" << (total_begin + i * interval)
       << "\">" << pointer << "</Pointer>";
   }
   o << "</HashIntermediatePage>";
   return o;
 }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/storage/hash/hash_page_impl.hpp
/home/shino/foedus_code/foedus-core/src/foedus/storage/hash/hash_page_impl.cpp