libfoedus-core: foedus::assorted::DumbSpinlock Class Reference
foedus::assorted::DumbSpinlock Class Reference
FOEDUS Programming Idioms » Assorted Methods/Classes
A simple spinlock using a boolean field.
Detailed Description
A simple spinlock using a boolean field.
As the name suggests, this spinlock implementation is not scalable at all. It's the dumbest implementation of lock, which might cause cacheline invalidation storm when contended. However, in many places it's enough and also the simplicity helps. You just need memory for one bool, that's it. It trivially works for a shared memory, too.
Use this object where you don't expect much contention.
Definition at line 40 of file dumb_spinlock.hpp.
#include <dumb_spinlock.hpp>
Public Member Functions
DumbSpinlock (bool *locked, bool lock_initially=true)
~DumbSpinlock ()
automatically unlocks when out of scope.
bool is_locked_by_me () const
void lock ()
Locks it if I haven't locked it yet.
bool try_lock ()
try-version of the lock.
void unlock ()
Unlocks it if I locked it.
Constructor & Destructor Documentation
foedus::assorted::DumbSpinlock::DumbSpinlock (bool * locked, bool lock_initially = true) inline
Definition at line 42 of file dumb_spinlock.hpp.
References lock().
                                                          : locked_by_me_(false), locked_(locked) {
     if (lock_initially) {
       lock();
     }
   }
foedus::assorted::DumbSpinlock::~DumbSpinlock () inline
automatically unlocks when out of scope.
Definition at line 48 of file dumb_spinlock.hpp.
References unlock().
 { unlock(); }
Member Function Documentation
bool foedus::assorted::DumbSpinlock::is_locked_by_me () const inline
Definition at line 50 of file dumb_spinlock.hpp.
Referenced by foedus::storage::masstree::GrowFirstLayerRoot::run().
 { return locked_by_me_; }
void foedus::assorted::DumbSpinlock::lock () inline
Locks it if I haven't locked it yet.
This method is idempotent.
Definition at line 53 of file dumb_spinlock.hpp.
References SPINLOCK_WHILE, and try_lock().
Referenced by DumbSpinlock().
               {
     SPINLOCK_WHILE(true) {
       if (try_lock()) {
         break;
       }
     }
   }
bool foedus::assorted::DumbSpinlock::try_lock () inline
try-version of the lock.
Definition at line 61 of file dumb_spinlock.hpp.
References ASSERT_ND.
Referenced by lock(), and foedus::storage::masstree::GrowFirstLayerRoot::run().
                   {
     if (locked_by_me_) {
       return true;  // already locked
     }
     bool expected = false;
     if (raw_atomic_compare_exchange_weak<bool>(locked_, &expected, true)) {
       ASSERT_ND(*locked_);
       locked_by_me_ = true;
       return true;
     } else {
       ASSERT_ND(expected);
       return false;
     }
   }
void foedus::assorted::DumbSpinlock::unlock () inline
Unlocks it if I locked it.
This method is idempotent. You can safely call many times.
Definition at line 78 of file dumb_spinlock.hpp.
References ASSERT_ND, and foedus::assorted::memory_fence_acq_rel().
Referenced by ~DumbSpinlock().
                 {
     if (locked_by_me_) {
       ASSERT_ND(*locked_);
       locked_by_me_ = false;
       assorted::memory_fence_acq_rel();
       *locked_ = false;
       assorted::memory_fence_acq_rel();
     }
   }
The documentation for this class was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/assorted/dumb_spinlock.hpp