libfoedus-core: foedus::storage::Storage< CONTROL_BLOCK > Class Template Reference
foedus::storage::Storage< CONTROL_BLOCK > Class Template Reference
FOEDUS Components » Storage Manager
Represents one key-value store.
Detailed Description
template<typename CONTROL_BLOCK>
class foedus::storage::Storage< CONTROL_BLOCK >
Represents one key-value store.
This pure virtual class represents a set of key-value pairs. The individual storage class defines how they are stored.
Storage vs Tables/Indexes
One storage corresponds to one set of key-value pairs. A relational Table consists of one or more storages, primary storage and zero or more secondary storages (secondary indexes). However, libfoedus-core is agnostic to relational layer. It only knows about key-value store. The relation between primary and secondary storages are controlled by higher layers.
Instantiating Storage
Storage object is instantiated in two ways. To newly create a storage, the user invokes storage manager's create_xxx, which instantiates this object and calls create(). To retrieve an existing storage, bluh bluh
No virtual methods
As storages are placed in shared memory, everything is just data bits without RTTI. There is no point to use storage objects in polymorphoc way. Thus, no virtual methods.
Definition at line 116 of file storage.hpp.
#include <storage.hpp>
Public Member Functions
Storage ()
Storage (Engine *engine, CONTROL_BLOCK *control_block)
Storage (Engine *engine, StorageControlBlock *control_block)
Storage (Engine *engine, StorageId id)
Shorthand for engine->get_storage_manager()->get_storage(id)
Storage (Engine *engine, const StorageName &name)
Shorthand for engine->get_storage_manager()->get_storage(name)
Storage (const Storage &other)
Storage & operator= (const Storage &other)
StorageId get_id () const
Returns the unique ID of this storage.
StorageType get_type () const
Returns the type of this storage.
const StorageName & get_name () const
Returns the unique name of this storage.
const Metadata * get_metadata () const
Returns the metadata of this storage.
bool exists () const
Returns whether this storage is already created.
Public Member Functions inherited from foedus::Attachable< CONTROL_BLOCK >
Attachable ()
Attachable (Engine *engine)
Attachable (Engine *engine, CONTROL_BLOCK *control_block)
Attachable (CONTROL_BLOCK *control_block)
virtual ~Attachable ()
Attachable (const Attachable &other)
Attachable & operator= (const Attachable &other)
virtual void attach (CONTROL_BLOCK *control_block)
Attaches to the given shared memory.
bool is_attached () const
Returns whether the object has been already attached to some shared memory.
CONTROL_BLOCK * get_control_block () const
Engine * get_engine () const
void set_engine (Engine *engine)
Additional Inherited Members
Protected Attributes inherited from foedus::Attachable< CONTROL_BLOCK >
Engine * engine_
Most attachable object stores an engine pointer (local engine), so we define it here.
CONTROL_BLOCK * control_block_
The shared data on shared memory that has been initialized in some SOC or master engine.
Constructor & Destructor Documentation
template<typename CONTROL_BLOCK> foedus::storage::Storage< CONTROL_BLOCK >::Storage () inline
Definition at line 118 of file storage.hpp.
 : Attachable<CONTROL_BLOCK>() {}
template<typename CONTROL_BLOCK> foedus::storage::Storage< CONTROL_BLOCK >::Storage (Engine * engine, CONTROL_BLOCK * control_block) inline
Definition at line 119 of file storage.hpp.
     : Attachable<CONTROL_BLOCK>(engine, control_block) {}
template<typename CONTROL_BLOCK> foedus::storage::Storage< CONTROL_BLOCK >::Storage (Engine * engine, StorageControlBlock * control_block) inline
Definition at line 121 of file storage.hpp.
     : Attachable<CONTROL_BLOCK>(engine, reinterpret_cast<CONTROL_BLOCK*>(control_block)) {}
template<typename CONTROL_BLOCK> foedus::storage::Storage< CONTROL_BLOCK >::Storage (Engine * engine, StorageId id) inline
Shorthand for engine->get_storage_manager()->get_storage(id)
Definition at line 124 of file storage.hpp.
     : Attachable<CONTROL_BLOCK>(
         engine,
         reinterpret_cast<CONTROL_BLOCK*>(get_storage_control_block(engine, id))) {}
template<typename CONTROL_BLOCK> foedus::storage::Storage< CONTROL_BLOCK >::Storage (Engine * engine, const StorageName & name) inline
Shorthand for engine->get_storage_manager()->get_storage(name)
Definition at line 129 of file storage.hpp.
     : Attachable<CONTROL_BLOCK>(
       engine,
       reinterpret_cast<CONTROL_BLOCK*>(get_storage_control_block(engine, name))) {}
template<typename CONTROL_BLOCK> foedus::storage::Storage< CONTROL_BLOCK >::Storage (const Storage< CONTROL_BLOCK > & other) inline
Definition at line 134 of file storage.hpp.
     : Attachable<CONTROL_BLOCK>(other.engine_, other.control_block_) {}
Member Function Documentation
template<typename CONTROL_BLOCK> bool foedus::storage::Storage< CONTROL_BLOCK >::exists () const inline
Returns whether this storage is already created.
Definition at line 169 of file storage.hpp.
Referenced by foedus::storage::array::array_volatile_page_init(), foedus::storage::array::ArrayComposer::ArrayComposer(), foedus::storage::hash::HashPartitioner::design_partition(), foedus::storage::array::ArrayPartitioner::design_partition(), foedus::storage::Storage< MasstreeStorageControlBlock >::exists(), foedus::storage::hash::HashComposer::HashComposer(), and foedus::storage::masstree::MasstreeComposer::MasstreeComposer().
{
     return this->control_block_ != CXX11_NULLPTR &&
       reinterpret_cast<const StorageControlBlock*>(this->control_block_)->exists();
   }
template<typename CONTROL_BLOCK> StorageId foedus::storage::Storage< CONTROL_BLOCK >::get_id () const inline
Returns the unique ID of this storage.
Definition at line 145 of file storage.hpp.
Referenced by foedus::storage::array::operator<<(), foedus::storage::masstree::operator<<(), foedus::storage::sequential::operator<<(), and foedus::storage::hash::operator<<().
 { return get_metadata()->id_; }
template<typename CONTROL_BLOCK> const Metadata* foedus::storage::Storage< CONTROL_BLOCK >::get_metadata () const inline
Returns the metadata of this storage.
Returns
metadata for the individual storage instance. You can dynamic_cast it to derived metadata object.
Definition at line 162 of file storage.hpp.
Referenced by foedus::storage::array::ArrayComposer::construct_root(), foedus::storage::hash::HashComposer::construct_root(), foedus::storage::sequential::SequentialComposer::construct_root(), foedus::storage::Storage< MasstreeStorageControlBlock >::get_id(), foedus::storage::Storage< MasstreeStorageControlBlock >::get_name(), and foedus::storage::Storage< MasstreeStorageControlBlock >::get_type().
{
     return &(reinterpret_cast<const StorageControlBlock*>(this->control_block_)->meta_);
   }
template<typename CONTROL_BLOCK> const StorageName& foedus::storage::Storage< CONTROL_BLOCK >::get_name () const inline
Returns the unique name of this storage.
Definition at line 155 of file storage.hpp.
Referenced by foedus::storage::array::ArrayComposer::drop_root_volatile(), foedus::storage::hash::HashComposer::drop_root_volatile(), foedus::storage::masstree::MasstreeComposer::drop_root_volatile(), foedus::storage::array::ArrayComposer::drop_volatiles(), foedus::storage::hash::HashComposer::drop_volatiles(), foedus::storage::masstree::MasstreeComposer::drop_volatiles(), foedus::storage::array::operator<<(), foedus::storage::masstree::operator<<(), foedus::storage::sequential::operator<<(), and foedus::storage::hash::operator<<().
 { return get_metadata()->name_; }
template<typename CONTROL_BLOCK> StorageType foedus::storage::Storage< CONTROL_BLOCK >::get_type () const inline
Returns the type of this storage.
Definition at line 150 of file storage.hpp.
 { return get_metadata()->type_; }
template<typename CONTROL_BLOCK> Storage& foedus::storage::Storage< CONTROL_BLOCK >::operator= (const Storage< CONTROL_BLOCK > & other) inline
Definition at line 136 of file storage.hpp.
{
     this->engine_ = other.engine_;
     this->control_block_ = other.control_block_;
     return *this;
   }
The documentation for this class was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/storage/storage.hpp