libfoedus-core: foedus::storage::array::ArrayPage Class Reference
foedus::storage::array::ArrayPage Class Reference final
FOEDUS Components » Storage Manager » Array Storage
Represents one data page in Array Storage.
Detailed Description
Represents one data page in Array Storage.
This is a private implementation-details of Array Storage, thus file name ends with _impl. Do not include this header from a client program unless you know what you are doing.
Attention
Do NOT instantiate this object or derive from this class. A page is always reinterpret-ed from a pooled memory region. No meaningful RTTI.
Definition at line 46 of file array_page_impl.hpp.
#include <array_page_impl.hpp>
Classes
union Data
Data union for either leaf (dynamic size) or interior (fixed size).
Public Member Functions
ArrayPage ()=delete
ArrayPage (const ArrayPage &other)=delete
ArrayPage & operator= (const ArrayPage &other)=delete
PageHeader & header ()
const PageHeader & header () const
StorageId get_storage_id () const
uint16_t get_leaf_record_count () const
uint16_t get_payload_size () const
bool is_leaf () const
uint8_t get_level () const
const ArrayRange & get_array_range () const
void initialize_snapshot_page (Epoch initial_epoch, StorageId storage_id, SnapshotPagePointer page_id, uint16_t payload_size, uint8_t level, const ArrayRange &array_range)
Called only when this page is initialized.
void initialize_volatile_page (Epoch initial_epoch, StorageId storage_id, VolatilePagePointer page_id, uint16_t payload_size, uint8_t level, const ArrayRange &array_range)
const Record * get_leaf_record (uint16_t record, uint16_t payload_size) const __attribute__((always_inline))
Record * get_leaf_record (uint16_t record, uint16_t payload_size) __attribute__((always_inline))
const DualPagePointer & get_interior_record (uint16_t record) const __attribute__((always_inline))
DualPagePointer & get_interior_record (uint16_t record) __attribute__((always_inline))
uint8_t unused_dummy_func_reserved1 () const
uint32_t unused_dummy_func_reserved2 () const
Constructor & Destructor Documentation
foedus::storage::array::ArrayPage::ArrayPage () delete
foedus::storage::array::ArrayPage::ArrayPage (const ArrayPage & other) delete
Member Function Documentation
const ArrayRange& foedus::storage::array::ArrayPage::get_array_range () const inline
Definition at line 72 of file array_page_impl.hpp.
Referenced by foedus::storage::array::array_volatile_page_init(), foedus::storage::array::ArrayComposer::construct_root(), foedus::storage::array::ArrayComposeContext::execute(), foedus::storage::array::ArrayStoragePimpl::locate_record_for_read(), foedus::storage::array::ArrayStoragePimpl::locate_record_for_write(), foedus::storage::array::ArrayStoragePimpl::lookup_for_read(), foedus::storage::array::ArrayStoragePimpl::lookup_for_write(), and foedus::storage::array::ArrayStoragePimpl::prefetch_pages_recurse().
 { return array_range_; }
const DualPagePointer& foedus::storage::array::ArrayPage::get_interior_record (uint16_t record) const inline
Definition at line 105 of file array_page_impl.hpp.
Referenced by foedus::storage::array::ArrayComposer::construct_root(), foedus::storage::array::ArrayPartitioner::design_partition(), foedus::storage::array::ArrayComposer::drop_volatiles(), foedus::storage::array::ArrayStoragePimpl::follow_pointers_for_read_batch(), foedus::storage::array::ArrayStoragePimpl::follow_pointers_for_write_batch(), foedus::storage::array::ArrayStoragePimpl::hcc_reset_all_temperature_stat_intermediate(), foedus::storage::array::ArrayStoragePimpl::lookup_for_read(), foedus::storage::array::ArrayStoragePimpl::lookup_for_read_batch(), foedus::storage::array::ArrayStoragePimpl::lookup_for_write(), foedus::storage::array::ArrayStoragePimpl::lookup_for_write_batch(), foedus::storage::array::ArrayStoragePimpl::prefetch_pages_recurse(), and foedus::storage::array::ArrayStoragePimpl::verify_single_thread().
{
     return const_cast<ArrayPage*>(this)->get_interior_record(record);
   }
DualPagePointer& foedus::storage::array::ArrayPage::get_interior_record (uint16_t record) inline
Definition at line 108 of file array_page_impl.hpp.
References ASSERT_ND, foedus::storage::array::ArrayPage::Data::interior_data, is_leaf(), and foedus::storage::array::kInteriorFanout.
{
     ASSERT_ND(!is_leaf());
     ASSERT_ND(record < kInteriorFanout);
     return data_.interior_data[record];
   }
const Record* foedus::storage::array::ArrayPage::get_leaf_record (uint16_t record, uint16_t payload_size) const inline
Definition at line 91 of file array_page_impl.hpp.
References foedus::assorted::align8(), ASSERT_ND, is_leaf(), foedus::storage::array::kDataSize, foedus::storage::kRecordOverhead, and foedus::storage::array::ArrayPage::Data::leaf_data.
Referenced by foedus::storage::array::ArrayComposer::drop_root_volatile(), foedus::storage::array::ArrayStoragePimpl::follow_pointers_for_read_batch(), foedus::storage::array::ArrayStoragePimpl::follow_pointers_for_write_batch(), initialize_snapshot_page(), initialize_volatile_page(), foedus::storage::array::ArrayStoragePimpl::locate_record_for_read(), foedus::storage::array::ArrayStoragePimpl::locate_record_for_read_batch(), foedus::storage::array::ArrayStoragePimpl::locate_record_for_write(), foedus::storage::array::ArrayStoragePimpl::lookup_for_read(), foedus::storage::array::ArrayStoragePimpl::lookup_for_read_batch(), foedus::storage::array::ArrayStoragePimpl::lookup_for_write(), foedus::storage::array::ArrayStoragePimpl::lookup_for_write_batch(), and foedus::storage::array::ArrayStoragePimpl::verify_single_thread().
{
     ASSERT_ND(payload_size_ == payload_size);
     ASSERT_ND(is_leaf());
     ASSERT_ND((record + 1) * (kRecordOverhead + assorted::align8(payload_size_)) <= kDataSize);
     return reinterpret_cast<const Record*>(
       data_.leaf_data + record * (kRecordOverhead + assorted::align8(payload_size_)));
   }
Record* foedus::storage::array::ArrayPage::get_leaf_record (uint16_t record, uint16_t payload_size) inline
Definition at line 98 of file array_page_impl.hpp.
References foedus::assorted::align8(), ASSERT_ND, is_leaf(), foedus::storage::array::kDataSize, foedus::storage::kRecordOverhead, and foedus::storage::array::ArrayPage::Data::leaf_data.
{
     ASSERT_ND(payload_size_ == payload_size);
     ASSERT_ND(is_leaf());
     ASSERT_ND((record + 1) * (kRecordOverhead + assorted::align8(payload_size_)) <= kDataSize);
     return reinterpret_cast<Record*>(
       data_.leaf_data + record * (kRecordOverhead + assorted::align8(payload_size_)));
   }
uint16_t foedus::storage::array::ArrayPage::get_leaf_record_count () const inline
Definition at line 66 of file array_page_impl.hpp.
References foedus::assorted::align8(), foedus::storage::array::kDataSize, and foedus::storage::kRecordOverhead.
Referenced by initialize_snapshot_page(), initialize_volatile_page(), and foedus::storage::array::ArrayStoragePimpl::verify_single_thread().
{
     return kDataSize / (kRecordOverhead + assorted::align8(payload_size_));
   }
uint8_t foedus::storage::array::ArrayPage::get_level () const inline
Definition at line 71 of file array_page_impl.hpp.
Referenced by foedus::storage::array::array_volatile_page_init(), foedus::storage::array::ArrayStoragePimpl::follow_pointer(), foedus::storage::array::ArrayStoragePimpl::follow_pointers_for_read_batch(), foedus::storage::array::ArrayStoragePimpl::follow_pointers_for_write_batch(), foedus::storage::array::ArrayStoragePimpl::hcc_reset_all_temperature_stat_intermediate(), and foedus::storage::array::ArrayStoragePimpl::prefetch_pages_recurse().
 { return level_; }
uint16_t foedus::storage::array::ArrayPage::get_payload_size () const inline
Definition at line 69 of file array_page_impl.hpp.
 { return payload_size_; }
StorageId foedus::storage::array::ArrayPage::get_storage_id () const inline
Definition at line 65 of file array_page_impl.hpp.
References foedus::storage::PageHeader::storage_id_.
Referenced by foedus::storage::array::array_volatile_page_init().
 { return header_.storage_id_; }
PageHeader& foedus::storage::array::ArrayPage::header () inline
Definition at line 63 of file array_page_impl.hpp.
Referenced by foedus::storage::array::ArrayComposer::construct_root(), foedus::storage::array::ArrayStoragePimpl::follow_pointers_for_read_batch(), foedus::storage::array::ArrayStoragePimpl::follow_pointers_for_write_batch(), foedus::storage::array::ArrayStoragePimpl::hcc_reset_all_temperature_stat_intermediate(), foedus::storage::array::ArrayStoragePimpl::lookup_for_read(), foedus::storage::array::ArrayStoragePimpl::lookup_for_read_batch(), foedus::storage::array::ArrayStoragePimpl::lookup_for_write(), foedus::storage::array::ArrayStoragePimpl::lookup_for_write_batch(), and foedus::storage::array::ArrayStoragePimpl::prefetch_pages_recurse().
 { return header_; }
const PageHeader& foedus::storage::array::ArrayPage::header () const inline
Definition at line 64 of file array_page_impl.hpp.
 { return header_; }
void foedus::storage::array::ArrayPage::initialize_snapshot_page (Epoch initial_epoch, StorageId storage_id, SnapshotPagePointer page_id, uint16_t payload_size, uint8_t level, const ArrayRange & array_range)
Called only when this page is initialized.
Definition at line 32 of file array_page_impl.cpp.
References ASSERT_ND, get_leaf_record(), get_leaf_record_count(), foedus::storage::PageHeader::init_snapshot(), is_leaf(), foedus::Epoch::is_valid(), foedus::storage::kArrayPageType, and foedus::storage::kPageSize.
Referenced by foedus::storage::array::ArrayComposer::construct_root().
{
   ASSERT_ND(initial_epoch.is_valid());
   std::memset(this, 0, kPageSize);
   header_.init_snapshot(page_id, storage_id, kArrayPageType);
   payload_size_ = payload_size;
   level_ = level;
   array_range_ = array_range;
   if (is_leaf()) {
     uint16_t records = get_leaf_record_count();
     for (uint16_t i = 0; i < records; ++i) {
       auto* rec = get_leaf_record(i, payload_size);
       rec->owner_id_.lock_.reset();
       rec->owner_id_.xct_id_.set_epoch(initial_epoch);
     }
   }
 }
void foedus::storage::array::ArrayPage::initialize_volatile_page (Epoch initial_epoch, StorageId storage_id, VolatilePagePointer page_id, uint16_t payload_size, uint8_t level, const ArrayRange & array_range)
Definition at line 55 of file array_page_impl.cpp.
References ASSERT_ND, get_leaf_record(), get_leaf_record_count(), foedus::storage::PageHeader::init_volatile(), is_leaf(), foedus::Epoch::is_valid(), foedus::storage::kArrayPageType, and foedus::storage::kPageSize.
Referenced by foedus::storage::array::array_volatile_page_init(), and foedus::storage::array::ArrayStoragePimpl::load_empty().
{
   ASSERT_ND(initial_epoch.is_valid());
   std::memset(this, 0, kPageSize);
   header_.init_volatile(page_id, storage_id, kArrayPageType);
   payload_size_ = payload_size;
   level_ = level;
   array_range_ = array_range;
   if (is_leaf()) {
     uint16_t records = get_leaf_record_count();
     for (uint16_t i = 0; i < records; ++i) {
       auto* rec = get_leaf_record(i, payload_size);
       rec->owner_id_.lock_.reset();
       rec->owner_id_.xct_id_.set_epoch(initial_epoch);
     }
   }
 }
bool foedus::storage::array::ArrayPage::is_leaf () const inline
Definition at line 70 of file array_page_impl.hpp.
Referenced by foedus::storage::array::ArrayPartitioner::design_partition(), foedus::storage::array::ArrayComposer::drop_root_volatile(), foedus::storage::array::ArrayComposer::drop_volatiles(), foedus::storage::array::ArrayStoragePimpl::follow_pointer(), foedus::storage::array::ArrayStoragePimpl::follow_pointers_for_read_batch(), foedus::storage::array::ArrayStoragePimpl::follow_pointers_for_write_batch(), get_interior_record(), get_leaf_record(), foedus::storage::array::ArrayStoragePimpl::hcc_reset_all_temperature_stat_intermediate(), initialize_snapshot_page(), initialize_volatile_page(), foedus::storage::array::ArrayStoragePimpl::locate_record_for_read(), foedus::storage::array::ArrayStoragePimpl::locate_record_for_write(), foedus::storage::array::ArrayStoragePimpl::lookup_for_read(), foedus::storage::array::ArrayStoragePimpl::lookup_for_write(), foedus::storage::array::ArrayStoragePimpl::prefetch_pages(), and foedus::storage::array::ArrayStoragePimpl::verify_single_thread().
 { return level_ == 0; }
ArrayPage& foedus::storage::array::ArrayPage::operator= (const ArrayPage & other) delete
uint8_t foedus::storage::array::ArrayPage::unused_dummy_func_reserved1 () const inline
Definition at line 114 of file array_page_impl.hpp.
 { return reserved1_; }
uint32_t foedus::storage::array::ArrayPage::unused_dummy_func_reserved2 () const inline
Definition at line 115 of file array_page_impl.hpp.
 { return reserved2_; }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/storage/array/array_page_impl.hpp
/home/shino/foedus_code/foedus-core/src/foedus/storage/array/array_page_impl.cpp