libfoedus-core: foedus::soc::SharedCond Class Reference
foedus::soc::SharedCond Class Reference final
FOEDUS Components » SOC and IPC
A conditional variable that can be placed in shared memory and used from multiple processes.
Detailed Description
A conditional variable that can be placed in shared memory and used from multiple processes.
Analogous to SharedMutex. This is for conditional variable. This class also avoids the pthread bug described in foedus::thread::ConditionVariable. This file does not assume C++11.
Definition at line 39 of file shared_cond.hpp.
#include <shared_cond.hpp>
Public Member Functions
SharedCond ()
~SharedCond ()
SharedCond (const SharedCond &)=delete
SharedCond & operator= (const SharedCond &)=delete
void initialize ()
void uninitialize ()
bool is_initialized () const
void wait (SharedMutexScope *scope)
Unconditionally wait for the event.
bool timedwait (SharedMutexScope *scope, uint64_t timeout_nanosec)
Wait for the event up to the given timeout.
void broadcast (SharedMutexScope *scope)
Unblock all waiters.
void broadcast_nolock ()
Unblock all waiters without a mutex held by the signaller.
void signal (SharedMutexScope *scope)
Unblock one waiter.
SharedMutex * get_mutex ()
Returns the mutex that protects this condition variable.
bool exists_waiters () const
A non-synchronized method to tell seemingly whether there is a waiter or not.
Constructor & Destructor Documentation
foedus::soc::SharedCond::SharedCond () inline
Definition at line 41 of file shared_cond.hpp.
References initialize().
 : initialized_(false), waiters_(0), notifiers_(0) { initialize(); }
foedus::soc::SharedCond::~SharedCond () inline
Definition at line 42 of file shared_cond.hpp.
References uninitialize().
 { uninitialize(); }
foedus::soc::SharedCond::SharedCond (const SharedCond &) delete
Member Function Documentation
void foedus::soc::SharedCond::broadcast (SharedMutexScope * scope)
Unblock all waiters.
Parameters
[in,out] scope the mutex scope that protects this conditional variable
Precondition
scope->is_locked_by_me() (the caller must have locked it)
scope->get_mutex() == &mutex_ (the scope should be protecting this variable)
Postcondition
scope is no longer locked
You should set the real condition variable itself after locking the mutex before calling this method to avoid lost signals.
Attention
Consider using broadcast_nolock(). We encountered a deadlock bug with a very high contention. We were not sure where the problem is; maybe the glibc's pthread_cond_broadcast() issue, simply our code's bug (lack or duplicated release etc), or a contention that causes repeated wakeup/broadcast loop. But, we did observe that the problem went away with broadcast_nolock().
Deprecated:
see above. But, not yet 100% sure why it happened... We should have a wiki entry to track this issue.
Definition at line 123 of file shared_cond.cpp.
References ASSERT_ND, foedus::assorted::memory_fence_acq_rel(), foedus::assorted::spinlock_yield(), foedus::soc::ugly_atomic_dec(), foedus::soc::ugly_atomic_inc(), and foedus::soc::SharedMutexScope::unlock().
{
   common_assert(scope);
   ugly_atomic_inc(&notifiers_);
   // to avoid the glibc 2.18 pthread bug in broadcast, we use signal, one by one.
   scope->unlock();
   while (waiters_ > 0) {
     // int ret = ::pthread_cond_broadcast(&cond_);
     int ret = ::pthread_cond_signal(&cond_);
     ASSERT_ND(ret == 0);
     assorted::memory_fence_acq_rel();
     assorted::spinlock_yield();
   }
   ugly_atomic_dec(&notifiers_);
 }
void foedus::soc::SharedCond::broadcast_nolock ()
Unblock all waiters without a mutex held by the signaller.
You should set the real condition variable itself after locking the mutex, AND release it before calling this method. This method does not assume a mutex, thus a lost signal is possible.
Definition at line 141 of file shared_cond.cpp.
References ASSERT_ND, foedus::soc::ugly_atomic_dec(), and foedus::soc::ugly_atomic_inc().
{
   ugly_atomic_inc(&notifiers_);
   // int ret = ::pthread_cond_broadcast(&cond_);
   int ret = ::pthread_cond_signal(&cond_);
   ASSERT_ND(ret == 0);
   ugly_atomic_dec(&notifiers_);
 }
bool foedus::soc::SharedCond::exists_waiters () const inline
A non-synchronized method to tell seemingly whether there is a waiter or not.
The caller is responsible for using this method with appropriate fences, retries, etc.
Definition at line 134 of file shared_cond.hpp.
 { return waiters_ != 0; }
SharedMutex* foedus::soc::SharedCond::get_mutex () inline
Returns the mutex that protects this condition variable.
You must lock this mutex BEFORE you call wait/notify/etc in this class along with checking the real boolean condition itself. Otherwise, you will get lost signals. This is why the methods above receive SharedMutexScope as parameter.
Definition at line 128 of file shared_cond.hpp.
 { return &mutex_; }
void foedus::soc::SharedCond::initialize ()
Definition at line 33 of file shared_cond.cpp.
References ASSERT_ND, foedus::soc::SharedMutex::initialize(), and uninitialize().
Referenced by SharedCond().
{
   uninitialize();
   waiters_ = 0;
   notifiers_ = 0;
   mutex_.initialize();
   int attr_ret = ::pthread_condattr_init(&attr_);
   ASSERT_ND(attr_ret == 0);
   int shared_ret = ::pthread_condattr_setpshared(&attr_, PTHREAD_PROCESS_SHARED);
   ASSERT_ND(shared_ret == 0);
   int cond_ret = ::pthread_cond_init(&cond_, &attr_);
   ASSERT_ND(cond_ret == 0);
   initialized_ = true;
 }
bool foedus::soc::SharedCond::is_initialized () const inline
Definition at line 50 of file shared_cond.hpp.
 { return initialized_; }
SharedCond& foedus::soc::SharedCond::operator= (const SharedCond &) delete
void foedus::soc::SharedCond::signal (SharedMutexScope * scope)
Unblock one waiter.
Parameters
[in,out] scope the mutex scope that protects this conditional variable
Precondition
scope->is_locked_by_me() (the caller must have locked it)
scope->get_mutex() == &mutex_ (the scope should be protecting this variable)
Postcondition
scope is no longer locked
You should set the real condition variable itself after locking the mutex before calling this method to avoid lost signals.
Definition at line 149 of file shared_cond.cpp.
References ASSERT_ND, foedus::soc::ugly_atomic_dec(), foedus::soc::ugly_atomic_inc(), and foedus::soc::SharedMutexScope::unlock().
{
   common_assert(scope);
   ugly_atomic_inc(&notifiers_);
   scope->unlock();
   if (waiters_ > 0) {
     int ret = ::pthread_cond_signal(&cond_);
     ASSERT_ND(ret == 0);
   }
   ugly_atomic_dec(&notifiers_);
 }
bool foedus::soc::SharedCond::timedwait (SharedMutexScope * scope, uint64_t timeout_nanosec)
Wait for the event up to the given timeout.
Parameters
[in,out] scope the mutex scope that protects this conditional variable
[in] timeout_nanosec timeout in nanoseconds
Precondition
scope->is_locked_by_me() (the caller must have locked it)
scope->get_mutex() == &mutex_ (the scope should be protecting this variable)
Postcondition
scope is still locked
Returns
whether this thread received the signal (though still spurrious wakeup possible). false if timeout happened.
This method does NOT rule out spurrious wakeup as described above.
Definition at line 103 of file shared_cond.cpp.
References ASSERT_ND, CXX11_NULLPTR, foedus::soc::SharedMutex::get_raw_mutex(), foedus::soc::ugly_atomic_dec(), and foedus::soc::ugly_atomic_inc().
{
   common_assert(scope);
   struct timespec timeout;
   struct timeval now;
   ::gettimeofday(&now, CXX11_NULLPTR);
   timeout.tv_sec = now.tv_sec + (timeout_nanosec / 1000000000ULL);
   timeout.tv_nsec = now.tv_usec * 1000ULL + timeout_nanosec % 1000000000ULL;
   timeout.tv_sec += (timeout.tv_nsec) / 1000000000ULL;
   timeout.tv_nsec %= 1000000000ULL;
   ugly_atomic_inc(&waiters_);
   int ret = ::pthread_cond_timedwait(&cond_, mutex_.get_raw_mutex(), &timeout);
   ASSERT_ND(ret == 0 || ret == ETIMEDOUT);
   ASSERT_ND(waiters_ > 0);
   ugly_atomic_dec(&waiters_);
   return ret == 0;
 }
void foedus::soc::SharedCond::uninitialize ()
Definition at line 50 of file shared_cond.cpp.
References ASSERT_ND, foedus::assorted::memory_fence_acquire(), foedus::assorted::spinlock_yield(), and foedus::soc::SharedMutex::uninitialize().
Referenced by initialize(), and ~SharedCond().
{
   if (!initialized_) {
     return;
   }
   assorted::memory_fence_acquire();
   ASSERT_ND(waiters_ == 0);
   // we must wait until all notifiers exit notify_all.
   // this assumes no new notifiers are newly coming in this situation.
   while (notifiers_ > 0) {
     assorted::spinlock_yield();
     assorted::memory_fence_acquire();
   }
   mutex_.uninitialize();
   int cond_ret = ::pthread_cond_destroy(&cond_);
   ASSERT_ND(cond_ret == 0);
   int attr_ret = ::pthread_condattr_destroy(&attr_);
   ASSERT_ND(attr_ret == 0);
   initialized_ = false;
 }
void foedus::soc::SharedCond::wait (SharedMutexScope * scope)
Unconditionally wait for the event.
Parameters
[in,out] scope the mutex scope that protects this conditional variable
Precondition
scope->is_locked_by_me() (the caller must have locked it)
scope->get_mutex() == &mutex_ (the scope should be protecting this variable)
Postcondition
scope is still locked
This method does NOT rule out spurrious wakeup. We could receive a lambda to check the condition, but this class should be C++11-free. So, the caller should do the loop herself if she doesn't want a spurrious wakeup. Instead, you can easily avoid lost signals by checking the condition after locking the mutex before calling this method.
Definition at line 90 of file shared_cond.cpp.
References ASSERT_ND, foedus::soc::SharedMutex::get_raw_mutex(), foedus::soc::ugly_atomic_dec(), and foedus::soc::ugly_atomic_inc().
{
   common_assert(scope);
   ugly_atomic_inc(&waiters_);
   // probably pthread_cond_wait implies a full fence, but to make sure.
   int ret = ::pthread_cond_wait(&cond_, mutex_.get_raw_mutex());
   ASSERT_ND(ret == 0);
   ASSERT_ND(waiters_ > 0);
   ugly_atomic_dec(&waiters_);
 }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/soc/shared_cond.hpp
/home/shino/foedus_code/foedus-core/src/foedus/soc/shared_cond.cpp