libfoedus-core: foedus::storage::sequential::SequentialPartitioner Class Reference
foedus::storage::sequential::SequentialPartitioner Class Reference final
FOEDUS Components » Storage Manager » Sequential Storage
Partitioner for an sequential storage.
Detailed Description
Partitioner for an sequential storage.
Partitioning/sorting policy for Sequential Storage is super simple; it does nothing. We put all logs in node-x to snapshot of node-x for the best performance. As the only read access pattern is full-scan, we don't care partitioning. We just minimize the communication cost by this policy. No sorting either.
Note
This is a private implementation-details of Sequential Storage, thus file name ends with _impl. Do not include this header from a client program. There is no case client program needs to access this internal class.
Definition at line 50 of file sequential_partitioner_impl.hpp.
#include <sequential_partitioner_impl.hpp>
Public Member Functions
SequentialPartitioner (Partitioner *parent)
ErrorStack design_partition (const Partitioner::DesignPartitionArguments &args)
bool is_partitionable () const
void partition_batch (const Partitioner::PartitionBatchArguments &args) const
void sort_batch (const Partitioner::SortBatchArguments &args) const
Friends
std::ostream & operator<< (std::ostream &o, const SequentialPartitioner &v)
Constructor & Destructor Documentation
foedus::storage::sequential::SequentialPartitioner::SequentialPartitioner (Partitioner * parent) explicit
Definition at line 27 of file sequential_partitioner_impl.cpp.
   : engine_(parent->get_engine()),
     id_(parent->get_storage_id()),
     metadata_(PartitionerMetadata::get_metadata(engine_, id_)) {
 }
Member Function Documentation
ErrorStack foedus::storage::sequential::SequentialPartitioner::design_partition (const Partitioner::DesignPartitionArguments & args)
Definition at line 33 of file sequential_partitioner_impl.cpp.
References foedus::storage::PartitionerMetadata::data_offset_, foedus::storage::PartitionerMetadata::data_size_, foedus::kRetOk, and foedus::storage::PartitionerMetadata::valid_.
Referenced by foedus::storage::Partitioner::design_partition().
{
   // no data required for SequentialPartitioner
   metadata_->data_offset_ = 0;
   metadata_->data_size_ = 0;
   metadata_->valid_ = true;
   return kRetOk;
 }
bool foedus::storage::sequential::SequentialPartitioner::is_partitionable () const inline
Definition at line 55 of file sequential_partitioner_impl.hpp.
Referenced by foedus::storage::Partitioner::is_partitionable().
 { return true; }
void foedus::storage::sequential::SequentialPartitioner::partition_batch (const Partitioner::PartitionBatchArguments & args) const
Definition at line 42 of file sequential_partitioner_impl.cpp.
References foedus::storage::Partitioner::PartitionBatchArguments::local_partition_, foedus::storage::Partitioner::PartitionBatchArguments::logs_count_, and foedus::storage::Partitioner::PartitionBatchArguments::results_.
Referenced by foedus::storage::Partitioner::partition_batch().
{
   // all local
   for (uint32_t i = 0; i < args.logs_count_; ++i) {
     args.results_[i] = args.local_partition_;
   }
 }
void foedus::storage::sequential::SequentialPartitioner::sort_batch (const Partitioner::SortBatchArguments & args) const
Definition at line 50 of file sequential_partitioner_impl.cpp.
References foedus::storage::Partitioner::SortBatchArguments::log_positions_, foedus::storage::Partitioner::SortBatchArguments::logs_count_, foedus::storage::Partitioner::SortBatchArguments::output_buffer_, and foedus::storage::Partitioner::SortBatchArguments::written_count_.
Referenced by foedus::storage::Partitioner::sort_batch().
{
   // no sorting needed.
   std::memcpy(
     args.output_buffer_,
     args.log_positions_,
     sizeof(snapshot::BufferPosition) * args.logs_count_);
   *args.written_count_ = args.logs_count_;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const SequentialPartitioner & v) friend
Definition at line 60 of file sequential_partitioner_impl.cpp.
{
   o << "<SequentialPartitioner>"
     << "</SequentialPartitioner>";
   return o;
 }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/storage/sequential/sequential_partitioner_impl.hpp
/home/shino/foedus_code/foedus-core/src/foedus/storage/sequential/sequential_partitioner_impl.cpp