libfoedus-core: foedus::assorted::ZipfianRandom Class Reference
foedus::assorted::ZipfianRandom Class Reference
FOEDUS Programming Idioms » Assorted Methods/Classes
A simple zipfian generator based off of YCSB's Java implementation.
Detailed Description
A simple zipfian generator based off of YCSB's Java implementation.
The major user is YCSB. 0 <= theta < 1, higher means more skewed. Generates a random number between 0 and max_.
Definition at line 37 of file zipfian_random.hpp.
#include <zipfian_random.hpp>
Public Member Functions
void init (uint64_t items, double theta, uint64_t urnd_seed)
ZipfianRandom (uint64_t items, double theta, uint64_t urnd_seed)
ZipfianRandom ()
uint64_t next ()
uint64_t get_current_seed () const
void set_current_seed (uint64_t seed)
Constructor & Destructor Documentation
foedus::assorted::ZipfianRandom::ZipfianRandom (uint64_t items, double theta, uint64_t urnd_seed) inline
Definition at line 57 of file zipfian_random.hpp.
References init().
{
     init(items, theta, urnd_seed);
   }
foedus::assorted::ZipfianRandom::ZipfianRandom () inline
Definition at line 61 of file zipfian_random.hpp.
 {}
Member Function Documentation
uint64_t foedus::assorted::ZipfianRandom::get_current_seed () const inline
Definition at line 78 of file zipfian_random.hpp.
References foedus::assorted::UniformRandom::get_current_seed().
 { return urnd_.get_current_seed(); }
void foedus::assorted::ZipfianRandom::init (uint64_t items, double theta, uint64_t urnd_seed) inline
Definition at line 48 of file zipfian_random.hpp.
References foedus::assorted::UniformRandom::set_current_seed().
Referenced by ZipfianRandom().
{
     max_ = items - 1;
     theta_ = theta;
     zetan_ = zeta(items);
     alpha_ = 1.0 / (1.0 - theta_);
     eta_ = (1 - std::pow(2.0 / items, 1 - theta_)) / (1 - zeta(2) / zetan_);
     urnd_.set_current_seed(urnd_seed);
   }
uint64_t foedus::assorted::ZipfianRandom::next () inline
Definition at line 63 of file zipfian_random.hpp.
References foedus::assorted::UniformRandom::uniform_within().
                   {
     double u = urnd_.uniform_within(0, max_) / static_cast<double>(max_);
     double uz = u * zetan_;
     if (uz < 1.0) {
       return 0;
     }
     if (uz < 1.0 + std::pow(0.5, theta_)) {
       return 1;
     }
     uint64_t ret = static_cast<uint64_t>(max_ * std::pow(eta_ * u - eta_ + 1, alpha_));
     return ret;
   }
void foedus::assorted::ZipfianRandom::set_current_seed (uint64_t seed) inline
Definition at line 79 of file zipfian_random.hpp.
References foedus::assorted::UniformRandom::set_current_seed().
 { urnd_.set_current_seed(seed); }
The documentation for this class was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/assorted/zipfian_random.hpp