libfoedus-core: foedus::thread::GrabFreeVolatilePagesScope Class Reference
foedus::thread::GrabFreeVolatilePagesScope Class Reference
Obtains multiple free volatile pages at once and releases them automatically when this object gets out of scope.
Detailed Description
Obtains multiple free volatile pages at once and releases them automatically when this object gets out of scope.
You can also dispatch some of the grabbed pages, which means they will NOT be released.
Definition at line 391 of file thread.hpp.
#include <thread.hpp>
Public Member Functions
GrabFreeVolatilePagesScope (Thread *context, memory::PagePoolOffset *offsets)
~GrabFreeVolatilePagesScope ()
ErrorCode grab (uint32_t count)
If this thread doesn't have enough free pages, no page is obtained, returning kErrorCodeMemoryNoFreePages.
void release ()
Idempotent.
uint32_t get_count () const
void dispatch (uint32_t index)
Call this when the page is placed somewhere.
memory::PagePoolOffset get (uint32_t index) const
Constructor & Destructor Documentation
foedus::thread::GrabFreeVolatilePagesScope::GrabFreeVolatilePagesScope (Thread * context, memory::PagePoolOffset * offsets) inline
Definition at line 393 of file thread.hpp.
     : context_(context), offsets_(offsets), count_(0) {}
foedus::thread::GrabFreeVolatilePagesScope::~GrabFreeVolatilePagesScope () inline
Definition at line 395 of file thread.hpp.
References release().
{
     release();
   }
Member Function Documentation
void foedus::thread::GrabFreeVolatilePagesScope::dispatch (uint32_t index) inline
Call this when the page is placed somewhere.
Definition at line 409 of file thread.hpp.
References ASSERT_ND.
Referenced by foedus::storage::masstree::SplitBorder::run(), and foedus::storage::masstree::SplitIntermediate::split_impl_no_error().
{
     ASSERT_ND(index < count_);
     offsets_[index] = 0;  // This entry will be skipped in release()
   }
memory::PagePoolOffset foedus::thread::GrabFreeVolatilePagesScope::get (uint32_t index) const inline
Definition at line 413 of file thread.hpp.
References ASSERT_ND.
Referenced by foedus::storage::masstree::SplitIntermediate::split_impl_no_error().
{
     ASSERT_ND(index < count_);
     return offsets_[index];
   }
uint32_t foedus::thread::GrabFreeVolatilePagesScope::get_count () const inline
Definition at line 406 of file thread.hpp.
 { return count_; }
ErrorCode foedus::thread::GrabFreeVolatilePagesScope::grab (uint32_t count)
If this thread doesn't have enough free pages, no page is obtained, returning kErrorCodeMemoryNoFreePages.
Definition at line 147 of file thread.cpp.
References foedus::thread::Thread::get_thread_memory(), foedus::memory::NumaCoreMemory::grab_free_volatile_page(), foedus::kErrorCodeMemoryNoFreePages, foedus::kErrorCodeOk, release(), and foedus::memory::NumaCoreMemory::release_free_volatile_page().
Referenced by foedus::storage::masstree::Adopt::adopt_case_b(), foedus::storage::masstree::SplitBorder::run(), and foedus::storage::masstree::SplitIntermediate::run().
{
   if (count_) {
     release();
   }
   memory::NumaCoreMemory* memory = context_->get_thread_memory();
   for (uint32_t i = 0; i < count; ++i) {
     offsets_[i] = memory->grab_free_volatile_page();
     if (offsets_[i] == 0) {
       for (uint32_t j = 0; j < i; ++j) {
         memory->release_free_volatile_page(offsets_[j]);
       }
       return kErrorCodeMemoryNoFreePages;
     }
   }
   count_ = count;
   return kErrorCodeOk;
 }
void foedus::thread::GrabFreeVolatilePagesScope::release ()
Idempotent.
You can release it at any moment.
Definition at line 165 of file thread.cpp.
References foedus::thread::Thread::get_thread_memory(), and foedus::memory::NumaCoreMemory::release_free_volatile_page().
Referenced by grab(), and ~GrabFreeVolatilePagesScope().
{
   memory::NumaCoreMemory* memory = context_->get_thread_memory();
   for (uint32_t i = 0; i < count_; ++i) {
     if (offsets_[i] != 0) {
       memory->release_free_volatile_page(offsets_[i]);
     }
   }
   count_ = 0;
 }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/thread/thread.hpp
/home/shino/foedus_code/foedus-core/src/foedus/thread/thread.cpp