libfoedus-core: foedus::memory::NumaNodeMemoryRef Class Reference
foedus::memory::NumaNodeMemoryRef Class Reference final
FOEDUS Components » Memory Manager » Memory Hierarchy
A view of NumaNodeMemory for other SOCs and master engine.
Detailed Description
A view of NumaNodeMemory for other SOCs and master engine.
Definition at line 167 of file numa_node_memory.hpp.
#include <numa_node_memory.hpp>
Public Member Functions
NumaNodeMemoryRef ()=delete
NumaNodeMemoryRef (Engine *engine, foedus::thread::ThreadGroupId numa_node)
Engine * get_engine ()
foedus::thread::ThreadGroupId get_numa_node () const
PagePool * get_volatile_pool ()
std::string dump_free_memory_stat () const
Report rough statistics of free memory.
Constructor & Destructor Documentation
foedus::memory::NumaNodeMemoryRef::NumaNodeMemoryRef () delete
foedus::memory::NumaNodeMemoryRef::NumaNodeMemoryRef (Engine * engine, foedus::thread::ThreadGroupId numa_node)
Definition at line 235 of file numa_node_memory.cpp.
References foedus::memory::PagePool::attach(), foedus::soc::SharedMemoryRepo::get_node_memory_anchors(), foedus::Engine::get_options(), foedus::soc::SocManager::get_shared_memory_repo(), foedus::Engine::get_soc_manager(), foedus::soc::SharedMemoryRepo::get_volatile_pool(), foedus::EngineOptions::memory_, foedus::memory::MemoryOptions::page_pool_size_mb_per_node_, and foedus::soc::NodeMemoryAnchors::volatile_pool_status_.
   : engine_(engine), numa_node_(numa_node) {
   soc::SharedMemoryRepo* memory_repo = engine->get_soc_manager()->get_shared_memory_repo();
   volatile_pool_.attach(
     memory_repo->get_node_memory_anchors(numa_node)->volatile_pool_status_,
     memory_repo->get_volatile_pool(numa_node),
     static_cast<uint64_t>(engine->get_options().memory_.page_pool_size_mb_per_node_) << 20,
     false,
     false);
 }
Member Function Documentation
std::string foedus::memory::NumaNodeMemoryRef::dump_free_memory_stat () const
Report rough statistics of free memory.
Definition at line 246 of file numa_node_memory.cpp.
References foedus::memory::PagePool::Stat::allocated_pages_, foedus::memory::PagePool::get_stat(), and foedus::memory::PagePool::Stat::total_pages_.
Referenced by foedus::memory::EngineMemory::dump_free_memory_stat().
{
   std::stringstream ret;
   PagePool::Stat volatile_stat = volatile_pool_.get_stat();
   ret << "    Volatile-Pool: " << volatile_stat.allocated_pages_ << " allocated pages, "
     << volatile_stat.total_pages_ << " total pages, "
     << (volatile_stat.total_pages_ - volatile_stat.allocated_pages_) << " free pages"
     << std::endl;
   return ret.str();
 }
Engine* foedus::memory::NumaNodeMemoryRef::get_engine () inline
Definition at line 172 of file numa_node_memory.hpp.
 { return engine_; }
foedus::thread::ThreadGroupId foedus::memory::NumaNodeMemoryRef::get_numa_node () const inline
Definition at line 173 of file numa_node_memory.hpp.
 { return numa_node_; }
PagePool* foedus::memory::NumaNodeMemoryRef::get_volatile_pool () inline
Definition at line 175 of file numa_node_memory.hpp.
Referenced by foedus::storage::hash::HashStoragePimpl::create(), foedus::storage::sequential::SequentialStoragePimpl::drop(), foedus::storage::Composer::DropVolatilesArguments::drop(), foedus::snapshot::SnapshotManagerPimpl::drop_volatile_pages_parallel(), foedus::storage::sequential::SequentialComposer::drop_volatiles(), foedus::thread::ThreadPimpl::flush_retired_volatile_page(), foedus::storage::sequential::SequentialStoragePimpl::for_every_page(), foedus::memory::DivvyupPageGrabBatch::grab(), foedus::memory::EngineMemory::grab_one_volatile_page(), foedus::storage::sequential::SequentialStoragePimpl::initialize_head_tail_pages(), foedus::memory::EngineMemory::initialize_once(), foedus::storage::masstree::MasstreeStoragePimpl::load_empty(), foedus::memory::RoundRobinPageGrabBatch::release_all(), foedus::memory::DivvyupPageGrabBatch::release_all(), foedus::memory::PageReleaseBatch::release_chunk(), and foedus::thread::ThreadPimpl::uninitialize_once().
 { return &volatile_pool_; }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/memory/numa_node_memory.hpp
/home/shino/foedus_code/foedus-core/src/foedus/memory/numa_node_memory.cpp