libfoedus-core: foedus::thread::ThreadRef Class Reference
foedus::thread::ThreadRef Class Reference final
FOEDUS Components » Thread and Thread-Group
A view of Thread object for other SOCs and master engine.
Detailed Description
A view of Thread object for other SOCs and master engine.
Definition at line 39 of file thread_ref.hpp.
#include <thread_ref.hpp>
Public Member Functions
ThreadRef ()
ThreadRef (Engine *engine, ThreadId id)
bool try_impersonate (const proc::ProcName &proc_name, const void *task_input, uint64_t task_input_size, ImpersonateSession *session)
Conditionally try to occupy this thread, or impersonate.
Engine * get_engine () const
ThreadId get_thread_id () const
ThreadGroupId get_numa_node () const
void * get_task_input_memory () const
void * get_task_output_memory () const
xct::McsWwBlock * get_mcs_ww_blocks () const
xct::McsRwSimpleBlock * get_mcs_rw_simple_blocks () const
xct::McsRwExtendedBlock * get_mcs_rw_extended_blocks () const
void get_mcs_rw_blocks (xct::McsRwSimpleBlock **out) const
void get_mcs_rw_blocks (xct::McsRwExtendedBlock **out) const
xct::McsRwAsyncMapping * get_mcs_rw_async_mapping (xct::UniversalLockId lock_id)
ThreadControlBlock * get_control_block () const
Epoch get_in_commit_epoch () const
uint64_t get_snapshot_cache_hits () const
uint64_t get_snapshot_cache_misses () const
void reset_snapshot_cache_counts () const
Friends
std::ostream & operator<< (std::ostream &o, const ThreadRef &v)
Constructor & Destructor Documentation
foedus::thread::ThreadRef::ThreadRef ()
Definition at line 36 of file thread_ref.cpp.
   : engine_(nullptr),
   id_(0),
   control_block_(nullptr),
   task_input_memory_(nullptr),
   task_output_memory_(nullptr),
   mcs_ww_blocks_(nullptr),
   mcs_rw_simple_blocks_(nullptr),
   mcs_rw_extended_blocks_(nullptr),
   mcs_rw_async_mappings_(nullptr) {}
foedus::thread::ThreadRef::ThreadRef (Engine * engine, ThreadId id)
Definition at line 47 of file thread_ref.cpp.
References foedus::soc::SocManager::get_shared_memory_repo(), foedus::Engine::get_soc_manager(), foedus::soc::SharedMemoryRepo::get_thread_memory_anchors(), foedus::soc::ThreadMemoryAnchors::mcs_rw_async_mappings_memories_, foedus::soc::ThreadMemoryAnchors::mcs_rw_extended_lock_memories_, foedus::soc::ThreadMemoryAnchors::mcs_rw_simple_lock_memories_, foedus::soc::ThreadMemoryAnchors::mcs_ww_lock_memories_, foedus::soc::ThreadMemoryAnchors::task_input_memory_, foedus::soc::ThreadMemoryAnchors::task_output_memory_, and foedus::soc::ThreadMemoryAnchors::thread_memory_.
                                                 : engine_(engine), id_(id) {
   soc::SharedMemoryRepo* memory_repo = engine->get_soc_manager()->get_shared_memory_repo();
   soc::ThreadMemoryAnchors* anchors = memory_repo->get_thread_memory_anchors(id);
   control_block_ = anchors->thread_memory_;
   task_input_memory_ = anchors->task_input_memory_;
   task_output_memory_ = anchors->task_output_memory_;
   mcs_ww_blocks_ = anchors->mcs_ww_lock_memories_;
   mcs_rw_simple_blocks_ = anchors->mcs_rw_simple_lock_memories_;
   mcs_rw_extended_blocks_ = anchors->mcs_rw_extended_lock_memories_;
   mcs_rw_async_mappings_ = anchors->mcs_rw_async_mappings_memories_;
 }
Member Function Documentation
ThreadControlBlock* foedus::thread::ThreadRef::get_control_block () const inline
Definition at line 71 of file thread_ref.hpp.
Referenced by foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::get_other_cur_block(), foedus::thread::ImpersonateSession::get_output_size(), foedus::thread::ImpersonateSession::get_result(), foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::get_rw_other_block(), foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::get_ww_other_block(), foedus::thread::ImpersonateSession::is_running(), foedus::thread::operator<<(), foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::other_waiting(), foedus::thread::ImpersonateSession::release(), foedus::thread::ImpersonateSession::wait(), and foedus::thread::ImpersonateSession::wait_for().
 { return control_block_; }
Engine* foedus::thread::ThreadRef::get_engine () const inline
Definition at line 59 of file thread_ref.hpp.
 { return engine_; }
Epoch foedus::thread::ThreadRef::get_in_commit_epoch () const
See also
foedus::xct::InCommitEpochGuard
Definition at line 114 of file thread_ref.cpp.
References foedus::thread::ThreadControlBlock::in_commit_epoch_, and foedus::assorted::memory_fence_acquire().
{
   assorted::memory_fence_acquire();
   return control_block_->in_commit_epoch_;
 }
xct::McsRwAsyncMapping * foedus::thread::ThreadRef::get_mcs_rw_async_mapping (xct::UniversalLockId lock_id)
Definition at line 149 of file thread_ref.cpp.
References ASSERT_ND, and foedus::thread::ThreadControlBlock::mcs_rw_async_mapping_current_.
Referenced by foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::get_rw_other_async_block().
{
   uint32_t nmappings = control_block_->mcs_rw_async_mapping_current_;
   for (uint32_t i = 0; i < nmappings; ++i) {
     if (mcs_rw_async_mappings_[i].lock_id_ == lock_id) {
       return mcs_rw_async_mappings_ + i;
     }
   }
   ASSERT_ND(false);
   return nullptr;
 }
void foedus::thread::ThreadRef::get_mcs_rw_blocks (xct::McsRwSimpleBlock ** out) const inline
Definition at line 68 of file thread_ref.hpp.
Referenced by foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::get_rw_other_block().
 { *out = mcs_rw_simple_blocks_; }
void foedus::thread::ThreadRef::get_mcs_rw_blocks (xct::McsRwExtendedBlock ** out) const inline
Definition at line 69 of file thread_ref.hpp.
 { *out = mcs_rw_extended_blocks_; }
xct::McsRwExtendedBlock* foedus::thread::ThreadRef::get_mcs_rw_extended_blocks () const inline
Definition at line 66 of file thread_ref.hpp.
 { return mcs_rw_extended_blocks_; }
xct::McsRwSimpleBlock* foedus::thread::ThreadRef::get_mcs_rw_simple_blocks () const inline
Definition at line 65 of file thread_ref.hpp.
 { return mcs_rw_simple_blocks_; }
xct::McsWwBlock* foedus::thread::ThreadRef::get_mcs_ww_blocks () const inline
Definition at line 64 of file thread_ref.hpp.
Referenced by foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::get_ww_other_block().
 { return mcs_ww_blocks_; }
ThreadGroupId foedus::thread::ThreadRef::get_numa_node () const inline
Definition at line 61 of file thread_ref.hpp.
References foedus::thread::decompose_numa_node().
 { return decompose_numa_node(id_); }
uint64_t foedus::thread::ThreadRef::get_snapshot_cache_hits () const
Definition at line 119 of file thread_ref.cpp.
References foedus::thread::ThreadControlBlock::stat_snapshot_cache_hits_.
{
   return control_block_->stat_snapshot_cache_hits_;
 }
uint64_t foedus::thread::ThreadRef::get_snapshot_cache_misses () const
Definition at line 123 of file thread_ref.cpp.
References foedus::thread::ThreadControlBlock::stat_snapshot_cache_misses_.
{
   return control_block_->stat_snapshot_cache_misses_;
 }
void* foedus::thread::ThreadRef::get_task_input_memory () const inline
Definition at line 62 of file thread_ref.hpp.
 { return task_input_memory_; }
void* foedus::thread::ThreadRef::get_task_output_memory () const inline
Definition at line 63 of file thread_ref.hpp.
Referenced by foedus::thread::ImpersonateSession::get_output(), and foedus::thread::ImpersonateSession::get_raw_output_buffer().
 { return task_output_memory_; }
ThreadId foedus::thread::ThreadRef::get_thread_id () const inline
Definition at line 60 of file thread_ref.hpp.
Referenced by foedus::thread::operator<<().
 { return id_; }
void foedus::thread::ThreadRef::reset_snapshot_cache_counts () const
Definition at line 127 of file thread_ref.cpp.
References foedus::thread::ThreadControlBlock::stat_snapshot_cache_hits_, and foedus::thread::ThreadControlBlock::stat_snapshot_cache_misses_.
{
   control_block_->stat_snapshot_cache_hits_ = 0;
   control_block_->stat_snapshot_cache_misses_ = 0;
 }
bool foedus::thread::ThreadRef::try_impersonate (const proc::ProcName & proc_name, const void * task_input, uint64_t task_input_size, ImpersonateSession * session)
Conditionally try to occupy this thread, or impersonate.
If it fails, it immediately returns.
Parameters
[in] proc_name the name of the procedure to run on this thread.
[in] task_input input data of arbitrary format for the procedure.
[in] task_input_size byte size of the input data to copy into the thread's memory.
[out] session the session to run on this thread. On success, the session receives a ticket so that the caller can wait for the completion.
Returns
whether successfully impersonated.
Definition at line 59 of file thread_ref.cpp.
References foedus::thread::ThreadControlBlock::current_ticket_, foedus::thread::ThreadControlBlock::input_len_, foedus::thread::ImpersonateSession::is_valid(), foedus::thread::kNotInitialized, foedus::thread::kWaitingForExecution, foedus::thread::kWaitingForTask, foedus::assorted::memory_fence_acquire(), foedus::thread::ThreadControlBlock::proc_name_, foedus::thread::ImpersonateSession::release(), foedus::soc::SharedPolling::signal(), foedus::thread::ThreadControlBlock::status_, foedus::thread::ThreadControlBlock::task_mutex_, foedus::thread::ImpersonateSession::thread_, foedus::thread::ImpersonateSession::ticket_, UNLIKELY, and foedus::thread::ThreadControlBlock::wakeup_cond_.
Referenced by foedus::thread::ThreadPoolPimpl::impersonate(), foedus::thread::ThreadPoolPimpl::impersonate_on_numa_core(), and foedus::thread::ThreadPoolPimpl::impersonate_on_numa_node().
{
   if (session->is_valid()) {
     LOG(WARNING) << "This session is already attached to some thread. Releasing the current one..";
     session->release();
   }
   if (UNLIKELY(control_block_->status_ == kNotInitialized)) {
     // The worker thread has not started working.
     // In this case, wait until it's initialized.
     while (control_block_->status_ == kNotInitialized) {
       std::this_thread::sleep_for(std::chrono::milliseconds(1));
       assorted::memory_fence_acquire();
     }
   }
   if (control_block_->status_ != kWaitingForTask) {
     DVLOG(0) << "(fast path) Someone already took Thread-" << id_ << ".";
     return false;
   }
   {
     // now, check it and grab it with mutex
     soc::SharedMutexScope scope(&control_block_->task_mutex_);
     if (control_block_->status_ != kWaitingForTask) {
       DVLOG(0) << "(slow path) Someone already took Thread-" << id_ << ".";
       return false;
     }
     session->thread_ = this;
     session->ticket_ = ++control_block_->current_ticket_;
     control_block_->proc_name_ = proc_name;
     control_block_->status_ = kWaitingForExecution;
     control_block_->input_len_ = task_input_size;
     if (task_input_size > 0) {
       std::memcpy(task_input_memory_, task_input, task_input_size);
     }
   }
   // waking up doesn't need mutex
   control_block_->wakeup_cond_.signal();
   VLOG(0) << "Impersonation succeeded for Thread-" << id_ << ".";
   return true;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const ThreadRef & v) friend
Definition at line 172 of file thread_ref.cpp.
{
   o << "ThreadRef-" << v.get_thread_id() << "[";
   o << "status=" << (v.get_control_block()->status_);
   o << "]";
   return o;
 }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/thread/thread_ref.hpp
/home/shino/foedus_code/foedus-core/src/foedus/thread/thread_ref.cpp