libfoedus-core: foedus::soc::SharedMutex Class Reference
foedus::soc::SharedMutex Class Reference final
FOEDUS Components » SOC and IPC
A mutex that can be placed in shared memory and used from multiple processes.
Detailed Description
A mutex that can be placed in shared memory and used from multiple processes.
C++11's mutex doesn't work for multi-process. We need to directly manipulate pthread_mutexattr_setpshared, hence this class. This object is also shared-memory friendly, meaning it has no heap-allocated member. It can be reset to a usable state via memset(zero), too.
Example usage:
SharedMutex mtx;
mtx.initialize();  // omit this if you invoked constructor. be careful on reinterpret_cast
mtx.lock();
do_something();
mtx.unlock();  // or automatically released when mtx gets out of scope
mtx.uninitialize();  // same above, but not the end of the world
Definition at line 47 of file shared_mutex.hpp.
#include <shared_mutex.hpp>
Public Member Functions
SharedMutex ()
~SharedMutex ()
SharedMutex (const SharedMutex &)=delete
SharedMutex & operator= (const SharedMutex &)=delete
void initialize (bool recursive=false)
void uninitialize ()
bool is_initialized () const
bool is_recursive () const
void lock ()
Unconditionally lock.
bool timedlock (uint64_t timeout_nanosec)
Try lock up to the given timeout.
bool trylock ()
Instantaneously try the lock.
void unlock ()
Unlock it.
pthread_mutex_t * get_raw_mutex ()
Constructor & Destructor Documentation
foedus::soc::SharedMutex::SharedMutex () inline
Definition at line 49 of file shared_mutex.hpp.
References initialize().
 : initialized_(false), recursive_(false) { initialize(); }
foedus::soc::SharedMutex::~SharedMutex () inline
Definition at line 50 of file shared_mutex.hpp.
References uninitialize().
 { uninitialize(); }
foedus::soc::SharedMutex::SharedMutex (const SharedMutex &) delete
Member Function Documentation
pthread_mutex_t* foedus::soc::SharedMutex::get_raw_mutex () inline
Definition at line 80 of file shared_mutex.hpp.
Referenced by foedus::soc::SharedCond::timedwait(), and foedus::soc::SharedCond::wait().
 { return &mutex_; }
void foedus::soc::SharedMutex::initialize (bool recursive = false)
Definition at line 29 of file shared_mutex.cpp.
References ASSERT_ND, and uninitialize().
Referenced by foedus::log::MetaLogControlBlock::initialize(), foedus::proc::ProcManagerControlBlock::initialize(), foedus::savepoint::SavepointManagerControlBlock::initialize(), foedus::memory::PagePoolControlBlock::initialize(), foedus::storage::StorageManagerControlBlock::initialize(), foedus::log::LogManagerControlBlock::initialize(), foedus::soc::SharedCond::initialize(), foedus::thread::ThreadControlBlock::initialize(), foedus::storage::StorageControlBlock::initialize(), foedus::log::LoggerControlBlock::initialize(), foedus::storage::PartitionerMetadata::initialize(), and SharedMutex().
{
   uninitialize();
   int attr_ret = ::pthread_mutexattr_init(&attr_);
   ASSERT_ND(attr_ret == 0);
   int shared_ret = ::pthread_mutexattr_setpshared(&attr_, PTHREAD_PROCESS_SHARED);
   ASSERT_ND(shared_ret == 0);
   int type_ret = ::pthread_mutexattr_settype(
     &attr_,
     recursive ? PTHREAD_MUTEX_RECURSIVE_NP : PTHREAD_MUTEX_FAST_NP);
   ASSERT_ND(type_ret == 0);
   int mutex_ret = ::pthread_mutex_init(&mutex_, &attr_);
   ASSERT_ND(mutex_ret == 0);
   recursive_ = recursive;
   initialized_ = true;
 }
bool foedus::soc::SharedMutex::is_initialized () const inline
Definition at line 58 of file shared_mutex.hpp.
Referenced by foedus::storage::array::ArrayPartitioner::ArrayPartitioner(), foedus::storage::hash::HashPartitioner::design_partition(), foedus::storage::array::ArrayPartitioner::design_partition(), foedus::storage::hash::HashPartitioner::HashPartitioner(), foedus::snapshot::SnapshotManagerPimpl::initialize_once(), and foedus::snapshot::SnapshotManagerPimpl::uninitialize_once().
 { return initialized_; }
bool foedus::soc::SharedMutex::is_recursive () const inline
Definition at line 59 of file shared_mutex.hpp.
 { return recursive_; }
void foedus::soc::SharedMutex::lock ()
Unconditionally lock.
Definition at line 63 of file shared_mutex.cpp.
References ASSERT_ND.
Referenced by foedus::soc::SharedMutexScope::lock().
{
   ASSERT_ND(initialized_);
   int ret = ::pthread_mutex_lock(&mutex_);
   ASSERT_ND(ret == 0);
 }
SharedMutex& foedus::soc::SharedMutex::operator= (const SharedMutex &) delete
bool foedus::soc::SharedMutex::timedlock (uint64_t timeout_nanosec)
Try lock up to the given timeout.
Parameters
[in] timeout_nanosec timeout in nanoseconds
Returns
whether this thread acquired the lock
Definition at line 69 of file shared_mutex.cpp.
References ASSERT_ND, CXX11_NULLPTR, and trylock().
{
   if (timeout_nanosec == 0) {
     return trylock();
   }
   ASSERT_ND(initialized_);
   struct timespec timeout;
   struct timeval now;
   ::gettimeofday(&now, CXX11_NULLPTR);
   timeout.tv_sec = now.tv_sec + (timeout_nanosec / 1000000000ULL);
   timeout.tv_nsec = now.tv_usec * 1000ULL + timeout_nanosec % 1000000000ULL;
   timeout.tv_sec += (timeout.tv_nsec) / 1000000000ULL;
   timeout.tv_nsec %= 1000000000ULL;
   int ret = ::pthread_mutex_timedlock(&mutex_, &timeout);
   ASSERT_ND(ret == 0 || ret == ETIMEDOUT);
   return ret == 0;
 }
bool foedus::soc::SharedMutex::trylock ()
Instantaneously try the lock.
Returns
whether this thread acquired the lock
Definition at line 87 of file shared_mutex.cpp.
References ASSERT_ND.
Referenced by timedlock().
{
   ASSERT_ND(initialized_);
   int ret = ::pthread_mutex_trylock(&mutex_);
   return ret == 0;
 }
void foedus::soc::SharedMutex::uninitialize ()
Definition at line 49 of file shared_mutex.cpp.
References ASSERT_ND.
Referenced by initialize(), foedus::proc::ProcManagerControlBlock::uninitialize(), foedus::log::MetaLogControlBlock::uninitialize(), foedus::memory::PagePoolControlBlock::uninitialize(), foedus::storage::StorageManagerControlBlock::uninitialize(), foedus::soc::SharedCond::uninitialize(), foedus::savepoint::SavepointManagerControlBlock::uninitialize(), foedus::log::LogManagerControlBlock::uninitialize(), foedus::storage::StorageControlBlock::uninitialize(), foedus::thread::ThreadControlBlock::uninitialize(), foedus::log::LoggerControlBlock::uninitialize(), foedus::storage::PartitionerMetadata::uninitialize(), and ~SharedMutex().
{
   if (!initialized_) {
     return;
   }
   int mutex_ret = ::pthread_mutex_destroy(&mutex_);
   ASSERT_ND(mutex_ret == 0);
   int attr_ret = ::pthread_mutexattr_destroy(&attr_);
   ASSERT_ND(attr_ret == 0);
   initialized_ = false;
 }
void foedus::soc::SharedMutex::unlock ()
Unlock it.
Definition at line 93 of file shared_mutex.cpp.
References ASSERT_ND.
Referenced by foedus::soc::SharedMutexScope::unlock().
{
   ASSERT_ND(initialized_);
   int ret = ::pthread_mutex_unlock(&mutex_);
   ASSERT_ND(ret == 0);
 }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/soc/shared_mutex.hpp
/home/shino/foedus_code/foedus-core/src/foedus/soc/shared_mutex.cpp