libfoedus-core: foedus::xct::XctManager Class Reference
foedus::xct::XctManager Class Reference final
FOEDUS Components » Transaction Manager
Xct Manager class that provides API to begin/abort/commit transaction.
Detailed Description
Xct Manager class that provides API to begin/abort/commit transaction.
Client programs should first call begin_xct(), then either call abort_xct() or precommit_xct(). In the latter case, the client programs should either keep running other transactions without returning the results to users, or call wait_for_commit() to immediately return the results.
Definition at line 35 of file xct_manager.hpp.
#include <xct_manager.hpp>
Public Member Functions
XctManager (Engine *engine)
~XctManager ()
XctManager ()=delete
XctManager (const XctManager &)=delete
XctManager & operator= (const XctManager &)=delete
ErrorStack initialize () override
Acquires resources in this object, usually called right after constructor.
bool is_initialized () const override
Returns whether the object has been already initialized or not.
ErrorStack uninitialize () override
An idempotent method to release all resources of this object, if any.
Epoch get_current_global_epoch () const
Returns the current global epoch, the epoch a newly started transaction will be in.
Epoch get_current_global_epoch_weak () const
Epoch get_current_grace_epoch () const
Returns the current grace-period epoch (global epoch - 1), the epoch some transaction might be still in (though rare).
Epoch get_current_grace_epoch_weak () const
void wait_for_current_global_epoch (Epoch target_epoch, int64_t wait_microseconds=-1)
Passively wait until the current global epoch becomes the given value.
void advance_current_global_epoch ()
Requests to advance the current global epoch as soon as possible and blocks until it actually does.
ErrorCode begin_xct (thread::Thread *context, IsolationLevel isolation_level)
Begins a new transaction on the thread.
ErrorCode precommit_xct (thread::Thread *context, Epoch *commit_epoch)
Prepares the currently running transaction on the thread for commit.
ErrorCode wait_for_commit (Epoch commit_epoch, int64_t wait_microseconds=-1)
Synchronously blocks until the durable global epoch reaches the given commit epoch or the given duration elapses.
ErrorCode abort_xct (thread::Thread *context)
Aborts the currently running transaction on the thread.
void pause_accepting_xct ()
Pause all begin_xct until you call resume_accepting_xct()
void resume_accepting_xct ()
Make sure you call this after pause_accepting_xct().
Public Member Functions inherited from foedus::Initializable
virtual ~Initializable ()
Constructor & Destructor Documentation
foedus::xct::XctManager::XctManager (Engine * engine) explicit
Definition at line 22 of file xct_manager.cpp.
                                      : pimpl_(nullptr) {
   pimpl_ = new XctManagerPimpl(engine);
 }
foedus::xct::XctManager::~XctManager ()
Definition at line 25 of file xct_manager.cpp.
{
   delete pimpl_;
   pimpl_ = nullptr;
 }
foedus::xct::XctManager::XctManager () delete
foedus::xct::XctManager::XctManager (const XctManager &) delete
Member Function Documentation
ErrorCode foedus::xct::XctManager::abort_xct (thread::Thread * context)
Aborts the currently running transaction on the thread.
Parameters
[in,out] context Thread context
Precondition
context->is_running_xct() == true
Definition at line 82 of file xct_manager_pimpl.cpp.
References foedus::xct::XctManagerPimpl::abort_xct().
 { return pimpl_->abort_xct(context); }
void foedus::xct::XctManager::advance_current_global_epoch ()
Requests to advance the current global epoch as soon as possible and blocks until it actually does.
This method is used when some thread immediately needs the next epoch for some reason, eg transactional threads ran out of ordinal (per-thread/epoch identifier) in the epoch.
Definition at line 70 of file xct_manager_pimpl.cpp.
References foedus::xct::XctManagerPimpl::advance_current_global_epoch().
Referenced by foedus::log::MetaLogBuffer::commit(), foedus::thread::ThreadPimpl::flush_retired_volatile_page(), foedus::cache::CacheManagerPimpl::handle_cleaner(), and foedus::xct::Xct::issue_next_id().
 { pimpl_->advance_current_global_epoch(); }
ErrorCode foedus::xct::XctManager::begin_xct (thread::Thread * context, IsolationLevel isolation_level)
Begins a new transaction on the thread.
Parameters
[in,out] context Thread context
[in] isolation_level concurrency isolation level of the new transaction
Precondition
context->is_running_xct() == false
Definition at line 75 of file xct_manager_pimpl.cpp.
References foedus::xct::XctManagerPimpl::begin_xct().
{
   return pimpl_->begin_xct(context, isolation_level);
 }
Epoch foedus::xct::XctManager::get_current_global_epoch () const
Returns the current global epoch, the epoch a newly started transaction will be in.
Definition at line 57 of file xct_manager_pimpl.cpp.
References foedus::xct::XctManagerPimpl::get_current_global_epoch().
Referenced by foedus::log::MetaLogBuffer::commit(), foedus::thread::ThreadPimpl::flush_retired_volatile_page(), foedus::Engine::get_current_global_epoch(), foedus::cache::CacheManagerPimpl::handle_cleaner(), foedus::xct::Xct::issue_next_id(), and foedus::savepoint::SavepointManagerPimpl::savepoint_main().
{
   return pimpl_->get_current_global_epoch();
 }
Epoch foedus::xct::XctManager::get_current_global_epoch_weak () const
Definition at line 60 of file xct_manager_pimpl.cpp.
References foedus::xct::XctManagerPimpl::get_current_global_epoch_weak().
Referenced by foedus::thread::ThreadPimpl::collect_retired_volatile_page(), and foedus::xct::Xct::issue_next_id().
{
   return pimpl_->get_current_global_epoch_weak();
 }
Epoch foedus::xct::XctManager::get_current_grace_epoch () const
Returns the current grace-period epoch (global epoch - 1), the epoch some transaction might be still in (though rare).
Definition at line 63 of file xct_manager_pimpl.cpp.
References foedus::xct::XctManagerPimpl::get_current_global_epoch(), and foedus::Epoch::one_less().
Referenced by foedus::Engine::get_current_grace_epoch(), and foedus::storage::sequential::SequentialCursor::SequentialCursor().
{
   return pimpl_->get_current_global_epoch().one_less();
 }
Epoch foedus::xct::XctManager::get_current_grace_epoch_weak () const
Definition at line 66 of file xct_manager_pimpl.cpp.
References foedus::xct::XctManagerPimpl::get_current_global_epoch_weak(), and foedus::Epoch::one_less().
{
   return pimpl_->get_current_global_epoch_weak().one_less();
 }
ErrorStack foedus::xct::XctManager::initialize () override virtual
Acquires resources in this object, usually called right after constructor.
Precondition
is_initialized() == FALSE
If and only if the return value was not an error, is_initialized() will return TRUE. This method is usually not idempotent, but some implementation can choose to be. In that case, the implementation class should clarify that it's idempotent. This method is responsible for releasing all acquired resources when initialization fails. This method itself is NOT thread-safe. Do not call this in a racy situation.
Implements foedus::Initializable.
Definition at line 30 of file xct_manager.cpp.
References foedus::DefaultInitializable::initialize().
 { return pimpl_->initialize(); }
bool foedus::xct::XctManager::is_initialized () const override virtual
Returns whether the object has been already initialized or not.
Implements foedus::Initializable.
Definition at line 31 of file xct_manager.cpp.
References foedus::DefaultInitializable::is_initialized().
Referenced by foedus::cache::CacheManagerPimpl::handle_cleaner(), foedus::restart::RestartManagerPimpl::initialize_once(), and foedus::restart::RestartManagerPimpl::uninitialize_once().
 { return pimpl_->is_initialized(); }
XctManager& foedus::xct::XctManager::operator= (const XctManager &) delete
void foedus::xct::XctManager::pause_accepting_xct ()
Pause all begin_xct until you call resume_accepting_xct()
Definition at line 33 of file xct_manager.cpp.
References foedus::xct::XctManagerPimpl::pause_accepting_xct().
Referenced by foedus::snapshot::SnapshotManagerPimpl::drop_volatile_pages().
 { pimpl_->pause_accepting_xct(); }
ErrorCode foedus::xct::XctManager::precommit_xct (thread::Thread * context, Epoch * commit_epoch)
Prepares the currently running transaction on the thread for commit.
Precondition
context->is_running_xct() == true
Parameters
[in,out] context Thread context
[out] commit_epoch When successfully prepared, this value indicates the commit epoch of the prepared transaction. When the global epoch reaches this value, the transaction is deemed as committed.
As the name of this method implies, this method is NOT a commit yet. The transaction is deemed as committed only when the durable global epoch reaches the returned commit epoch. This method merely prepares this transaction to be committed so that the caller can choose either moving on to other transactions in the meantime or to immediately wait for the commit using wait_for_commit().
See also
wait_for_commit()
Definition at line 79 of file xct_manager_pimpl.cpp.
References foedus::xct::XctManagerPimpl::precommit_xct().
{
   return pimpl_->precommit_xct(context, commit_epoch);
 }
void foedus::xct::XctManager::resume_accepting_xct ()
Make sure you call this after pause_accepting_xct().
Definition at line 34 of file xct_manager.cpp.
References foedus::xct::XctManagerPimpl::resume_accepting_xct().
Referenced by foedus::snapshot::SnapshotManagerPimpl::drop_volatile_pages().
 { pimpl_->resume_accepting_xct(); }
ErrorStack foedus::xct::XctManager::uninitialize () override virtual
An idempotent method to release all resources of this object, if any.
After this method, is_initialized() will return FALSE. Whether this method encounters an error or not, the implementation should make the best effort to release as many resources as possible. In other words, Do not leak all resources because of one issue. This method itself is NOT thread-safe. Do not call this in a racy situation.
Attention
This method is NOT automatically called from the destructor. This is due to the fundamental limitation in C++. Explicitly call this method as soon as you are done, checking the returned value. You can also use UninitializeGuard to ameliorate the issue, but it's not perfect.
Returns
The error this method encounters, if any. In case there are multiple errors while uninitialization, the implementation should use ErrorStackBatch to produce a batched ErrorStack object.
Implements foedus::Initializable.
Definition at line 32 of file xct_manager.cpp.
References foedus::DefaultInitializable::uninitialize().
 { return pimpl_->uninitialize(); }
ErrorCode foedus::xct::XctManager::wait_for_commit (Epoch commit_epoch, int64_t wait_microseconds = -1)
Synchronously blocks until the durable global epoch reaches the given commit epoch or the given duration elapses.
Parameters
[in] commit_epoch Returns kRetOk iff the durable global epoch reaches this value.
[in] wait_microseconds Or, returns a TIMEOUT error when this duration elapses, whichever comes first. Negative value means waiting forever. 0 means conditional, immediately returning without blocking, which is useful to quickly check the committed-ness.
Client programs can either call this method for each transaction right after precommit_xct() or call this method after a bunch of precommit_xct() calls (group-commit). In either case, remember that both read-only and read-write transactions must not return results to clients until the durable global epoch reaches the given commit epoch. Otherwise, you violate serializability (which might be okay depending on your desired isolation level).
Definition at line 71 of file xct_manager_pimpl.cpp.
References foedus::xct::XctManagerPimpl::wait_for_commit().
{
   return pimpl_->wait_for_commit(commit_epoch, wait_microseconds);
 }
void foedus::xct::XctManager::wait_for_current_global_epoch (Epoch target_epoch, int64_t wait_microseconds = -1)
Passively wait until the current global epoch becomes the given value.
Definition at line 35 of file xct_manager.cpp.
References foedus::xct::XctManagerPimpl::wait_for_current_global_epoch().
Referenced by foedus::cache::CacheManagerPimpl::handle_cleaner().
{
   pimpl_->wait_for_current_global_epoch(target_epoch, wait_microseconds);
 }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/xct/xct_manager.hpp
/home/shino/foedus_code/foedus-core/src/foedus/xct/xct_manager.cpp
/home/shino/foedus_code/foedus-core/src/foedus/xct/xct_manager_pimpl.cpp