libfoedus-core: foedus::xct::McsWwOwnerlessImpl Class Reference
foedus::xct::McsWwOwnerlessImpl Class Reference
FOEDUS Components » Transaction Manager
A ownerless (contextless) interface for McsWwImpl.
Detailed Description
A ownerless (contextless) interface for McsWwImpl.
Conceptually this is part of McsWwImpl, but this doesn't depend on Adaptor because guests don't need any context in MCSg. We separate the methods to this class for easier use.
Definition at line 218 of file xct_mcs_impl.hpp.
#include <xct_mcs_impl.hpp>
Public Member Functions
McsWwOwnerlessImpl ()=delete
~McsWwOwnerlessImpl ()=delete
Static Public Member Functions
static void ownerless_acquire_unconditional (McsWwLock *lock)
[WW-Guest] Unconditionally takes exclusive-only guest lock on the given MCSg lock.
static bool ownerless_acquire_try (McsWwLock *lock)
[WW-Guest] Try to take an exclusive guest lock on the given MCSg lock.
static void ownerless_release (McsWwLock *lock)
static void ownerless_initial (McsWwLock *lock)
Constructor & Destructor Documentation
foedus::xct::McsWwOwnerlessImpl::McsWwOwnerlessImpl () delete
foedus::xct::McsWwOwnerlessImpl::~McsWwOwnerlessImpl () delete
Member Function Documentation
bool foedus::xct::McsWwOwnerlessImpl::ownerless_acquire_try (McsWwLock * lock) static
[WW-Guest] Try to take an exclusive guest lock on the given MCSg lock.
Returns
whether we got the lock. If you receive true, you are responsible to call ownerless_release()
Definition at line 292 of file xct_mcs_impl.cpp.
References foedus::xct::assert_mcs_aligned(), ASSERT_ND, foedus::xct::McsWwLock::is_locked(), foedus::xct::McsWwBlockData::is_valid_relaxed(), foedus::xct::kMcsGuestId, foedus::xct::McsWwLock::tail_, and foedus::xct::McsWwBlockData::word_.
{
   // Similar to acquire_try()
   assert_mcs_aligned(mcs_lock);
   auto* int_address = &(mcs_lock->tail_.word_);
   assert_mcs_aligned(int_address);
   McsWwBlockData pred;                      // purely local copy. okay to be always relaxed.
   ASSERT_ND(!pred.is_valid_relaxed());
   bool swapped = assorted::raw_atomic_compare_exchange_weak<uint64_t>(
     &(mcs_lock->tail_.word_),
     &pred.word_,
     kMcsGuestId);
   if (swapped) {
     ASSERT_ND(mcs_lock->is_locked());
     DVLOG(2) << "Okay, got a guest lock uncontended.";
     // We can't test is_guest here because we might now have a successor swapping it.
     ASSERT_ND(!pred.is_valid_relaxed());
     return true;
   } else {
     return true;
   }
 }
void foedus::xct::McsWwOwnerlessImpl::ownerless_acquire_unconditional (McsWwLock * lock) static
[WW-Guest] Unconditionally takes exclusive-only guest lock on the given MCSg lock.
Ownerless interface for WW-lock implementations.
Definition at line 272 of file xct_mcs_impl.cpp.
References foedus::xct::assert_mcs_aligned(), ASSERT_ND, foedus::xct::McsWwLock::is_locked(), foedus::xct::McsWwBlockData::is_valid_relaxed(), foedus::xct::kMcsGuestId, foedus::xct::spin_until(), foedus::xct::McsWwLock::tail_, and foedus::xct::McsWwBlockData::word_.
Referenced by foedus::xct::McsWwLock::ownerless_acquire_lock().
{
   // Basically _all_ writes in this function must come with some memory barrier. Be careful!
   // Also, the performance of this method really matters, especially that of common path.
   // Check objdump -d. Everything in common path should be inlined.
   // Also, check minimal sufficient mfences (note, xchg implies lock prefix. not a compiler's bug!).
   assert_mcs_aligned(mcs_lock);
   auto* int_address = &(mcs_lock->tail_.word_);
   assert_mcs_aligned(int_address);
   spin_until([mcs_lock, int_address]{
     McsWwBlockData old;
     ASSERT_ND(!old.is_valid_relaxed());
     return assorted::raw_atomic_compare_exchange_weak<uint64_t>(
       int_address,
       &old.word_,
       kMcsGuestId);
   });
   DVLOG(1) << "Okay, now I hold the lock. me=guest";
   ASSERT_ND(mcs_lock->is_locked());
 }
void foedus::xct::McsWwOwnerlessImpl::ownerless_initial (McsWwLock * lock) static
Definition at line 315 of file xct_mcs_impl.cpp.
References foedus::xct::assert_mcs_aligned(), ASSERT_ND, foedus::xct::McsWwLock::is_locked(), and foedus::xct::McsWwLock::reset_guest_id_release().
Referenced by foedus::xct::McsWwLock::ownerless_initial_lock().
{
   assert_mcs_aligned(mcs_lock);
   ASSERT_ND(!mcs_lock->is_locked());
   mcs_lock->reset_guest_id_release();
 }
void foedus::xct::McsWwOwnerlessImpl::ownerless_release (McsWwLock * lock) static
Definition at line 321 of file xct_mcs_impl.cpp.
References foedus::xct::assert_mcs_aligned(), ASSERT_ND, foedus::xct::McsWwBlockData::is_guest_relaxed(), foedus::xct::McsWwLock::is_locked(), foedus::xct::McsWwBlockData::is_valid_relaxed(), foedus::xct::kMcsGuestId, foedus::xct::spin_until(), foedus::xct::McsWwLock::tail_, and foedus::xct::McsWwBlockData::word_.
Referenced by foedus::xct::McsWwLock::ownerless_release_lock().
{
   // Basically _all_ writes in this function must come with some memory barrier. Be careful!
   // Also, the performance of this method really matters, especially that of common path.
   // Check objdump -d. Everything in common path should be inlined.
   // Also, check minimal sufficient mfences (note, xchg implies lock prefix. not a compiler's bug!).
   assert_mcs_aligned(mcs_lock);
   auto* int_address = &(mcs_lock->tail_.word_);
   assert_mcs_aligned(int_address);
   ASSERT_ND(mcs_lock->is_locked());
   spin_until([int_address]{
     McsWwBlockData old(kMcsGuestId);
     ASSERT_ND(old.is_valid_relaxed());
     ASSERT_ND(old.is_guest_relaxed());
     return assorted::raw_atomic_compare_exchange_weak<uint64_t>(int_address, &old.word_, 0);
   });
   DVLOG(1) << "Okay, guest released the lock.";
 }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/xct/xct_mcs_impl.hpp
/home/shino/foedus_code/foedus-core/src/foedus/xct/xct_mcs_impl.cpp