libfoedus-core: foedus::storage::hash::HashDataPage Class Reference
foedus::storage::hash::HashDataPage Class Reference final
FOEDUS Components » Storage Manager » Hashtable Storage
Represents an individual data page in Hashtable Storage.
Detailed Description
Represents an individual data page in Hashtable Storage.
This is one of the page types in hash. A data page contains full keys and values.
Page Layout
Headers, including bloom filter for faster check
Record Data part, which grows forward
Unused part
Slot part (32 bytes per record), which grows backward
Definition at line 155 of file hash_page_impl.hpp.
#include <hash_page_impl.hpp>
Classes
struct Slot
Fix-sized slot for each record, which is placed at the end of data region.
Public Member Functions
HashDataPage ()=delete
HashDataPage (const HashDataPage &other)=delete
HashDataPage & operator= (const HashDataPage &other)=delete
void initialize_volatile_page (StorageId storage_id, VolatilePagePointer page_id, const Page *parent, HashBin bin, uint8_t bin_shifts)
void initialize_snapshot_page (StorageId storage_id, SnapshotPagePointer page_id, HashBin bin, uint8_t bin_bits, uint8_t bin_shifts)
void release_pages_recursive (const memory::GlobalVolatilePageResolver &page_resolver, memory::PageReleaseBatch *batch)
PageHeader & header ()
const PageHeader & header () const
bool is_locked () const
VolatilePagePointer get_volatile_page_id () const
SnapshotPagePointer get_snapshot_page_id () const
const DualPagePointer & next_page () const __attribute__((always_inline))
DualPagePointer & next_page () __attribute__((always_inline))
const DualPagePointer * next_page_address () const __attribute__((always_inline))
DualPagePointer * next_page_address () __attribute__((always_inline))
const DataPageBloomFilter & bloom_filter () const __attribute__((always_inline))
DataPageBloomFilter & bloom_filter () __attribute__((always_inline))
uint16_t get_record_count () const __attribute__((always_inline))
const Slot & get_slot (DataPageSlotIndex record) const __attribute__((always_inline))
Slot & get_slot (DataPageSlotIndex record) __attribute__((always_inline))
Slot & get_new_slot (DataPageSlotIndex record) __attribute__((always_inline))
const Slot * get_slot_address (DataPageSlotIndex record) const __attribute__((always_inline))
same as &get_slot(), but this is more explicit and easier to understand/maintain
Slot * get_slot_address (DataPageSlotIndex record) __attribute__((always_inline))
DataPageSlotIndex to_slot_index (const Slot *slot) const __attribute__((always_inline))
char * record_from_offset (uint16_t offset)
const char * record_from_offset (uint16_t offset) const
uint16_t available_space () const
Returns usable space in bytes.
uint16_t next_offset () const
Returns offset of a next record.
DataPageSlotIndex reserve_record (HashValue hash, const BloomFilterFingerprint &fingerprint, const void *key, uint16_t key_length, uint16_t payload_length)
A system transaction that creates a logically deleted record in this page for the given key.
void create_record_in_snapshot (xct::XctId xct_id, HashValue hash, const BloomFilterFingerprint &fingerprint, const void *key, uint16_t key_length, const void *payload, uint16_t payload_length) __attribute__((always_inline))
A simplified/efficient version to insert an active record, which must be used only in snapshot pages.
DataPageSlotIndex search_key_physical (HashValue hash, const BloomFilterFingerprint &fingerprint, const void *key, KeyLength key_length, DataPageSlotIndex record_count, DataPageSlotIndex check_from=0) const
Search for a physical slot that exactly contains the given key.
bool compare_slot_key (DataPageSlotIndex index, HashValue hash, const void *key, uint16_t key_length) const
returns whether the slot contains the exact key specified
HashBin get_bin () const
void assert_bin (HashBin bin) const __attribute__((always_inline))
void protected_set_bin_shifts (uint8_t bin_shifts)
this method should be called only in page creation.
uint8_t get_bin_shifts () const
void assert_entries () const __attribute__((always_inline))
void assert_entries_impl () const
defined in hash_page_debug.cpp.
Static Public Member Functions
static uint16_t required_space (uint16_t key_length, uint16_t payload_length)
returns physical_record_length_ for a new record
Friends
struct ReserveRecords
std::ostream & operator<< (std::ostream &o, const HashDataPage &v)
defined in hash_page_debug.cpp.
Constructor & Destructor Documentation
foedus::storage::hash::HashDataPage::HashDataPage () delete
foedus::storage::hash::HashDataPage::HashDataPage (const HashDataPage & other) delete
Member Function Documentation
void foedus::storage::hash::HashDataPage::assert_bin (HashBin bin) const inline
Definition at line 413 of file hash_page_impl.hpp.
References ASSERT_ND.
 { ASSERT_ND(bin_ == bin); }
void foedus::storage::hash::HashDataPage::assert_entries () const inline
Definition at line 424 of file hash_page_impl.hpp.
References assert_entries_impl().
{
 #ifndef NDEBUG
     assert_entries_impl();
 #endif  // NDEBUG
   }
void foedus::storage::hash::HashDataPage::assert_entries_impl () const
defined in hash_page_debug.cpp.
Definition at line 89 of file hash_page_debug.cpp.
References foedus::storage::hash::DataPageBloomFilter::add(), ASSERT_ND, foedus::storage::hash::DataPageBloomFilter::clear(), foedus::storage::hash::DataPageBloomFilter::extract_fingerprint(), foedus::storage::hash::HashDataPage::Slot::get_aligned_key_length(), get_bin_shifts(), get_record_count(), get_slot_address(), foedus::storage::hash::HashDataPage::Slot::hash_, foedus::storage::hash::hashinate(), foedus::storage::hash::HashDataPage::Slot::key_length_, foedus::storage::hash::kHashDataPageHeaderSize, foedus::storage::kPageSize, next_page(), foedus::storage::hash::HashDataPage::Slot::offset_, foedus::storage::hash::HashDataPage::Slot::payload_length_, foedus::storage::hash::HashDataPage::Slot::physical_record_length_, record_from_offset(), foedus::storage::PageHeader::snapshot_, and foedus::storage::hash::DataPageBloomFilter::values_.
Referenced by assert_entries().
{
   const uint8_t bin_shifts = get_bin_shifts();
   uint8_t records = get_record_count();
   if (header_.snapshot_) {
     ASSERT_ND(next_page().volatile_pointer_.is_null());
   } else {
     ASSERT_ND(next_page().snapshot_pointer_ == 0);
   }
   DataPageBloomFilter correct_filter;
   correct_filter.clear();
   for (DataPageSlotIndex i = 0; i < records; ++i) {
     const HashDataPage::Slot* slot = get_slot_address(i);
     if (i > 0) {
       const HashDataPage::Slot* pre = get_slot_address(i - 1);
       ASSERT_ND(slot->offset_ == pre->offset_ + pre->physical_record_length_);
     }
     HashValue hash = hashinate(record_from_offset(slot->offset_), slot->key_length_);
     ASSERT_ND(slot->hash_ == hash);
     HashBin bin = hash >> bin_shifts;
     ASSERT_ND(bin_ == bin);
     correct_filter.add(DataPageBloomFilter::extract_fingerprint(slot->hash_));
     ASSERT_ND(slot->physical_record_length_
       >= slot->get_aligned_key_length() + slot->payload_length_);
     uint16_t end_offset = slot->offset_ + slot->physical_record_length_;
     ASSERT_ND(end_offset + records * sizeof(Slot) <= (kPageSize - kHashDataPageHeaderSize));
   }
   for (uint16_t i = 0; i < sizeof(correct_filter.values_); ++i) {
     ASSERT_ND(correct_filter.values_[i] == bloom_filter_.values_[i]);
   }
 }
uint16_t foedus::storage::hash::HashDataPage::available_space () const inline
Returns usable space in bytes.
Definition at line 281 of file hash_page_impl.hpp.
References ASSERT_ND, get_record_count(), and next_offset().
Referenced by foedus::storage::hash::ReserveRecords::append_record_to_page(), foedus::storage::hash::ReserveRecords::create_new_record_in_tail_page(), create_record_in_snapshot(), foedus::storage::hash::ReserveRecords::expand_record(), foedus::storage::hash::ReserveRecords::find_and_lock_spacious_tail(), and reserve_record().
{
     uint16_t consumed = next_offset() + get_record_count() * sizeof(Slot);
     ASSERT_ND(consumed <= sizeof(data_));
     if (consumed > sizeof(data_)) {  // just to be conservative on release build
       return 0;
     }
     return sizeof(data_) - consumed;
   }
const DataPageBloomFilter& foedus::storage::hash::HashDataPage::bloom_filter () const inline
Definition at line 243 of file hash_page_impl.hpp.
Referenced by foedus::storage::hash::HashStoragePimpl::insert_record(), and foedus::storage::hash::HashStoragePimpl::upsert_record().
 { return bloom_filter_; }
DataPageBloomFilter& foedus::storage::hash::HashDataPage::bloom_filter () inline
Definition at line 244 of file hash_page_impl.hpp.
 { return bloom_filter_; }
bool foedus::storage::hash::HashDataPage::compare_slot_key (DataPageSlotIndex index, HashValue hash, const void * key, uint16_t key_length) const inline
returns whether the slot contains the exact key specified
Definition at line 396 of file hash_page_impl.hpp.
References ASSERT_ND, get_record_count(), get_slot(), foedus::storage::hash::HashDataPage::Slot::hash_, foedus::storage::hash::hashinate(), foedus::storage::hash::HashDataPage::Slot::key_length_, foedus::storage::hash::HashDataPage::Slot::offset_, and record_from_offset().
Referenced by foedus::storage::hash::HashStoragePimpl::locate_record(), and foedus::storage::hash::HashStoragePimpl::locate_record_in_snapshot().
{
     ASSERT_ND(index < get_record_count());  // record count purely increasing
     const Slot& slot = get_slot(index);
     ASSERT_ND(hashinate(record_from_offset(slot.offset_), slot.key_length_) == slot.hash_);
     // quick check first
     if (slot.hash_ != hash || slot.key_length_ != key_length) {
       return false;
     }
     const void* data = record_from_offset(slot.offset_);
     return std::memcmp(data, key, key_length) == 0;
   }
void foedus::storage::hash::HashDataPage::create_record_in_snapshot (xct::XctId xct_id, HashValue hash, const BloomFilterFingerprint & fingerprint, const void * key, uint16_t key_length, const void * payload, uint16_t payload_length) inline
A simplified/efficient version to insert an active record, which must be used only in snapshot pages.
Parameters
[in] xct_id XctId of the record.
[in] hash hash value of the key.
[in] fingerprint Bloom Filter fingerprint of the key.
[in] key full key.
[in] key_length full key length.
[in] payload the payload of the new record
[in] payload_length length of payload
Precondition
the page is a snapshot page being constructed
the page doesn't have the key
required_space(key_length, payload_length) <= available_space()
On constructing snapshot pages, we don't need any concurrency control, and we can loosen all restrictions. We thus have this method as an optimized version for snapshot pages. Inlined to make it more efficient.
Definition at line 480 of file hash_page_impl.hpp.
References foedus::storage::hash::DataPageBloomFilter::add(), foedus::assorted::align8(), ASSERT_ND, ASSUME_ALIGNED, available_space(), get_record_count(), get_slot(), foedus::storage::hash::HashDataPage::Slot::hash_, foedus::storage::PageHeader::increment_key_count(), foedus::storage::hash::HashDataPage::Slot::key_length_, foedus::storage::kPageSize, next_offset(), foedus::storage::hash::HashDataPage::Slot::offset_, foedus::storage::hash::HashDataPage::Slot::payload_length_, foedus::storage::hash::HashDataPage::Slot::physical_record_length_, record_from_offset(), required_space(), foedus::storage::PageHeader::snapshot_, foedus::storage::hash::HashDataPage::Slot::tid_, and foedus::xct::RwLockableXctId::xct_id_.
{
   ASSERT_ND(header_.snapshot_);
   ASSERT_ND(available_space() >= required_space(key_length, payload_length));
   ASSERT_ND(reinterpret_cast<uintptr_t>(this) % kPageSize == 0);
   ASSERT_ND(reinterpret_cast<uintptr_t>(key_arg) % 8 == 0);
   ASSERT_ND(reinterpret_cast<uintptr_t>(payload_arg) % 8 == 0);
   const void* key = ASSUME_ALIGNED(key_arg, 8U);
   const void* payload = ASSUME_ALIGNED(payload_arg, 8U);
   DataPageSlotIndex index = get_record_count();
   Slot& slot = get_slot(index);
   slot.tid_.xct_id_ = xct_id;
   slot.offset_ = next_offset();
   slot.hash_ = hash;
   slot.key_length_ = key_length;
   uint16_t aligned_key_length = assorted::align8(key_length);
   slot.physical_record_length_ = aligned_key_length + assorted::align8(payload_length);
   slot.payload_length_ = payload_length;
   ASSERT_ND(reinterpret_cast<uintptr_t>(record_from_offset(slot.offset_)) % 8 == 0);
   char* record = reinterpret_cast<char*>(ASSUME_ALIGNED(record_from_offset(slot.offset_), 8U));
   ASSERT_ND(key_length > 0);
   std::memcpy(record, key, key_length);
   if (key_length != aligned_key_length) {
     std::memset(record + key_length, 0, aligned_key_length - key_length % 8);
   }
   if (payload_length > 0) {
     char* dest = reinterpret_cast<char*>(ASSUME_ALIGNED(record + aligned_key_length, 8U));
     uint16_t aligned_payload_length = assorted::align8(payload_length);
     std::memcpy(dest, payload, payload_length);
     if (key_length != aligned_payload_length) {
       std::memset(dest + payload_length, 0, aligned_payload_length - payload_length);
     }
   }
   bloom_filter_.add(fingerprint);
   header_.increment_key_count();
 }
HashBin foedus::storage::hash::HashDataPage::get_bin () const inline
Definition at line 412 of file hash_page_impl.hpp.
Referenced by foedus::storage::hash::ReserveRecords::create_new_tail_page(), foedus::storage::hash::HashStoragePimpl::follow_page_bin_head(), foedus::storage::hash::hash_data_volatile_page_init(), initialize_volatile_page(), foedus::storage::hash::HashStoragePimpl::locate_bin(), foedus::storage::hash::HashStoragePimpl::locate_record(), foedus::storage::hash::HashStoragePimpl::locate_record_in_snapshot(), foedus::storage::hash::operator<<(), release_pages_recursive(), foedus::storage::hash::HashStoragePimpl::verify_single_thread_data(), and foedus::storage::hash::HashStoragePimpl::verify_single_thread_intermediate().
 { return bin_; }
uint8_t foedus::storage::hash::HashDataPage::get_bin_shifts () const inline
Definition at line 422 of file hash_page_impl.hpp.
References foedus::storage::PageHeader::masstree_layer_.
Referenced by assert_entries_impl(), foedus::storage::hash::ReserveRecords::create_new_tail_page(), and initialize_volatile_page().
 { return header_.masstree_layer_; }
Slot& foedus::storage::hash::HashDataPage::get_new_slot (DataPageSlotIndex record) inline
Definition at line 254 of file hash_page_impl.hpp.
Referenced by foedus::storage::hash::ReserveRecords::append_record_to_page().
{
     // Only in this method, record is okay to be == key_count
     return reinterpret_cast<Slot*>(this + 1)[-record - 1];
   }
uint16_t foedus::storage::hash::HashDataPage::get_record_count () const inline
Definition at line 246 of file hash_page_impl.hpp.
References foedus::storage::PageHeader::key_count_.
Referenced by foedus::storage::hash::ReserveRecords::append_record_to_page(), assert_entries_impl(), available_space(), compare_slot_key(), create_record_in_snapshot(), foedus::storage::hash::ReserveRecords::find_or_create_or_expand(), foedus::storage::hash::HashStoragePimpl::locate_record(), foedus::storage::hash::HashStoragePimpl::locate_record_in_snapshot(), next_offset(), foedus::storage::hash::operator<<(), reserve_record(), search_key_physical(), foedus::storage::hash::ReserveRecords::search_within_page(), and foedus::storage::hash::HashStoragePimpl::track_moved_record_search().
 { return header_.key_count_; }
const Slot& foedus::storage::hash::HashDataPage::get_slot (DataPageSlotIndex record) const inline
Definition at line 248 of file hash_page_impl.hpp.
Referenced by compare_slot_key(), create_record_in_snapshot(), foedus::storage::hash::ReserveRecords::expand_record(), foedus::storage::hash::ReserveRecords::find_or_create_or_expand(), next_offset(), reserve_record(), and search_key_physical().
{
     return reinterpret_cast<const Slot*>(this + 1)[-record - 1];
   }
Slot& foedus::storage::hash::HashDataPage::get_slot (DataPageSlotIndex record) inline
Definition at line 251 of file hash_page_impl.hpp.
{
     return reinterpret_cast<Slot*>(this + 1)[-record - 1];
   }
const Slot* foedus::storage::hash::HashDataPage::get_slot_address (DataPageSlotIndex record) const inline
same as &get_slot(), but this is more explicit and easier to understand/maintain
Definition at line 259 of file hash_page_impl.hpp.
Referenced by assert_entries_impl(), foedus::storage::hash::operator<<(), foedus::storage::hash::RecordLocation::populate_logical(), foedus::storage::hash::RecordLocation::populate_physical(), foedus::storage::hash::HashStoragePimpl::register_record_write_log(), and foedus::storage::hash::HashStoragePimpl::track_moved_record_search().
{
     return reinterpret_cast<const Slot*>(this + 1) - record - 1;
   }
Slot* foedus::storage::hash::HashDataPage::get_slot_address (DataPageSlotIndex record) inline
Definition at line 262 of file hash_page_impl.hpp.
{
     return reinterpret_cast<Slot*>(this + 1) - record - 1;
   }
SnapshotPagePointer foedus::storage::hash::HashDataPage::get_snapshot_page_id () const inline
Definition at line 233 of file hash_page_impl.hpp.
References ASSERT_ND, foedus::storage::PageHeader::page_id_, and foedus::storage::PageHeader::snapshot_.
{
     ASSERT_ND(header_.snapshot_);
     return static_cast<SnapshotPagePointer>(header_.page_id_);
   }
VolatilePagePointer foedus::storage::hash::HashDataPage::get_volatile_page_id () const inline
Definition at line 229 of file hash_page_impl.hpp.
References ASSERT_ND, foedus::storage::PageHeader::page_id_, and foedus::storage::PageHeader::snapshot_.
Referenced by foedus::storage::hash::ReserveRecords::create_new_record_in_tail_page(), foedus::storage::hash::ReserveRecords::expand_record(), and foedus::storage::hash::ReserveRecords::find_and_lock_spacious_tail().
{
     ASSERT_ND(!header_.snapshot_);
     return VolatilePagePointer(header_.page_id_);
   }
PageHeader& foedus::storage::hash::HashDataPage::header () inline
Definition at line 225 of file hash_page_impl.hpp.
Referenced by foedus::storage::hash::ReserveRecords::create_new_record_in_tail_page(), foedus::storage::hash::ReserveRecords::create_new_tail_page(), foedus::storage::hash::ReserveRecords::find_and_lock_spacious_tail(), foedus::storage::hash::ReserveRecords::find_or_create_or_expand(), foedus::storage::hash::HashStoragePimpl::follow_page_bin_head(), foedus::storage::hash::HashStoragePimpl::hcc_reset_all_temperature_stat_data(), foedus::storage::hash::HashStoragePimpl::insert_record(), foedus::storage::hash::HashStoragePimpl::locate_record(), foedus::storage::hash::HashStoragePimpl::locate_record_in_snapshot(), foedus::storage::hash::operator<<(), foedus::storage::hash::HashIntermediatePage::release_pages_recursive(), release_pages_recursive(), foedus::storage::hash::resolve_data_impl(), foedus::storage::hash::ReserveRecords::search_within_page(), foedus::storage::hash::HashStoragePimpl::track_moved_record_search(), and foedus::storage::hash::HashStoragePimpl::upsert_record().
 { return header_; }
const PageHeader& foedus::storage::hash::HashDataPage::header () const inline
Definition at line 226 of file hash_page_impl.hpp.
 { return header_; }
void foedus::storage::hash::HashDataPage::initialize_snapshot_page (StorageId storage_id, SnapshotPagePointer page_id, HashBin bin, uint8_t bin_bits, uint8_t bin_shifts)
Definition at line 93 of file hash_page_impl.cpp.
References ASSERT_ND, foedus::storage::PageHeader::init_snapshot(), foedus::storage::kHashDataPageType, foedus::storage::kPageSize, and protected_set_bin_shifts().
                       {
   ASSERT_ND(bin_bits + bin_shifts == 64U);
   std::memset(this, 0, kPageSize);
   header_.init_snapshot(page_id, storage_id, kHashDataPageType);
   bin_ = bin;
   protected_set_bin_shifts(bin_shifts);
 }
void foedus::storage::hash::HashDataPage::initialize_volatile_page (StorageId storage_id, VolatilePagePointer page_id, const Page * parent, HashBin bin, uint8_t bin_shifts)
Definition at line 70 of file hash_page_impl.cpp.
References ASSERT_ND, foedus::storage::hash::HashBinRange::contains(), get_bin(), foedus::storage::hash::HashIntermediatePage::get_bin_range(), get_bin_shifts(), foedus::storage::Page::get_header(), foedus::storage::hash::HashIntermediatePage::get_level(), foedus::storage::PageHeader::get_page_type(), foedus::storage::PageHeader::init_volatile(), foedus::storage::kHashDataPageType, foedus::storage::kHashIntermediatePageType, foedus::storage::kPageSize, and protected_set_bin_shifts().
Referenced by foedus::storage::hash::ReserveRecords::create_new_tail_page(), and foedus::storage::hash::hash_data_volatile_page_init().
                       {
   std::memset(this, 0, kPageSize);
   header_.init_volatile(page_id, storage_id, kHashDataPageType);
   bin_ = bin;
   protected_set_bin_shifts(bin_shifts);
   ASSERT_ND(parent);
   if (parent->get_header().get_page_type() == kHashIntermediatePageType) {
     const HashIntermediatePage* parent_casted
       = reinterpret_cast<const HashIntermediatePage*>(parent);
     ASSERT_ND(parent_casted->get_level() == 0);
     ASSERT_ND(parent_casted->get_bin_range().contains(bin));
   } else {
     const HashDataPage* parent_casted = reinterpret_cast<const HashDataPage*>(parent);
     ASSERT_ND(parent_casted->get_bin() == bin);
     ASSERT_ND(parent_casted->get_bin_shifts() == bin_shifts);
   }
 }
bool foedus::storage::hash::HashDataPage::is_locked () const inline
Definition at line 227 of file hash_page_impl.hpp.
References foedus::storage::PageVersion::is_locked(), and foedus::storage::PageHeader::page_version_.
Referenced by foedus::storage::hash::ReserveRecords::create_new_record_in_tail_page(), foedus::storage::hash::ReserveRecords::create_new_tail_page(), foedus::storage::hash::ReserveRecords::expand_record(), and foedus::storage::hash::ReserveRecords::find_or_create_or_expand().
 { return header_.page_version_.is_locked(); }
uint16_t foedus::storage::hash::HashDataPage::next_offset () const inline
Returns offset of a next record.
Definition at line 291 of file hash_page_impl.hpp.
References ASSERT_ND, get_record_count(), get_slot(), foedus::storage::hash::HashDataPage::Slot::offset_, and foedus::storage::hash::HashDataPage::Slot::physical_record_length_.
Referenced by foedus::storage::hash::ReserveRecords::append_record_to_page(), available_space(), create_record_in_snapshot(), and reserve_record().
{
     DataPageSlotIndex count = get_record_count();
     if (count == 0) {
       return 0;
     }
     const Slot& last_slot = get_slot(count - 1);
     ASSERT_ND((last_slot.offset_ + last_slot.physical_record_length_) % 8 == 0);
     return last_slot.offset_ + last_slot.physical_record_length_;
   }
const DualPagePointer& foedus::storage::hash::HashDataPage::next_page () const inline
Definition at line 238 of file hash_page_impl.hpp.
Referenced by assert_entries_impl(), foedus::storage::hash::ReserveRecords::create_new_record_in_tail_page(), foedus::storage::hash::ReserveRecords::find_and_lock_spacious_tail(), foedus::storage::hash::ReserveRecords::find_or_create_or_expand(), foedus::storage::hash::HashStoragePimpl::follow_page_bin_head(), foedus::storage::hash::operator<<(), and foedus::storage::hash::ReserveRecords::search_within_page().
 { return next_page_; }
DualPagePointer& foedus::storage::hash::HashDataPage::next_page () inline
Definition at line 239 of file hash_page_impl.hpp.
 { return next_page_; }
const DualPagePointer* foedus::storage::hash::HashDataPage::next_page_address () const inline
Definition at line 240 of file hash_page_impl.hpp.
Referenced by foedus::storage::hash::HashStoragePimpl::follow_page_bin_head(), foedus::storage::hash::HashStoragePimpl::locate_record(), foedus::storage::hash::HashStoragePimpl::locate_record_in_snapshot(), and foedus::storage::hash::HashStoragePimpl::track_moved_record_search().
 { return &next_page_; }
DualPagePointer* foedus::storage::hash::HashDataPage::next_page_address () inline
Definition at line 241 of file hash_page_impl.hpp.
 { return &next_page_; }
HashDataPage& foedus::storage::hash::HashDataPage::operator= (const HashDataPage & other) delete
void foedus::storage::hash::HashDataPage::protected_set_bin_shifts (uint8_t bin_shifts) inline
this method should be called only in page creation.
bin_shifts is immutable after that. we currently reuse header_.masstree_layer_ (not applicable to hash storage) for bin_shifts to squeeze space.
Definition at line 421 of file hash_page_impl.hpp.
References foedus::storage::PageHeader::masstree_layer_.
Referenced by initialize_snapshot_page(), and initialize_volatile_page().
 { header_.masstree_layer_ = bin_shifts; }
char* foedus::storage::hash::HashDataPage::record_from_offset (uint16_t offset) inline
Definition at line 275 of file hash_page_impl.hpp.
Referenced by foedus::storage::hash::ReserveRecords::append_record_to_page(), assert_entries_impl(), compare_slot_key(), create_record_in_snapshot(), foedus::storage::hash::operator<<(), foedus::storage::hash::RecordLocation::populate_logical(), foedus::storage::hash::RecordLocation::populate_physical(), reserve_record(), search_key_physical(), and foedus::storage::hash::HashStoragePimpl::track_moved_record_search().
 { return data_ + offset; }
const char* foedus::storage::hash::HashDataPage::record_from_offset (uint16_t offset) const inline
Definition at line 276 of file hash_page_impl.hpp.
 { return data_ + offset; }
void foedus::storage::hash::HashDataPage::release_pages_recursive (const memory::GlobalVolatilePageResolver & page_resolver, memory::PageReleaseBatch * batch)
Definition at line 329 of file hash_page_impl.cpp.
References ASSERT_ND, foedus::storage::VolatilePagePointer::clear(), get_bin(), foedus::storage::PageHeader::get_in_layer_level(), header(), foedus::storage::VolatilePagePointer::is_null(), foedus::storage::PageHeader::page_id_, foedus::memory::PageReleaseBatch::release(), release_pages_recursive(), foedus::memory::GlobalVolatilePageResolver::resolve_offset(), foedus::storage::DualPagePointer::volatile_pointer_, and foedus::storage::VolatilePagePointer::word.
Referenced by foedus::storage::hash::HashIntermediatePage::release_pages_recursive(), and release_pages_recursive().
{
   if (!next_page_.volatile_pointer_.is_null()) {
     HashDataPage* next = reinterpret_cast<HashDataPage*>(
       page_resolver.resolve_offset(next_page_.volatile_pointer_));
     ASSERT_ND(next->header().get_in_layer_level() == 0);
     ASSERT_ND(next->get_bin() == get_bin());
     next->release_pages_recursive(page_resolver, batch);
     next_page_.volatile_pointer_.clear();
   }
   VolatilePagePointer volatile_id;
   volatile_id.word = header().page_id_;
   batch->release(volatile_id);
 }
static uint16_t foedus::storage::hash::HashDataPage::required_space (uint16_t key_length, uint16_t payload_length) inline static
returns physical_record_length_ for a new record
Definition at line 302 of file hash_page_impl.hpp.
References foedus::assorted::align8().
Referenced by foedus::storage::hash::ReserveRecords::append_record_to_page(), foedus::storage::hash::ReserveRecords::create_new_record_in_tail_page(), create_record_in_snapshot(), foedus::storage::hash::ReserveRecords::expand_record(), foedus::storage::hash::ReserveRecords::find_and_lock_spacious_tail(), and reserve_record().
{
     return assorted::align8(key_length) + assorted::align8(payload_length) + sizeof(Slot);
   }
DataPageSlotIndex foedus::storage::hash::HashDataPage::reserve_record (HashValue hash, const BloomFilterFingerprint & fingerprint, const void * key, uint16_t key_length, uint16_t payload_length)
A system transaction that creates a logically deleted record in this page for the given key.
Parameters
[in] hash hash value of the key.
[in] fingerprint Bloom Filter fingerprint of the key.
[in] key full key.
[in] key_length full key length.
[in] payload_length the new record can contain at least this length of payload
Returns
slot index of the newly created record
Precondition
the page is locked
the page must not already contain a record with the exact key except it's moved
required_space(key_length, payload_length) <= available_space()
This method also adds the fingerprint to the bloom filter.
Definition at line 170 of file hash_page_impl.cpp.
References foedus::storage::hash::DataPageBloomFilter::add(), foedus::assorted::align8(), ASSERT_ND, available_space(), get_record_count(), get_slot(), foedus::storage::hash::HashDataPage::Slot::hash_, foedus::storage::PageHeader::increment_key_count(), foedus::storage::PageVersion::is_locked(), foedus::Epoch::kEpochInitialCurrent, foedus::storage::hash::HashDataPage::Slot::key_length_, foedus::assorted::memory_fence_release(), next_offset(), foedus::storage::hash::HashDataPage::Slot::offset_, foedus::storage::PageHeader::page_version_, foedus::storage::hash::HashDataPage::Slot::payload_length_, foedus::storage::hash::HashDataPage::Slot::physical_record_length_, record_from_offset(), required_space(), foedus::xct::RwLockableXctId::reset(), foedus::xct::XctId::set(), foedus::xct::XctId::set_deleted(), foedus::storage::hash::HashDataPage::Slot::tid_, and foedus::xct::RwLockableXctId::xct_id_.
{
   ASSERT_ND(header_.page_version_.is_locked());
   ASSERT_ND(available_space() >= HashDataPage::required_space(key_length, payload_length));
   DataPageSlotIndex index = get_record_count();
   Slot& slot = get_slot(index);
   slot.offset_ = next_offset();
   slot.hash_ = hash;
   slot.key_length_ = key_length;
   slot.physical_record_length_ = assorted::align8(key_length) + assorted::align8(payload_length);
   slot.payload_length_ = 0;
   char* record = record_from_offset(slot.offset_);
   std::memcpy(record, key, key_length);
   if (key_length % 8 != 0) {
     std::memset(record + key_length, 0, 8 - (key_length % 8));
   }
   xct::XctId initial_id;
   initial_id.set(
     Epoch::kEpochInitialCurrent,  // TODO(Hideaki) this should be something else
     0);
   initial_id.set_deleted();
   // FIXME(tzwang): do this in a more meaningful place,
   // e.g., have something like get_new_slot.
   slot.tid_.reset();
   slot.tid_.xct_id_ = initial_id;
   // we install the fingerprint to bloom filter BEFORE we increment key count.
   // it's okay for concurrent reads to see false positives, but false negatives are wrong!
   bloom_filter_.add(fingerprint);
   // we increment key count AFTER installing the key because otherwise the optimistic read
   // might see the record but find that the key doesn't match. we need a fence to prevent it.
   assorted::memory_fence_release();
   header_.increment_key_count();
   return index;
 }
DataPageSlotIndex foedus::storage::hash::HashDataPage::search_key_physical (HashValue hash, const BloomFilterFingerprint & fingerprint, const void * key, KeyLength key_length, DataPageSlotIndex record_count, DataPageSlotIndex check_from = 0) const
Search for a physical slot that exactly contains the given key.
Parameters
[in] hash hash value of the key.
[in] fingerprint Bloom Filter fingerprint of the key.
[in] key full key.
[in] key_length full key length.
[in] record_count how many records this page supposedly contains. See below.
[in] check_from From which record we start searching. If you know that records before this index do definitely not contain the keys, this will speed up the search. The caller must guarantee that none of the records before this index have the key or they have been moved.
Returns
index of the slot that has the key. kSlotNotFound if not found (including the case where an exactly-matched record's TID says it's "moved").
Invariant
hash == hashinate(key, key_length)
If you have acquired record_count in a protected way (after a page lock, which you still keep) then this method is an exact search. Otherwise, a concurrent thread might be now inserting, so this method might have false negative (which is why you should take PageVersion for miss-search). However, no false positive possible.
This method searches for a physical slot no matter whether the record is logically deleted. However, "moved" records are completely ignored.
This method is physical-only. The returend record might be now being modified or moved. The only contract is the returend slot (if not kSlotNotFound) points to a physical record whose key is exactly same as the given one. It is trivially guaranteed because key/hash in physical records in our hash pages are immutable.
Definition at line 106 of file hash_page_impl.cpp.
References ASSERT_ND, foedus::storage::hash::DataPageBloomFilter::contains(), foedus::storage::hash::DataPageBloomFilter::extract_fingerprint(), get_record_count(), get_slot(), foedus::storage::hash::HashDataPage::Slot::hash_, foedus::storage::hash::hashinate(), foedus::xct::XctId::is_moved(), foedus::storage::hash::HashDataPage::Slot::key_length_, foedus::storage::hash::kSlotNotFound, LIKELY, foedus::storage::hash::HashDataPage::Slot::offset_, record_from_offset(), foedus::storage::hash::HashDataPage::Slot::tid_, and foedus::xct::RwLockableXctId::xct_id_.
Referenced by foedus::storage::hash::HashStoragePimpl::locate_record(), foedus::storage::hash::HashStoragePimpl::locate_record_in_snapshot(), foedus::storage::hash::ReserveRecords::search_within_page(), and foedus::storage::hash::HashStoragePimpl::track_moved_record_search().
{
   // invariant checks
   ASSERT_ND(hash == hashinate(key, key_length));
   ASSERT_ND(DataPageBloomFilter::extract_fingerprint(hash) == fingerprint);
   ASSERT_ND(record_count <= get_record_count());  // it must be increasing.
 #ifndef NDEBUG
   // Check the invariant on check_from
   for (uint16_t i = 0; i < check_from; ++i) {
     const Slot& s = get_slot(i);
     if (LIKELY(s.hash_ != hash) || s.key_length_ != key_length) {
       continue;
     } else if (s.tid_.xct_id_.is_moved()) {
       continue;
     }
     const char* data = record_from_offset(s.offset_);
     ASSERT_ND(s.key_length_ != key_length || std::memcmp(data, key, key_length) != 0);
   }
 #endif  // NDEBUG
   // check bloom filter first.
   if (!bloom_filter_.contains(fingerprint)) {
     return kSlotNotFound;
   }
   // then most likely this page contains it. let's check one by one.
   for (uint16_t i = check_from; i < record_count; ++i) {
     const Slot& s = get_slot(i);
     if (LIKELY(s.hash_ != hash) || s.key_length_ != key_length) {
       continue;
     }
     // At this point, we don't take read-set (this is a physical search).
     // We thus mind seeing being-written. The logical check will follow.
     // We can also simply check is_moved because the flag is guaranteed to remain once set.
     // But, remember, it might be NOW being moved, so a logical read-set must follow.
     if (s.tid_.xct_id_.is_moved()) {
       // not so rare. this happens.
       DVLOG(1) << "Hash matched, but the record was moved";
       continue;
     }
     const char* data = record_from_offset(s.offset_);
     if (s.key_length_ == key_length && std::memcmp(data, key, key_length) == 0) {
       return i;
     }
     // hash matched, but key didn't match? wow, that's rare
     DLOG(INFO) << "Hash matched, but key didn't match. interesting. hash="
       << assorted::Hex(hash, 16) << ", key="
       << assorted::HexString(std::string(reinterpret_cast<const char*>(key), key_length))
       << ", key_slot="  << assorted::HexString(std::string(data, s.key_length_));
   }
   // should be 1~2%
   DVLOG(0) << "Nope, bloom filter contained it, but key not found in this page. false positive";
   return kSlotNotFound;
 }
DataPageSlotIndex foedus::storage::hash::HashDataPage::to_slot_index (const Slot * slot) const inline
Definition at line 266 of file hash_page_impl.hpp.
References ASSERT_ND.
{
     ASSERT_ND(this);
     ASSERT_ND(slot);
     int64_t index = reinterpret_cast<const Slot*>(this + 1) - slot - 1;
     ASSERT_ND(index >= 0);
     ASSERT_ND(index < static_cast<int64_t>(sizeof(data_) / sizeof(Slot)));
     return static_cast<DataPageSlotIndex>(index);
   }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const HashDataPage & v) friend
defined in hash_page_debug.cpp.
Definition at line 52 of file hash_page_debug.cpp.
{
   o << "<HashDataPage>";
   o << std::endl << "  <vaddr>" << assorted::Hex(reinterpret_cast<uintptr_t>(&v), 16) << "</vaddr>";
   o << std::endl << v.header();
   o << std::endl << "  <bin>" << assorted::Hex(v.get_bin()) << "</bin>";
   uint16_t records = v.get_record_count();
   o << std::endl << "  <record_count>" << records << "</record_count>";
   o << std::endl << "  <next_page>" << v.next_page() << "</next_page>";
   o << std::endl << "  <records>";
   for (DataPageSlotIndex i = 0; i < records; ++i) {
     const HashDataPage::Slot* slot = v.get_slot_address(i);
     o << std::endl << "  <record index=\"" << i
       << "\" hash=\"" << assorted::Hex(slot->hash_, 16)
       << "\" physical_record_len=\"" << slot->physical_record_length_
       << "\" key_length_=\"" << slot->key_length_
       << "\" offset=\"" << slot->offset_
       << "\" payload_len=\"" << slot->payload_length_
       << "\">";
     const char* data = v.record_from_offset(slot->offset_);
     std::string key(data, slot->key_length_);
     o << "<key>" << assorted::HexString(key) << "</key>";
     if (slot->payload_length_ > 0) {
       std::string payload(data + slot->get_aligned_key_length(), slot->payload_length_);
       o << "<payload>" << assorted::HexString(payload) << "</payload>";
     }
     BloomFilterFingerprint fingerprint = DataPageBloomFilter::extract_fingerprint(slot->hash_);
     o << fingerprint;
     o << slot->tid_;
     o << "</record>";
   }
   o << std::endl << "  </records>";
   o << std::endl << "  <BloomFilter>" << v.bloom_filter_ << "</BloomFilter>";
   o << "</HashDataPage>";
   return o;
 }
friend struct ReserveRecords friend
Definition at line 157 of file hash_page_impl.hpp.
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/storage/hash/hash_page_impl.hpp
/home/shino/foedus_code/foedus-core/src/foedus/storage/hash/hash_page_debug.cpp
/home/shino/foedus_code/foedus-core/src/foedus/storage/hash/hash_page_impl.cpp