libfoedus-core: foedus::log::MetaLogger Class Reference
foedus::log::MetaLogger Class Reference final
FOEDUS Components » Log Manager
A log writer for metadata operation.
Detailed Description
A log writer for metadata operation.
This logger instance is created only in the master engine.
Definition at line 45 of file meta_logger_impl.hpp.
#include <meta_logger_impl.hpp>
Public Member Functions
MetaLogger (Engine *engine)
ErrorStack initialize_once () override
ErrorStack uninitialize_once () override
MetaLogger ()=delete
MetaLogger (const MetaLogger &other)=delete
MetaLogger & operator= (const MetaLogger &other)=delete
Public Member Functions inherited from foedus::DefaultInitializable
DefaultInitializable ()
virtual ~DefaultInitializable ()
DefaultInitializable (const DefaultInitializable &)=delete
DefaultInitializable & operator= (const DefaultInitializable &)=delete
ErrorStack initialize () override final
Typical implementation of Initializable::initialize() that provides initialize-once semantics.
ErrorStack uninitialize () override final
Typical implementation of Initializable::uninitialize() that provides uninitialize-once semantics.
bool is_initialized () const override final
Returns whether the object has been already initialized or not.
Public Member Functions inherited from foedus::Initializable
virtual ~Initializable ()
Friends
std::ostream & operator<< (std::ostream &o, const MetaLogger &v)
Constructor & Destructor Documentation
foedus::log::MetaLogger::MetaLogger (Engine * engine) inline explicit
Definition at line 47 of file meta_logger_impl.hpp.
 : engine_(engine), control_block_(nullptr) {}
foedus::log::MetaLogger::MetaLogger () delete
foedus::log::MetaLogger::MetaLogger (const MetaLogger & other) delete
Member Function Documentation
ErrorStack foedus::log::MetaLogger::initialize_once () override virtual
Implements foedus::DefaultInitializable.
Definition at line 36 of file meta_logger_impl.cpp.
References ASSERT_ND, CHECK_ERROR, foedus::log::LogOptions::construct_meta_log_path(), foedus::fs::create_directories(), foedus::log::LogOptions::emulation_, foedus::fs::exists(), foedus::fs::DirectIoFile::get_current_offset(), foedus::soc::SharedMemoryRepo::get_global_memory_anchors(), foedus::savepoint::SavepointManager::get_meta_logger_offsets(), foedus::Engine::get_options(), foedus::savepoint::SavepointManager::get_saved_durable_epoch(), foedus::Engine::get_savepoint_manager(), foedus::soc::SocManager::get_shared_memory_repo(), foedus::Engine::get_soc_manager(), foedus::log::MetaLogControlBlock::initialize(), foedus::Engine::is_master(), foedus::kRetOk, foedus::EngineOptions::log_, foedus::soc::GlobalMemoryAnchors::meta_logger_memory_, foedus::fs::DirectIoFile::open(), and WRAP_ERROR_CODE.
{
   ASSERT_ND(engine_->is_master());
   control_block_ = engine_->get_soc_manager()->get_shared_memory_repo()
         ->get_global_memory_anchors()->meta_logger_memory_;
   control_block_->initialize();
   std::memset(control_block_->buffer_, 0, sizeof(control_block_->buffer_));
   fs::Path path(engine_->get_options().log_.construct_meta_log_path());
   if (!fs::exists(path.parent_path())) {
     fs::create_directories(path.parent_path());
   }
   engine_->get_savepoint_manager()->get_meta_logger_offsets(
     &control_block_->oldest_offset_,
     &control_block_->durable_offset_);
   // Open log file
   current_file_ = new fs::DirectIoFile(path, engine_->get_options().log_.emulation_);
   WRAP_ERROR_CODE(current_file_->open(true, true, true, true));
   CHECK_ERROR(truncate_non_durable(engine_->get_savepoint_manager()->get_saved_durable_epoch()));
   ASSERT_ND(control_block_->durable_offset_ == current_file_->get_current_offset());
   stop_requested_ = false;
   logger_thread_ = std::move(std::thread(&MetaLogger::meta_logger_main, this));
   return kRetOk;
 }
MetaLogger& foedus::log::MetaLogger::operator= (const MetaLogger & other) delete
ErrorStack foedus::log::MetaLogger::uninitialize_once () override virtual
Implements foedus::DefaultInitializable.
Definition at line 164 of file meta_logger_impl.cpp.
References ASSERT_ND, foedus::fs::DirectIoFile::close(), foedus::Engine::is_master(), foedus::kRetOk, foedus::log::MetaLogControlBlock::logger_wakeup_, foedus::soc::SharedPolling::signal(), and foedus::log::MetaLogControlBlock::uninitialize().
{
   ASSERT_ND(engine_->is_master());
   if (logger_thread_.joinable()) {
     {
       stop_requested_ = true;
       control_block_->logger_wakeup_.signal();
     }
     logger_thread_.join();
   }
   control_block_->uninitialize();
   if (current_file_) {
     current_file_->close();
     delete current_file_;
     current_file_ = nullptr;
   }
   return kRetOk;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const MetaLogger & v) friend
Definition at line 228 of file meta_logger_impl.cpp.
{
   o << "<MetaLogger>"
     << "<current_file_>";
   if (v.current_file_) {
     o << *v.current_file_;
   } else {
     o << "nullptr";
   }
   o << "</current_file_>"
     << "</MetaLogger>";
   return o;
 }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/log/meta_logger_impl.hpp
/home/shino/foedus_code/foedus-core/src/foedus/log/meta_logger_impl.cpp