libfoedus-core: foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK > Class Template Reference
foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK > Class Template Reference
FOEDUS Components » Thread and Thread-Group
Implements McsAdaptorConcept over ThreadPimpl.
Detailed Description
template<typename RW_BLOCK>
class foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >
Implements McsAdaptorConcept over ThreadPimpl.
This object is instantiated for every MCS lock invocation in ThreadPimpl, but this object is essentially just the this pointer itself (pimpl_). The compiler will/should eliminate basically everything.
Definition at line 38 of file fwd.hpp.
#include <fwd.hpp>
Public Types
typedef RW_BLOCK ThisRwBlock
Public Member Functions
ThreadPimplMcsAdaptor (ThreadPimpl *pimpl)
~ThreadPimplMcsAdaptor ()
xct::McsBlockIndex issue_new_block ()
void cancel_new_block (xct::McsBlockIndex the_block)
xct::McsBlockIndex get_cur_block () const
ThreadId get_my_id () const
ThreadGroupId get_my_numa_node () const
std::atomic< bool > * me_waiting ()
xct::McsWwBlock * get_ww_my_block (xct::McsBlockIndex index)
RW_BLOCK * get_rw_my_block (xct::McsBlockIndex index)
std::atomic< bool > * other_waiting (ThreadId id)
xct::McsBlockIndex get_other_cur_block (ThreadId id)
xct::McsWwBlock * get_ww_other_block (ThreadId id, xct::McsBlockIndex index)
RW_BLOCK * get_rw_other_block (ThreadId id, xct::McsBlockIndex index)
RW_BLOCK * dereference_rw_tail_block (uint32_t tail_int)
xct::McsRwExtendedBlock * get_rw_other_async_block (ThreadId id, xct::McsRwLock *lock)
void add_rw_async_mapping (xct::McsRwLock *lock, xct::McsBlockIndex block_index)
void remove_rw_async_mapping (xct::McsRwLock *lock)
Member Typedef Documentation
template<typename RW_BLOCK> typedef RW_BLOCK foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::ThisRwBlock
Definition at line 406 of file thread_pimpl.hpp.
Constructor & Destructor Documentation
template<typename RW_BLOCK> foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::ThreadPimplMcsAdaptor (ThreadPimpl * pimpl) inline explicit
Definition at line 408 of file thread_pimpl.hpp.
 : pimpl_(pimpl) {}
template<typename RW_BLOCK> foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::~ThreadPimplMcsAdaptor () inline
Definition at line 409 of file thread_pimpl.hpp.
 {}
Member Function Documentation
template<typename RW_BLOCK> void foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::add_rw_async_mapping (xct::McsRwLock * lock, xct::McsBlockIndex block_index) inline
Definition at line 481 of file thread_pimpl.hpp.
References ASSERT_ND, foedus::xct::McsRwAsyncMapping::block_index_, foedus::thread::ThreadPimpl::control_block_, foedus::thread::ThreadPimpl::global_volatile_page_resolver_, foedus::xct::kNullUniversalLockId, foedus::xct::McsRwAsyncMapping::lock_id_, foedus::thread::ThreadControlBlock::mcs_rw_async_mapping_current_, foedus::thread::ThreadPimpl::mcs_rw_async_mappings_, and foedus::xct::rw_lock_to_universal_lock_id().
{
     // TLS, no concurrency control needed
     auto index = pimpl_->control_block_->mcs_rw_async_mapping_current_;
     ASSERT_ND(index <= pimpl_->control_block_->mcs_block_current_);
     ASSERT_ND(pimpl_->mcs_rw_async_mappings_[index].lock_id_ == xct::kNullUniversalLockId);
     ASSERT_ND(pimpl_->mcs_rw_async_mappings_[index].block_index_ == 0);
     pimpl_->mcs_rw_async_mappings_[index].lock_id_ =
       xct::rw_lock_to_universal_lock_id(pimpl_->global_volatile_page_resolver_, lock);
     pimpl_->mcs_rw_async_mappings_[index].block_index_ = block_index;
     ++pimpl_->control_block_->mcs_rw_async_mapping_current_;
   }
template<typename RW_BLOCK> void foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::cancel_new_block (xct::McsBlockIndex the_block) inline
Definition at line 416 of file thread_pimpl.hpp.
References ASSERT_ND, foedus::thread::ThreadPimpl::control_block_, and foedus::thread::ThreadControlBlock::mcs_block_current_.
{
     ASSERT_ND(pimpl_->control_block_->mcs_block_current_ == the_block);
     --pimpl_->control_block_->mcs_block_current_;
   }
template<typename RW_BLOCK> RW_BLOCK* foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::dereference_rw_tail_block (uint32_t tail_int) inline
Definition at line 464 of file thread_pimpl.hpp.
References foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::get_rw_other_block(), foedus::xct::McsRwLock::get_tail_waiter(), foedus::xct::McsRwLock::get_tail_waiter_block(), and foedus::xct::McsRwLock::tail_.
{
     xct::McsRwLock tail_tmp;
     tail_tmp.tail_ = tail_int;
     uint32_t tail_id = tail_tmp.get_tail_waiter();
     uint32_t tail_block = tail_tmp.get_tail_waiter_block();
     return get_rw_other_block(tail_id, tail_block);
   }
template<typename RW_BLOCK> xct::McsBlockIndex foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::get_cur_block () const inline
Definition at line 420 of file thread_pimpl.hpp.
References foedus::thread::ThreadPimpl::control_block_, and foedus::thread::ThreadControlBlock::mcs_block_current_.
 { return pimpl_->control_block_->mcs_block_current_; }
template<typename RW_BLOCK> ThreadId foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::get_my_id () const inline
Definition at line 421 of file thread_pimpl.hpp.
References foedus::thread::ThreadPimpl::id_.
Referenced by foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::get_rw_other_async_block().
 { return pimpl_->id_; }
template<typename RW_BLOCK> ThreadGroupId foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::get_my_numa_node () const inline
Definition at line 422 of file thread_pimpl.hpp.
References foedus::thread::ThreadPimpl::numa_node_.
 { return pimpl_->numa_node_; }
template<typename RW_BLOCK> xct::McsBlockIndex foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::get_other_cur_block (ThreadId id) inline
Definition at line 445 of file thread_pimpl.hpp.
References foedus::thread::ThreadRef::get_control_block(), foedus::thread::ThreadPimpl::get_thread_ref(), and foedus::thread::ThreadControlBlock::mcs_block_current_.
{
     ThreadRef other = pimpl_->get_thread_ref(id);
     return other.get_control_block()->mcs_block_current_;
   }
template<typename RW_BLOCK> RW_BLOCK* foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::get_rw_my_block (xct::McsBlockIndex index) inline
Definition at line 431 of file thread_pimpl.hpp.
References ASSERT_ND, and foedus::thread::ThreadPimpl::get_mcs_rw_my_blocks().
{
     ASSERT_ND(index > 0);
     ASSERT_ND(index < 0xFFFFU);
     ASSERT_ND(index <= pimpl_->control_block_->mcs_block_current_);
     RW_BLOCK* ret;
     pimpl_->get_mcs_rw_my_blocks(&ret);
     ret += index;
     return ret;
   }
template<typename RW_BLOCK> xct::McsRwExtendedBlock* foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::get_rw_other_async_block (ThreadId id, xct::McsRwLock * lock) inline
Definition at line 471 of file thread_pimpl.hpp.
References ASSERT_ND, foedus::thread::ThreadRef::get_mcs_rw_async_mapping(), foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::get_my_id(), foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::get_rw_other_block(), foedus::thread::ThreadPimpl::get_thread_ref(), foedus::thread::ThreadPimpl::global_volatile_page_resolver_, foedus::assorted::memory_fence_acquire(), and foedus::xct::rw_lock_to_universal_lock_id().
{
     ASSERT_ND(id != get_my_id());
     ThreadRef other = pimpl_->get_thread_ref(id);
     assorted::memory_fence_acquire();
     auto lock_id = xct::rw_lock_to_universal_lock_id(pimpl_->global_volatile_page_resolver_, lock);
     auto* mapping = other.get_mcs_rw_async_mapping(lock_id);
     ASSERT_ND(mapping);
     ASSERT_ND(mapping->lock_id_ == lock_id);
     return get_rw_other_block(id, mapping->block_index_);
   }
template<typename RW_BLOCK> RW_BLOCK* foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::get_rw_other_block (ThreadId id, xct::McsBlockIndex index) inline
Definition at line 454 of file thread_pimpl.hpp.
References ASSERT_ND, foedus::thread::ThreadRef::get_control_block(), foedus::thread::ThreadRef::get_mcs_rw_blocks(), foedus::thread::ThreadPimpl::get_thread_ref(), and foedus::thread::ThreadControlBlock::mcs_block_current_.
Referenced by foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::dereference_rw_tail_block(), and foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::get_rw_other_async_block().
{
     ASSERT_ND(index > 0);
     ASSERT_ND(index < 0xFFFFU);
     ThreadRef other = pimpl_->get_thread_ref(id);
     RW_BLOCK* ret;
     other.get_mcs_rw_blocks(&ret);
     ASSERT_ND(index <= other.get_control_block()->mcs_block_current_);
     ret += index;
     return ret;
   }
template<typename RW_BLOCK> xct::McsWwBlock* foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::get_ww_my_block (xct::McsBlockIndex index) inline
Definition at line 425 of file thread_pimpl.hpp.
References ASSERT_ND, and foedus::thread::ThreadPimpl::mcs_ww_blocks_.
{
     ASSERT_ND(index > 0);
     ASSERT_ND(index < 0xFFFFU);
     ASSERT_ND(index <= pimpl_->control_block_->mcs_block_current_);
     return pimpl_->mcs_ww_blocks_ + index;
   }
template<typename RW_BLOCK> xct::McsWwBlock* foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::get_ww_other_block (ThreadId id, xct::McsBlockIndex index) inline
Definition at line 449 of file thread_pimpl.hpp.
References ASSERT_ND, foedus::thread::ThreadRef::get_control_block(), foedus::thread::ThreadRef::get_mcs_ww_blocks(), foedus::thread::ThreadPimpl::get_thread_ref(), and foedus::thread::ThreadControlBlock::mcs_block_current_.
{
     ThreadRef other = pimpl_->get_thread_ref(id);
     ASSERT_ND(index <= other.get_control_block()->mcs_block_current_);
     return other.get_mcs_ww_blocks() + index;
   }
template<typename RW_BLOCK> xct::McsBlockIndex foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::issue_new_block () inline
Definition at line 411 of file thread_pimpl.hpp.
References ASSERT_ND, foedus::thread::ThreadPimpl::control_block_, and foedus::thread::ThreadControlBlock::mcs_block_current_.
{
     // if this assertion fires, probably we are retrying something too many times
     ASSERT_ND(pimpl_->control_block_->mcs_block_current_ < 0xFFFFU);
     return ++pimpl_->control_block_->mcs_block_current_;
   }
template<typename RW_BLOCK> std::atomic<bool>* foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::me_waiting () inline
Definition at line 423 of file thread_pimpl.hpp.
References foedus::thread::ThreadPimpl::control_block_, and foedus::thread::ThreadControlBlock::mcs_waiting_.
 { return &pimpl_->control_block_->mcs_waiting_; }
template<typename RW_BLOCK> std::atomic<bool>* foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::other_waiting (ThreadId id) inline
Definition at line 441 of file thread_pimpl.hpp.
References foedus::thread::ThreadRef::get_control_block(), foedus::thread::ThreadPimpl::get_thread_ref(), and foedus::thread::ThreadControlBlock::mcs_waiting_.
{
     ThreadRef other = pimpl_->get_thread_ref(id);
     return &(other.get_control_block()->mcs_waiting_);
   }
template<typename RW_BLOCK> void foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >::remove_rw_async_mapping (xct::McsRwLock * lock) inline
Definition at line 492 of file thread_pimpl.hpp.
References ASSERT_ND, foedus::xct::McsRwAsyncMapping::block_index_, foedus::thread::ThreadPimpl::control_block_, foedus::thread::ThreadPimpl::global_volatile_page_resolver_, foedus::xct::kNullUniversalLockId, foedus::xct::McsRwAsyncMapping::lock_id_, foedus::thread::ThreadControlBlock::mcs_rw_async_mapping_current_, foedus::thread::ThreadPimpl::mcs_rw_async_mappings_, and foedus::xct::rw_lock_to_universal_lock_id().
{
     xct::UniversalLockId lock_id =
       xct::rw_lock_to_universal_lock_id(pimpl_->global_volatile_page_resolver_, lock);
     ASSERT_ND(pimpl_->control_block_->mcs_rw_async_mapping_current_);
     for (uint32_t i = 0; i < pimpl_->control_block_->mcs_rw_async_mapping_current_; ++i) {
       if (pimpl_->mcs_rw_async_mappings_[i].lock_id_ == lock_id) {
         ASSERT_ND(pimpl_->mcs_rw_async_mappings_[i].block_index_);
         pimpl_->mcs_rw_async_mappings_[i].lock_id_ = xct::kNullUniversalLockId;
         pimpl_->mcs_rw_async_mappings_[i].block_index_= 0;
         return;
       }
     }
     ASSERT_ND(false);
   }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/thread/fwd.hpp
/home/shino/foedus_code/foedus-core/include/foedus/thread/thread_pimpl.hpp