libfoedus-core: foedus::memory::NumaNodeMemory Class Reference
foedus::memory::NumaNodeMemory Class Reference final
FOEDUS Components » Memory Manager » Memory HierarchyFOEDUS Components » | Thread and Thread-Group
Repository of memories dynamically acquired and shared within one NUMA node (socket).
Detailed Description
Repository of memories dynamically acquired and shared within one NUMA node (socket).
One NumaNodeMemory corresponds to one foedus::thread::ThreadGroup. All threads in the thread group belong to the NUMA node, thus sharing memories between them must be efficient. So, all memories here are allocated/freed via numa_alloc_interleaved(), numa_alloc_onnode(), and numa_free() (except the user specifies to not use them).
Definition at line 48 of file numa_node_memory.hpp.
#include <numa_node_memory.hpp>
Public Member Functions
NumaNodeMemory ()=delete
NumaNodeMemory (Engine *engine, foedus::thread::ThreadGroupId numa_node)
ErrorStack initialize_once () override
ErrorStack uninitialize_once () override
foedus::thread::ThreadGroupId get_numa_node () const
PagePool * get_volatile_pool ()
PagePool * get_snapshot_pool ()
cache::CacheHashtable * get_snapshot_cache_table ()
foedus::thread::ThreadLocalOrdinal get_core_memory_count () const
std::vector< NumaCoreMemory * > & get_core_memories ()
NumaCoreMemory * get_core_memory (foedus::thread::ThreadId id) const
NumaCoreMemory * get_core_memory (foedus::thread::ThreadLocalOrdinal ordinal) const
ErrorStack allocate_numa_memory_general (uint64_t size, uint64_t alignment, AlignedMemory *out) const
Allocate a memory of the given size on this NUMA node.
ErrorStack allocate_numa_memory (uint64_t size, AlignedMemory *out) const
ErrorStack allocate_huge_numa_memory (uint64_t size, AlignedMemory *out) const
PagePoolOffsetChunk * get_volatile_offset_chunk_memory_piece (foedus::thread::ThreadLocalOrdinal core_ordinal)
PagePoolOffsetChunk * get_snapshot_offset_chunk_memory_piece (foedus::thread::ThreadLocalOrdinal core_ordinal)
AlignedMemorySlice get_log_buffer_memory_piece (log::LoggerId logger)
std::string dump_free_memory_stat () const
Report rough statistics of free memory.
Public Member Functions inherited from foedus::DefaultInitializable
DefaultInitializable ()
virtual ~DefaultInitializable ()
DefaultInitializable (const DefaultInitializable &)=delete
DefaultInitializable & operator= (const DefaultInitializable &)=delete
ErrorStack initialize () override final
Typical implementation of Initializable::initialize() that provides initialize-once semantics.
ErrorStack uninitialize () override final
Typical implementation of Initializable::uninitialize() that provides uninitialize-once semantics.
bool is_initialized () const override final
Returns whether the object has been already initialized or not.
Public Member Functions inherited from foedus::Initializable
virtual ~Initializable ()
Constructor & Destructor Documentation
foedus::memory::NumaNodeMemory::NumaNodeMemory () delete
foedus::memory::NumaNodeMemory::NumaNodeMemory (Engine * engine, foedus::thread::ThreadGroupId numa_node)
Definition at line 41 of file numa_node_memory.cpp.
   : engine_(engine),
     numa_node_(numa_node),
     cores_(engine_->get_options().thread_.thread_count_per_group_),
     loggers_(engine_->get_options().log_.loggers_per_node_),
     snapshot_cache_table_(nullptr) {
 }
Member Function Documentation
ErrorStack foedus::memory::NumaNodeMemory::allocate_huge_numa_memory (uint64_t size, AlignedMemory * out) const inline
Definition at line 88 of file numa_node_memory.hpp.
References allocate_numa_memory_general(), and foedus::memory::kHugepageSize.
Referenced by initialize_once().
{
     return allocate_numa_memory_general(size, kHugepageSize, out);
   }
ErrorStack foedus::memory::NumaNodeMemory::allocate_numa_memory (uint64_t size, AlignedMemory * out) const inline
Definition at line 85 of file numa_node_memory.hpp.
References allocate_numa_memory_general().
Referenced by initialize_once(), foedus::memory::NumaCoreMemory::initialize_once(), and foedus::log::Logger::initialize_once().
{
     return allocate_numa_memory_general(size, 1 << 12, out);
   }
ErrorStack foedus::memory::NumaNodeMemory::allocate_numa_memory_general (uint64_t size, uint64_t alignment, AlignedMemory * out) const
Allocate a memory of the given size on this NUMA node.
Parameters
[in] size byte size of the memory to acquire
[in] alignment alignment size
[out] out allocated memory is moved to object
Returns
Expect OUTOFMEMORY error.
Definition at line 201 of file numa_node_memory.cpp.
References foedus::memory::AlignedMemory::alloc(), ASSERT_ND, ERROR_STACK, foedus::Engine::get_options(), foedus::memory::AlignedMemory::is_null(), foedus::kErrorCodeOutofmemory, foedus::memory::kHugepageSize, foedus::memory::AlignedMemory::kNumaAllocOnnode, foedus::memory::AlignedMemory::kNumaMmapOneGbPages, foedus::kRetOk, foedus::EngineOptions::memory_, and foedus::memory::MemoryOptions::use_mmap_hugepages_.
Referenced by allocate_huge_numa_memory(), and allocate_numa_memory().
{
   ASSERT_ND(out);
   if (engine_->get_options().memory_.use_mmap_hugepages_ &&
     alignment >= kHugepageSize
     && size >= (1ULL << 30) * 8 / 10) {
     LOG(INFO) << "This is a big memory allocation. Let's use the mmap hugepage (1GB pages)";
     out->alloc(size, 1ULL << 30, AlignedMemory::kNumaMmapOneGbPages, numa_node_);
   } else {
     out->alloc(size, alignment, AlignedMemory::kNumaAllocOnnode, numa_node_);
   }
   if (out->is_null()) {
     return ERROR_STACK(kErrorCodeOutofmemory);
   }
   return kRetOk;
 }
std::string foedus::memory::NumaNodeMemory::dump_free_memory_stat () const
Report rough statistics of free memory.
Definition at line 220 of file numa_node_memory.cpp.
References foedus::memory::PagePool::Stat::allocated_pages_, foedus::memory::PagePool::get_stat(), and foedus::memory::PagePool::Stat::total_pages_.
{
   std::stringstream ret;
   PagePool::Stat volatile_stat = volatile_pool_.get_stat();
   ret << "    Volatile-Pool: " << volatile_stat.allocated_pages_ << " allocated pages, "
     << volatile_stat.total_pages_ << " total pages, "
     << (volatile_stat.total_pages_ - volatile_stat.allocated_pages_) << " free pages"
     << std::endl;
   PagePool::Stat snapshot_stat = snapshot_pool_.get_stat();
   ret << "    Snapshot-Pool: " << snapshot_stat.allocated_pages_ << " allocated pages, "
     << snapshot_stat.total_pages_ << " total pages, "
     << (snapshot_stat.total_pages_ - snapshot_stat.allocated_pages_) << " free pages"
     << std::endl;
   return ret.str();
 }
std::vector<NumaCoreMemory*>& foedus::memory::NumaNodeMemory::get_core_memories () inline
Definition at line 66 of file numa_node_memory.hpp.
 { return core_memories_; }
NumaCoreMemory* foedus::memory::NumaNodeMemory::get_core_memory (foedus::thread::ThreadId id) const inline
Definition at line 67 of file numa_node_memory.hpp.
References foedus::thread::decompose_numa_local_ordinal().
Referenced by foedus::thread::ThreadPimpl::initialize_once(), and foedus::log::ThreadLogBuffer::initialize_once().
{
     return core_memories_[foedus::thread::decompose_numa_local_ordinal(id)];
   }
NumaCoreMemory* foedus::memory::NumaNodeMemory::get_core_memory (foedus::thread::ThreadLocalOrdinal ordinal) const inline
Definition at line 70 of file numa_node_memory.hpp.
{
     return core_memories_[ordinal];
   }
foedus::thread::ThreadLocalOrdinal foedus::memory::NumaNodeMemory::get_core_memory_count () const inline
Definition at line 62 of file numa_node_memory.hpp.
References ASSERT_ND, and foedus::thread::kMaxThreadLocalOrdinal.
{
     ASSERT_ND(core_memories_.size() <= foedus::thread::kMaxThreadLocalOrdinal);
     return static_cast<foedus::thread::ThreadLocalOrdinal>(core_memories_.size());
   }
AlignedMemorySlice foedus::memory::NumaNodeMemory::get_log_buffer_memory_piece (log::LoggerId logger) inline
Definition at line 100 of file numa_node_memory.hpp.
Referenced by foedus::memory::NumaCoreMemory::initialize_once().
{
     return log_buffer_memory_pieces_[logger];
   }
foedus::thread::ThreadGroupId foedus::memory::NumaNodeMemory::get_numa_node () const inline
Definition at line 55 of file numa_node_memory.hpp.
Referenced by foedus::memory::NumaCoreMemory::NumaCoreMemory().
 { return numa_node_; }
cache::CacheHashtable* foedus::memory::NumaNodeMemory::get_snapshot_cache_table () inline
Definition at line 59 of file numa_node_memory.hpp.
Referenced by foedus::cache::CacheManagerPimpl::initialize_once(), and foedus::thread::ThreadPimpl::initialize_once().
 { return snapshot_cache_table_; }
PagePoolOffsetChunk* foedus::memory::NumaNodeMemory::get_snapshot_offset_chunk_memory_piece (foedus::thread::ThreadLocalOrdinal core_ordinal) inline
Definition at line 96 of file numa_node_memory.hpp.
Referenced by foedus::memory::NumaCoreMemory::initialize_once().
{
     return snapshot_offset_chunk_memory_pieces_[core_ordinal];
   }
PagePool* foedus::memory::NumaNodeMemory::get_snapshot_pool () inline
Definition at line 58 of file numa_node_memory.hpp.
Referenced by foedus::cache::CacheManagerPimpl::initialize_once(), foedus::memory::NumaCoreMemory::initialize_once(), and foedus::thread::ThreadPimpl::initialize_once().
 { return &snapshot_pool_; }
PagePoolOffsetChunk* foedus::memory::NumaNodeMemory::get_volatile_offset_chunk_memory_piece (foedus::thread::ThreadLocalOrdinal core_ordinal) inline
Definition at line 92 of file numa_node_memory.hpp.
Referenced by foedus::memory::NumaCoreMemory::initialize_once().
{
     return volatile_offset_chunk_memory_pieces_[core_ordinal];
   }
PagePool* foedus::memory::NumaNodeMemory::get_volatile_pool () inline
Definition at line 57 of file numa_node_memory.hpp.
Referenced by foedus::memory::NumaCoreMemory::initialize_once(), and foedus::thread::ThreadPimpl::initialize_once().
 { return &volatile_pool_; }
ErrorStack foedus::memory::NumaNodeMemory::initialize_once () override virtual
Implements foedus::DefaultInitializable.
Definition at line 57 of file numa_node_memory.cpp.
References foedus::memory::AlignedMemory::alloc(), allocate_huge_numa_memory(), allocate_numa_memory(), ASSERT_ND, foedus::memory::PagePool::attach(), foedus::EngineOptions::cache_, CHECK_ERROR, foedus::memory::AlignedMemory::get_block(), foedus::memory::PagePool::get_memory_size(), foedus::soc::SharedMemoryRepo::get_node_memory_anchors(), foedus::memory::get_numa_node_size(), foedus::Engine::get_options(), foedus::soc::SocManager::get_shared_memory_repo(), foedus::memory::AlignedMemory::get_size(), foedus::Engine::get_soc_manager(), foedus::soc::SharedMemoryRepo::get_volatile_pool(), foedus::memory::PagePool::initialize(), foedus::memory::PagePool::is_initialized(), foedus::memory::AlignedMemory::kNumaAllocOnnode, foedus::storage::kPageSize, foedus::kRetOk, foedus::EngineOptions::memory_, foedus::memory::MemoryOptions::page_pool_size_mb_per_node_, foedus::memory::MemoryOptions::rigorous_page_boundary_check_, foedus::memory::PagePool::set_debug_pool_name(), foedus::cache::CacheOptions::snapshot_cache_size_mb_per_node_, and foedus::soc::NodeMemoryAnchors::volatile_pool_status_.
{
   LOG(INFO) << "Initializing NumaNodeMemory for node " << static_cast<int>(numa_node_) << "."
     << " BEFORE: numa_node_size=" << get_numa_node_size(numa_node_);
   // volatile pool is placed on the shared memory
   soc::SharedMemoryRepo* memory_repo = engine_->get_soc_manager()->get_shared_memory_repo();
   uint64_t volatile_size =
     static_cast<uint64_t>(engine_->get_options().memory_.page_pool_size_mb_per_node_) << 20;
   volatile_pool_.attach(
     memory_repo->get_node_memory_anchors(numa_node_)->volatile_pool_status_,
     memory_repo->get_volatile_pool(numa_node_),
     volatile_size,
     true,
     engine_->get_options().memory_.rigorous_page_boundary_check_);
   volatile_pool_.set_debug_pool_name(
     std::string("VolatilePool-")
     + std::to_string(static_cast<int>(numa_node_)));
   // snapshot pool is SOC-local
   uint64_t snapshot_pool_bytes
     = static_cast<uint64_t>(engine_->get_options().cache_.snapshot_cache_size_mb_per_node_) << 20;
   if (engine_->get_options().memory_.rigorous_page_boundary_check_) {
     // mprotect raises EINVAL if the underlying pages are hugepages.
     LOG(INFO) << "rigorous_page_boundary_check_ is specified, so disabled hugepages.";
     allocate_numa_memory(snapshot_pool_bytes, &snapshot_pool_memory_);
   } else {
     allocate_huge_numa_memory(snapshot_pool_bytes, &snapshot_pool_memory_);
   }
   snapshot_pool_control_block_.alloc(1 << 12, 1 << 12, AlignedMemory::kNumaAllocOnnode, numa_node_);
   snapshot_pool_.attach(
     reinterpret_cast<PagePoolControlBlock*>(snapshot_pool_control_block_.get_block()),
     snapshot_pool_memory_.get_block(),
     snapshot_pool_memory_.get_size(),
     true,
     engine_->get_options().memory_.rigorous_page_boundary_check_);
   snapshot_pool_.set_debug_pool_name(
     std::string("SnapshotPool-")
     + std::to_string(static_cast<int>(numa_node_)));
   CHECK_ERROR(volatile_pool_.initialize());
   CHECK_ERROR(snapshot_pool_.initialize());
   // snapshot_pool_ consumes #pages * 4kb bytes of memory.
   // CacheBucket is 16 bytes, so even with 32-fold (3% full hashtable), we spend only
   // #pages * 0.5kb for hash buckets. This is a neligible overhead.
   uint64_t cache_hashtable_buckets = (snapshot_pool_.get_memory_size() / storage::kPageSize) * 32;
   snapshot_cache_table_ = new cache::CacheHashtable(cache_hashtable_buckets, numa_node_);
   CHECK_ERROR(initialize_page_offset_chunk_memory());
   CHECK_ERROR(initialize_log_buffers_memory());
   for (auto ordinal = 0; ordinal < cores_; ++ordinal) {
     CHECK_ERROR(initialize_core_memory(ordinal));
   }
   ASSERT_ND(volatile_pool_.is_initialized());
   ASSERT_ND(snapshot_pool_.is_initialized());
   ASSERT_ND(core_memories_.size() == cores_);
   ASSERT_ND(volatile_offset_chunk_memory_pieces_.size() == cores_);
   ASSERT_ND(snapshot_offset_chunk_memory_pieces_.size() == cores_);
   ASSERT_ND(log_buffer_memory_pieces_.size() == cores_);
   LOG(INFO) << "Initialized NumaNodeMemory for node " << static_cast<int>(numa_node_) << "."
     << " AFTER: numa_node_size=" << get_numa_node_size(numa_node_);
   return kRetOk;
 }
ErrorStack foedus::memory::NumaNodeMemory::uninitialize_once () override virtual
Implements foedus::DefaultInitializable.
Definition at line 175 of file numa_node_memory.cpp.
References foedus::ErrorStackBatch::emprace_back(), foedus::memory::get_numa_node_size(), foedus::memory::AlignedMemory::release_block(), SUMMARIZE_ERROR_BATCH, foedus::memory::PagePool::uninitialize(), and foedus::ErrorStackBatch::uninitialize_and_delete_all().
{
   LOG(INFO) << "Uninitializing NumaNodeMemory for node " << static_cast<int>(numa_node_) << "."
     << " BEFORE: numa_node_size=" << get_numa_node_size(numa_node_);
   ErrorStackBatch batch;
   batch.uninitialize_and_delete_all(&core_memories_);
   volatile_offset_chunk_memory_pieces_.clear();
   volatile_offset_chunk_memory_.release_block();
   snapshot_offset_chunk_memory_pieces_.clear();
   snapshot_offset_chunk_memory_.release_block();
   log_buffer_memory_pieces_.clear();
   log_buffer_memory_.release_block();
   if (snapshot_cache_table_) {
     delete snapshot_cache_table_;
     snapshot_cache_table_ = nullptr;
   }
   batch.emprace_back(volatile_pool_.uninitialize());
   batch.emprace_back(snapshot_pool_.uninitialize());
   snapshot_pool_memory_.release_block();
   snapshot_pool_control_block_.release_block();
   LOG(INFO) << "Uninitialized NumaNodeMemory for node " << static_cast<int>(numa_node_) << "."
     << " AFTER: numa_node_size=" << get_numa_node_size(numa_node_);
   return SUMMARIZE_ERROR_BATCH(batch);
 }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/memory/numa_node_memory.hpp
/home/shino/foedus_code/foedus-core/src/foedus/memory/numa_node_memory.cpp