libfoedus-core: foedus::ErrorStackBatch Class Reference
foedus::ErrorStackBatch Class Reference
FOEDUS Programming Idioms » Error codes, messages, and stacktraces
Batches zero or more ErrorStack objects to represent in one ErrorStack.
Detailed Description
Batches zero or more ErrorStack objects to represent in one ErrorStack.
This batching is useful in a context that might observe multiple errors while it can return only one ErrorStack object; e.g., Initializable::uninitialize().
Definition at line 34 of file error_stack_batch.hpp.
#include <error_stack_batch.hpp>
Public Member Functions
ErrorStackBatch ()
ErrorStackBatch (const ErrorStackBatch &other)
Non-move copy constructor.
ErrorStackBatch & operator= (const ErrorStackBatch &other)
Non-move assignment.
ErrorStackBatch (ErrorStackBatch &&other)
Move constructor that steals the internal std::vector without copying.
ErrorStackBatch & operator= (ErrorStackBatch &&other)
Move assignment that steals the internal std::vector without copying.
void clear ()
void push_back (const ErrorStack &error_stack)
If the given ErrorStack is an error, this method adds it to the end of this batch.
void emprace_back (ErrorStack &&error_stack)
If the given ErrorStack is an error, this method adds it to the end of this batch.
bool is_error () const
Returns whether there was any error.
template<class T >
void uninitialize_and_delete_all (std::vector< T * > *vec)
A convenience method to uninitialize and delete all Initializable objects in a vector, storing all errors in this batch.
ErrorStack summarize (const char *filename, const char *func, uint32_t linenum) const
Instantiate an ErrorStack object that summarizes all errors in this batch.
Friends
std::ostream & operator<< (std::ostream &o, const ErrorStackBatch &obj)
Constructor & Destructor Documentation
foedus::ErrorStackBatch::ErrorStackBatch () inline
Definition at line 36 of file error_stack_batch.hpp.
 {}
foedus::ErrorStackBatch::ErrorStackBatch (const ErrorStackBatch & other) inline
Non-move copy constructor.
Definition at line 38 of file error_stack_batch.hpp.
 : error_batch_(other.error_batch_) {}
foedus::ErrorStackBatch::ErrorStackBatch (ErrorStackBatch && other) inline
Move constructor that steals the internal std::vector without copying.
This is more efficient than non-move copy constructor, but provided only when C++11 is supported.
Definition at line 52 of file error_stack_batch.hpp.
{
     error_batch_ = std::move(other.error_batch_);
   }
Member Function Documentation
void foedus::ErrorStackBatch::clear () inline
Definition at line 66 of file error_stack_batch.hpp.
 { error_batch_.clear(); }
void foedus::ErrorStackBatch::emprace_back (ErrorStack && error_stack) inline
If the given ErrorStack is an error, this method adds it to the end of this batch.
This method is more efficient than push_back() but provided only when C++11 is supported.
Definition at line 83 of file error_stack_batch.hpp.
Referenced by uninitialize_and_delete_all(), foedus::thread::ThreadPoolPimpl::uninitialize_once(), foedus::restart::RestartManagerPimpl::uninitialize_once(), foedus::memory::NumaNodeMemory::uninitialize_once(), foedus::memory::EngineMemory::uninitialize_once(), foedus::EnginePimpl::uninitialize_once(), foedus::storage::StorageManagerPimpl::uninitialize_once(), foedus::log::LogManagerPimpl::uninitialize_once(), foedus::xct::XctManagerPimpl::uninitialize_once(), foedus::thread::ThreadPimpl::uninitialize_once(), foedus::snapshot::SnapshotManagerPimpl::uninitialize_once(), and foedus::snapshot::LogReducer::uninitialize_once().
{
     if (!error_stack.is_error()) {
       return;
     }
     error_batch_.emplace_back(error_stack);
   }
bool foedus::ErrorStackBatch::is_error () const inline
Returns whether there was any error.
Definition at line 92 of file error_stack_batch.hpp.
Referenced by summarize().
 { return !error_batch_.empty(); }
ErrorStackBatch& foedus::ErrorStackBatch::operator= (const ErrorStackBatch & other) inline
Non-move assignment.
Definition at line 41 of file error_stack_batch.hpp.
{
     error_batch_ = other.error_batch_;
     return *this;
   }
ErrorStackBatch& foedus::ErrorStackBatch::operator= (ErrorStackBatch && other) inline
Move assignment that steals the internal std::vector without copying.
This is more efficient, but provided only when C++11 is supported.
Definition at line 60 of file error_stack_batch.hpp.
{
     error_batch_ = std::move(other.error_batch_);
     return *this;
   }
void foedus::ErrorStackBatch::push_back (const ErrorStack & error_stack) inline
If the given ErrorStack is an error, this method adds it to the end of this batch.
Definition at line 71 of file error_stack_batch.hpp.
References foedus::ErrorStack::is_error().
Referenced by uninitialize_and_delete_all().
{
     if (!error_stack.is_error()) {
       return;
     }
     error_batch_.push_back(error_stack);
   }
ErrorStack foedus::ErrorStackBatch::summarize (const char * filename, const char * func, uint32_t linenum) const
Instantiate an ErrorStack object that summarizes all errors in this batch.
Consider using SUMMARIZE_ERROR_BATCH(batch).
Definition at line 24 of file error_stack_batch.cpp.
References is_error(), foedus::kErrorCodeBatchedError, and foedus::kRetOk.
{
   if (!is_error()) {
     return kRetOk;
   } else if (error_batch_.size() == 1) {
     return error_batch_[0];
   } else {
     // there were multiple errors. we must batch them.
     std::stringstream message;
     for (size_t i = 0; i < error_batch_.size(); ++i) {
       if (i > 0) {
         message << std::endl;
       }
       message << "Error[" << i << "]:" << error_batch_[i];
     }
     return ErrorStack(filename, func, linenum, kErrorCodeBatchedError, message.str().c_str());
   }
 }
template<class T > void foedus::ErrorStackBatch::uninitialize_and_delete_all (std::vector< T * > * vec) inline
A convenience method to uninitialize and delete all Initializable objects in a vector, storing all errors in this batch.
Definition at line 99 of file error_stack_batch.hpp.
References emprace_back(), and push_back().
Referenced by foedus::thread::ThreadGroup::uninitialize_once(), foedus::memory::NumaNodeMemory::uninitialize_once(), and foedus::log::LogManagerPimpl::uninitialize_once().
{
     while (!vec->empty()) {
       if (vec->back()->is_initialized()) {
 #ifndef DISABLE_CXX11_IN_PUBLIC_HEADERS
         emprace_back(vec->back()->uninitialize());
 #else   // DISABLE_CXX11_IN_PUBLIC_HEADERS
         push_back(vec->back()->uninitialize());
 #endif  // DISABLE_CXX11_IN_PUBLIC_HEADERS
       }
       delete vec->back();
       vec->pop_back();
     }
   }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const ErrorStackBatch & obj) friend
Definition at line 43 of file error_stack_batch.cpp.
{
   o << SUMMARIZE_ERROR_BATCH(obj);
   return o;
 }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/error_stack_batch.hpp
/home/shino/foedus_code/foedus-core/src/foedus/error_stack_batch.cpp