libfoedus-core: foedus::restart::RestartManager Class Reference
foedus::restart::RestartManager Class Reference final
FOEDUS Components » Restart Manager
Restart manager, which recovers the state of database by invoking log-gleaner at start-up.
Detailed Description
Restart manager, which recovers the state of database by invoking log-gleaner at start-up.
Simplistic Restart
A DBMS usually has a complex ('sophisticated') restart routine especially if they try to reduce start-up time. On the other hand, FOEDUS simply invokes the log gleaner just like a periodic snapshot. This is a huge saving in code complexity. As far as we optimize the log gleaner, the start-up time is not slower than typical replay-every-log-style traditional restart, either.
Definition at line 36 of file restart_manager.hpp.
#include <restart_manager.hpp>
Public Member Functions
RestartManager (Engine *engine)
~RestartManager ()
RestartManager ()=delete
RestartManager (const RestartManager &)=delete
RestartManager & operator= (const RestartManager &)=delete
ErrorStack initialize () override
Acquires resources in this object, usually called right after constructor.
bool is_initialized () const override
Returns whether the object has been already initialized or not.
ErrorStack uninitialize () override
An idempotent method to release all resources of this object, if any.
Public Member Functions inherited from foedus::Initializable
virtual ~Initializable ()
Constructor & Destructor Documentation
foedus::restart::RestartManager::RestartManager (Engine * engine) explicit
Definition at line 22 of file restart_manager.cpp.
                                              : pimpl_(nullptr) {
   pimpl_ = new RestartManagerPimpl(engine);
 }
foedus::restart::RestartManager::~RestartManager ()
Definition at line 25 of file restart_manager.cpp.
{
   delete pimpl_;
   pimpl_ = nullptr;
 }
foedus::restart::RestartManager::RestartManager () delete
foedus::restart::RestartManager::RestartManager (const RestartManager &) delete
Member Function Documentation
ErrorStack foedus::restart::RestartManager::initialize () override virtual
Acquires resources in this object, usually called right after constructor.
Precondition
is_initialized() == FALSE
If and only if the return value was not an error, is_initialized() will return TRUE. This method is usually not idempotent, but some implementation can choose to be. In that case, the implementation class should clarify that it's idempotent. This method is responsible for releasing all acquired resources when initialization fails. This method itself is NOT thread-safe. Do not call this in a racy situation.
Implements foedus::Initializable.
Definition at line 30 of file restart_manager.cpp.
References foedus::DefaultInitializable::initialize().
 { return pimpl_->initialize(); }
bool foedus::restart::RestartManager::is_initialized () const override virtual
Returns whether the object has been already initialized or not.
Implements foedus::Initializable.
Definition at line 31 of file restart_manager.cpp.
References foedus::DefaultInitializable::is_initialized().
 { return pimpl_->is_initialized(); }
RestartManager& foedus::restart::RestartManager::operator= (const RestartManager &) delete
ErrorStack foedus::restart::RestartManager::uninitialize () override virtual
An idempotent method to release all resources of this object, if any.
After this method, is_initialized() will return FALSE. Whether this method encounters an error or not, the implementation should make the best effort to release as many resources as possible. In other words, Do not leak all resources because of one issue. This method itself is NOT thread-safe. Do not call this in a racy situation.
Attention
This method is NOT automatically called from the destructor. This is due to the fundamental limitation in C++. Explicitly call this method as soon as you are done, checking the returned value. You can also use UninitializeGuard to ameliorate the issue, but it's not perfect.
Returns
The error this method encounters, if any. In case there are multiple errors while uninitialization, the implementation should use ErrorStackBatch to produce a batched ErrorStack object.
Implements foedus::Initializable.
Definition at line 32 of file restart_manager.cpp.
References foedus::DefaultInitializable::uninitialize().
 { return pimpl_->uninitialize(); }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/restart/restart_manager.hpp
/home/shino/foedus_code/foedus-core/src/foedus/restart/restart_manager.cpp