libfoedus-core: foedus::thread::ThreadGroup Class Reference
foedus::thread::ThreadGroup Class Reference final
FOEDUS Components » Thread and Thread-Group
Represents a group of pre-allocated threads running in one NUMA node.
Detailed Description
Represents a group of pre-allocated threads running in one NUMA node.
Detailed description of this class.
Definition at line 38 of file thread_group.hpp.
#include <thread_group.hpp>
Public Member Functions
ThreadGroup ()=delete
ThreadGroup (Engine *engine, ThreadGroupId group_id)
~ThreadGroup ()
ErrorStack initialize_once () override
ErrorStack uninitialize_once () override
ThreadGroupId get_group_id () const
memory::NumaNodeMemory * get_node_memory () const
Thread * get_thread (ThreadLocalOrdinal ordinal) const
Returns Thread object for the given ordinal in this group.
Public Member Functions inherited from foedus::DefaultInitializable
DefaultInitializable ()
virtual ~DefaultInitializable ()
DefaultInitializable (const DefaultInitializable &)=delete
DefaultInitializable & operator= (const DefaultInitializable &)=delete
ErrorStack initialize () override final
Typical implementation of Initializable::initialize() that provides initialize-once semantics.
ErrorStack uninitialize () override final
Typical implementation of Initializable::uninitialize() that provides uninitialize-once semantics.
bool is_initialized () const override final
Returns whether the object has been already initialized or not.
Public Member Functions inherited from foedus::Initializable
virtual ~Initializable ()
Friends
std::ostream & operator<< (std::ostream &o, const ThreadGroup &v)
Constructor & Destructor Documentation
foedus::thread::ThreadGroup::ThreadGroup () delete
foedus::thread::ThreadGroup::ThreadGroup (Engine * engine, ThreadGroupId group_id)
Definition at line 32 of file thread_group.cpp.
   : engine_(engine), group_id_(group_id) {
 }
foedus::thread::ThreadGroup::~ThreadGroup ()
Definition at line 35 of file thread_group.cpp.
{
 }
Member Function Documentation
ThreadGroupId foedus::thread::ThreadGroup::get_group_id () const inline
Definition at line 46 of file thread_group.hpp.
 { return group_id_; }
memory::NumaNodeMemory* foedus::thread::ThreadGroup::get_node_memory () const inline
Definition at line 47 of file thread_group.hpp.
 { return node_memory_; }
Thread* foedus::thread::ThreadGroup::get_thread (ThreadLocalOrdinal ordinal) const inline
Returns Thread object for the given ordinal in this group.
Definition at line 50 of file thread_group.hpp.
Referenced by foedus::log::Logger::initialize_once().
 { return threads_[ordinal]; }
ErrorStack foedus::thread::ThreadGroup::initialize_once () override virtual
Implements foedus::DefaultInitializable.
Definition at line 38 of file thread_group.cpp.
References CHECK_ERROR, foedus::thread::compose_thread_id(), foedus::memory::EngineMemory::get_local_memory(), foedus::Engine::get_memory_manager(), foedus::Engine::get_options(), foedus::kRetOk, foedus::EngineOptions::thread_, foedus::thread::ThreadOptions::thread_count_per_group_, and foedus::thread::to_global_ordinal().
{
   node_memory_ = engine_->get_memory_manager()->get_local_memory();
   ThreadLocalOrdinal count = engine_->get_options().thread_.thread_count_per_group_;
   for (ThreadLocalOrdinal ordinal = 0; ordinal < count; ++ordinal) {
     ThreadId id = compose_thread_id(group_id_, ordinal);
     ThreadGlobalOrdinal global_ordinal = to_global_ordinal(id, count);
     threads_.push_back(new Thread(engine_, id, global_ordinal));
     CHECK_ERROR(threads_.back()->initialize());
   }
   return kRetOk;
 }
ErrorStack foedus::thread::ThreadGroup::uninitialize_once () override virtual
Implements foedus::DefaultInitializable.
Definition at line 50 of file thread_group.cpp.
References SUMMARIZE_ERROR_BATCH, and foedus::ErrorStackBatch::uninitialize_and_delete_all().
{
   ErrorStackBatch batch;
   batch.uninitialize_and_delete_all(&threads_);
   node_memory_ = nullptr;
   return SUMMARIZE_ERROR_BATCH(batch);
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const ThreadGroup & v) friend
Definition at line 57 of file thread_group.cpp.
{
   o << "<ThreadGroup>";
   o << "<group_id_>" << static_cast<int>(v.group_id_) << "</group_id_>";
   o << "<threads_>";
   for (Thread* child_thread : v.threads_) {
     o << *child_thread;
   }
   o << "</threads_>";
   o << "</ThreadGroup>";
   return o;
 }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/thread/thread_group.hpp
/home/shino/foedus_code/foedus-core/src/foedus/thread/thread_group.cpp