libfoedus-core: foedus::FixedErrorStack Class Reference
foedus::FixedErrorStack Class Reference
FOEDUS Programming Idioms » Error codes, messages, and stacktraces
Representation of ErrorStack that can be copied to other processes and even serialized to files.
Detailed Description
Representation of ErrorStack that can be copied to other processes and even serialized to files.
ErrorStack contains char*, so can't be trivially passed to other processes or serialized. This object is used in such a situation. It does string copying and (if too long) truncation, so do not use this unless required.
Definition at line 41 of file fixed_error_stack.hpp.
#include <fixed_error_stack.hpp>
Public Types
typedef assorted::FixedString< 124 > FixedFileName
typedef assorted::FixedString< 124 > FixedFuncName
typedef assorted::FixedString< 508 > FixedErrorMessage
Public Member Functions
FixedErrorStack ()
Empty constructor.
FixedErrorStack (const ErrorStack &src)
Copy the content of the given ErrorStack.
FixedErrorStack & operator= (const ErrorStack &src)
Assignment operator.
bool is_error () const
Returns if this return code is not kErrorCodeOk.
ErrorCode get_error_code () const
Return the integer error code.
const char * get_message () const
Returns the error message inferred by the error code.
const FixedErrorMessage & get_custom_message () const
Returns the custom error message.
uint16_t get_stack_depth () const
Returns the depth of stack this error code has collected.
uint32_t get_linenum (uint16_t stack_index) const
Returns the line number of the given stack position.
const FixedFileName & get_filename (uint16_t stack_index) const
Returns the file name of the given stack position.
const FixedFuncName & get_func (uint16_t stack_index) const
Returns the function name of the given stack position.
void output (std::ostream *ptr) const
Describe this object to the given stream.
void clear ()
ErrorStack to_error_stack () const
Instantiates an ErrorStack object based on this object.
void from_error_stack (const ErrorStack &other)
Convert ErrorStack to this object.
Friends
std::ostream & operator<< (std::ostream &o, const FixedErrorStack &obj)
Member Typedef Documentation
typedef assorted::FixedString<508> foedus::FixedErrorStack::FixedErrorMessage
Definition at line 45 of file fixed_error_stack.hpp.
typedef assorted::FixedString<124> foedus::FixedErrorStack::FixedFileName
Definition at line 43 of file fixed_error_stack.hpp.
typedef assorted::FixedString<124> foedus::FixedErrorStack::FixedFuncName
Definition at line 44 of file fixed_error_stack.hpp.
Constructor & Destructor Documentation
foedus::FixedErrorStack::FixedErrorStack () inline
Empty constructor.
Definition at line 48 of file fixed_error_stack.hpp.
 : os_errno_(0), error_code_(kErrorCodeOk), stack_depth_(0) {}
foedus::FixedErrorStack::FixedErrorStack (const ErrorStack & src) inline explicit
Copy the content of the given ErrorStack.
Definition at line 50 of file fixed_error_stack.hpp.
References operator=().
 { operator=(src); }
Member Function Documentation
void foedus::FixedErrorStack::clear () inline
Definition at line 91 of file fixed_error_stack.hpp.
References foedus::kErrorCodeOk.
Referenced by from_error_stack(), and foedus::thread::ThreadControlBlock::initialize().
 { error_code_ = kErrorCodeOk; }
void foedus::FixedErrorStack::from_error_stack (const ErrorStack & other)
Convert ErrorStack to this object.
Opposite of to_error_stack
Definition at line 85 of file fixed_error_stack.cpp.
References clear(), foedus::assorted::FixedString< MAXLEN, CHAR >::clear(), foedus::ErrorStack::get_custom_message(), foedus::ErrorStack::get_error_code(), foedus::ErrorStack::get_filename(), foedus::ErrorStack::get_func(), foedus::ErrorStack::get_linenum(), foedus::ErrorStack::get_os_errno(), foedus::ErrorStack::get_stack_depth(), and foedus::ErrorStack::is_error().
{
   if (!other.is_error()) {
     clear();
     return;
   }
   error_code_ = other.get_error_code();
   os_errno_ = other.get_os_errno();
   stack_depth_ = other.get_stack_depth();
   custom_message_.clear();
   if (other.get_custom_message()) {
     custom_message_ = other.get_custom_message();
   }
   for (uint16_t i = 0; i < stack_depth_; ++i) {
     filenames_[i] = other.get_filename(i);
     funcs_[i] = other.get_func(i);
     linenums_[i] = other.get_linenum(i);
   }
 }
const FixedErrorMessage& foedus::FixedErrorStack::get_custom_message () const inline
Returns the custom error message.
Definition at line 65 of file fixed_error_stack.hpp.
Referenced by output().
 { return custom_message_; }
ErrorCode foedus::FixedErrorStack::get_error_code () const inline
Return the integer error code.
Definition at line 59 of file fixed_error_stack.hpp.
 { return error_code_; }
const FixedFileName& foedus::FixedErrorStack::get_filename (uint16_t stack_index) const inline
Returns the file name of the given stack position.
Definition at line 77 of file fixed_error_stack.hpp.
References ASSERT_ND.
Referenced by output().
{
     ASSERT_ND(stack_index < stack_depth_);
     return filenames_[stack_index];
   }
const FixedFuncName& foedus::FixedErrorStack::get_func (uint16_t stack_index) const inline
Returns the function name of the given stack position.
Definition at line 83 of file fixed_error_stack.hpp.
References ASSERT_ND.
Referenced by output().
{
     ASSERT_ND(stack_index < stack_depth_);
     return funcs_[stack_index];
   }
uint32_t foedus::FixedErrorStack::get_linenum (uint16_t stack_index) const inline
Returns the line number of the given stack position.
Definition at line 71 of file fixed_error_stack.hpp.
References ASSERT_ND.
Referenced by output().
{
     ASSERT_ND(stack_index < stack_depth_);
     return linenums_[stack_index];
   }
const char* foedus::FixedErrorStack::get_message () const inline
Returns the error message inferred by the error code.
Definition at line 62 of file fixed_error_stack.hpp.
References foedus::get_error_message().
Referenced by output().
 { return get_error_message(error_code_); }
uint16_t foedus::FixedErrorStack::get_stack_depth () const inline
Returns the depth of stack this error code has collected.
Definition at line 68 of file fixed_error_stack.hpp.
Referenced by output().
 { return stack_depth_; }
bool foedus::FixedErrorStack::is_error () const inline
Returns if this return code is not kErrorCodeOk.
Definition at line 56 of file fixed_error_stack.hpp.
References foedus::kErrorCodeOk.
Referenced by output(), and to_error_stack().
 { return error_code_ != kErrorCodeOk; }
FixedErrorStack & foedus::FixedErrorStack::operator= (const ErrorStack & src)
Assignment operator.
Definition at line 27 of file fixed_error_stack.cpp.
References foedus::assorted::FixedString< MAXLEN, CHAR >::assign(), foedus::assorted::FixedString< MAXLEN, CHAR >::clear(), foedus::ErrorStack::get_custom_message(), foedus::ErrorStack::get_error_code(), foedus::ErrorStack::get_filename(), foedus::ErrorStack::get_func(), foedus::ErrorStack::get_linenum(), foedus::ErrorStack::get_os_errno(), foedus::ErrorStack::get_stack_depth(), foedus::ErrorStack::is_error(), and foedus::kErrorCodeOk.
Referenced by FixedErrorStack().
{
   os_errno_ = 0;
   error_code_ = kErrorCodeOk;
   stack_depth_ = 0;
   custom_message_.clear();
   if (!src.is_error()) {
     return *this;
   }
   if (src.get_custom_message()) {
     custom_message_.assign(src.get_custom_message());
   }
   stack_depth_ = src.get_stack_depth();
   for (uint16_t i = 0; i < stack_depth_; ++i) {
     filenames_[i].assign(src.get_filename(i));
     funcs_[i].assign(src.get_func(i));
     linenums_[i] = src.get_linenum(i);
   }
   os_errno_ = src.get_os_errno();
   error_code_ = src.get_error_code();
   return *this;
 }
void foedus::FixedErrorStack::output (std::ostream * ptr) const
Describe this object to the given stream.
Definition at line 50 of file fixed_error_stack.cpp.
References get_custom_message(), foedus::get_error_name(), get_filename(), get_func(), get_linenum(), get_message(), get_stack_depth(), is_error(), foedus::ErrorStack::kMaxStackDepth, and foedus::assorted::os_error().
Referenced by foedus::operator<<(), and to_error_stack().
{
   std::ostream &o = *ptr;  // just to workaround non-const reference rule.
   if (!is_error()) {
     o << "No error";
   } else {
     o << get_error_name(error_code_) << "(" << error_code_ << "):" << get_message();
     if (os_errno_ != 0) {
       o << " (Latest system call error=" << assorted::os_error(os_errno_) << ")";
     }
     if (!get_custom_message().empty()) {
       o << " (Additional message=" << get_custom_message() << ")";
     }
     for (uint16_t stack_index = 0; stack_index < get_stack_depth(); ++stack_index) {
       o << std::endl << "  " << get_filename(stack_index)
         << ":" << get_linenum(stack_index) << ": ";
       if (!get_func(stack_index).empty()) {
         o << get_func(stack_index) << "()";
       }
     }
     if (get_stack_depth() >= ErrorStack::kMaxStackDepth) {
       o << std::endl << "  .. and more. Increase kMaxStackDepth to see full stacktraces";
     }
   }
 }
ErrorStack foedus::FixedErrorStack::to_error_stack () const
Instantiates an ErrorStack object based on this object.
We can't generate a completely same object (ErrorStack needs const char* pointers), so we put much of information as custom error message.
Definition at line 76 of file fixed_error_stack.cpp.
References ERROR_STACK_MSG, is_error(), foedus::kRetOk, and output().
Referenced by foedus::thread::ImpersonateSession::get_result().
{
   if (!is_error()) {
     return kRetOk;
   }
   std::stringstream msg;
   output(&msg);
   return ERROR_STACK_MSG(error_code_, msg.str().c_str());
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const FixedErrorStack & obj) friend
Definition at line 106 of file fixed_error_stack.cpp.
{
   obj.output(&o);
   return o;
 }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/fixed_error_stack.hpp
/home/shino/foedus_code/foedus-core/src/foedus/fixed_error_stack.cpp