libfoedus-core: foedus::xct::McsWwImpl< ADAPTOR > Class Template Reference
foedus::xct::McsWwImpl< ADAPTOR > Class Template Reference
FOEDUS Components » Transaction Manager
A specialized/simplified implementation of an MCS-locking Algorithm for exclusive-only (WW) locks.
Detailed Description
template<typename ADAPTOR>
class foedus::xct::McsWwImpl< ADAPTOR >
A specialized/simplified implementation of an MCS-locking Algorithm for exclusive-only (WW) locks.
This is exactly same as MCSg. Most places in our codebase now use RW locks, but still there are a few WW-only places, such as page-lock (well, so far).
Definition at line 182 of file xct_mcs_impl.hpp.
#include <xct_mcs_impl.hpp>
Public Member Functions
McsWwImpl (ADAPTOR adaptor)
McsBlockIndex acquire_unconditional (McsWwLock *lock)
[WW] Unconditionally takes exclusive-only MCS lock on the given lock.
McsBlockIndex acquire_try (McsWwLock *lock)
[WW] Try to take an exclusive lock.
McsBlockIndex initial (McsWwLock *lock)
[WW] This doesn't use any atomic operation.
void release (McsWwLock *lock, McsBlockIndex block_index)
[WW] Unlcok an MCS lock acquired by this thread.
Constructor & Destructor Documentation
template<typename ADAPTOR> foedus::xct::McsWwImpl< ADAPTOR >::McsWwImpl (ADAPTOR adaptor) inline explicit
Definition at line 184 of file xct_mcs_impl.hpp.
 : adaptor_(adaptor) {}
Member Function Documentation
template<typename ADAPTOR > McsBlockIndex foedus::xct::McsWwImpl< ADAPTOR >::acquire_try (McsWwLock * lock)
[WW] Try to take an exclusive lock.
Precondition
the lock must NOT be taken by this thread yet.
Returns
0 if failed, the block index if acquired.
Definition at line 137 of file xct_mcs_impl.cpp.
References foedus::xct::assert_mcs_aligned(), ASSERT_ND, foedus::xct::McsWwBlock::clear_successor_release(), foedus::xct::McsWwBlockData::get_thread_id_relaxed(), foedus::xct::McsWwBlockData::is_guest_relaxed(), foedus::xct::McsWwLock::is_locked(), foedus::xct::McsWwBlockData::is_valid_relaxed(), foedus::xct::McsWwLock::tail_, and foedus::xct::McsWwBlockData::word_.
{
   assert_mcs_aligned(mcs_lock);
   // In this function, we don't even need to modify me_waiting because
   // we are not waiting whether we fail or succeed.
   ASSERT_ND(!adaptor_.me_waiting()->load());
   ASSERT_ND(adaptor_.get_cur_block() < 0xFFFFU);
   McsBlockIndex block_index = adaptor_.issue_new_block();
   ASSERT_ND(block_index > 0);
   ASSERT_ND(block_index <= 0xFFFFU);
   McsWwBlock* my_block = adaptor_.get_ww_my_block(block_index);
   my_block->clear_successor_release();
   const thread::ThreadId id = adaptor_.get_my_id();
   McsWwBlockData desired(id, block_index);  // purely local copy. okay to be always relaxed.
   auto* address = &(mcs_lock->tail_);     // be careful on this one!
   assert_mcs_aligned(address);
   McsWwBlockData pred;                      // purely local copy. okay to be always relaxed.
   ASSERT_ND(!pred.is_valid_relaxed());
   // atomic op should imply full barrier, but make sure announcing the initialized new block.
   ASSERT_ND(address->get_word_atomic() != desired.word_);
   bool swapped = assorted::raw_atomic_compare_exchange_weak<uint64_t>(
     &address->word_,
     &pred.word_,
     desired.word_);
   if (swapped) {
     // this means it was not locked.
     ASSERT_ND(mcs_lock->is_locked());
     DVLOG(2) << "Okay, got a lock uncontended. me=" << id;
     ASSERT_ND(address->is_valid_atomic());
     ASSERT_ND(!address->is_guest_atomic());
     ASSERT_ND(!pred.is_valid_relaxed());
     ASSERT_ND(!adaptor_.me_waiting()->load());
     return block_index;  // we got it!
   }
   // We couldn't get the lock. As we didn't even install the queue in this case,
   // we don't need anything for cleanup either. Let's just do sanity check on pred
 #ifndef NDEBUG
   ASSERT_ND(pred.is_valid_relaxed());
   ASSERT_ND(!adaptor_.me_waiting()->load());
   if (!pred.is_guest_relaxed()) {
     thread::ThreadId predecessor_id = pred.get_thread_id_relaxed();
     ASSERT_ND(predecessor_id != id);
   }
 #endif  // NDEBUG
   // In this case, we are 100% sure no one else observed the block, so let's decrement
   // the counter to reuse the block index. Otherwise we'll quickly reach 2^16.
   adaptor_.cancel_new_block(block_index);
   return 0;
 }
template<typename ADAPTOR > McsBlockIndex foedus::xct::McsWwImpl< ADAPTOR >::acquire_unconditional (McsWwLock * mcs_lock)
[WW] Unconditionally takes exclusive-only MCS lock on the given lock.
WW-lock implementations (all simple versions) These do not depend on RW_BLOCK, so they are primary templates without partial specialization.
So we don't need any trick.
Definition at line 53 of file xct_mcs_impl.cpp.
References foedus::xct::assert_mcs_aligned(), ASSERT_ND, foedus::xct::McsWwBlock::clear_successor_release(), foedus::xct::McsWwBlockData::get_block_relaxed(), foedus::xct::McsWwBlockData::get_thread_id_relaxed(), foedus::xct::McsWwBlockData::is_guest_relaxed(), foedus::xct::McsWwLock::is_locked(), foedus::xct::McsWwBlockData::is_valid_relaxed(), foedus::xct::kMcsGuestId, foedus::xct::spin_until(), foedus::xct::McsWwLock::tail_, UNLIKELY, and foedus::xct::McsWwBlockData::word_.
{
   // Basically _all_ writes in this function must come with some memory barrier. Be careful!
   // Also, the performance of this method really matters, especially that of common path.
   // Check objdump -d. Everything in common path should be inlined.
   // Also, check minimal sufficient mfences (note, xchg implies lock prefix. not a compiler's bug!).
   std::atomic<bool>* me_waiting = adaptor_.me_waiting();
   ASSERT_ND(!me_waiting->load());
   assert_mcs_aligned(mcs_lock);
   // so far we allow only 2^16 MCS blocks per transaction. we might increase later.
   ASSERT_ND(adaptor_.get_cur_block() < 0xFFFFU);
   McsBlockIndex block_index = adaptor_.issue_new_block();
   ASSERT_ND(block_index > 0);
   ASSERT_ND(block_index <= 0xFFFFU);
   McsWwBlock* my_block = adaptor_.get_ww_my_block(block_index);
   my_block->clear_successor_release();
   me_waiting->store(true, std::memory_order_release);
   const thread::ThreadId id = adaptor_.get_my_id();
   McsWwBlockData desired(id, block_index);  // purely local copy. okay to be always relaxed.
   McsWwBlockData group_tail = desired;      // purely local copy. okay to be always relaxed.
   auto* address = &(mcs_lock->tail_);     // be careful on this one!
   assert_mcs_aligned(address);
   McsWwBlockData pred;                      // purely local copy. okay to be always relaxed.
   ASSERT_ND(!pred.is_valid_relaxed());
   while (true) {
     // if it's obviously locked by a guest, we should wait until it's released.
     // so far this is busy-wait, we can do sth. to prevent priority inversion later.
     if (UNLIKELY(address->is_guest_relaxed())) {
       spin_until([address]{ return !address->is_guest_acquire(); });
     }
     // atomic op should imply full barrier, but make sure announcing the initialized new block.
     ASSERT_ND(!group_tail.is_guest_relaxed());
     ASSERT_ND(group_tail.is_valid_relaxed());
     ASSERT_ND(address->get_word_atomic() != group_tail.word_);
     pred.word_ = assorted::raw_atomic_exchange<uint64_t>(&address->word_, group_tail.word_);
     ASSERT_ND(pred != group_tail);
     ASSERT_ND(pred != desired);
     if (!pred.is_valid_relaxed()) {
       // this means it was not locked.
       ASSERT_ND(mcs_lock->is_locked());
       DVLOG(2) << "Okay, got a lock uncontended. me=" << id;
       me_waiting->store(false, std::memory_order_release);
       ASSERT_ND(address->is_valid_atomic());
       return block_index;
     } else if (UNLIKELY(pred.is_guest_relaxed())) {
       // ouch, I don't want to keep the guest ID! return it back.
       // This also determines the group_tail of this queue
       group_tail.word_ = assorted::raw_atomic_exchange<uint64_t>(&address->word_, kMcsGuestId);
       ASSERT_ND(group_tail.is_valid_relaxed() && !group_tail.is_guest_relaxed());
       continue;
     } else {
       break;
     }
   }
   ASSERT_ND(pred.is_valid_relaxed() && !pred.is_guest_relaxed());
   ASSERT_ND(address->is_valid_atomic());
   ASSERT_ND(!address->is_guest_atomic());
   ASSERT_ND(mcs_lock->is_locked());
   thread::ThreadId predecessor_id = pred.get_thread_id_relaxed();
   ASSERT_ND(predecessor_id != id);
   McsBlockIndex predecessor_block = pred.get_block_relaxed();
   DVLOG(0) << "mm, contended, we have to wait.. me=" << id << " pred=" << predecessor_id;
   ASSERT_ND(me_waiting->load());
   McsWwBlock* pred_block = adaptor_.get_ww_other_block(predecessor_id, predecessor_block);
   ASSERT_ND(!pred_block->has_successor_atomic());
   pred_block->set_successor_release(id, block_index);
   ASSERT_ND(address->is_valid_atomic());
   ASSERT_ND(!address->is_guest_atomic());
   spin_until([me_waiting]{ return !me_waiting->load(std::memory_order_acquire); });
   DVLOG(1) << "Okay, now I hold the lock. me=" << id << ", ex-pred=" << predecessor_id;
   ASSERT_ND(!me_waiting->load());
   ASSERT_ND(mcs_lock->is_locked());
   ASSERT_ND(address->is_valid_atomic());
   ASSERT_ND(!address->is_guest_atomic());
   return block_index;
 }
template<typename ADAPTOR > McsBlockIndex foedus::xct::McsWwImpl< ADAPTOR >::initial (McsWwLock * lock)
[WW] This doesn't use any atomic operation.
only allowed when there is no race TASK(Hideaki): This will be renamed to mcs_non_racy_lock(). "initial_lock" is ambiguous.
Definition at line 191 of file xct_mcs_impl.cpp.
References foedus::xct::assert_mcs_aligned(), ASSERT_ND, foedus::xct::McsWwBlock::clear_successor_release(), foedus::xct::McsWwLock::is_locked(), and foedus::xct::McsWwLock::reset_release().
{
   // Basically _all_ writes in this function must come with release barrier.
   // This method itself doesn't need barriers, but then we need to later take a seq_cst barrier
   // in an appropriate place. That's hard to debug, so just take release barriers here.
   // Also, everything should be inlined.
   assert_mcs_aligned(mcs_lock);
   ASSERT_ND(!adaptor_.me_waiting()->load());
   ASSERT_ND(!mcs_lock->is_locked());
   // so far we allow only 2^16 MCS blocks per transaction. we might increase later.
   ASSERT_ND(adaptor_.get_cur_block() < 0xFFFFU);
   McsBlockIndex block_index = adaptor_.issue_new_block();
   ASSERT_ND(block_index > 0 && block_index <= 0xFFFFU);
   McsWwBlock* my_block = adaptor_.get_ww_my_block(block_index);
   my_block->clear_successor_release();
   const thread::ThreadId id = adaptor_.get_my_id();
   mcs_lock->reset_release(id, block_index);
   return block_index;
 }
template<typename ADAPTOR > void foedus::xct::McsWwImpl< ADAPTOR >::release (McsWwLock * lock, McsBlockIndex block_index)
[WW] Unlcok an MCS lock acquired by this thread.
Definition at line 212 of file xct_mcs_impl.cpp.
References foedus::xct::assert_mcs_aligned(), ASSERT_ND, foedus::xct::McsWwBlock::get_successor_thread_id_relaxed(), foedus::xct::McsWwLock::get_tail_waiter(), foedus::xct::McsWwBlock::has_successor_acquire(), foedus::xct::McsWwBlockData::is_guest_relaxed(), foedus::xct::McsWwLock::is_locked(), foedus::xct::McsWwBlockData::is_valid_relaxed(), foedus::xct::spin_until(), foedus::xct::McsWwLock::tail_, UNLIKELY, and foedus::xct::McsWwBlockData::word_.
Referenced by foedus::xct::SysxctLockList::release_all_locks().
{
   // Basically _all_ writes in this function must come with some memory barrier. Be careful!
   // Also, the performance of this method really matters, especially that of common path.
   // Check objdump -d. Everything in common path should be inlined.
   // Also, check minimal sufficient lock/mfences.
   assert_mcs_aligned(mcs_lock);
   ASSERT_ND(!adaptor_.me_waiting()->load());
   ASSERT_ND(mcs_lock->is_locked());
   ASSERT_ND(block_index > 0);
   ASSERT_ND(adaptor_.get_cur_block() >= block_index);
   const thread::ThreadId id = adaptor_.get_my_id();
   const McsWwBlockData myself(id, block_index);   // purely local copy. okay to be always relaxed.
   auto* address = &(mcs_lock->tail_);           // be careful on this one!
   McsWwBlock* block = adaptor_.get_ww_my_block(block_index);
   if (!block->has_successor_acquire()) {
     // okay, successor "seems" nullptr (not contended), but we have to make it sure with atomic CAS
     McsWwBlockData expected = myself;             // purely local copy. okay to be always relaxed.
     assert_mcs_aligned(address);
     bool swapped
       = assorted::raw_atomic_compare_exchange_strong<uint64_t>(
         &address->word_,
         &expected.word_,
         0);
     if (swapped) {
       // we have just unset the locked flag, but someone else might have just acquired it,
       // so we can't put assertion here.
       ASSERT_ND(id == 0 || mcs_lock->get_tail_waiter() != id);
       ASSERT_ND(expected == myself);
       ASSERT_ND(address->copy_atomic() != myself);
       DVLOG(2) << "Okay, release a lock uncontended. me=" << id;
       return;
     }
     ASSERT_ND(expected.is_valid_relaxed());
     ASSERT_ND(!expected.is_guest_relaxed());
     DVLOG(0) << "Interesting contention on MCS release. I thought it's null, but someone has just "
       " jumped in. me=" << id << ", mcs_lock=" << *mcs_lock;
     // wait for someone else to set the successor
     ASSERT_ND(mcs_lock->is_locked());
     if (UNLIKELY(!block->has_successor_acquire())) {
       spin_until([block]{ return block->has_successor_acquire(); });
     }
   }
   // Relax: In either case above, we confirmed that block->has_successor with fences.
   // We thus can just read in relaxed mode here.
   thread::ThreadId successor_id = block->get_successor_thread_id_relaxed();
   DVLOG(1) << "Okay, I have a successor. me=" << id << ", succ=" << successor_id;
   ASSERT_ND(successor_id != id);
   ASSERT_ND(address->copy_atomic() != myself);
   ASSERT_ND(adaptor_.other_waiting(successor_id)->load());
   ASSERT_ND(mcs_lock->is_locked());
   ASSERT_ND(address->copy_atomic() != myself);
   adaptor_.other_waiting(successor_id)->store(false, std::memory_order_release);
   ASSERT_ND(address->copy_atomic() != myself);
 }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/xct/xct_mcs_impl.hpp
/home/shino/foedus_code/foedus-core/src/foedus/xct/xct_mcs_impl.cpp