libfoedus-core: foedus::snapshot::SnapshotManager Class Reference
foedus::snapshot::SnapshotManager Class Reference final
FOEDUS Components » Snapshot Manager
Snapshot manager that atomically and durably writes out a snapshot file.
Detailed Description
Snapshot manager that atomically and durably writes out a snapshot file.
Definition at line 31 of file snapshot_manager.hpp.
#include <snapshot_manager.hpp>
Public Member Functions
SnapshotManager (Engine *engine)
~SnapshotManager ()
SnapshotManager ()=delete
SnapshotManager (const SnapshotManager &)=delete
SnapshotManager & operator= (const SnapshotManager &)=delete
ErrorStack initialize () override
Acquires resources in this object, usually called right after constructor.
bool is_initialized () const override
Returns whether the object has been already initialized or not.
ErrorStack uninitialize () override
An idempotent method to release all resources of this object, if any.
Epoch get_snapshot_epoch () const
Returns the most recently snapshot-ed epoch, all logs upto this epoch is safe to delete.
Epoch get_snapshot_epoch_weak () const
Non-atomic version.
SnapshotId get_previous_snapshot_id () const
Returns the most recent snapshot's ID.
SnapshotId get_previous_snapshot_id_weak () const
Non-atomic version.
ErrorStack read_snapshot_metadata (SnapshotId snapshot_id, SnapshotMetadata *out)
Read the snapshot metadata file that contains storages as of the snapshot.
void trigger_snapshot_immediate (bool wait_completion, Epoch suggested_snapshot_epoch=INVALID_EPOCH)
Immediately take a snapshot.
SnapshotManagerPimpl * get_pimpl ()
Do not use this unless you know what you are doing.
Public Member Functions inherited from foedus::Initializable
virtual ~Initializable ()
Constructor & Destructor Documentation
foedus::snapshot::SnapshotManager::SnapshotManager (Engine * engine) explicit
Definition at line 22 of file snapshot_manager.cpp.
                                                : pimpl_(nullptr) {
   pimpl_ = new SnapshotManagerPimpl(engine);
 }
foedus::snapshot::SnapshotManager::~SnapshotManager ()
Definition at line 25 of file snapshot_manager.cpp.
{
   delete pimpl_;
   pimpl_ = nullptr;
 }
foedus::snapshot::SnapshotManager::SnapshotManager () delete
foedus::snapshot::SnapshotManager::SnapshotManager (const SnapshotManager &) delete
Member Function Documentation
SnapshotManagerPimpl* foedus::snapshot::SnapshotManager::get_pimpl () inline
Do not use this unless you know what you are doing.
Definition at line 79 of file snapshot_manager.hpp.
Referenced by foedus::restart::RestartManagerPimpl::recover(), and foedus::restart::RestartManagerPimpl::uninitialize_once().
 { return pimpl_; }
SnapshotId foedus::snapshot::SnapshotManager::get_previous_snapshot_id () const
Returns the most recent snapshot's ID.
kNullSnapshotId if no snapshot is taken.
Definition at line 39 of file snapshot_manager.cpp.
References foedus::snapshot::SnapshotManagerPimpl::get_previous_snapshot_id().
{
   return pimpl_->get_previous_snapshot_id();
 }
SnapshotId foedus::snapshot::SnapshotManager::get_previous_snapshot_id_weak () const
Non-atomic version.
Definition at line 43 of file snapshot_manager.cpp.
References foedus::snapshot::SnapshotManagerPimpl::get_previous_snapshot_id_weak().
{
   return pimpl_->get_previous_snapshot_id_weak();
 }
Epoch foedus::snapshot::SnapshotManager::get_snapshot_epoch () const
Returns the most recently snapshot-ed epoch, all logs upto this epoch is safe to delete.
If not snapshot has been taken, invalid epoch.
Definition at line 34 of file snapshot_manager.cpp.
References foedus::snapshot::SnapshotManagerPimpl::get_snapshot_epoch().
Referenced by foedus::restart::RestartManagerPimpl::recover().
 { return pimpl_->get_snapshot_epoch(); }
Epoch foedus::snapshot::SnapshotManager::get_snapshot_epoch_weak () const
Non-atomic version.
Definition at line 35 of file snapshot_manager.cpp.
References foedus::snapshot::SnapshotManagerPimpl::get_snapshot_epoch_weak().
{
   return pimpl_->get_snapshot_epoch_weak();
 }
ErrorStack foedus::snapshot::SnapshotManager::initialize () override virtual
Acquires resources in this object, usually called right after constructor.
Precondition
is_initialized() == FALSE
If and only if the return value was not an error, is_initialized() will return TRUE. This method is usually not idempotent, but some implementation can choose to be. In that case, the implementation class should clarify that it's idempotent. This method is responsible for releasing all acquired resources when initialization fails. This method itself is NOT thread-safe. Do not call this in a racy situation.
Implements foedus::Initializable.
Definition at line 30 of file snapshot_manager.cpp.
References foedus::DefaultInitializable::initialize().
 { return pimpl_->initialize(); }
bool foedus::snapshot::SnapshotManager::is_initialized () const override virtual
Returns whether the object has been already initialized or not.
Implements foedus::Initializable.
Definition at line 31 of file snapshot_manager.cpp.
References foedus::DefaultInitializable::is_initialized().
 { return pimpl_->is_initialized(); }
SnapshotManager& foedus::snapshot::SnapshotManager::operator= (const SnapshotManager &) delete
ErrorStack foedus::snapshot::SnapshotManager::read_snapshot_metadata (SnapshotId snapshot_id, SnapshotMetadata * out)
Read the snapshot metadata file that contains storages as of the snapshot.
This is used only when the engine starts up.
Definition at line 47 of file snapshot_manager.cpp.
References foedus::snapshot::SnapshotManagerPimpl::read_snapshot_metadata().
Referenced by foedus::storage::StorageManagerPimpl::initialize_read_latest_snapshot().
{
   return pimpl_->read_snapshot_metadata(snapshot_id, out);
 }
void foedus::snapshot::SnapshotManager::trigger_snapshot_immediate (bool wait_completion, Epoch suggested_snapshot_epoch = INVALID_EPOCH)
Immediately take a snapshot.
Parameters
[in] wait_completion whether to block until the completion of entire snapshotting
[in] suggested_snapshot_epoch the epoch up to which we will snapshot. Must be a durable epoch that is after the previous snapshot epoch. If not specified, the latest durable epoch is used, which is in most cases what you want.
This method is used to immediately take snapshot for either recovery or memory-saving purpose.
Definition at line 52 of file snapshot_manager.cpp.
References foedus::snapshot::SnapshotManagerPimpl::trigger_snapshot_immediate().
{
   pimpl_->trigger_snapshot_immediate(wait_completion, suggested_snapshot_epoch);
 }
ErrorStack foedus::snapshot::SnapshotManager::uninitialize () override virtual
An idempotent method to release all resources of this object, if any.
After this method, is_initialized() will return FALSE. Whether this method encounters an error or not, the implementation should make the best effort to release as many resources as possible. In other words, Do not leak all resources because of one issue. This method itself is NOT thread-safe. Do not call this in a racy situation.
Attention
This method is NOT automatically called from the destructor. This is due to the fundamental limitation in C++. Explicitly call this method as soon as you are done, checking the returned value. You can also use UninitializeGuard to ameliorate the issue, but it's not perfect.
Returns
The error this method encounters, if any. In case there are multiple errors while uninitialization, the implementation should use ErrorStackBatch to produce a batched ErrorStack object.
Implements foedus::Initializable.
Definition at line 32 of file snapshot_manager.cpp.
References foedus::DefaultInitializable::uninitialize().
 { return pimpl_->uninitialize(); }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/snapshot/snapshot_manager.hpp
/home/shino/foedus_code/foedus-core/src/foedus/snapshot/snapshot_manager.cpp