libfoedus-core: foedus::storage::sequential::SequentialRootPage Class Reference
foedus::storage::sequential::SequentialRootPage Class Reference final
FOEDUS Components » Storage Manager » Sequential Storage
Represents one stable root page in Sequential Storage.
Detailed Description
Represents one stable root page in Sequential Storage.
In Sequential Storage, a root page is merely a set of pointers to head pages, which are the beginnings of singly-linked list of data pages. Root pages themselves can form singly-linked list if there are many head pages after many snapshotting (on head page for each node in each snapshot, so it can be many in a large machine).
All contents of root pages are stable. They are never dynamically changed. The volatile part of Sequential Storage is maintained as a set of singly-linked list pointed directly from the storage object, so there is no root page for it.
This is a private implementation-details of Sequential Storage, thus file name ends with _impl. Do not include this header from a client program unless you know what you are doing.
Attention
Do NOT instantiate this object or derive from this class. A page is always reinterpret-ed from a pooled memory region. No meaningful RTTI.
Definition at line 250 of file sequential_page_impl.hpp.
#include <sequential_page_impl.hpp>
Public Member Functions
SequentialRootPage ()=delete
SequentialRootPage (const SequentialRootPage &other)=delete
SequentialRootPage & operator= (const SequentialRootPage &other)=delete
PageHeader & header ()
const PageHeader & header () const
uint16_t get_pointer_count () const
Returns How many pointers to head pages exist in this page.
const HeadPagePointer * get_pointers () const
void set_pointers (HeadPagePointer *pointers, uint16_t pointer_count)
SnapshotPagePointer get_next_page () const
void set_next_page (SnapshotPagePointer page)
void initialize_snapshot_page (StorageId storage_id, SnapshotPagePointer page_id)
Called only when this page is initialized.
const char * unused_dummy_func_filler () const
Constructor & Destructor Documentation
foedus::storage::sequential::SequentialRootPage::SequentialRootPage () delete
foedus::storage::sequential::SequentialRootPage::SequentialRootPage (const SequentialRootPage & other) delete
Member Function Documentation
SnapshotPagePointer foedus::storage::sequential::SequentialRootPage::get_next_page () const inline
Definition at line 271 of file sequential_page_impl.hpp.
Referenced by foedus::storage::sequential::SequentialComposer::construct_root().
 { return next_page_; }
uint16_t foedus::storage::sequential::SequentialRootPage::get_pointer_count () const inline
Returns How many pointers to head pages exist in this page.
Definition at line 262 of file sequential_page_impl.hpp.
Referenced by foedus::storage::sequential::SequentialComposer::construct_root().
 { return pointer_count_; }
const HeadPagePointer* foedus::storage::sequential::SequentialRootPage::get_pointers () const inline
Definition at line 263 of file sequential_page_impl.hpp.
Referenced by foedus::storage::sequential::SequentialComposer::construct_root().
 { return head_page_pointers_; }
PageHeader& foedus::storage::sequential::SequentialRootPage::header () inline
Definition at line 258 of file sequential_page_impl.hpp.
Referenced by foedus::storage::sequential::SequentialComposer::construct_root().
 { return header_; }
const PageHeader& foedus::storage::sequential::SequentialRootPage::header () const inline
Definition at line 259 of file sequential_page_impl.hpp.
 { return header_; }
void foedus::storage::sequential::SequentialRootPage::initialize_snapshot_page (StorageId storage_id, SnapshotPagePointer page_id) inline
Called only when this page is initialized.
Definition at line 275 of file sequential_page_impl.hpp.
References foedus::storage::PageHeader::init_snapshot(), and foedus::storage::kSequentialRootPageType.
Referenced by foedus::storage::sequential::SequentialComposer::construct_root().
{
     header_.init_snapshot(page_id, storage_id, kSequentialRootPageType);
     pointer_count_ = 0;
     next_page_ = 0;
   }
SequentialRootPage& foedus::storage::sequential::SequentialRootPage::operator= (const SequentialRootPage & other) delete
void foedus::storage::sequential::SequentialRootPage::set_next_page (SnapshotPagePointer page) inline
Definition at line 272 of file sequential_page_impl.hpp.
Referenced by foedus::storage::sequential::SequentialComposer::construct_root().
 { next_page_ = page; }
void foedus::storage::sequential::SequentialRootPage::set_pointers (HeadPagePointer * pointers, uint16_t pointer_count) inline
Definition at line 265 of file sequential_page_impl.hpp.
References ASSERT_ND, and foedus::storage::sequential::kRootPageMaxHeadPointers.
Referenced by foedus::storage::sequential::SequentialComposer::construct_root().
{
     ASSERT_ND(pointer_count <= kRootPageMaxHeadPointers);
     pointer_count_ = pointer_count;
     std::memcpy(head_page_pointers_, pointers, sizeof(HeadPagePointer) * pointer_count);
   }
const char* foedus::storage::sequential::SequentialRootPage::unused_dummy_func_filler () const inline
Definition at line 281 of file sequential_page_impl.hpp.
 { return filler_; }
The documentation for this class was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/storage/sequential/sequential_page_impl.hpp