libfoedus-core: foedus::thread::ThreadPoolPimpl Class Reference
foedus::thread::ThreadPoolPimpl Class Reference final
FOEDUS Components » Thread and Thread-Group » Thread-Pool and Impersonation
Pimpl object of ThreadPool.
Detailed Description
Pimpl object of ThreadPool.
A private pimpl object for ThreadPool. Do not include this header from a client program unless you know what you are doing.
Definition at line 41 of file thread_pool_pimpl.hpp.
#include <thread_pool_pimpl.hpp>
Public Member Functions
ThreadPoolPimpl ()=delete
ThreadPoolPimpl (Engine *engine)
ErrorStack initialize_once () override
ErrorStack uninitialize_once () override
bool impersonate (const proc::ProcName &proc_name, const void *task_input, uint64_t task_input_size, ImpersonateSession *session)
bool impersonate_on_numa_node (ThreadGroupId node, const proc::ProcName &proc_name, const void *task_input, uint64_t task_input_size, ImpersonateSession *session)
bool impersonate_on_numa_core (ThreadId core, const proc::ProcName &proc_name, const void *task_input, uint64_t task_input_size, ImpersonateSession *session)
ThreadGroupRef * get_group (ThreadGroupId numa_node)
ThreadGroup * get_local_group () const
ThreadRef * get_thread (ThreadId id)
ThreadRef get_thread_ref (ThreadId id) __attribute__((always_inline))
For better performance, but for some reason this method causes an issue in MCS lock.
Public Member Functions inherited from foedus::DefaultInitializable
DefaultInitializable ()
virtual ~DefaultInitializable ()
DefaultInitializable (const DefaultInitializable &)=delete
DefaultInitializable & operator= (const DefaultInitializable &)=delete
ErrorStack initialize () override final
Typical implementation of Initializable::initialize() that provides initialize-once semantics.
ErrorStack uninitialize () override final
Typical implementation of Initializable::uninitialize() that provides uninitialize-once semantics.
bool is_initialized () const override final
Returns whether the object has been already initialized or not.
Public Member Functions inherited from foedus::Initializable
virtual ~Initializable ()
Public Attributes
Engine *const engine_
ThreadGroup * local_group_
Thread group of the local SOC engine.
std::vector< ThreadGroupRef > groups_
List of all thread groups, one for each NUMA node in this engine.
Friends
std::ostream & operator<< (std::ostream &o, const ThreadPoolPimpl &v)
Constructor & Destructor Documentation
foedus::thread::ThreadPoolPimpl::ThreadPoolPimpl () delete
foedus::thread::ThreadPoolPimpl::ThreadPoolPimpl (Engine * engine) inline explicit
Definition at line 44 of file thread_pool_pimpl.hpp.
 : engine_(engine), local_group_(nullptr) {}
Member Function Documentation
ThreadGroupRef* foedus::thread::ThreadPoolPimpl::get_group (ThreadGroupId numa_node) inline
Definition at line 66 of file thread_pool_pimpl.hpp.
References groups_.
Referenced by foedus::thread::ThreadPool::get_group_ref(), and get_thread().
 { return &groups_[numa_node]; }
ThreadGroup* foedus::thread::ThreadPoolPimpl::get_local_group () const inline
Definition at line 67 of file thread_pool_pimpl.hpp.
References local_group_.
Referenced by foedus::log::Logger::initialize_once().
 { return local_group_; }
ThreadRef * foedus::thread::ThreadPoolPimpl::get_thread (ThreadId id)
Definition at line 74 of file thread_pool_pimpl.cpp.
References foedus::thread::decompose_numa_local_ordinal(), foedus::thread::decompose_numa_node(), get_group(), and foedus::thread::ThreadGroupRef::get_thread().
Referenced by foedus::thread::ThreadPool::get_thread_ref(), and impersonate_on_numa_core().
{
   return get_group(decompose_numa_node(id))->get_thread(decompose_numa_local_ordinal(id));
 }
ThreadRef foedus::thread::ThreadPoolPimpl::get_thread_ref (ThreadId id) inline
For better performance, but for some reason this method causes an issue in MCS lock.
Definition at line 92 of file thread_pool_pimpl.hpp.
References foedus::thread::decompose_numa_local_ordinal(), foedus::thread::decompose_numa_node(), and groups_.
Referenced by foedus::thread::ThreadPimpl::get_thread_ref().
{
   ThreadGroupId numa_node = decompose_numa_node(id);
   ThreadLocalOrdinal core_ordinal = decompose_numa_local_ordinal(id);
   return groups_[numa_node].get_thread_ref(core_ordinal);
 }
bool foedus::thread::ThreadPoolPimpl::impersonate (const proc::ProcName & proc_name, const void * task_input, uint64_t task_input_size, ImpersonateSession * session)
Definition at line 79 of file thread_pool_pimpl.cpp.
References engine_, foedus::Engine::get_options(), groups_, foedus::EngineOptions::thread_, foedus::thread::ThreadOptions::thread_count_per_group_, and foedus::thread::ThreadRef::try_impersonate().
Referenced by foedus::thread::ThreadPool::impersonate().
{
   uint16_t thread_per_group = engine_->get_options().thread_.thread_count_per_group_;
   for (ThreadGroupRef& group : groups_) {
     for (size_t j = 0; j < thread_per_group; ++j) {
       ThreadRef* thread = group.get_thread(j);
       if (thread->try_impersonate(proc_name, task_input, task_input_size, session)) {
         return true;
       }
     }
   }
   return false;
 }
bool foedus::thread::ThreadPoolPimpl::impersonate_on_numa_core (ThreadId core, const proc::ProcName & proc_name, const void * task_input, uint64_t task_input_size, ImpersonateSession * session)
Definition at line 111 of file thread_pool_pimpl.cpp.
References get_thread(), and foedus::thread::ThreadRef::try_impersonate().
Referenced by foedus::thread::ThreadPool::impersonate_on_numa_core().
{
   ThreadRef* thread = get_thread(core);
   return thread->try_impersonate(proc_name, task_input, task_input_size, session);
 }
bool foedus::thread::ThreadPoolPimpl::impersonate_on_numa_node (ThreadGroupId node, const proc::ProcName & proc_name, const void * task_input, uint64_t task_input_size, ImpersonateSession * session)
Definition at line 95 of file thread_pool_pimpl.cpp.
References engine_, foedus::Engine::get_options(), foedus::thread::ThreadGroupRef::get_thread(), groups_, foedus::EngineOptions::thread_, foedus::thread::ThreadOptions::thread_count_per_group_, and foedus::thread::ThreadRef::try_impersonate().
Referenced by foedus::thread::ThreadPool::impersonate_on_numa_node().
{
   uint16_t thread_per_group = engine_->get_options().thread_.thread_count_per_group_;
   ThreadGroupRef& group = groups_[node];
   for (size_t j = 0; j < thread_per_group; ++j) {
     ThreadRef* thread = group.get_thread(j);
     if (thread->try_impersonate(proc_name, task_input, task_input_size, session)) {
       return true;
     }
   }
   return false;
 }
ErrorStack foedus::thread::ThreadPoolPimpl::initialize_once () override virtual
Implements foedus::DefaultInitializable.
Definition at line 40 of file thread_pool_pimpl.cpp.
References ASSERT_ND, CHECK_ERROR, engine_, ERROR_STACK, foedus::Engine::get_memory_manager(), foedus::Engine::get_options(), foedus::Engine::get_soc_id(), groups_, foedus::DefaultInitializable::initialize(), foedus::DefaultInitializable::is_initialized(), foedus::Engine::is_master(), foedus::kErrorCodeDepedentModuleUnavailableInit, foedus::kRetOk, local_group_, and foedus::EngineOptions::thread_.
{
   if (!engine_->get_memory_manager()->is_initialized()) {
     return ERROR_STACK(kErrorCodeDepedentModuleUnavailableInit);
   }
   ASSERT_ND(groups_.empty());
   const ThreadOptions &options = engine_->get_options().thread_;
   for (ThreadGroupId group_id = 0; group_id < options.group_count_; ++group_id) {
     groups_.emplace_back(ThreadGroupRef(engine_, group_id));
   }
   if (!engine_->is_master()) {
     // initialize local thread group object
     soc::SocId node = engine_->get_soc_id();
     local_group_ = new ThreadGroup(engine_, node);
     CHECK_ERROR(local_group_->initialize());
   }
   return kRetOk;
 }
ErrorStack foedus::thread::ThreadPoolPimpl::uninitialize_once () override virtual
Implements foedus::DefaultInitializable.
Definition at line 59 of file thread_pool_pimpl.cpp.
References ASSERT_ND, foedus::ErrorStackBatch::emprace_back(), engine_, ERROR_STACK, foedus::Engine::get_memory_manager(), groups_, foedus::DefaultInitializable::is_initialized(), foedus::Engine::is_master(), foedus::kErrorCodeDepedentModuleUnavailableUninit, local_group_, SUMMARIZE_ERROR_BATCH, and foedus::DefaultInitializable::uninitialize().
{
   ErrorStackBatch batch;
   if (!engine_->get_memory_manager()->is_initialized()) {
     batch.emprace_back(ERROR_STACK(kErrorCodeDepedentModuleUnavailableUninit));
   }
   groups_.clear();
   if (local_group_) {
     ASSERT_ND(!engine_->is_master());
     batch.emprace_back(local_group_->uninitialize());
     delete local_group_;
     local_group_ = nullptr;
   }
   return SUMMARIZE_ERROR_BATCH(batch);
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const ThreadPoolPimpl & v) friend
Definition at line 121 of file thread_pool_pimpl.cpp.
{
   o << "<ThreadPool>";
   o << "<groups>";
   for (const ThreadGroupRef& group : v.groups_) {
     o << group;
   }
   o << "</groups>";
   o << "</ThreadPool>";
   return o;
 }
Member Data Documentation
Engine* const foedus::thread::ThreadPoolPimpl::engine_
Definition at line 77 of file thread_pool_pimpl.hpp.
Referenced by impersonate(), impersonate_on_numa_node(), initialize_once(), and uninitialize_once().
std::vector<ThreadGroupRef> foedus::thread::ThreadPoolPimpl::groups_
List of all thread groups, one for each NUMA node in this engine.
Index is ThreadGroupId.
Definition at line 89 of file thread_pool_pimpl.hpp.
Referenced by get_group(), get_thread_ref(), impersonate(), impersonate_on_numa_node(), initialize_once(), foedus::thread::operator<<(), and uninitialize_once().
ThreadGroup* foedus::thread::ThreadPoolPimpl::local_group_
Thread group of the local SOC engine.
If this is a master engine, null.
Definition at line 83 of file thread_pool_pimpl.hpp.
Referenced by get_local_group(), initialize_once(), and uninitialize_once().
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/thread/thread_pool_pimpl.hpp
/home/shino/foedus_code/foedus-core/src/foedus/thread/thread_pool_pimpl.cpp