libfoedus-core: foedus::soc::SharedMutexScope Class Reference
foedus::soc::SharedMutexScope Class Reference final
FOEDUS Components » SOC and IPC
Auto-lock scope object for SharedMutex.
Detailed Description
Auto-lock scope object for SharedMutex.
SharedMutex itself has auto-release feature, but only when it is on stack. In many cases SharedMutex is placed in shared memory, so its destructor is never called. Instead, this object provides the auto-release semantics.
Definition at line 100 of file shared_mutex.hpp.
#include <shared_mutex.hpp>
Public Member Functions
SharedMutexScope (SharedMutex *mutex, bool lock_initially=true)
~SharedMutexScope ()
SharedMutexScope (const SharedMutexScope &)=delete
SharedMutexScope & operator= (const SharedMutexScope &)=delete
bool is_locked_by_me () const
SharedMutex * get_mutex () const
void lock ()
void unlock ()
Constructor & Destructor Documentation
foedus::soc::SharedMutexScope::SharedMutexScope (SharedMutex * mutex, bool lock_initially = true) inline
Definition at line 102 of file shared_mutex.hpp.
References lock().
     : mutex_(mutex), locked_by_me_(false) {
     if (lock_initially) {
       lock();
     }
   }
foedus::soc::SharedMutexScope::~SharedMutexScope () inline
Definition at line 108 of file shared_mutex.hpp.
References unlock().
 { unlock(); }
foedus::soc::SharedMutexScope::SharedMutexScope (const SharedMutexScope &) delete
Member Function Documentation
SharedMutex* foedus::soc::SharedMutexScope::get_mutex () const inline
Definition at line 115 of file shared_mutex.hpp.
Referenced by foedus::storage::PartitionerMetadata::allocate_data().
 { return mutex_; }
bool foedus::soc::SharedMutexScope::is_locked_by_me () const inline
Definition at line 114 of file shared_mutex.hpp.
Referenced by foedus::storage::PartitionerMetadata::allocate_data().
 { return locked_by_me_; }
void foedus::soc::SharedMutexScope::lock ()
Definition at line 99 of file shared_mutex.cpp.
References foedus::soc::SharedMutex::lock().
Referenced by SharedMutexScope().
{
   if (locked_by_me_) {
     return;
   }
   mutex_->lock();
   locked_by_me_ = true;
 }
SharedMutexScope& foedus::soc::SharedMutexScope::operator= (const SharedMutexScope &) delete
void foedus::soc::SharedMutexScope::unlock ()
Definition at line 108 of file shared_mutex.cpp.
References foedus::soc::SharedMutex::unlock().
Referenced by foedus::soc::SharedCond::broadcast(), foedus::soc::SharedCond::signal(), and ~SharedMutexScope().
{
   if (!locked_by_me_) {
     return;
   }
   mutex_->unlock();
   locked_by_me_ = false;
 }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/soc/shared_mutex.hpp
/home/shino/foedus_code/foedus-core/src/foedus/soc/shared_mutex.cpp