libfoedus-core: foedus::UninitializeGuard Class Reference
foedus::UninitializeGuard Class Reference
FOEDUS Programming Idioms » Initialize/Uninitialize Resources
Calls Initializable::uninitialize() automatically when it gets out of scope.
Detailed Description
Calls Initializable::uninitialize() automatically when it gets out of scope.
NOT A SILVER BULLET! This is a scope guard object to help release Initializable objects, but there are inherent difficulties to handle errors out of uninitialization. eg: http://stackoverflow.com/questions/159240/raii-vs-exceptions
The only correct solution is for every code to make sure calling uninitialize() explicitly and handling the returned ErrorStack responsively. This object is just an imperfect safety net.
Definition at line 220 of file initializable.hpp.
#include <initializable.hpp>
Public Types
enum Policy { kAbortIfNotExplicitlyUninitialized = 0, kAbortIfUninitializeError, kWarnIfUninitializeError, kSilent }
Defines the behavior of this scope guard.
Public Member Functions
UninitializeGuard (Initializable *target, Policy policy=kAbortIfUninitializeError)
~UninitializeGuard ()
Member Enumeration Documentation
enum foedus::UninitializeGuard::Policy
Defines the behavior of this scope guard.
Enumerator
kAbortIfNotExplicitlyUninitialized
Terminates the entire program if uninitialize() wasn't called when it gets out of scope.
This is used to look for coding issues where we overlook chances of early returns. Although this is stringent, recommended.
kAbortIfUninitializeError
Automatically calls if uninitialize() wasn't called when it gets out of scope, and terminates the entire program when uninitialize() actually returns an error.
In either case, we warn about the lack of explicit uninitialize() call in debug log. This is the default.
kWarnIfUninitializeError
Automatically calls if uninitialize() wasn't called when it gets out of scope, and just complains when uninitialize() actually returns an error in debug log.
kSilent
Automatically calls if uninitialize() wasn't called when it gets out of scope, and does nothing even when uninitialize() actually returns an error in debug log.
NOT RECOMMENDED.
Definition at line 225 of file initializable.hpp.
               {
     kAbortIfNotExplicitlyUninitialized = 0,
     kAbortIfUninitializeError,
     kWarnIfUninitializeError,
     kSilent,
   };
Constructor & Destructor Documentation
foedus::UninitializeGuard::UninitializeGuard (Initializable * target, Policy policy = kAbortIfUninitializeError) inline
Definition at line 251 of file initializable.hpp.
     : target_(target), policy_(policy) {}
foedus::UninitializeGuard::~UninitializeGuard ()
Definition at line 29 of file initializable.cpp.
References ASSERT_ND, foedus::ErrorStack::is_error(), foedus::Initializable::is_initialized(), kAbortIfNotExplicitlyUninitialized, kAbortIfUninitializeError, kSilent, kWarnIfUninitializeError, foedus::print_backtrace(), and foedus::Initializable::uninitialize().
{
   if (target_->is_initialized()) {
     if (policy_ != kSilent) {
       LOG(ERROR) << "UninitializeGuard has found that " << typeid(*target_).name()
         <<  "#uninitialize() was not called when it was destructed. This is a BUG!"
         << " We must call uninitialize() before destructors!";
       print_backtrace();
     }
     if (policy_ == kAbortIfNotExplicitlyUninitialized) {
       LOG(FATAL) << "FATAL: According to kAbortIfNotExplicitlyUninitialized policy,"
         << " we abort the program" << std::endl;
       ASSERT_ND(false);
       std::abort();
     } else {
       // okay, call uninitialize().
       ErrorStack error = target_->uninitialize();
       // Note that this is AFTER uninitialize(). "target_" might be Engine
       // or DebuggingSupports. So, we might not be able to use glog any more.
       // Thus, we must use stderr in this case.
       if (error.is_error()) {
         switch (policy_) {
         case kAbortIfUninitializeError:
           std::cerr << "FATAL: UninitializeGuard encounters an error on uninitialize()."
             << " Aborting as we can't propagate this error appropriately."
             << " error=" << error << std::endl;
           ASSERT_ND(false);
           std::abort();
           break;
         case kWarnIfUninitializeError:
           std::cerr << "WARN: UninitializeGuard encounters an error on uninitialize()."
             << " We can't propagate this error appropriately. Not cool!"
             << " error=" << error << std::endl;
           break;
         default:
           // warns nothing. this policy is NOT recommended
           ASSERT_ND(policy_ == kSilent);
         }
       } else {
         if (policy_ != kSilent) {
           std::cerr << "But, fortunately uninitialize() didn't return errors, phew"
             << std::endl;
         }
       }
     }
   }
 }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/initializable.hpp
/home/shino/foedus_code/foedus-core/src/foedus/initializable.cpp