libfoedus-core: foedus::xct::McsImpl< ADAPTOR, McsRwExtendedBlock > Class Template Reference
foedus::xct::McsImpl< ADAPTOR, McsRwExtendedBlock > Class Template Reference
The Extended MCS-RW lock.
Detailed Description
template<typename ADAPTOR>
class foedus::xct::McsImpl< ADAPTOR, McsRwExtendedBlock >
The Extended MCS-RW lock.
Same as above, we partially specialize the whole class, not functions.
Definition at line 676 of file xct_mcs_impl.cpp.
Public Member Functions
McsBlockIndex acquire_unconditional_rw_reader (McsRwLock *lock)
McsBlockIndex acquire_unconditional_rw_writer (McsRwLock *lock)
McsBlockIndex acquire_try_rw_writer (McsRwLock *lock)
Instant-try versions, won't leave node in the queue if failed.
McsBlockIndex acquire_try_rw_reader (McsRwLock *lock)
void release_rw_reader (McsRwLock *lock, McsBlockIndex block_index)
void release_rw_writer (McsRwLock *lock, McsBlockIndex block_index)
AcquireAsyncRet acquire_async_rw_reader (McsRwLock *lock)
Async acquire methods, passing timeout 0 will avoid cancelling upon timeout in the internal rountines; caller should explicitly cancel when needed.
AcquireAsyncRet acquire_async_rw_writer (McsRwLock *lock)
bool retry_async_rw_reader (McsRwLock *lock, McsBlockIndex block_index)
bool retry_async_rw_writer (McsRwLock *lock, McsBlockIndex block_index)
void cancel_async_rw_reader (McsRwLock *lock, McsBlockIndex block_index)
void cancel_async_rw_writer (McsRwLock *lock, McsBlockIndex block_index)
Static Public Member Functions
static bool does_support_try_rw_reader ()
Member Function Documentation
template<typename ADAPTOR > AcquireAsyncRet foedus::xct::McsImpl< ADAPTOR, McsRwExtendedBlock >::acquire_async_rw_reader (McsRwLock * lock) inline
Async acquire methods, passing timeout 0 will avoid cancelling upon timeout in the internal rountines; caller should explicitly cancel when needed.
Definition at line 804 of file xct_mcs_impl.cpp.
References ASSERT_ND, foedus::kErrorCodeLockRequested, foedus::kErrorCodeOk, and foedus::xct::McsRwExtendedBlock::kTimeoutZero.
{
     McsBlockIndex block_index = 0;
     auto ret = acquire_reader_lock(lock, &block_index, McsRwExtendedBlock::kTimeoutZero);
     ASSERT_ND(ret == kErrorCodeOk || ret == kErrorCodeLockRequested);
 #ifndef NDEBUG
     auto* my_block = adaptor_.get_rw_my_block(block_index);
     if (ret == kErrorCodeOk) {
       ASSERT_ND(my_block->pred_flag_is_granted());
       ASSERT_ND(my_block->next_flag_is_granted());
     } else {
       ASSERT_ND(ret == kErrorCodeLockRequested);
       ASSERT_ND(!my_block->next_flag_is_granted());
     }
 #endif
     ASSERT_ND(block_index);
     return {ret == kErrorCodeOk, block_index};
   }
template<typename ADAPTOR > AcquireAsyncRet foedus::xct::McsImpl< ADAPTOR, McsRwExtendedBlock >::acquire_async_rw_writer (McsRwLock * lock) inline
Definition at line 821 of file xct_mcs_impl.cpp.
References ASSERT_ND, foedus::kErrorCodeLockRequested, foedus::kErrorCodeOk, and foedus::xct::McsRwExtendedBlock::kTimeoutZero.
{
     McsBlockIndex block_index = 0;
     auto ret = acquire_writer_lock(lock, &block_index, McsRwExtendedBlock::kTimeoutZero);
     ASSERT_ND(ret == kErrorCodeOk || ret == kErrorCodeLockRequested);
     ASSERT_ND(block_index);
 #ifndef NDEBUG
     auto* my_block = adaptor_.get_rw_my_block(block_index);
     if (ret == kErrorCodeOk) {
       ASSERT_ND(my_block->pred_flag_is_granted());
       ASSERT_ND(my_block->next_flag_is_granted());
     } else {
       ASSERT_ND(ret == kErrorCodeLockRequested);
       ASSERT_ND(!my_block->next_flag_is_granted());
     }
 #endif
     return {ret == kErrorCodeOk, block_index};
   }
template<typename ADAPTOR > McsBlockIndex foedus::xct::McsImpl< ADAPTOR, McsRwExtendedBlock >::acquire_try_rw_reader (McsRwLock * lock) inline
Definition at line 756 of file xct_mcs_impl.cpp.
References ASSERT_ND, foedus::kErrorCodeLockCancelled, and foedus::kErrorCodeOk.
{
     // This is a bit special, we do an async acquire with a very short timeout:
     // giving 0 timeout might cause unnecessary cancelling because of delay in
     // lock granting from reader predecessor. Note that there is a delay even if
     // there are only readers, the last requester has to wait for its predecessor
     // to notify about the granting of the lock.
     McsBlockIndex block_index = 0;
     auto ret = acquire_reader_lock(lock, &block_index, 10);
     ASSERT_ND(ret == kErrorCodeOk || ret == kErrorCodeLockCancelled);
     ASSERT_ND(block_index);
     if (ret == kErrorCodeOk) {
       return block_index;
     } else {
       // NOTE: In this case, we CANNOT do this. Extended version's try-reader
       // actually inserts the qnode. So others might have observed it.
       // //  adaptor_.cancel_new_block(block_index);
       // To avoid using up 2^16 qnodes, we might want a "peek" check to
       // exit before putting qnode when obviously there is a writer.
       return 0;
     }
     /* The old version that uses 0 timeout:
     McsBlockIndex block_index = 0;
     auto ret = acquire_reader_lock(lock, &block_index, McsRwExtendedBlock::kTimeoutZero);
     ASSERT_ND(ret == kErrorCodeOk || ret == kErrorCodeLockRequested);
     ASSERT_ND(block_index);
     if (ret == kErrorCodeOk) {
       return block_index;
     }
     ASSERT_ND(ret == kErrorCodeLockRequested);
     uint32_t my_tail_int =
       xct::McsRwLock::to_tail_int(static_cast<uint32_t>(adaptor_.get_my_id()), block_index);
     // check once
     if (retry_async_rw_reader(lock, block_index) ||
       cancel_reader_lock(lock, my_tail_int) == kErrorCodeOk) {
       return block_index;
     }
     return 0;
     */
   }
template<typename ADAPTOR > McsBlockIndex foedus::xct::McsImpl< ADAPTOR, McsRwExtendedBlock >::acquire_try_rw_writer (McsRwLock * lock) inline
Instant-try versions, won't leave node in the queue if failed.
Different from SimpleRWLock, here we use the async try/retry/cancel trio.
Definition at line 705 of file xct_mcs_impl.cpp.
References foedus::xct::McsRwLock::tail_, and foedus::xct::McsRwLock::to_tail_int().
{
     const thread::ThreadId id = adaptor_.get_my_id();
     McsBlockIndex block_index = 0;
     auto* my_block = init_block(&block_index, true);
     McsRwLock tmp;
     uint64_t expected = *reinterpret_cast<uint64_t*>(&tmp);
     McsRwLock tmp2;
     tmp2.tail_ = McsRwLock::to_tail_int(id, block_index);
     uint64_t desired = *reinterpret_cast<uint64_t*>(&tmp2);
     my_block->set_flags_granted();
     if (assorted::raw_atomic_compare_exchange_weak<uint64_t>(
       reinterpret_cast<uint64_t*>(lock), &expected, desired)) {
       return block_index;
     } else {
       // The block is never observed. reuse
       adaptor_.cancel_new_block(block_index);
       return 0;
     }
   /*
    * XXX(tzwang, Feb 2016): it turns out the above CAS-try is better than using the trio -
    * the difference could be as much as 10x under high contention (DL580). The reason
    * I think is under high contention, often we need to cancel anyway, which is much
    * more expensive than a simple weak CAS.
    *
    * But the case for readers is a bit different: the trio wins especially with a lot of
    * reads because it allows real reader-sharing.
    */
   /*
     McsBlockIndex block_index = 0;
     //auto ret = acquire_writer_lock(lock, &block_index, McsRwExtendedBlock::kTimeoutZero);
     auto ret = acquire_writer_lock(lock, &block_index, 1000);
     ASSERT_ND(ret == kErrorCodeOk || ret == kErrorCodeLockRequested);
     ASSERT_ND(block_index);
     if (ret == kErrorCodeOk) {
       return block_index;
     }
     return 0;
     ASSERT_ND(ret == kErrorCodeLockRequested);
     uint32_t my_tail_int =
       xct::McsRwLock::to_tail_int(static_cast<uint32_t>(adaptor_.get_my_id()), block_index);
     // check once
     if (retry_async_rw_writer(lock, block_index) ||
       cancel_writer_lock(lock, my_tail_int) == kErrorCodeOk) {
       return block_index;
     }
     return 0;
   */
   }
template<typename ADAPTOR > McsBlockIndex foedus::xct::McsImpl< ADAPTOR, McsRwExtendedBlock >::acquire_unconditional_rw_reader (McsRwLock * lock) inline
Definition at line 679 of file xct_mcs_impl.cpp.
References ASSERT_ND, foedus::kErrorCodeOk, and foedus::xct::McsRwExtendedBlock::kTimeoutNever.
{
     McsBlockIndex block_index = 0;
     auto ret = acquire_reader_lock(lock, &block_index, McsRwExtendedBlock::kTimeoutNever);
     ASSERT_ND(block_index);
     ASSERT_ND(ret == kErrorCodeOk);
 #ifndef NDEBUG
     auto* my_block = adaptor_.get_rw_my_block(block_index);
     ASSERT_ND(my_block->next_flag_is_granted());
     ASSERT_ND(my_block->pred_flag_is_granted());
 #endif
     return block_index;
   }
template<typename ADAPTOR > McsBlockIndex foedus::xct::McsImpl< ADAPTOR, McsRwExtendedBlock >::acquire_unconditional_rw_writer (McsRwLock * lock) inline
Definition at line 691 of file xct_mcs_impl.cpp.
References ASSERT_ND, foedus::kErrorCodeOk, and foedus::xct::McsRwExtendedBlock::kTimeoutNever.
{
     McsBlockIndex block_index = 0;
     auto ret = acquire_writer_lock(lock, &block_index, McsRwExtendedBlock::kTimeoutNever);
     ASSERT_ND(block_index);
     ASSERT_ND(ret == kErrorCodeOk);
 #ifndef NDEBUG
     auto* my_block = adaptor_.get_rw_my_block(block_index);
     ASSERT_ND(my_block->next_flag_is_granted());
     ASSERT_ND(my_block->pred_flag_is_granted());
 #endif
     return block_index;
   }
template<typename ADAPTOR > void foedus::xct::McsImpl< ADAPTOR, McsRwExtendedBlock >::cancel_async_rw_reader (McsRwLock * lock, McsBlockIndex block_index) inline
Definition at line 867 of file xct_mcs_impl.cpp.
References foedus::kErrorCodeOk, foedus::xct::McsImpl< ADAPTOR, RW_BLOCK >::retry_async_rw_reader(), and foedus::xct::McsRwLock::to_tail_int().
{
     if (!retry_async_rw_reader(lock, block_index)) {
       uint32_t my_tail_int = McsRwLock::to_tail_int(adaptor_.get_my_id(), block_index);
       if (cancel_reader_lock(lock, my_tail_int) == kErrorCodeOk) {
         // actually got the lock, have to release then
         release_reader_lock(lock, block_index);
       }
     } else {
       release_reader_lock(lock, block_index);
     }
   }
template<typename ADAPTOR > void foedus::xct::McsImpl< ADAPTOR, McsRwExtendedBlock >::cancel_async_rw_writer (McsRwLock * lock, McsBlockIndex block_index) inline
Definition at line 878 of file xct_mcs_impl.cpp.
References foedus::kErrorCodeOk, and foedus::xct::McsRwLock::to_tail_int().
{
     uint32_t my_tail_int = McsRwLock::to_tail_int(adaptor_.get_my_id(), block_index);
     if (cancel_writer_lock(lock, my_tail_int) == kErrorCodeOk) {
       release_writer_lock(lock, block_index);
     }
   }
template<typename ADAPTOR > static bool foedus::xct::McsImpl< ADAPTOR, McsRwExtendedBlock >::does_support_try_rw_reader () inline static
Definition at line 678 of file xct_mcs_impl.cpp.
 { return true; }
template<typename ADAPTOR > void foedus::xct::McsImpl< ADAPTOR, McsRwExtendedBlock >::release_rw_reader (McsRwLock * lock, McsBlockIndex block_index) inline
Definition at line 796 of file xct_mcs_impl.cpp.
{
     release_reader_lock(lock, block_index);
   }
template<typename ADAPTOR > void foedus::xct::McsImpl< ADAPTOR, McsRwExtendedBlock >::release_rw_writer (McsRwLock * lock, McsBlockIndex block_index) inline
Definition at line 799 of file xct_mcs_impl.cpp.
{
     release_writer_lock(lock, block_index);
   }
template<typename ADAPTOR > bool foedus::xct::McsImpl< ADAPTOR, McsRwExtendedBlock >::retry_async_rw_reader (McsRwLock * lock, McsBlockIndex block_index) inline
Definition at line 838 of file xct_mcs_impl.cpp.
References ASSERT_ND, foedus::kErrorCodeOk, and foedus::xct::McsRwLock::to_tail_int().
{
     auto* block = adaptor_.get_rw_my_block(block_index);
     if (block->pred_flag_is_granted()) {
       // checking me.next.flags.granted is ok - we're racing with ourself
       if (!block->next_flag_is_granted()) {
         auto ret = finish_acquire_reader_lock(lock, block,
           xct::McsRwLock::to_tail_int(static_cast<uint32_t>(adaptor_.get_my_id()), block_index));
         ASSERT_ND(ret == kErrorCodeOk);
       }
       ASSERT_ND(block->next_flag_is_granted());
       return true;
     }
     ASSERT_ND(!block->next_flag_is_granted());
     return false;
   }
template<typename ADAPTOR > bool foedus::xct::McsImpl< ADAPTOR, McsRwExtendedBlock >::retry_async_rw_writer (McsRwLock * lock, McsBlockIndex block_index) inline
Definition at line 853 of file xct_mcs_impl.cpp.
References ASSERT_ND.
{
     auto* block = adaptor_.get_rw_my_block(block_index);
     if (block->pred_flag_is_granted()) {
       // checking me.next.flags.granted is ok - we're racing with ourself
       if (!block->next_flag_is_granted()) {
         block->set_next_flag_granted();
         adaptor_.remove_rw_async_mapping(lock);
       }
       ASSERT_ND(block->next_flag_is_granted());
       return true;
     }
     ASSERT_ND(!block->next_flag_is_granted());
     return false;
   }
The documentation for this class was generated from the following file:
/home/shino/foedus_code/foedus-core/src/foedus/xct/xct_mcs_impl.cpp