libfoedus-core: foedus::log::MetaLogBuffer Class Reference
foedus::log::MetaLogBuffer Class Reference
FOEDUS Components » Log Manager
A single log buffer for metadata (eg create/drop storage).
Detailed Description
A single log buffer for metadata (eg create/drop storage).
Per-engine/storage operations such as CREATE/DROP STORAGE are logged differently. They are always separated from usual transactions and also written to a separate log file. Metadata operation is rare, so we don't optimize the code here. Instead, this class is much simpler than ThreadLogBuffer. More precisely:
Metadata operation is always the only operation in the transaction.
Metadata operation never gets aborted.
Every epoch has at most one metadata operation; for each metadata operation, we immediately advance epoch.
Each metadata log is immediately synched to log file.
Shared log buffer
Unlike ThreadLogBuffer, this buffer is placed in shared memory and every thread in every SOC can write to this log buffer with mutex.
Definition at line 91 of file meta_log_buffer.hpp.
#include <meta_log_buffer.hpp>
Public Member Functions
MetaLogBuffer ()
MetaLogBuffer (Engine *engine, MetaLogControlBlock *block)
void commit (BaseLogType *metalog, Epoch *commit_epoch)
Synchronously writes out the given log to metadata log file.
Public Member Functions inherited from foedus::Attachable< MetaLogControlBlock >
Attachable ()
Attachable (Engine *engine)
Attachable (Engine *engine, MetaLogControlBlock *control_block)
Attachable (MetaLogControlBlock *control_block)
Attachable (const Attachable &other)
virtual ~Attachable ()
Attachable & operator= (const Attachable &other)
virtual void attach (MetaLogControlBlock *control_block)
Attaches to the given shared memory.
bool is_attached () const
Returns whether the object has been already attached to some shared memory.
MetaLogControlBlock * get_control_block () const
Engine * get_engine () const
void set_engine (Engine *engine)
Friends
std::ostream & operator<< (std::ostream &o, const MetaLogBuffer &v)
Additional Inherited Members
Protected Attributes inherited from foedus::Attachable< MetaLogControlBlock >
Engine * engine_
Most attachable object stores an engine pointer (local engine), so we define it here.
MetaLogControlBlock * control_block_
The shared data on shared memory that has been initialized in some SOC or master engine.
Constructor & Destructor Documentation
foedus::log::MetaLogBuffer::MetaLogBuffer () inline
Definition at line 93 of file meta_log_buffer.hpp.
 : Attachable<MetaLogControlBlock>() {}
foedus::log::MetaLogBuffer::MetaLogBuffer (Engine * engine, MetaLogControlBlock * block) inline
Definition at line 94 of file meta_log_buffer.hpp.
     : Attachable<MetaLogControlBlock>(engine, block) {}
Member Function Documentation
void foedus::log::MetaLogBuffer::commit (BaseLogType * metalog, Epoch * commit_epoch)
Synchronously writes out the given log to metadata log file.
Definition at line 33 of file meta_log_buffer.cpp.
References foedus::xct::XctManager::advance_current_global_epoch(), ASSERT_ND, foedus::Attachable< MetaLogControlBlock >::control_block_, foedus::Attachable< MetaLogControlBlock >::engine_, foedus::xct::XctManager::get_current_global_epoch(), foedus::log::LogHeader::get_kind(), foedus::Engine::get_xct_manager(), foedus::log::BaseLogType::header_, foedus::log::kEngineLogs, foedus::log::kStorageLogs, foedus::log::LogHeader::log_length_, foedus::assorted::memory_fence_acquire(), foedus::xct::XctId::set_epoch(), and foedus::log::LogHeader::xct_id_.
Referenced by foedus::storage::StorageManagerPimpl::create_storage_and_log(), foedus::storage::StorageManagerPimpl::drop_storage(), and foedus::storage::sequential::SequentialStoragePimpl::truncate().
{
   LOG(INFO) << "Writing a metadata log. " << metalog->header_ << "...";
   {
     soc::SharedMutexScope scope(&control_block_->mutex_);
     // access to metadata buffer is mutex-protected
     ASSERT_ND(control_block_->buffer_used_ == 0);
     // To avoid mixing with normal operations on the storage in this epoch, advance epoch.
     // This happens within the mutex, so this is assured to be the only metadata log in the epoch.
     engine_->get_xct_manager()->advance_current_global_epoch();
     *commit_epoch = engine_->get_xct_manager()->get_current_global_epoch();
     LOG(INFO) << "Issued an epoch for the metadata log: " << *commit_epoch << "...";
     metalog->header_.xct_id_.set_epoch(*commit_epoch);
     // copy to buffer_ first
     ASSERT_ND(metalog->header_.get_kind() == kStorageLogs
       || metalog->header_.get_kind() == kEngineLogs);
     std::memcpy(control_block_->buffer_, metalog, metalog->header_.log_length_);
     // then write buffer_used_ after fence for the logger to safely read it
     // Also, do it within mutex to avoid lost signal
     {
       // Wakeup the logger
       control_block_->buffer_used_ = metalog->header_.log_length_;
       control_block_->logger_wakeup_.signal();
     }
     // Simply sleep for a while. Metadata logging is not so often, so we can simply spin
     // with a short sleep.
     while (control_block_->buffer_used_ > 0) {
       std::this_thread::sleep_for(std::chrono::microseconds(100));
       assorted::memory_fence_acquire();
     }
   }
   LOG(INFO) << "Wrote a metadata log. " << metalog->header_ << "...";
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const MetaLogBuffer & v) friend
Definition at line 70 of file meta_log_buffer.cpp.
{
   o << "<MetaLogBuffer>"
     << "<buffer_used_>" << v.control_block_->buffer_used_ << "</buffer_used_>"
     << "<oldest_offset_>" << v.control_block_->oldest_offset_ << "</oldest_offset_>"
     << "<durable_offset_>" << v.control_block_->durable_offset_ << "</durable_offset_>"
     << "</MetaLogBuffer>";
   return o;
 }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/log/meta_log_buffer.hpp
/home/shino/foedus_code/foedus-core/src/foedus/log/meta_log_buffer.cpp