libfoedus-core: foedus::snapshot::LogGleanerRef Class Reference
foedus::snapshot::LogGleanerRef Class Reference
FOEDUS Components » Snapshot Manager
A remote view of LogGleaner from all engines.
Detailed Description
A remote view of LogGleaner from all engines.
Definition at line 36 of file log_gleaner_ref.hpp.
#include <log_gleaner_ref.hpp>
Public Member Functions
LogGleanerRef ()
LogGleanerRef (Engine *engine)
bool is_error () const
void wakeup ()
const Snapshot & get_cur_snapshot () const
SnapshotId get_snapshot_id () const
Epoch get_base_epoch () const
Epoch get_valid_until_epoch () const
uint16_t increment_completed_count ()
uint16_t increment_completed_mapper_count ()
uint16_t increment_error_count ()
uint16_t increment_exit_count ()
bool is_all_exitted () const
bool is_all_completed () const
bool is_all_mappers_completed () const
uint16_t get_mappers_count () const
uint16_t get_reducers_count () const
uint16_t get_all_count () const
Public Member Functions inherited from foedus::Attachable< LogGleanerControlBlock >
Attachable ()
Attachable (Engine *engine)
Attachable (Engine *engine, LogGleanerControlBlock *control_block)
Attachable (LogGleanerControlBlock *control_block)
Attachable (const Attachable &other)
virtual ~Attachable ()
Attachable & operator= (const Attachable &other)
virtual void attach (LogGleanerControlBlock *control_block)
Attaches to the given shared memory.
bool is_attached () const
Returns whether the object has been already attached to some shared memory.
LogGleanerControlBlock * get_control_block () const
Engine * get_engine () const
void set_engine (Engine *engine)
Protected Attributes
storage::PartitionerMetadata * partitioner_metadata_
void * partitioner_data_
Protected Attributes inherited from foedus::Attachable< LogGleanerControlBlock >
Engine * engine_
Most attachable object stores an engine pointer (local engine), so we define it here.
LogGleanerControlBlock * control_block_
The shared data on shared memory that has been initialized in some SOC or master engine.
Constructor & Destructor Documentation
foedus::snapshot::LogGleanerRef::LogGleanerRef ()
Definition at line 26 of file log_gleaner_ref.cpp.
References partitioner_data_, and partitioner_metadata_.
                              : Attachable<LogGleanerControlBlock>() {
   partitioner_metadata_ = nullptr;
   partitioner_data_ = nullptr;
 }
foedus::snapshot::LogGleanerRef::LogGleanerRef (Engine * engine) explicit
Definition at line 30 of file log_gleaner_ref.cpp.
References foedus::Attachable< LogGleanerControlBlock >::control_block_, foedus::Attachable< LogGleanerControlBlock >::engine_, foedus::soc::SharedMemoryRepo::get_global_memory_anchors(), foedus::soc::SocManager::get_shared_memory_repo(), foedus::Engine::get_soc_manager(), foedus::snapshot::SnapshotManagerControlBlock::gleaner_, partitioner_data_, foedus::soc::GlobalMemoryAnchors::partitioner_data_, partitioner_metadata_, foedus::soc::GlobalMemoryAnchors::partitioner_metadata_, and foedus::soc::GlobalMemoryAnchors::snapshot_manager_memory_.
   : Attachable<LogGleanerControlBlock>() {
   engine_ = engine;
   soc::GlobalMemoryAnchors* anchors
     = engine_->get_soc_manager()->get_shared_memory_repo()->get_global_memory_anchors();
   control_block_ =  &anchors->snapshot_manager_memory_->gleaner_;
   partitioner_metadata_ = anchors->partitioner_metadata_;
   partitioner_data_ = anchors->partitioner_data_;
 }
Member Function Documentation
uint16_t foedus::snapshot::LogGleanerRef::get_all_count () const
Definition at line 69 of file log_gleaner_ref.cpp.
References foedus::Attachable< LogGleanerControlBlock >::control_block_.
 { return control_block_->all_count_; }
Epoch foedus::snapshot::LogGleanerRef::get_base_epoch () const
Definition at line 77 of file log_gleaner_ref.cpp.
References foedus::snapshot::Snapshot::base_epoch_, and get_cur_snapshot().
Referenced by foedus::snapshot::LogMapper::handle_process().
 { return get_cur_snapshot().base_epoch_; }
const Snapshot & foedus::snapshot::LogGleanerRef::get_cur_snapshot () const
Definition at line 75 of file log_gleaner_ref.cpp.
References foedus::Attachable< LogGleanerControlBlock >::control_block_.
Referenced by get_base_epoch(), get_snapshot_id(), and get_valid_until_epoch().
 { return control_block_->cur_snapshot_; }
uint16_t foedus::snapshot::LogGleanerRef::get_mappers_count () const
Definition at line 67 of file log_gleaner_ref.cpp.
References foedus::Attachable< LogGleanerControlBlock >::control_block_.
 { return control_block_->mappers_count_; }
uint16_t foedus::snapshot::LogGleanerRef::get_reducers_count () const
Definition at line 68 of file log_gleaner_ref.cpp.
References foedus::Attachable< LogGleanerControlBlock >::control_block_.
 { return control_block_->reducers_count_; }
SnapshotId foedus::snapshot::LogGleanerRef::get_snapshot_id () const
Definition at line 76 of file log_gleaner_ref.cpp.
References get_cur_snapshot(), and foedus::snapshot::Snapshot::id_.
Referenced by foedus::snapshot::LogGleaner::execute().
 { return get_cur_snapshot().id_; }
Epoch foedus::snapshot::LogGleanerRef::get_valid_until_epoch () const
Definition at line 78 of file log_gleaner_ref.cpp.
References get_cur_snapshot(), and foedus::snapshot::Snapshot::valid_until_epoch_.
Referenced by foedus::snapshot::LogMapper::handle_process().
 { return get_cur_snapshot().valid_until_epoch_; }
uint16_t foedus::snapshot::LogGleanerRef::increment_completed_count ()
Definition at line 40 of file log_gleaner_ref.cpp.
References ASSERT_ND, and foedus::Attachable< LogGleanerControlBlock >::control_block_.
{
   ASSERT_ND(control_block_->completed_count_ < control_block_->all_count_);
   return ++control_block_->completed_count_;
 }
uint16_t foedus::snapshot::LogGleanerRef::increment_completed_mapper_count ()
Definition at line 44 of file log_gleaner_ref.cpp.
References ASSERT_ND, and foedus::Attachable< LogGleanerControlBlock >::control_block_.
{
   ASSERT_ND(control_block_->completed_mapper_count_ < control_block_->mappers_count_);
   return ++control_block_->completed_mapper_count_;
 }
uint16_t foedus::snapshot::LogGleanerRef::increment_error_count ()
Definition at line 48 of file log_gleaner_ref.cpp.
References ASSERT_ND, and foedus::Attachable< LogGleanerControlBlock >::control_block_.
{
   ASSERT_ND(control_block_->error_count_ < control_block_->all_count_);
   return ++control_block_->error_count_;
 }
uint16_t foedus::snapshot::LogGleanerRef::increment_exit_count ()
Definition at line 52 of file log_gleaner_ref.cpp.
References ASSERT_ND, and foedus::Attachable< LogGleanerControlBlock >::control_block_.
{
   ASSERT_ND(control_block_->exit_count_ < control_block_->all_count_);
   return ++control_block_->exit_count_;
 }
bool foedus::snapshot::LogGleanerRef::is_all_completed () const
Definition at line 61 of file log_gleaner_ref.cpp.
References foedus::Attachable< LogGleanerControlBlock >::control_block_.
Referenced by foedus::snapshot::LogGleaner::execute().
{
   return control_block_->completed_count_ >= control_block_->all_count_;
 }
bool foedus::snapshot::LogGleanerRef::is_all_exitted () const
Definition at line 57 of file log_gleaner_ref.cpp.
References foedus::Attachable< LogGleanerControlBlock >::control_block_.
Referenced by foedus::snapshot::LogGleaner::execute().
{
   return control_block_->exit_count_ >= control_block_->all_count_;
 }
bool foedus::snapshot::LogGleanerRef::is_all_mappers_completed () const
Definition at line 64 of file log_gleaner_ref.cpp.
References foedus::Attachable< LogGleanerControlBlock >::control_block_.
Referenced by foedus::snapshot::LogReducer::handle_process().
{
   return control_block_->completed_mapper_count_ >= control_block_->mappers_count_;
 }
bool foedus::snapshot::LogGleanerRef::is_error () const
Definition at line 71 of file log_gleaner_ref.cpp.
References foedus::Attachable< LogGleanerControlBlock >::control_block_.
Referenced by foedus::snapshot::MapReduceBase::check_cancelled(), and foedus::snapshot::LogGleaner::execute().
 { return control_block_->is_error(); }
void foedus::snapshot::LogGleanerRef::wakeup ()
Definition at line 72 of file log_gleaner_ref.cpp.
{
 }
Member Data Documentation
void* foedus::snapshot::LogGleanerRef::partitioner_data_ protected
Definition at line 63 of file log_gleaner_ref.hpp.
Referenced by LogGleanerRef().
storage::PartitionerMetadata* foedus::snapshot::LogGleanerRef::partitioner_metadata_ protected
Definition at line 62 of file log_gleaner_ref.hpp.
Referenced by LogGleanerRef().
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/snapshot/log_gleaner_ref.hpp
/home/shino/foedus_code/foedus-core/src/foedus/snapshot/log_gleaner_ref.cpp