libfoedus-core: foedus::assorted::FixedString< MAXLEN, CHAR > Class Template Reference
foedus::assorted::FixedString< MAXLEN, CHAR > Class Template Reference
FOEDUS Programming Idioms » Assorted Methods/Classes
An embedded string object of fixed max-length, which uses no external memory.
Detailed Description
template<uint MAXLEN, typename CHAR = char>
class foedus::assorted::FixedString< MAXLEN, CHAR >
An embedded string object of fixed max-length, which uses no external memory.
This header-only object behaves like std::string in many ways. The key difference is that this object is essentially a fixed array while std::string allocates memory in heap (with some exception for optimized stack-allocation, but that's not the point).
This implies a few crucial characteristics.
We can copy/overwrite a piece of memory containing this object without taking care of heap-allocated memory (which makes the handling of shared memory much easier).
We have limit on the length of the string, determined at compile time (a template param).
We always consume that much memory regardless the actual content.
Usecases
As mentioned above, this object is used where we can't use std::string that points to somewhere else. For example, use it as follows.
struct MyPage {
  FixedString<12>  str1_;  // +4+12
  FixedString<8>   str2_;  // +4+8+4 (Anyway 8 byte aligned..)
  char             other_data_[4096-32];
};
// This page can be simply memcpy-ed unlike a struct that contains std::string.
Limitations
No char traits for exotic comparison rules. Not more than 2^32-1 chars. Length 2^32-1 is reserved for npos.
Definition at line 65 of file fixed_string.hpp.
#include <fixed_string.hpp>
Public Member Functions
FixedString () noexcept
Constructs an empty string.
template<uint MAXLEN2>
FixedString (const FixedString< MAXLEN2, CHAR > &other) noexcept
Copy constructor for all FixedString objects.
FixedString (const CHAR *str, uint32_t len) noexcept
Copy constructor for char* and len.
FixedString (const CHAR *str) noexcept
Copy constructor for null-terminated char*.
template<uint MAXLEN2>
FixedString & operator= (const FixedString< MAXLEN2, CHAR > &other) noexcept
Assign operator for all FixedString objects.
template<uint MAXLEN2>
bool operator== (const FixedString< MAXLEN2, CHAR > &other) const noexcept
template<uint MAXLEN2>
bool operator!= (const FixedString< MAXLEN2, CHAR > &other) const noexcept
template<uint MAXLEN2>
bool operator< (const FixedString< MAXLEN2, CHAR > &other) const noexcept
template<uint MAXLEN2>
void assign (const FixedString< MAXLEN2, CHAR > &other) noexcept
Assign operator for all FixedString objects.
void assign (const std::basic_string< CHAR > &str) noexcept
Assign operator for std::string.
void assign (const CHAR *str, uint32_t len) noexcept
Assign operator for char* and length.
template<uint MAXLEN2>
void append (const FixedString< MAXLEN2, CHAR > &other) noexcept
Append operator for all FixedString objects.
void append (const std::basic_string< CHAR > &str) noexcept
Append operator for std::string.
void append (const CHAR *str, uint32_t len) noexcept
Append operator for char* and length.
uint32_t length () const noexcept
Returns the length of this string.
uint32_t size () const noexcept
Returns the length of this string.
uint32_t capacity () const noexcept
Return size of allocated storage.
uint32_t max_size () const noexcept
Return maximum size of string.
void clear () noexcept
Clear string.
bool empty () const noexcept
Test if string is empty.
void zero_fill_remaining () const noexcept
Sets zeros to unused data_ region.
const CHAR * data () const noexcept
Get string data.
std::basic_string< CHAR > str () const
Convert to a std::string object.
const CHAR * c_str () const
Convert to a C string.
Static Public Member Functions
static uint32_t strlen (const char *str) noexcept
static uint32_t strlen (const wchar_t *str) noexcept
Static Public Attributes
static const uint32_t npos = -1
npos is a static member constant value with the greatest possible value for uint32_t.
Friends
std::ostream & operator<< (std::ostream &o, const FixedString &v)
Constructor & Destructor Documentation
template<uint MAXLEN, typename CHAR = char> foedus::assorted::FixedString< MAXLEN, CHAR >::FixedString () inline noexcept
Constructs an empty string.
Definition at line 68 of file fixed_string.hpp.
 : length_(0) {}
template<uint MAXLEN, typename CHAR = char> template<uint MAXLEN2> foedus::assorted::FixedString< MAXLEN, CHAR >::FixedString (const FixedString< MAXLEN2, CHAR > & other) inline explicit noexcept
Copy constructor for all FixedString objects.
Note that too-long strings are truncated.
Definition at line 72 of file fixed_string.hpp.
 { assign(other); }
template<uint MAXLEN, typename CHAR = char> foedus::assorted::FixedString< MAXLEN, CHAR >::FixedString (const CHAR * str, uint32_t len) inline noexcept
Copy constructor for char* and len.
Note that too-long strings are truncated.
Definition at line 75 of file fixed_string.hpp.
 { assign(str, len); }
template<uint MAXLEN, typename CHAR = char> foedus::assorted::FixedString< MAXLEN, CHAR >::FixedString (const CHAR * str) inline noexcept
Copy constructor for null-terminated char*.
Note that too-long strings are truncated.
Definition at line 78 of file fixed_string.hpp.
                                               {  // NOLINT(runtime/explicit) follows std::string
     assign(str, strlen(str));
   }
Member Function Documentation
template<uint MAXLEN, typename CHAR = char> template<uint MAXLEN2> void foedus::assorted::FixedString< MAXLEN, CHAR >::append (const FixedString< MAXLEN2, CHAR > & other) inline noexcept
Append operator for all FixedString objects.
Note that too-long strings are truncated.
Definition at line 138 of file fixed_string.hpp.
{
     ASSERT_ND(other.length() <= MAXLEN2);
     uint32_t len = length_ + other.length() > MAXLEN ? MAXLEN - length_ : other.length();
     std::memcpy(data_ + length_, other.data(), len * sizeof(CHAR));
     length_ += len;
   }
template<uint MAXLEN, typename CHAR = char> void foedus::assorted::FixedString< MAXLEN, CHAR >::append (const std::basic_string< CHAR > & str) inline noexcept
Append operator for std::string.
Note that too-long strings are truncated.
Definition at line 146 of file fixed_string.hpp.
{
     uint32_t len = length_ + str.size() > MAXLEN ? MAXLEN - length_ : str.size();
     std::memcpy(data_ + length_, str.data(), len * sizeof(CHAR));
     length_ += len;
   }
template<uint MAXLEN, typename CHAR = char> void foedus::assorted::FixedString< MAXLEN, CHAR >::append (const CHAR * str, uint32_t len) inline noexcept
Append operator for char* and length.
Note that too-long strings are truncated.
Definition at line 153 of file fixed_string.hpp.
{
     len = length_ + len > MAXLEN ? MAXLEN - length_ : len;
     std::memcpy(data_ + length_, str, len * sizeof(CHAR));
     length_ += len;
   }
template<uint MAXLEN, typename CHAR = char> template<uint MAXLEN2> void foedus::assorted::FixedString< MAXLEN, CHAR >::assign (const FixedString< MAXLEN2, CHAR > & other) inline noexcept
Assign operator for all FixedString objects.
Note that too-long strings are truncated.
Definition at line 119 of file fixed_string.hpp.
Referenced by foedus::assorted::FixedString< 60 >::FixedString(), foedus::externalize::Externalizable::get_element(), foedus::FixedErrorStack::operator=(), foedus::assorted::FixedString< 60 >::operator=(), and foedus::memory::PagePoolPimpl::set_debug_pool_name().
{
     ASSERT_ND(other.length() <= MAXLEN2);
     length_ = other.length() > MAXLEN ? MAXLEN : other.length();
     std::memcpy(data_, other.data(), length_ * sizeof(CHAR));
   }
template<uint MAXLEN, typename CHAR = char> void foedus::assorted::FixedString< MAXLEN, CHAR >::assign (const std::basic_string< CHAR > & str) inline noexcept
Assign operator for std::string.
Note that too-long strings are truncated.
Definition at line 125 of file fixed_string.hpp.
{
     length_ = str.size() > MAXLEN ? MAXLEN : str.size();
     std::memcpy(data_, str.data(), length_ * sizeof(CHAR));
   }
template<uint MAXLEN, typename CHAR = char> void foedus::assorted::FixedString< MAXLEN, CHAR >::assign (const CHAR * str, uint32_t len) inline noexcept
Assign operator for char* and length.
Note that too-long strings are truncated.
Definition at line 131 of file fixed_string.hpp.
{
     length_ = len > MAXLEN ? MAXLEN : len;
     std::memcpy(data_, str, length_ * sizeof(CHAR));
   }
template<uint MAXLEN, typename CHAR = char> const CHAR* foedus::assorted::FixedString< MAXLEN, CHAR >::c_str () const inline
Convert to a C string.
Definition at line 189 of file fixed_string.hpp.
Referenced by foedus::proc::ProcManagerPimpl::get_proc().
 { return str().c_str(); }
template<uint MAXLEN, typename CHAR = char> uint32_t foedus::assorted::FixedString< MAXLEN, CHAR >::capacity () const inline noexcept
Return size of allocated storage.
Actually a constexpr.
Definition at line 166 of file fixed_string.hpp.
 { return MAXLEN; }
template<uint MAXLEN, typename CHAR = char> void foedus::assorted::FixedString< MAXLEN, CHAR >::clear () inline noexcept
Clear string.
Definition at line 170 of file fixed_string.hpp.
Referenced by foedus::memory::PagePoolPimpl::attach(), foedus::FixedErrorStack::from_error_stack(), foedus::thread::ThreadControlBlock::initialize(), foedus::externalize::TinyxmlGetter< assorted::FixedString< MAXLEN, CHAR > >::operator()(), and foedus::FixedErrorStack::operator=().
 { length_ = 0; }
template<uint MAXLEN, typename CHAR = char> const CHAR* foedus::assorted::FixedString< MAXLEN, CHAR >::data () const inline noexcept
Get string data.
Definition at line 183 of file fixed_string.hpp.
 { return data_; }
template<uint MAXLEN, typename CHAR = char> bool foedus::assorted::FixedString< MAXLEN, CHAR >::empty () const inline noexcept
Test if string is empty.
Definition at line 172 of file fixed_string.hpp.
Referenced by foedus::soc::SocOptions::convert_spawn_executable_pattern(), foedus::soc::SocOptions::convert_spawn_ld_library_path_pattern(), foedus::storage::StorageManagerPimpl::create_storage(), foedus::storage::StorageManagerPimpl::create_storage_apply(), foedus::memory::PagePoolPimpl::get_debug_pool_name(), and foedus::storage::StorageManagerPimpl::initialize_read_latest_snapshot().
 { return length_ == 0; }
template<uint MAXLEN, typename CHAR = char> uint32_t foedus::assorted::FixedString< MAXLEN, CHAR >::length () const inline noexcept
Returns the length of this string.
Definition at line 162 of file fixed_string.hpp.
 { return length_; }
template<uint MAXLEN, typename CHAR = char> uint32_t foedus::assorted::FixedString< MAXLEN, CHAR >::max_size () const inline noexcept
Return maximum size of string.
Actually a constexpr.
Definition at line 168 of file fixed_string.hpp.
 { return MAXLEN; }
template<uint MAXLEN, typename CHAR = char> template<uint MAXLEN2> bool foedus::assorted::FixedString< MAXLEN, CHAR >::operator!= (const FixedString< MAXLEN2, CHAR > & other) const inline noexcept
Definition at line 101 of file fixed_string.hpp.
{
     return !operator==(other);
   }
template<uint MAXLEN, typename CHAR = char> template<uint MAXLEN2> bool foedus::assorted::FixedString< MAXLEN, CHAR >::operator< (const FixedString< MAXLEN2, CHAR > & other) const inline noexcept
Definition at line 105 of file fixed_string.hpp.
{
     uint32_t min_len = std::min<uint32_t>(length_, other.length());
     if (min_len == 0) {
       return length_ < other.length();
     }
     int result = std::memcmp(data_, other.data(), min_len * sizeof(CHAR));
     if (result != 0) {
       return result < 0;
     }
     return length_ < other.length();
   }
template<uint MAXLEN, typename CHAR = char> template<uint MAXLEN2> FixedString& foedus::assorted::FixedString< MAXLEN, CHAR >::operator= (const FixedString< MAXLEN2, CHAR > & other) inline noexcept
Assign operator for all FixedString objects.
Note that too-long strings are truncated.
Definition at line 87 of file fixed_string.hpp.
{
     assign(other);
     return *this;
   }
template<uint MAXLEN, typename CHAR = char> template<uint MAXLEN2> bool foedus::assorted::FixedString< MAXLEN, CHAR >::operator== (const FixedString< MAXLEN2, CHAR > & other) const inline noexcept
Definition at line 93 of file fixed_string.hpp.
Referenced by foedus::assorted::FixedString< 60 >::operator!=().
{
     if (length_ == 0) {
       return other.length() == 0;
     }
     return length_ == other.length() &&
       std::memcmp(data_, other.data(), length_ * sizeof(CHAR)) == 0;
   }
template<uint MAXLEN, typename CHAR = char> uint32_t foedus::assorted::FixedString< MAXLEN, CHAR >::size () const inline noexcept
Returns the length of this string.
Definition at line 164 of file fixed_string.hpp.
 { return length_; }
template<uint MAXLEN, typename CHAR = char> std::basic_string<CHAR> foedus::assorted::FixedString< MAXLEN, CHAR >::str () const inline
Convert to a std::string object.
Definition at line 185 of file fixed_string.hpp.
Referenced by foedus::externalize::Externalizable::add_element(), foedus::assorted::FixedString< 60 >::append(), foedus::assorted::FixedString< 60 >::assign(), foedus::assorted::FixedString< 60 >::c_str(), foedus::log::LogOptions::convert_folder_path_pattern(), foedus::snapshot::SnapshotOptions::convert_folder_path_pattern(), foedus::proc::ProcOptions::convert_shared_library_dir_pattern(), foedus::proc::ProcOptions::convert_shared_library_path_pattern(), foedus::soc::SocOptions::convert_spawn_executable_pattern(), foedus::soc::SocOptions::convert_spawn_ld_library_path_pattern(), foedus::assorted::FixedString< 60 >::FixedString(), foedus::memory::PagePoolPimpl::get_debug_pool_name(), foedus::savepoint::SavepointManagerPimpl::initialize_once(), foedus::externalize::TinyxmlSetter< assorted::FixedString< MAXLEN, CHAR > >::operator()(), and foedus::assorted::FixedString< 60 >::strlen().
{
     return std::basic_string<CHAR>(data_, length_);
   }
template<uint MAXLEN, typename CHAR = char> static uint32_t foedus::assorted::FixedString< MAXLEN, CHAR >::strlen (const char * str) inline static noexcept
Definition at line 82 of file fixed_string.hpp.
Referenced by foedus::assorted::FixedString< 60 >::FixedString().
 { return std::strlen(str); }
template<uint MAXLEN, typename CHAR = char> static uint32_t foedus::assorted::FixedString< MAXLEN, CHAR >::strlen (const wchar_t * str) inline static noexcept
Definition at line 83 of file fixed_string.hpp.
 { return std::wcslen(str); }
template<uint MAXLEN, typename CHAR = char> void foedus::assorted::FixedString< MAXLEN, CHAR >::zero_fill_remaining () const inline noexcept
Sets zeros to unused data_ region.
This is just to make valgrind happy.
Definition at line 174 of file fixed_string.hpp.
Referenced by foedus::storage::StorageManagerPimpl::create_storage().
{
     if (length_ < MAXLEN) {
       // this is not logically changing the content, so const is the right semantics.
       std::memset(const_cast<char*>(data_ + length_), 0, MAXLEN - length_);
     }
   }
Friends And Related Function Documentation
template<uint MAXLEN, typename CHAR = char> std::ostream& operator<< (std::ostream & o, const FixedString< MAXLEN, CHAR > & v) friend
Definition at line 200 of file fixed_string.hpp.
{
     o << v.str();
     return o;
   }
Member Data Documentation
template<uint MAXLEN, typename CHAR = char> const uint32_t foedus::assorted::FixedString< MAXLEN, CHAR >::npos = -1 static
npos is a static member constant value with the greatest possible value for uint32_t.
This value, when used as the value for a len (or sublen) parameter in this object, means "until the end of the string". As a return value, it is usually used to indicate no matches. This constant is defined with a value of -1, which because uint32_t is an unsigned integral type, it is the largest possible representable value for this type.
Definition at line 198 of file fixed_string.hpp.
The documentation for this class was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/assorted/fixed_string.hpp