libfoedus-core: foedus::snapshot::MapReduceBase Class Reference
foedus::snapshot::MapReduceBase Class Reference abstract
FOEDUS Components » Snapshot Manager
Base class for LogMapper and LogReducer to share common code.
Detailed Description
Base class for LogMapper and LogReducer to share common code.
The shared parts are:
init/uninit
synchronization with gleaner (main thread)
Note
This is a private implementation-details of Snapshot Manager, thus file name ends with _impl. Do not include this header from a client program. There is no case client program needs to access this internal class.
Definition at line 51 of file mapreduce_base_impl.hpp.
#include <mapreduce_base_impl.hpp>
Public Member Functions
MapReduceBase (Engine *engine, uint16_t id)
MapReduceBase ()=delete
MapReduceBase (const MapReduceBase &other)=delete
MapReduceBase & operator= (const MapReduceBase &other)=delete
LogGleanerRef * get_parent ()
uint16_t get_id () const
uint16_t get_numa_node () const
virtual std::string to_string () const =0
Expects "LogReducer-x", "LogMapper-y" etc.
void launch_thread ()
Start executing.
void join_thread ()
Public Member Functions inherited from foedus::DefaultInitializable
DefaultInitializable ()
virtual ~DefaultInitializable ()
DefaultInitializable (const DefaultInitializable &)=delete
DefaultInitializable & operator= (const DefaultInitializable &)=delete
ErrorStack initialize () override final
Typical implementation of Initializable::initialize() that provides initialize-once semantics.
ErrorStack uninitialize () override final
Typical implementation of Initializable::uninitialize() that provides uninitialize-once semantics.
bool is_initialized () const override final
Returns whether the object has been already initialized or not.
virtual ErrorStack initialize_once ()=0
virtual ErrorStack uninitialize_once ()=0
Public Member Functions inherited from foedus::Initializable
virtual ~Initializable ()
Protected Member Functions
virtual ErrorStack handle_process ()=0
Implements the specific logics in derived class.
ErrorCode check_cancelled () const
Derived class's handle_process() should occasionally call this to exit if it's cancelled.
Protected Attributes
Engine *const engine_
LogGleanerRef parent_
const uint16_t id_
Unique ID of this mapper or reducer.
const uint16_t numa_node_
std::atomic< bool > running_
only for sanity check
std::thread thread_
Constructor & Destructor Documentation
foedus::snapshot::MapReduceBase::MapReduceBase (Engine * engine, uint16_t id)
Definition at line 37 of file mapreduce_base_impl.cpp.
   : engine_(engine), parent_(engine), id_(id), numa_node_(engine->get_soc_id()), running_(false) {}
foedus::snapshot::MapReduceBase::MapReduceBase () delete
foedus::snapshot::MapReduceBase::MapReduceBase (const MapReduceBase & other) delete
Member Function Documentation
ErrorCode foedus::snapshot::MapReduceBase::check_cancelled () const protected
Derived class's handle_process() should occasionally call this to exit if it's cancelled.
Definition at line 54 of file mapreduce_base_impl.cpp.
References foedus::snapshot::LogGleanerRef::is_error(), foedus::kErrorCodeOk, foedus::kErrorCodeSnapshotCancelled, and parent_.
Referenced by foedus::snapshot::LogMapper::handle_process(), and foedus::snapshot::LogReducer::handle_process().
{
   if (parent_.is_error()) {
     return kErrorCodeSnapshotCancelled;
   }
   return kErrorCodeOk;
 }
uint16_t foedus::snapshot::MapReduceBase::get_id () const inline
Definition at line 60 of file mapreduce_base_impl.hpp.
References id_.
Referenced by foedus::snapshot::operator<<().
 { return id_; }
uint16_t foedus::snapshot::MapReduceBase::get_numa_node () const inline
Definition at line 61 of file mapreduce_base_impl.hpp.
References numa_node_.
Referenced by foedus::snapshot::LogReducer::initialize_once(), and foedus::snapshot::operator<<().
 { return numa_node_; }
LogGleanerRef* foedus::snapshot::MapReduceBase::get_parent () inline
Definition at line 59 of file mapreduce_base_impl.hpp.
References parent_.
 { return &parent_; }
virtual ErrorStack foedus::snapshot::MapReduceBase::handle_process () protected pure virtual
Implements the specific logics in derived class.
Implemented in foedus::snapshot::LogReducer, and foedus::snapshot::LogMapper.
void foedus::snapshot::MapReduceBase::join_thread ()
Definition at line 45 of file mapreduce_base_impl.cpp.
References thread_, and to_string().
Referenced by foedus::snapshot::SnapshotManagerPimpl::handle_snapshot_child().
{
   LOG(INFO) << "Waiting for the completion of thread: " << to_string();
   if (thread_.joinable()) {
     thread_.join();
   }
   LOG(INFO) << "Observed completion of thread: " << to_string();
 }
void foedus::snapshot::MapReduceBase::launch_thread ()
Start executing.
Definition at line 40 of file mapreduce_base_impl.cpp.
References thread_, and to_string().
Referenced by foedus::snapshot::SnapshotManagerPimpl::handle_snapshot_child().
{
   LOG(INFO) << "Launching thread for " << to_string();
   thread_ = std::move(std::thread(&MapReduceBase::handle, this));
 }
MapReduceBase& foedus::snapshot::MapReduceBase::operator= (const MapReduceBase & other) delete
virtual std::string foedus::snapshot::MapReduceBase::to_string () const pure virtual
Expects "LogReducer-x", "LogMapper-y" etc.
Used only for logging/debugging.
Implemented in foedus::snapshot::LogReducer, and foedus::snapshot::LogMapper.
Referenced by join_thread(), and launch_thread().
Member Data Documentation
Engine* const foedus::snapshot::MapReduceBase::engine_ protected
Definition at line 71 of file mapreduce_base_impl.hpp.
Referenced by foedus::snapshot::LogMapper::handle_process(), foedus::snapshot::LogMapper::initialize_once(), foedus::snapshot::LogReducer::initialize_once(), and foedus::snapshot::LogReducer::LogReducer().
const uint16_t foedus::snapshot::MapReduceBase::id_ protected
Unique ID of this mapper or reducer.
Definition at line 74 of file mapreduce_base_impl.hpp.
Referenced by get_id(), foedus::snapshot::LogMapper::handle_process(), foedus::snapshot::operator<<(), foedus::snapshot::LogMapper::to_string(), and foedus::snapshot::LogReducer::to_string().
const uint16_t foedus::snapshot::MapReduceBase::numa_node_ protected
Definition at line 75 of file mapreduce_base_impl.hpp.
Referenced by get_numa_node(), foedus::snapshot::LogMapper::handle_process(), foedus::snapshot::LogMapper::initialize_once(), foedus::snapshot::LogReducer::initialize_once(), foedus::snapshot::LogReducer::LogReducer(), and foedus::snapshot::operator<<().
LogGleanerRef foedus::snapshot::MapReduceBase::parent_ protected
Definition at line 72 of file mapreduce_base_impl.hpp.
Referenced by check_cancelled(), get_parent(), foedus::snapshot::LogMapper::handle_process(), and foedus::snapshot::LogReducer::handle_process().
std::atomic<bool> foedus::snapshot::MapReduceBase::running_ protected
only for sanity check
Definition at line 77 of file mapreduce_base_impl.hpp.
std::thread foedus::snapshot::MapReduceBase::thread_ protected
Definition at line 79 of file mapreduce_base_impl.hpp.
Referenced by join_thread(), and launch_thread().
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/snapshot/mapreduce_base_impl.hpp
/home/shino/foedus_code/foedus-core/src/foedus/snapshot/mapreduce_base_impl.cpp