libfoedus-core: foedus::soc::SharedRendezvous Class Reference
foedus::soc::SharedRendezvous Class Reference final
FOEDUS Components » SOC and IPC
A one-time single-producer multiple-consumer event synchronization in shared memory for multiple processes.
Detailed Description
A one-time single-producer multiple-consumer event synchronization in shared memory for multiple processes.
Analogous to SharedMutex. This is a shared version of foedus::thread::Rendezvous.
Definition at line 34 of file shared_rendezvous.hpp.
#include <shared_rendezvous.hpp>
Public Member Functions
SharedRendezvous ()
~SharedRendezvous ()
SharedRendezvous (const SharedRendezvous &)=delete
SharedRendezvous & operator= (const SharedRendezvous &)=delete
void initialize ()
void uninitialize ()
bool is_initialized () const
bool is_signaled () const
returns whether the even has signaled.
bool is_signaled_weak () const
weak version without fence.
void wait ()
Block until the event happens.
bool wait_for (uint64_t timeout_nanosec)
Block until the event happens or the given period elapses.
void signal ()
Notify all waiters that the event has happened.
Constructor & Destructor Documentation
foedus::soc::SharedRendezvous::SharedRendezvous () inline
Definition at line 36 of file shared_rendezvous.hpp.
References initialize().
 : signaled_(false), initialized_(false), cond_() { initialize(); }
foedus::soc::SharedRendezvous::~SharedRendezvous () inline
Definition at line 37 of file shared_rendezvous.hpp.
References uninitialize().
 { uninitialize(); }
foedus::soc::SharedRendezvous::SharedRendezvous (const SharedRendezvous &) delete
Member Function Documentation
void foedus::soc::SharedRendezvous::initialize ()
Definition at line 27 of file shared_rendezvous.cpp.
References foedus::soc::SharedPolling::initialize(), and uninitialize().
Referenced by SharedRendezvous().
{
   uninitialize();
   signaled_ = false;
   initialized_ = true;
   cond_.initialize();
 }
bool foedus::soc::SharedRendezvous::is_initialized () const inline
Definition at line 45 of file shared_rendezvous.hpp.
Referenced by uninitialize().
 { return initialized_; }
bool foedus::soc::SharedRendezvous::is_signaled () const inline
returns whether the even has signaled.
Definition at line 48 of file shared_rendezvous.hpp.
References foedus::assorted::memory_fence_acquire().
Referenced by wait(), and wait_for().
{
     assorted::memory_fence_acquire();
     return signaled_;
   }
bool foedus::soc::SharedRendezvous::is_signaled_weak () const inline
weak version without fence.
Definition at line 53 of file shared_rendezvous.hpp.
Referenced by wait(), and wait_for().
 { return signaled_; }
SharedRendezvous& foedus::soc::SharedRendezvous::operator= (const SharedRendezvous &) delete
void foedus::soc::SharedRendezvous::signal ()
Notify all waiters that the event has happened.
There must be only one thread that might call this method, and it should call this only once. Otherwise, the behavior is undefined.
Definition at line 67 of file shared_rendezvous.cpp.
References foedus::soc::SharedPolling::signal().
{
   signaled_ = true;
   cond_.signal();
 }
void foedus::soc::SharedRendezvous::uninitialize ()
Definition at line 34 of file shared_rendezvous.cpp.
References is_initialized().
Referenced by initialize(), and ~SharedRendezvous().
{
   if (!is_initialized()) {
     return;
   }
 }
void foedus::soc::SharedRendezvous::wait ()
Block until the event happens.
Definition at line 40 of file shared_rendezvous.cpp.
References foedus::soc::SharedPolling::acquire_ticket(), ASSERT_ND, is_signaled(), is_signaled_weak(), and foedus::soc::SharedPolling::wait().
{
   if (is_signaled_weak()) {  // just an optimization.
     return;
   }
   uint64_t demand = cond_.acquire_ticket();
   if (is_signaled()) {
     return;
   }
   cond_.wait(demand);
   ASSERT_ND(is_signaled());
 }
bool foedus::soc::SharedRendezvous::wait_for (uint64_t timeout_nanosec)
Block until the event happens or the given period elapses.
Returns
whether the event happened by now.
Definition at line 53 of file shared_rendezvous.cpp.
References foedus::soc::SharedPolling::acquire_ticket(), ASSERT_ND, is_signaled(), is_signaled_weak(), and foedus::soc::SharedPolling::timedwait().
{
   if (is_signaled_weak()) {  // just an optimization.
     return true;
   }
   uint64_t demand = cond_.acquire_ticket();
   if (is_signaled()) {
     return true;
   }
   bool received = cond_.timedwait(demand, timeout_nanosec / 1000);
   ASSERT_ND(!received || is_signaled());
   return is_signaled();
 }
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/soc/shared_rendezvous.hpp
/home/shino/foedus_code/foedus-core/src/foedus/soc/shared_rendezvous.cpp