libfoedus-core: foedus::savepoint::SavepointManagerPimpl Class Reference
foedus::savepoint::SavepointManagerPimpl Class Reference final
FOEDUS Components » Savepoint Manager
Pimpl object of SavepointManager.
Detailed Description
Pimpl object of SavepointManager.
A private pimpl object for SavepointManager. Do not include this header from a client program unless you know what you are doing.
Definition at line 110 of file savepoint_manager_pimpl.hpp.
#include <savepoint_manager_pimpl.hpp>
Public Member Functions
SavepointManagerPimpl ()=delete
SavepointManagerPimpl (Engine *engine)
ErrorStack initialize_once () override
ErrorStack uninitialize_once () override
Epoch get_initial_current_epoch () const
Epoch get_initial_durable_epoch () const
Epoch get_earliest_epoch () const
Epoch get_saved_durable_epoch () const
snapshot::SnapshotId get_latest_snapshot_id () const
Epoch get_latest_snapshot_epoch () const
Epoch get_requested_durable_epoch () const
void update_shared_savepoint (const Savepoint &src)
LoggerSavepointInfo get_logger_savepoint (log::LoggerId logger_id)
ErrorStack take_savepoint (Epoch new_global_durable_epoch)
ErrorStack take_savepoint_after_snapshot (snapshot::SnapshotId new_snapshot_id, Epoch new_snapshot_epoch)
void savepoint_main ()
bool is_stop_requested ()
Public Member Functions inherited from foedus::DefaultInitializable
DefaultInitializable ()
virtual ~DefaultInitializable ()
DefaultInitializable (const DefaultInitializable &)=delete
DefaultInitializable & operator= (const DefaultInitializable &)=delete
ErrorStack initialize () override final
Typical implementation of Initializable::initialize() that provides initialize-once semantics.
ErrorStack uninitialize () override final
Typical implementation of Initializable::uninitialize() that provides uninitialize-once semantics.
bool is_initialized () const override final
Returns whether the object has been already initialized or not.
Public Member Functions inherited from foedus::Initializable
virtual ~Initializable ()
Public Attributes
Engine *const engine_
SavepointManagerControlBlock * control_block_
std::thread savepoint_thread_
The thread to take savepoints.
std::atomic< bool > savepoint_thread_stop_requested_
fs::Path savepoint_path_
Path of the savepoint file.
Savepoint savepoint_
The current progress of the entire engine.
Constructor & Destructor Documentation
foedus::savepoint::SavepointManagerPimpl::SavepointManagerPimpl () delete
foedus::savepoint::SavepointManagerPimpl::SavepointManagerPimpl (Engine * engine) inline explicit
Definition at line 113 of file savepoint_manager_pimpl.hpp.
 : engine_(engine) {}
Member Function Documentation
Epoch foedus::savepoint::SavepointManagerPimpl::get_earliest_epoch () const inline
Definition at line 119 of file savepoint_manager_pimpl.hpp.
References control_block_, and foedus::savepoint::SavepointManagerControlBlock::earliest_epoch_.
Referenced by foedus::savepoint::SavepointManager::get_earliest_epoch().
 { return Epoch(control_block_->earliest_epoch_); }
Epoch foedus::savepoint::SavepointManagerPimpl::get_initial_current_epoch () const inline
Definition at line 117 of file savepoint_manager_pimpl.hpp.
References control_block_, and foedus::savepoint::SavepointManagerControlBlock::initial_current_epoch_.
Referenced by foedus::savepoint::SavepointManager::get_initial_current_epoch().
 { return Epoch(control_block_->initial_current_epoch_); }
Epoch foedus::savepoint::SavepointManagerPimpl::get_initial_durable_epoch () const inline
Definition at line 118 of file savepoint_manager_pimpl.hpp.
References control_block_, and foedus::savepoint::SavepointManagerControlBlock::initial_durable_epoch_.
Referenced by foedus::savepoint::SavepointManager::get_initial_durable_epoch().
 { return Epoch(control_block_->initial_durable_epoch_); }
Epoch foedus::savepoint::SavepointManagerPimpl::get_latest_snapshot_epoch () const inline
Definition at line 124 of file savepoint_manager_pimpl.hpp.
References control_block_, foedus::savepoint::FixedSavepoint::latest_snapshot_epoch_, and foedus::savepoint::SavepointManagerControlBlock::savepoint_.
Referenced by foedus::savepoint::SavepointManager::get_latest_snapshot_epoch(), and take_savepoint_after_snapshot().
{
     return Epoch(control_block_->savepoint_.latest_snapshot_epoch_);
   }
snapshot::SnapshotId foedus::savepoint::SavepointManagerPimpl::get_latest_snapshot_id () const inline
Definition at line 121 of file savepoint_manager_pimpl.hpp.
References control_block_, foedus::savepoint::FixedSavepoint::latest_snapshot_id_, and foedus::savepoint::SavepointManagerControlBlock::savepoint_.
Referenced by foedus::savepoint::SavepointManager::get_latest_snapshot_id(), and take_savepoint_after_snapshot().
{
     return control_block_->savepoint_.latest_snapshot_id_;
   }
LoggerSavepointInfo foedus::savepoint::SavepointManagerPimpl::get_logger_savepoint (log::LoggerId logger_id)
Definition at line 151 of file savepoint_manager_pimpl.cpp.
References ASSERT_ND, control_block_, foedus::savepoint::FixedSavepoint::logger_info_, foedus::savepoint::SavepointManagerControlBlock::savepoint_, savepoint_, and foedus::savepoint::SavepointManagerControlBlock::savepoint_mutex_.
Referenced by foedus::savepoint::SavepointManager::get_logger_savepoint().
{
   // read with mutex to not see garbage
   soc::SharedMutexScope scope(&control_block_->savepoint_mutex_);
   ASSERT_ND(logger_id < control_block_->savepoint_.get_total_logger_count());
   return control_block_->savepoint_.logger_info_[logger_id];
 }
Epoch foedus::savepoint::SavepointManagerPimpl::get_requested_durable_epoch () const inline
Definition at line 127 of file savepoint_manager_pimpl.hpp.
References control_block_, and foedus::savepoint::SavepointManagerControlBlock::requested_durable_epoch_.
Referenced by savepoint_main(), and take_savepoint().
{
     return Epoch(control_block_->requested_durable_epoch_);
   }
Epoch foedus::savepoint::SavepointManagerPimpl::get_saved_durable_epoch () const inline
Definition at line 120 of file savepoint_manager_pimpl.hpp.
References control_block_, and foedus::savepoint::SavepointManagerControlBlock::saved_durable_epoch_.
Referenced by foedus::savepoint::SavepointManager::get_saved_durable_epoch(), and take_savepoint().
 { return Epoch(control_block_->saved_durable_epoch_); }
ErrorStack foedus::savepoint::SavepointManagerPimpl::initialize_once () override virtual
Implements foedus::DefaultInitializable.
Definition at line 37 of file savepoint_manager_pimpl.cpp.
References CHECK_ERROR, foedus::savepoint::Savepoint::consistent(), control_block_, foedus::savepoint::Savepoint::current_epoch_, foedus::savepoint::Savepoint::durable_epoch_, foedus::savepoint::SavepointManagerControlBlock::earliest_epoch_, foedus::savepoint::Savepoint::earliest_epoch_, engine_, ERROR_STACK, ERROR_STACK_MSG, foedus::fs::exists(), foedus::Engine::get_options(), foedus::soc::SocManager::get_shared_memory_repo(), foedus::Engine::get_soc_manager(), foedus::thread::ThreadOptions::group_count_, foedus::savepoint::SavepointManagerControlBlock::initial_current_epoch_, foedus::savepoint::SavepointManagerControlBlock::initial_durable_epoch_, foedus::savepoint::SavepointManagerControlBlock::initialize(), foedus::Engine::is_master(), foedus::kErrorCodeSpInconsistentSavepoint, foedus::kErrorCodeTimeout, foedus::kRetOk, foedus::externalize::Externalizable::load_from_file(), foedus::EngineOptions::log_, foedus::log::LogOptions::loggers_per_node_, foedus::savepoint::SavepointManagerControlBlock::master_initialized_, foedus::assorted::memory_fence_release(), foedus::savepoint::Savepoint::populate_empty(), foedus::savepoint::SavepointManagerControlBlock::requested_durable_epoch_, foedus::externalize::Externalizable::save_to_file(), foedus::savepoint::SavepointManagerControlBlock::saved_durable_epoch_, foedus::EngineOptions::savepoint_, savepoint_, savepoint_main(), foedus::savepoint::SavepointOptions::savepoint_path_, savepoint_path_, savepoint_thread_, savepoint_thread_stop_requested_, foedus::assorted::FixedString< MAXLEN, CHAR >::str(), foedus::EngineOptions::thread_, and update_shared_savepoint().
{
   control_block_ = engine_->get_soc_manager()->get_shared_memory_repo()->
     get_global_memory_anchors()->savepoint_manager_memory_;
   if (engine_->is_master()) {
     // Savepoint takes place only in master
     control_block_->initialize();
     savepoint_ = Savepoint();
     savepoint_path_ = fs::Path(engine_->get_options().savepoint_.savepoint_path_.str());
     LOG(INFO) << "Initializing SavepointManager.. path=" << savepoint_path_;
     auto logger_count = engine_->get_options().log_.loggers_per_node_
       * engine_->get_options().thread_.group_count_;
     if (fs::exists(savepoint_path_)) {
       LOG(INFO) << "Existing savepoint file found. Loading..";
       CHECK_ERROR(savepoint_.load_from_file(savepoint_path_));
       if (!savepoint_.consistent(logger_count)) {
         return ERROR_STACK(kErrorCodeSpInconsistentSavepoint);
       }
     } else {
       LOG(INFO) << "Savepoint file does not exist. No savepoint taken so far.";
       // Create an empty savepoint file now. This makes sure the directory entry for the file
       // exists.
       savepoint_.populate_empty(logger_count);
       CHECK_ERROR(savepoint_.save_to_file(savepoint_path_));
     }
     update_shared_savepoint(savepoint_);
     control_block_->initial_current_epoch_ = savepoint_.current_epoch_;
     control_block_->initial_durable_epoch_ = savepoint_.durable_epoch_;
     control_block_->earliest_epoch_ = savepoint_.earliest_epoch_;
     control_block_->saved_durable_epoch_ = savepoint_.durable_epoch_;
     control_block_->requested_durable_epoch_ = savepoint_.durable_epoch_;
     savepoint_thread_stop_requested_ = false;
     assorted::memory_fence_release();
     savepoint_thread_ = std::move(std::thread(&SavepointManagerPimpl::savepoint_main, this));
     control_block_->master_initialized_ = true;
   } else {
     // other engines wait for the master engine until it finishes the initialization of
     // relevant fields. Some of the following modules depend on these values.
     uint32_t sleep_cont = 0;
     while (control_block_->master_initialized_ == false) {
       std::this_thread::sleep_for(std::chrono::milliseconds(10));
       if (++sleep_cont > 1000ULL) {
         return ERROR_STACK_MSG(kErrorCodeTimeout, "Master engine couldn't load savepoint??");
       }
     }
     LOG(INFO) << "Okay, master-engine has finished loading initial savepoint.";
   }
   return kRetOk;
 }
bool foedus::savepoint::SavepointManagerPimpl::is_stop_requested () inline
Definition at line 143 of file savepoint_manager_pimpl.hpp.
References savepoint_thread_stop_requested_.
Referenced by savepoint_main().
 { return savepoint_thread_stop_requested_; }
void foedus::savepoint::SavepointManagerPimpl::savepoint_main ()
Definition at line 158 of file savepoint_manager_pimpl.cpp.
References foedus::soc::SharedPolling::acquire_ticket(), foedus::log::LogManager::announce_new_durable_global_epoch(), foedus::savepoint::Savepoint::assert_epoch_values(), COERCE_ERROR, control_block_, foedus::log::LogManager::copy_logger_states(), foedus::savepoint::Savepoint::current_epoch_, foedus::savepoint::Savepoint::durable_epoch_, foedus::log::MetaLogControlBlock::durable_offset_, foedus::savepoint::Savepoint::earliest_epoch_, engine_, foedus::xct::XctManager::get_current_global_epoch(), foedus::Engine::get_earliest_epoch(), foedus::soc::SharedMemoryRepo::get_global_memory_anchors(), foedus::Engine::get_log_manager(), get_requested_durable_epoch(), foedus::soc::SocManager::get_shared_memory_repo(), foedus::Engine::get_soc_manager(), foedus::Engine::get_xct_manager(), is_stop_requested(), foedus::Epoch::kEpochInvalid, foedus::snapshot::kNullSnapshotId, foedus::savepoint::Savepoint::latest_snapshot_epoch_, foedus::savepoint::FixedSavepoint::latest_snapshot_epoch_, foedus::savepoint::Savepoint::latest_snapshot_id_, foedus::savepoint::FixedSavepoint::latest_snapshot_id_, foedus::assorted::memory_fence_release(), foedus::savepoint::Savepoint::meta_log_durable_offset_, foedus::savepoint::Savepoint::meta_log_oldest_offset_, foedus::soc::GlobalMemoryAnchors::meta_logger_memory_, foedus::savepoint::SavepointManagerControlBlock::new_snapshot_epoch_, foedus::savepoint::SavepointManagerControlBlock::new_snapshot_id_, foedus::log::MetaLogControlBlock::oldest_offset_, foedus::savepoint::SavepointManagerControlBlock::requested_durable_epoch_, foedus::savepoint::SavepointManagerControlBlock::save_done_event_, foedus::externalize::Externalizable::save_to_file(), foedus::savepoint::SavepointManagerControlBlock::save_wakeup_, foedus::savepoint::SavepointManagerControlBlock::saved_durable_epoch_, foedus::savepoint::SavepointManagerControlBlock::savepoint_, savepoint_path_, foedus::soc::SharedPolling::signal(), foedus::soc::SharedPolling::timedwait(), update_shared_savepoint(), and foedus::Epoch::value().
Referenced by initialize_once().
{
   LOG(INFO) << "Savepoint thread has started.";
   while (!is_stop_requested()) {
     {
       uint64_t demand = control_block_->save_wakeup_.acquire_ticket();
       if (!is_stop_requested() &&
         control_block_->requested_durable_epoch_ == control_block_->saved_durable_epoch_ &&
         control_block_->new_snapshot_id_ == snapshot::kNullSnapshotId) {
         control_block_->save_wakeup_.timedwait(demand, 100000ULL);
       }
     }
     if (is_stop_requested()) {
       break;
     }
     if (control_block_->new_snapshot_id_ != snapshot::kNullSnapshotId ||
       control_block_->requested_durable_epoch_ != control_block_->saved_durable_epoch_) {
       Savepoint new_savepoint;
       new_savepoint.current_epoch_ = engine_->get_xct_manager()->get_current_global_epoch().value();
       Epoch new_durable_epoch = get_requested_durable_epoch();
       new_savepoint.durable_epoch_ = new_durable_epoch.value();
       new_savepoint.earliest_epoch_ = engine_->get_earliest_epoch().value();
       engine_->get_log_manager()->copy_logger_states(&new_savepoint);
       if (control_block_->new_snapshot_id_ != snapshot::kNullSnapshotId) {
         new_savepoint.latest_snapshot_id_ = control_block_->new_snapshot_id_;
         new_savepoint.latest_snapshot_epoch_ = control_block_->new_snapshot_epoch_;
         control_block_->new_snapshot_id_ = snapshot::kNullSnapshotId;
         control_block_->new_snapshot_epoch_ = Epoch::kEpochInvalid;
       } else {
         new_savepoint.latest_snapshot_id_ = control_block_->savepoint_.latest_snapshot_id_;
         new_savepoint.latest_snapshot_epoch_ = control_block_->savepoint_.latest_snapshot_epoch_;
       }
       log::MetaLogControlBlock* metalog_block = engine_->get_soc_manager()->get_shared_memory_repo()
         ->get_global_memory_anchors()->meta_logger_memory_;
       // TASK(Hideaki) Here, we should update oldest_offset_ by checking where the snapshot_epoch
       // ends. So far we don't update this, but metalog is anyway tiny, so isn't a big issue.
       new_savepoint.meta_log_oldest_offset_ = metalog_block->oldest_offset_;
       new_savepoint.meta_log_durable_offset_ = metalog_block->durable_offset_;
       new_savepoint.assert_epoch_values();
       VLOG(0) << "Writing a savepoint...";
       VLOG(1) << "Savepoint content=" << new_savepoint;
       COERCE_ERROR(new_savepoint.save_to_file(savepoint_path_));
       update_shared_savepoint(new_savepoint);  // also write to shared memory
       VLOG(1) << "Wrote a savepoint.";
       engine_->get_log_manager()->announce_new_durable_global_epoch(new_durable_epoch);
       control_block_->saved_durable_epoch_ = new_durable_epoch.value();
       assorted::memory_fence_release();
       control_block_->save_done_event_.signal();
     }
   }
   LOG(INFO) << "Savepoint thread has terminated.";
 }
ErrorStack foedus::savepoint::SavepointManagerPimpl::take_savepoint (Epoch new_global_durable_epoch)
Definition at line 102 of file savepoint_manager_pimpl.cpp.
References foedus::soc::SharedPolling::acquire_ticket(), control_block_, get_requested_durable_epoch(), get_saved_durable_epoch(), foedus::kRetOk, foedus::savepoint::SavepointManagerControlBlock::requested_durable_epoch_, foedus::savepoint::SavepointManagerControlBlock::save_done_event_, foedus::savepoint::SavepointManagerControlBlock::save_wakeup_, foedus::soc::SharedPolling::signal(), foedus::Epoch::value(), and foedus::soc::SharedPolling::wait().
Referenced by foedus::savepoint::SavepointManager::take_savepoint().
{
   while (get_saved_durable_epoch() < new_global_durable_epoch) {
     if (get_requested_durable_epoch() < new_global_durable_epoch) {
       if (get_requested_durable_epoch() < new_global_durable_epoch) {
         control_block_->requested_durable_epoch_ = new_global_durable_epoch.value();
         control_block_->save_wakeup_.signal();
       }
     }
     {
       uint64_t demand = control_block_->save_done_event_.acquire_ticket();
       if (get_saved_durable_epoch() >= new_global_durable_epoch) {
         break;
       }
       control_block_->save_done_event_.wait(demand);
     }
   }
   return kRetOk;
 }
ErrorStack foedus::savepoint::SavepointManagerPimpl::take_savepoint_after_snapshot (snapshot::SnapshotId new_snapshot_id, Epoch new_snapshot_epoch)
Definition at line 120 of file savepoint_manager_pimpl.cpp.
References foedus::soc::SharedPolling::acquire_ticket(), ASSERT_ND, control_block_, get_latest_snapshot_epoch(), get_latest_snapshot_id(), foedus::kRetOk, foedus::savepoint::SavepointManagerControlBlock::new_snapshot_epoch_, foedus::savepoint::SavepointManagerControlBlock::new_snapshot_id_, foedus::savepoint::SavepointManagerControlBlock::save_done_event_, foedus::savepoint::SavepointManagerControlBlock::save_wakeup_, foedus::soc::SharedPolling::signal(), foedus::Epoch::value(), and foedus::soc::SharedPolling::wait().
Referenced by foedus::savepoint::SavepointManager::take_savepoint_after_snapshot().
{
   while (get_latest_snapshot_id() != new_snapshot_id) {
     {
       control_block_->new_snapshot_id_ = new_snapshot_id;
       control_block_->new_snapshot_epoch_ = new_snapshot_epoch.value();
       control_block_->save_wakeup_.signal();
     }
     {
       uint64_t demand = control_block_->save_done_event_.acquire_ticket();
       if (get_latest_snapshot_id() != new_snapshot_id) {
         control_block_->save_done_event_.wait(demand);
       }
     }
   }
   ASSERT_ND(get_latest_snapshot_id() == new_snapshot_id);
   ASSERT_ND(get_latest_snapshot_epoch() == new_snapshot_epoch);
   return kRetOk;
 }
ErrorStack foedus::savepoint::SavepointManagerPimpl::uninitialize_once () override virtual
Implements foedus::DefaultInitializable.
Definition at line 86 of file savepoint_manager_pimpl.cpp.
References control_block_, engine_, foedus::Engine::is_master(), foedus::savepoint::SavepointManagerControlBlock::save_wakeup_, savepoint_thread_, savepoint_thread_stop_requested_, foedus::soc::SharedPolling::signal(), SUMMARIZE_ERROR_BATCH, and foedus::savepoint::SavepointManagerControlBlock::uninitialize().
{
   LOG(INFO) << "Uninitializing SavepointManager..";
   ErrorStackBatch batch;
   if (engine_->is_master()) {
     if (savepoint_thread_.joinable()) {
       {
         savepoint_thread_stop_requested_ = true;
         control_block_->save_wakeup_.signal();
       }
       savepoint_thread_.join();
     }
     control_block_->uninitialize();
   }
   return SUMMARIZE_ERROR_BATCH(batch);
 }
void foedus::savepoint::SavepointManagerPimpl::update_shared_savepoint (const Savepoint & src)
Definition at line 141 of file savepoint_manager_pimpl.cpp.
References control_block_, engine_, foedus::Engine::get_options(), foedus::thread::ThreadOptions::group_count_, foedus::EngineOptions::log_, foedus::log::LogOptions::loggers_per_node_, foedus::savepoint::SavepointManagerControlBlock::savepoint_, foedus::savepoint::SavepointManagerControlBlock::savepoint_mutex_, foedus::EngineOptions::thread_, and foedus::savepoint::FixedSavepoint::update().
Referenced by initialize_once(), and savepoint_main().
{
   // write with mutex to not let readers see garbage.
   // there is only one writer anyway, btw.
   soc::SharedMutexScope scope(&control_block_->savepoint_mutex_);
   control_block_->savepoint_.update(
     engine_->get_options().thread_.group_count_,
     engine_->get_options().log_.loggers_per_node_,
     src);
 }
Member Data Documentation
SavepointManagerControlBlock* foedus::savepoint::SavepointManagerPimpl::control_block_
Definition at line 138 of file savepoint_manager_pimpl.hpp.
Referenced by foedus::savepoint::SavepointManager::change_meta_logger_durable_offset(), get_earliest_epoch(), get_initial_current_epoch(), get_initial_durable_epoch(), get_latest_snapshot_epoch(), get_latest_snapshot_id(), get_logger_savepoint(), foedus::savepoint::SavepointManager::get_meta_logger_offsets(), get_requested_durable_epoch(), get_saved_durable_epoch(), initialize_once(), savepoint_main(), take_savepoint(), take_savepoint_after_snapshot(), uninitialize_once(), and update_shared_savepoint().
Engine* const foedus::savepoint::SavepointManagerPimpl::engine_
Definition at line 137 of file savepoint_manager_pimpl.hpp.
Referenced by initialize_once(), savepoint_main(), uninitialize_once(), and update_shared_savepoint().
Savepoint foedus::savepoint::SavepointManagerPimpl::savepoint_
The current progress of the entire engine.
Definition at line 156 of file savepoint_manager_pimpl.hpp.
Referenced by get_logger_savepoint(), and initialize_once().
fs::Path foedus::savepoint::SavepointManagerPimpl::savepoint_path_
Path of the savepoint file.
Definition at line 151 of file savepoint_manager_pimpl.hpp.
Referenced by initialize_once(), and savepoint_main().
std::thread foedus::savepoint::SavepointManagerPimpl::savepoint_thread_
The thread to take savepoints.
Definition at line 146 of file savepoint_manager_pimpl.hpp.
Referenced by initialize_once(), and uninitialize_once().
std::atomic<bool> foedus::savepoint::SavepointManagerPimpl::savepoint_thread_stop_requested_
Definition at line 148 of file savepoint_manager_pimpl.hpp.
Referenced by initialize_once(), is_stop_requested(), and uninitialize_once().
The documentation for this class was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/savepoint/savepoint_manager_pimpl.hpp
/home/shino/foedus_code/foedus-core/src/foedus/savepoint/savepoint_manager_pimpl.cpp