var hierarchy =
[
    [ "foedus::xct::AcquireAsyncRet", "namespacefoedus_1_1xct.html#structfoedus_1_1xct_1_1AcquireAsyncRet", null ],
    [ "foedus::snapshot::MergeSort::AdjustComparatorMasstree", "structfoedus_1_1snapshot_1_1MergeSort_1_1AdjustComparatorMasstree.html", null ],
    [ "foedus::memory::AlignedMemory", "classfoedus_1_1memory_1_1AlignedMemory.html", null ],
    [ "foedus::memory::AlignedMemorySlice", "structfoedus_1_1memory_1_1AlignedMemorySlice.html", null ],
    [ "foedus::storage::array::ArrayComposeContext", "classfoedus_1_1storage_1_1array_1_1ArrayComposeContext.html", null ],
    [ "foedus::storage::array::ArrayComposer", "classfoedus_1_1storage_1_1array_1_1ArrayComposer.html", null ],
    [ "foedus::storage::array::ArrayPage", "classfoedus_1_1storage_1_1array_1_1ArrayPage.html", null ],
    [ "foedus::storage::array::ArrayPartitioner", "classfoedus_1_1storage_1_1array_1_1ArrayPartitioner.html", null ],
    [ "foedus::storage::array::ArrayPartitionerData", "structfoedus_1_1storage_1_1array_1_1ArrayPartitionerData.html", null ],
    [ "foedus::storage::array::ArrayRange", "structfoedus_1_1storage_1_1array_1_1ArrayRange.html", null ],
    [ "foedus::storage::array::ArrayRootInfoPage", "namespacefoedus_1_1storage_1_1array.html#structfoedus_1_1storage_1_1array_1_1ArrayRootInfoPage", null ],
    [ "foedus::storage::array::ArrayStorageControlBlock", "structfoedus_1_1storage_1_1array_1_1ArrayStorageControlBlock.html", null ],
    [ "foedus::storage::array::ArrayStoragePimpl", "classfoedus_1_1storage_1_1array_1_1ArrayStoragePimpl.html", null ],
    [ "foedus::Attachable< CONTROL_BLOCK >", "classfoedus_1_1Attachable.html", [
      [ "foedus::storage::Storage< CONTROL_BLOCK >", "classfoedus_1_1storage_1_1Storage.html", null ]
    ] ],
    [ "foedus::Attachable< ArrayStorageControlBlock >", "classfoedus_1_1Attachable.html", [
      [ "foedus::storage::Storage< ArrayStorageControlBlock >", "classfoedus_1_1storage_1_1Storage.html", [
        [ "foedus::storage::array::ArrayStorage", "classfoedus_1_1storage_1_1array_1_1ArrayStorage.html", null ]
      ] ]
    ] ],
    [ "foedus::Attachable< HashStorageControlBlock >", "classfoedus_1_1Attachable.html", [
      [ "foedus::storage::hash::HashStoragePimpl", "classfoedus_1_1storage_1_1hash_1_1HashStoragePimpl.html", null ],
      [ "foedus::storage::Storage< HashStorageControlBlock >", "classfoedus_1_1storage_1_1Storage.html", [
        [ "foedus::storage::hash::HashStorage", "classfoedus_1_1storage_1_1hash_1_1HashStorage.html", null ]
      ] ]
    ] ],
    [ "foedus::Attachable< LoggerControlBlock >", "classfoedus_1_1Attachable.html", [
      [ "foedus::log::LoggerRef", "classfoedus_1_1log_1_1LoggerRef.html", [
        [ "foedus::log::Logger", "classfoedus_1_1log_1_1Logger.html", null ]
      ] ]
    ] ],
    [ "foedus::Attachable< LogGleanerControlBlock >", "classfoedus_1_1Attachable.html", [
      [ "foedus::snapshot::LogGleanerRef", "classfoedus_1_1snapshot_1_1LogGleanerRef.html", [
        [ "foedus::snapshot::LogGleaner", "classfoedus_1_1snapshot_1_1LogGleaner.html", null ]
      ] ]
    ] ],
    [ "foedus::Attachable< MasstreeStorageControlBlock >", "classfoedus_1_1Attachable.html", [
      [ "foedus::storage::masstree::MasstreeStoragePimpl", "classfoedus_1_1storage_1_1masstree_1_1MasstreeStoragePimpl.html", null ],
      [ "foedus::storage::Storage< MasstreeStorageControlBlock >", "classfoedus_1_1storage_1_1Storage.html", [
        [ "foedus::storage::masstree::MasstreeStorage", "classfoedus_1_1storage_1_1masstree_1_1MasstreeStorage.html", null ]
      ] ]
    ] ],
    [ "foedus::Attachable< MetaLogControlBlock >", "classfoedus_1_1Attachable.html", [
      [ "foedus::log::MetaLogBuffer", "classfoedus_1_1log_1_1MetaLogBuffer.html", null ]
    ] ],
    [ "foedus::Attachable< PartitionerMetadata >", "classfoedus_1_1Attachable.html", [
      [ "foedus::storage::Partitioner", "classfoedus_1_1storage_1_1Partitioner.html", null ]
    ] ],
    [ "foedus::Attachable< SequentialStorageControlBlock >", "classfoedus_1_1Attachable.html", [
      [ "foedus::storage::sequential::SequentialStoragePimpl", "classfoedus_1_1storage_1_1sequential_1_1SequentialStoragePimpl.html", null ],
      [ "foedus::storage::Storage< SequentialStorageControlBlock >", "classfoedus_1_1storage_1_1Storage.html", [
        [ "foedus::storage::sequential::SequentialStorage", "classfoedus_1_1storage_1_1sequential_1_1SequentialStorage.html", null ]
      ] ]
    ] ],
    [ "foedus::memory::AutoVolatilePageReleaseScope", "structfoedus_1_1memory_1_1AutoVolatilePageReleaseScope.html", null ],
    [ "foedus::assorted::BacktraceContext", "structfoedus_1_1assorted_1_1BacktraceContext.html", null ],
    [ "foedus::log::BaseLogType", "structfoedus_1_1log_1_1BaseLogType.html", [
      [ "foedus::log::EngineLogType", "structfoedus_1_1log_1_1EngineLogType.html", [
        [ "foedus::log::EpochMarkerLogType", "structfoedus_1_1log_1_1EpochMarkerLogType.html", null ]
      ] ],
      [ "foedus::log::FillerLogType", "structfoedus_1_1log_1_1FillerLogType.html", null ],
      [ "foedus::log::RecordLogType", "structfoedus_1_1log_1_1RecordLogType.html", [
        [ "foedus::storage::array::ArrayCommonUpdateLogType", "structfoedus_1_1storage_1_1array_1_1ArrayCommonUpdateLogType.html", [
          [ "foedus::storage::array::ArrayIncrementLogType", "structfoedus_1_1storage_1_1array_1_1ArrayIncrementLogType.html", null ],
          [ "foedus::storage::array::ArrayOverwriteLogType", "structfoedus_1_1storage_1_1array_1_1ArrayOverwriteLogType.html", null ]
        ] ],
        [ "foedus::storage::hash::HashCommonLogType", "structfoedus_1_1storage_1_1hash_1_1HashCommonLogType.html", [
          [ "foedus::storage::hash::HashDeleteLogType", "structfoedus_1_1storage_1_1hash_1_1HashDeleteLogType.html", null ],
          [ "foedus::storage::hash::HashInsertLogType", "structfoedus_1_1storage_1_1hash_1_1HashInsertLogType.html", null ],
          [ "foedus::storage::hash::HashOverwriteLogType", "structfoedus_1_1storage_1_1hash_1_1HashOverwriteLogType.html", null ],
          [ "foedus::storage::hash::HashUpdateLogType", "structfoedus_1_1storage_1_1hash_1_1HashUpdateLogType.html", null ]
        ] ],
        [ "foedus::storage::masstree::MasstreeCommonLogType", "structfoedus_1_1storage_1_1masstree_1_1MasstreeCommonLogType.html", [
          [ "foedus::storage::masstree::MasstreeDeleteLogType", "structfoedus_1_1storage_1_1masstree_1_1MasstreeDeleteLogType.html", null ],
          [ "foedus::storage::masstree::MasstreeInsertLogType", "structfoedus_1_1storage_1_1masstree_1_1MasstreeInsertLogType.html", null ],
          [ "foedus::storage::masstree::MasstreeOverwriteLogType", "structfoedus_1_1storage_1_1masstree_1_1MasstreeOverwriteLogType.html", null ],
          [ "foedus::storage::masstree::MasstreeUpdateLogType", "structfoedus_1_1storage_1_1masstree_1_1MasstreeUpdateLogType.html", null ]
        ] ],
        [ "foedus::storage::sequential::SequentialAppendLogType", "structfoedus_1_1storage_1_1sequential_1_1SequentialAppendLogType.html", null ]
      ] ],
      [ "foedus::log::StorageLogType", "structfoedus_1_1log_1_1StorageLogType.html", [
        [ "foedus::storage::array::ArrayCreateLogType", "structfoedus_1_1storage_1_1array_1_1ArrayCreateLogType.html", null ],
        [ "foedus::storage::CreateLogType", "structfoedus_1_1storage_1_1CreateLogType.html", null ],
        [ "foedus::storage::DropLogType", "structfoedus_1_1storage_1_1DropLogType.html", null ],
        [ "foedus::storage::hash::HashCreateLogType", "structfoedus_1_1storage_1_1hash_1_1HashCreateLogType.html", null ],
        [ "foedus::storage::masstree::MasstreeCreateLogType", "structfoedus_1_1storage_1_1masstree_1_1MasstreeCreateLogType.html", null ],
        [ "foedus::storage::sequential::SequentialCreateLogType", "structfoedus_1_1storage_1_1sequential_1_1SequentialCreateLogType.html", null ],
        [ "foedus::storage::sequential::SequentialTruncateLogType", "structfoedus_1_1storage_1_1sequential_1_1SequentialTruncateLogType.html", null ]
      ] ]
    ] ],
    [ "bitmask", "numa_8h.html#structbitmask", null ],
    [ "foedus::snapshot::BlockHeaderBase", "structfoedus_1_1snapshot_1_1BlockHeaderBase.html", [
      [ "foedus::snapshot::FillerBlockHeader", "structfoedus_1_1snapshot_1_1FillerBlockHeader.html", null ],
      [ "foedus::snapshot::FullBlockHeader", "structfoedus_1_1snapshot_1_1FullBlockHeader.html", null ]
    ] ],
    [ "foedus::storage::hash::BloomFilterFingerprint", "structfoedus_1_1storage_1_1hash_1_1BloomFilterFingerprint.html", null ],
    [ "foedus::cache::CacheBucket", "structfoedus_1_1cache_1_1CacheBucket.html", null ],
    [ "foedus::cache::CacheHashtable", "classfoedus_1_1cache_1_1CacheHashtable.html", null ],
    [ "foedus::cache::CacheOverflowEntry", "namespacefoedus_1_1cache.html#structfoedus_1_1cache_1_1CacheOverflowEntry", null ],
    [ "foedus::cache::CacheRefCount", "structfoedus_1_1cache_1_1CacheRefCount.html", null ],
    [ "foedus::soc::ChildEngineStatus", "structfoedus_1_1soc_1_1ChildEngineStatus.html", null ],
    [ "foedus::snapshot::ReducerBufferStatus::Components", "group__SNAPSHOT.html#structfoedus_1_1snapshot_1_1ReducerBufferStatus_1_1Components", null ],
    [ "foedus::xct::McsRwSimpleBlock::Self::Components", "structfoedus_1_1xct_1_1McsRwSimpleBlock.html#structfoedus_1_1xct_1_1McsRwSimpleBlock_1_1Self_1_1Components", null ],
    [ "foedus::xct::McsRwExtendedBlock::Field::Components", "structfoedus_1_1xct_1_1McsRwExtendedBlock.html#structfoedus_1_1xct_1_1McsRwExtendedBlock_1_1Field_1_1Components", null ],
    [ "foedus::storage::Composer::ComposeArguments", "group__STORAGE.html#structfoedus_1_1storage_1_1Composer_1_1ComposeArguments", null ],
    [ "foedus::storage::hash::ComposedBin", "group__HASH.html#structfoedus_1_1storage_1_1hash_1_1ComposedBin", null ],
    [ "foedus::storage::hash::ComposedBinsBuffer", "structfoedus_1_1storage_1_1hash_1_1ComposedBinsBuffer.html", null ],
    [ "foedus::storage::hash::ComposedBinsMergedStream", "structfoedus_1_1storage_1_1hash_1_1ComposedBinsMergedStream.html", null ],
    [ "foedus::storage::Composer", "classfoedus_1_1storage_1_1Composer.html", null ],
    [ "foedus::thread::ConditionVariable", "classfoedus_1_1thread_1_1ConditionVariable.html", null ],
    [ "foedus::assorted::ConstDiv", "structfoedus_1_1assorted_1_1ConstDiv.html", null ],
    [ "foedus::storage::Composer::ConstructRootArguments", "group__STORAGE.html#structfoedus_1_1storage_1_1Composer_1_1ConstructRootArguments", null ],
    [ "foedus::xct::CurrentLockList", "classfoedus_1_1xct_1_1CurrentLockList.html", null ],
    [ "foedus::xct::CurrentLockListIteratorForWriteSet", "structfoedus_1_1xct_1_1CurrentLockListIteratorForWriteSet.html", null ],
    [ "foedus::storage::array::ArrayPage::Data", "group__ARRAY.html#unionfoedus_1_1storage_1_1array_1_1ArrayPage_1_1Data", null ],
    [ "foedus::storage::hash::DataPageBloomFilter", "structfoedus_1_1storage_1_1hash_1_1DataPageBloomFilter.html", null ],
    [ "foedus::storage::Partitioner::DesignPartitionArguments", "group__STORAGE.html#structfoedus_1_1storage_1_1Partitioner_1_1DesignPartitionArguments", null ],
    [ "foedus::fs::DirectIoFile", "classfoedus_1_1fs_1_1DirectIoFile.html", null ],
    [ "foedus::memory::DivvyupPageGrabBatch", "classfoedus_1_1memory_1_1DivvyupPageGrabBatch.html", null ],
    [ "foedus::storage::Composer::DropResult", "structfoedus_1_1storage_1_1Composer_1_1DropResult.html", null ],
    [ "foedus::storage::Composer::DropVolatilesArguments", "structfoedus_1_1storage_1_1Composer_1_1DropVolatilesArguments.html", null ],
    [ "foedus::storage::DualPagePointer", "structfoedus_1_1storage_1_1DualPagePointer.html", null ],
    [ "foedus::assorted::DumbSpinlock", "classfoedus_1_1assorted_1_1DumbSpinlock.html", null ],
    [ "foedus::Epoch", "classfoedus_1_1Epoch.html", null ],
    [ "foedus::log::EpochHistory", "structfoedus_1_1log_1_1EpochHistory.html", null ],
    [ "foedus::ErrorStack", "classfoedus_1_1ErrorStack.html", null ],
    [ "foedus::ErrorStackBatch", "classfoedus_1_1ErrorStackBatch.html", null ],
    [ "foedus::cache::CacheHashtable::EvictArgs", "structfoedus_1_1cache_1_1CacheHashtable_1_1EvictArgs.html", null ],
    [ "foedus::externalize::Externalizable", "structfoedus_1_1externalize_1_1Externalizable.html", [
      [ "foedus::cache::CacheOptions", "structfoedus_1_1cache_1_1CacheOptions.html", null ],
      [ "foedus::debugging::DebuggingOptions", "structfoedus_1_1debugging_1_1DebuggingOptions.html", null ],
      [ "foedus::EngineOptions", "structfoedus_1_1EngineOptions.html", null ],
      [ "foedus::fs::DeviceEmulationOptions", "structfoedus_1_1fs_1_1DeviceEmulationOptions.html", null ],
      [ "foedus::log::LogOptions", "structfoedus_1_1log_1_1LogOptions.html", null ],
      [ "foedus::memory::MemoryOptions", "structfoedus_1_1memory_1_1MemoryOptions.html", null ],
      [ "foedus::proc::ProcOptions", "structfoedus_1_1proc_1_1ProcOptions.html", null ],
      [ "foedus::restart::RestartOptions", "structfoedus_1_1restart_1_1RestartOptions.html", null ],
      [ "foedus::savepoint::Savepoint", "structfoedus_1_1savepoint_1_1Savepoint.html", null ],
      [ "foedus::savepoint::SavepointOptions", "structfoedus_1_1savepoint_1_1SavepointOptions.html", null ],
      [ "foedus::snapshot::SnapshotMetadata", "structfoedus_1_1snapshot_1_1SnapshotMetadata.html", null ],
      [ "foedus::snapshot::SnapshotOptions", "structfoedus_1_1snapshot_1_1SnapshotOptions.html", null ],
      [ "foedus::soc::SocOptions", "structfoedus_1_1soc_1_1SocOptions.html", null ],
      [ "foedus::storage::MetadataSerializer", "structfoedus_1_1storage_1_1MetadataSerializer.html", [
        [ "foedus::storage::array::ArrayMetadataSerializer", "structfoedus_1_1storage_1_1array_1_1ArrayMetadataSerializer.html", null ],
        [ "foedus::storage::hash::HashMetadataSerializer", "structfoedus_1_1storage_1_1hash_1_1HashMetadataSerializer.html", null ],
        [ "foedus::storage::masstree::MasstreeMetadataSerializer", "structfoedus_1_1storage_1_1masstree_1_1MasstreeMetadataSerializer.html", null ],
        [ "foedus::storage::sequential::SequentialMetadataSerializer", "structfoedus_1_1storage_1_1sequential_1_1SequentialMetadataSerializer.html", null ]
      ] ],
      [ "foedus::storage::StorageOptions", "structfoedus_1_1storage_1_1StorageOptions.html", null ],
      [ "foedus::thread::ThreadOptions", "structfoedus_1_1thread_1_1ThreadOptions.html", null ],
      [ "foedus::xct::XctOptions", "structfoedus_1_1xct_1_1XctOptions.html", null ]
    ] ],
    [ "foedus::storage::masstree::MasstreeComposeContext::FenceAndPointer", "group__MASSTREE.html#structfoedus_1_1storage_1_1masstree_1_1MasstreeComposeContext_1_1FenceAndPointer", null ],
    [ "foedus::xct::McsRwExtendedBlock::Field", "structfoedus_1_1xct_1_1McsRwExtendedBlock.html#unionfoedus_1_1xct_1_1McsRwExtendedBlock_1_1Field", null ],
    [ "foedus::fs::FileStatus", "structfoedus_1_1fs_1_1FileStatus.html", null ],
    [ "foedus::storage::masstree::MasstreeBorderPage::FindKeyForReserveResult", "structfoedus_1_1storage_1_1masstree_1_1MasstreeBorderPage_1_1FindKeyForReserveResult.html", null ],
    [ "foedus::FixedErrorStack", "classfoedus_1_1FixedErrorStack.html", null ],
    [ "foedus::savepoint::FixedSavepoint", "structfoedus_1_1savepoint_1_1FixedSavepoint.html", null ],
    [ "foedus::assorted::FixedString< MAXLEN, CHAR >", "classfoedus_1_1assorted_1_1FixedString.html", null ],
    [ "foedus::assorted::FixedString< 124 >", "classfoedus_1_1assorted_1_1FixedString.html", null ],
    [ "foedus::assorted::FixedString< 252 >", "classfoedus_1_1assorted_1_1FixedString.html", null ],
    [ "foedus::assorted::FixedString< 508 >", "classfoedus_1_1assorted_1_1FixedString.html", null ],
    [ "foedus::assorted::FixedString< 60 >", "classfoedus_1_1assorted_1_1FixedString.html", null ],
    [ "foedus::assorted::BacktraceContext::GlibcBacktraceInfo", "structfoedus_1_1assorted_1_1BacktraceContext_1_1GlibcBacktraceInfo.html", null ],
    [ "foedus::soc::GlobalMemoryAnchors", "structfoedus_1_1soc_1_1GlobalMemoryAnchors.html", null ],
    [ "foedus::memory::GlobalVolatilePageResolver", "structfoedus_1_1memory_1_1GlobalVolatilePageResolver.html", null ],
    [ "foedus::thread::GrabFreeVolatilePagesScope", "classfoedus_1_1thread_1_1GrabFreeVolatilePagesScope.html", null ],
    [ "foedus::snapshot::MergeSort::GroupifyResult", "structfoedus_1_1snapshot_1_1MergeSort_1_1GroupifyResult.html", null ],
    [ "foedus::storage::hash::HashBinRange", "structfoedus_1_1storage_1_1hash_1_1HashBinRange.html", null ],
    [ "foedus::storage::hash::HashCombo", "structfoedus_1_1storage_1_1hash_1_1HashCombo.html", null ],
    [ "foedus::storage::hash::HashComposeContext", "classfoedus_1_1storage_1_1hash_1_1HashComposeContext.html", null ],
    [ "foedus::storage::hash::HashComposedBinsPage", "group__HASH.html#structfoedus_1_1storage_1_1hash_1_1HashComposedBinsPage", null ],
    [ "foedus::storage::hash::HashComposer", "classfoedus_1_1storage_1_1hash_1_1HashComposer.html", null ],
    [ "foedus::storage::hash::HashDataPage", "classfoedus_1_1storage_1_1hash_1_1HashDataPage.html", null ],
    [ "foedus::cache::HashFunc", "structfoedus_1_1cache_1_1HashFunc.html", null ],
    [ "foedus::storage::hash::HashIntermediatePage", "classfoedus_1_1storage_1_1hash_1_1HashIntermediatePage.html", null ],
    [ "foedus::storage::hash::HashPartitioner", "classfoedus_1_1storage_1_1hash_1_1HashPartitioner.html", null ],
    [ "foedus::storage::hash::HashPartitionerData", "structfoedus_1_1storage_1_1hash_1_1HashPartitionerData.html", null ],
    [ "foedus::storage::hash::HashStorageControlBlock", "structfoedus_1_1storage_1_1hash_1_1HashStorageControlBlock.html", null ],
    [ "foedus::storage::hash::HashTmpBin", "classfoedus_1_1storage_1_1hash_1_1HashTmpBin.html", null ],
    [ "foedus::storage::sequential::HeadPagePointer", "group__SEQUENTIAL.html#structfoedus_1_1storage_1_1sequential_1_1HeadPagePointer", null ],
    [ "foedus::assorted::Hex", "structfoedus_1_1assorted_1_1Hex.html", null ],
    [ "foedus::assorted::HexString", "structfoedus_1_1assorted_1_1HexString.html", null ],
    [ "foedus::storage::masstree::HighFence", "structfoedus_1_1storage_1_1masstree_1_1HighFence.html", null ],
    [ "foedus::thread::ImpersonateSession", "structfoedus_1_1thread_1_1ImpersonateSession.html", null ],
    [ "foedus::xct::InCommitEpochGuard", "structfoedus_1_1xct_1_1InCommitEpochGuard.html", null ],
    [ "foedus::Initializable", "classfoedus_1_1Initializable.html", [
      [ "foedus::DefaultInitializable", "classfoedus_1_1DefaultInitializable.html", [
        [ "foedus::cache::CacheManager", "classfoedus_1_1cache_1_1CacheManager.html", null ],
        [ "foedus::cache::CacheManagerPimpl", "classfoedus_1_1cache_1_1CacheManagerPimpl.html", null ],
        [ "foedus::cache::SnapshotFileSet", "classfoedus_1_1cache_1_1SnapshotFileSet.html", null ],
        [ "foedus::debugging::DebuggingSupports", "classfoedus_1_1debugging_1_1DebuggingSupports.html", null ],
        [ "foedus::EnginePimpl", "classfoedus_1_1EnginePimpl.html", null ],
        [ "foedus::log::Logger", "classfoedus_1_1log_1_1Logger.html", null ],
        [ "foedus::log::LogManagerPimpl", "classfoedus_1_1log_1_1LogManagerPimpl.html", null ],
        [ "foedus::log::MetaLogger", "classfoedus_1_1log_1_1MetaLogger.html", null ],
        [ "foedus::log::ThreadLogBuffer", "classfoedus_1_1log_1_1ThreadLogBuffer.html", null ],
        [ "foedus::memory::EngineMemory", "classfoedus_1_1memory_1_1EngineMemory.html", null ],
        [ "foedus::memory::NumaCoreMemory", "classfoedus_1_1memory_1_1NumaCoreMemory.html", null ],
        [ "foedus::memory::NumaNodeMemory", "classfoedus_1_1memory_1_1NumaNodeMemory.html", null ],
        [ "foedus::memory::PagePoolPimpl", "classfoedus_1_1memory_1_1PagePoolPimpl.html", null ],
        [ "foedus::proc::ProcManagerPimpl", "classfoedus_1_1proc_1_1ProcManagerPimpl.html", null ],
        [ "foedus::restart::RestartManagerPimpl", "classfoedus_1_1restart_1_1RestartManagerPimpl.html", null ],
        [ "foedus::savepoint::SavepointManagerPimpl", "classfoedus_1_1savepoint_1_1SavepointManagerPimpl.html", null ],
        [ "foedus::snapshot::MapReduceBase", "classfoedus_1_1snapshot_1_1MapReduceBase.html", [
          [ "foedus::snapshot::LogMapper", "classfoedus_1_1snapshot_1_1LogMapper.html", null ],
          [ "foedus::snapshot::LogReducer", "classfoedus_1_1snapshot_1_1LogReducer.html", null ]
        ] ],
        [ "foedus::snapshot::MergeSort", "classfoedus_1_1snapshot_1_1MergeSort.html", null ],
        [ "foedus::snapshot::SnapshotManagerPimpl", "classfoedus_1_1snapshot_1_1SnapshotManagerPimpl.html", null ],
        [ "foedus::soc::SocManagerPimpl", "classfoedus_1_1soc_1_1SocManagerPimpl.html", null ],
        [ "foedus::storage::StorageManagerPimpl", "classfoedus_1_1storage_1_1StorageManagerPimpl.html", null ],
        [ "foedus::thread::ThreadGroup", "classfoedus_1_1thread_1_1ThreadGroup.html", null ],
        [ "foedus::thread::ThreadPimpl", "classfoedus_1_1thread_1_1ThreadPimpl.html", null ],
        [ "foedus::thread::ThreadPoolPimpl", "classfoedus_1_1thread_1_1ThreadPoolPimpl.html", null ],
        [ "foedus::xct::XctManagerPimpl", "classfoedus_1_1xct_1_1XctManagerPimpl.html", null ]
      ] ],
      [ "foedus::Engine", "classfoedus_1_1Engine.html", null ],
      [ "foedus::log::LogManager", "classfoedus_1_1log_1_1LogManager.html", null ],
      [ "foedus::memory::PagePool", "classfoedus_1_1memory_1_1PagePool.html", null ],
      [ "foedus::proc::ProcManager", "classfoedus_1_1proc_1_1ProcManager.html", null ],
      [ "foedus::restart::RestartManager", "classfoedus_1_1restart_1_1RestartManager.html", null ],
      [ "foedus::savepoint::SavepointManager", "classfoedus_1_1savepoint_1_1SavepointManager.html", null ],
      [ "foedus::snapshot::SnapshotManager", "classfoedus_1_1snapshot_1_1SnapshotManager.html", null ],
      [ "foedus::soc::SocManager", "classfoedus_1_1soc_1_1SocManager.html", null ],
      [ "foedus::storage::StorageManager", "classfoedus_1_1storage_1_1StorageManager.html", null ],
      [ "foedus::thread::Thread", "classfoedus_1_1thread_1_1Thread.html", null ],
      [ "foedus::thread::ThreadPool", "classfoedus_1_1thread_1_1ThreadPool.html", null ],
      [ "foedus::xct::XctManager", "classfoedus_1_1xct_1_1XctManager.html", null ]
    ] ],
    [ "foedus::snapshot::MergeSort::InputStatus", "structfoedus_1_1snapshot_1_1MergeSort_1_1InputStatus.html", null ],
    [ "foedus::storage::hash::IntermediateRoute", "unionfoedus_1_1storage_1_1hash_1_1IntermediateRoute.html", null ],
    [ "foedus::xct::LockEntry::LessThan", "structfoedus_1_1xct_1_1LockEntry_1_1LessThan.html", null ],
    [ "foedus::xct::SysxctLockEntry::LessThan", "structfoedus_1_1xct_1_1SysxctLockEntry_1_1LessThan.html", null ],
    [ "foedus::assorted::BacktraceContext::LibBacktraceInfo", "structfoedus_1_1assorted_1_1BacktraceContext.html#structfoedus_1_1assorted_1_1BacktraceContext_1_1LibBacktraceInfo", null ],
    [ "foedus::memory::LocalPageResolver", "structfoedus_1_1memory_1_1LocalPageResolver.html", null ],
    [ "foedus::xct::LockableXctId", "structfoedus_1_1xct_1_1LockableXctId.html", null ],
    [ "foedus::xct::LockEntry", "structfoedus_1_1xct_1_1LockEntry.html", null ],
    [ "foedus::xct::LockFreeReadXctAccess", "structfoedus_1_1xct_1_1LockFreeReadXctAccess.html", null ],
    [ "foedus::xct::LockFreeWriteXctAccess", "structfoedus_1_1xct_1_1LockFreeWriteXctAccess.html", null ],
    [ "foedus::snapshot::LogBuffer", "structfoedus_1_1snapshot_1_1LogBuffer.html", null ],
    [ "foedus::log::LoggerControlBlock", "structfoedus_1_1log_1_1LoggerControlBlock.html", null ],
    [ "foedus::savepoint::LoggerSavepointInfo", "namespacefoedus_1_1savepoint.html#structfoedus_1_1savepoint_1_1LoggerSavepointInfo", null ],
    [ "foedus::snapshot::LogGleanerControlBlock", "structfoedus_1_1snapshot_1_1LogGleanerControlBlock.html", null ],
    [ "foedus::snapshot::LogGleanerResource", "structfoedus_1_1snapshot_1_1LogGleanerResource.html", null ],
    [ "foedus::log::LogHeader", "structfoedus_1_1log_1_1LogHeader.html", null ],
    [ "foedus::log::LogManagerControlBlock", "structfoedus_1_1log_1_1LogManagerControlBlock.html", null ],
    [ "foedus::log::LogRange", "structfoedus_1_1log_1_1LogRange.html", null ],
    [ "foedus::snapshot::LogReducerControlBlock", "structfoedus_1_1snapshot_1_1LogReducerControlBlock.html", null ],
    [ "foedus::snapshot::LogReducerRef", "classfoedus_1_1snapshot_1_1LogReducerRef.html", null ],
    [ "foedus::storage::array::LookupRoute", "unionfoedus_1_1storage_1_1array_1_1LookupRoute.html", null ],
    [ "foedus::storage::array::LookupRouteFinder", "classfoedus_1_1storage_1_1array_1_1LookupRouteFinder.html", null ],
    [ "foedus::storage::masstree::MasstreeComposeContext", "classfoedus_1_1storage_1_1masstree_1_1MasstreeComposeContext.html", null ],
    [ "foedus::storage::masstree::MasstreeComposer", "classfoedus_1_1storage_1_1masstree_1_1MasstreeComposer.html", null ],
    [ "foedus::storage::masstree::MasstreeCursor", "classfoedus_1_1storage_1_1masstree_1_1MasstreeCursor.html", null ],
    [ "foedus::storage::masstree::MasstreeIntermediatePointerIterator", "structfoedus_1_1storage_1_1masstree_1_1MasstreeIntermediatePointerIterator.html", null ],
    [ "foedus::storage::masstree::MasstreePage", "classfoedus_1_1storage_1_1masstree_1_1MasstreePage.html", [
      [ "foedus::storage::masstree::MasstreeBorderPage", "classfoedus_1_1storage_1_1masstree_1_1MasstreeBorderPage.html", null ],
      [ "foedus::storage::masstree::MasstreeIntermediatePage", "classfoedus_1_1storage_1_1masstree_1_1MasstreeIntermediatePage.html", null ]
    ] ],
    [ "foedus::storage::masstree::MasstreePartitioner", "classfoedus_1_1storage_1_1masstree_1_1MasstreePartitioner.html", null ],
    [ "foedus::storage::masstree::MasstreePartitionerData", "structfoedus_1_1storage_1_1masstree_1_1MasstreePartitionerData.html", null ],
    [ "foedus::storage::masstree::MasstreeStorageControlBlock", "structfoedus_1_1storage_1_1masstree_1_1MasstreeStorageControlBlock.html", null ],
    [ "foedus::soc::MasterEngineStatus", "structfoedus_1_1soc_1_1MasterEngineStatus.html", null ],
    [ "foedus::xct::McsAdaptorConcept< RW_BLOCK >", "classfoedus_1_1xct_1_1McsAdaptorConcept.html", null ],
    [ "foedus::xct::McsImpl< ADAPTOR, RW_BLOCK >", "classfoedus_1_1xct_1_1McsImpl.html", null ],
    [ "foedus::xct::McsImpl< ADAPTOR, McsRwExtendedBlock >", "classfoedus_1_1xct_1_1McsImpl_3_01ADAPTOR_00_01McsRwExtendedBlock_01_4.html", null ],
    [ "foedus::xct::McsImpl< ADAPTOR, McsRwSimpleBlock >", "classfoedus_1_1xct_1_1McsImpl_3_01ADAPTOR_00_01McsRwSimpleBlock_01_4.html", null ],
    [ "foedus::xct::McsMockAdaptor< RW_BLOCK >", "classfoedus_1_1xct_1_1McsMockAdaptor.html", null ],
    [ "foedus::xct::McsMockContext< RW_BLOCK >", "structfoedus_1_1xct_1_1McsMockContext.html", null ],
    [ "foedus::xct::McsMockDataPage", "structfoedus_1_1xct_1_1McsMockDataPage.html", null ],
    [ "foedus::xct::McsMockNode< RW_BLOCK >", "structfoedus_1_1xct_1_1McsMockNode.html", null ],
    [ "foedus::xct::McsMockThread< RW_BLOCK >", "structfoedus_1_1xct_1_1McsMockThread.html", null ],
    [ "foedus::xct::McsOwnerlessLockScope", "classfoedus_1_1xct_1_1McsOwnerlessLockScope.html", null ],
    [ "foedus::xct::McsRwAsyncMapping", "structfoedus_1_1xct_1_1McsRwAsyncMapping.html", null ],
    [ "foedus::xct::McsRwExtendedBlock", "structfoedus_1_1xct_1_1McsRwExtendedBlock.html", null ],
    [ "foedus::xct::McsRwLock", "structfoedus_1_1xct_1_1McsRwLock.html", null ],
    [ "foedus::xct::McsRwSimpleBlock", "structfoedus_1_1xct_1_1McsRwSimpleBlock.html", null ],
    [ "foedus::xct::McsWwBlock", "structfoedus_1_1xct_1_1McsWwBlock.html", null ],
    [ "foedus::xct::McsWwBlockData", "structfoedus_1_1xct_1_1McsWwBlockData.html", null ],
    [ "foedus::xct::McsWwImpl< ADAPTOR >", "classfoedus_1_1xct_1_1McsWwImpl.html", null ],
    [ "foedus::xct::McsWwLock", "structfoedus_1_1xct_1_1McsWwLock.html", null ],
    [ "foedus::xct::McsWwOwnerlessImpl", "classfoedus_1_1xct_1_1McsWwOwnerlessImpl.html", null ],
    [ "foedus::storage::Metadata", "structfoedus_1_1storage_1_1Metadata.html", [
      [ "foedus::storage::array::ArrayMetadata", "structfoedus_1_1storage_1_1array_1_1ArrayMetadata.html", null ],
      [ "foedus::storage::hash::HashMetadata", "structfoedus_1_1storage_1_1hash_1_1HashMetadata.html", null ],
      [ "foedus::storage::masstree::MasstreeMetadata", "structfoedus_1_1storage_1_1masstree_1_1MasstreeMetadata.html", null ],
      [ "foedus::storage::sequential::SequentialMetadata", "structfoedus_1_1storage_1_1sequential_1_1SequentialMetadata.html", null ]
    ] ],
    [ "foedus::log::MetaLogControlBlock", "structfoedus_1_1log_1_1MetaLogControlBlock.html", null ],
    [ "foedus::storage::masstree::MasstreeIntermediatePage::MiniPage", "structfoedus_1_1storage_1_1masstree_1_1MasstreeIntermediatePage_1_1MiniPage.html", null ],
    [ "foedus::EnginePimpl::ModulePtr", "structfoedus_1_1EnginePimpl_1_1ModulePtr.html", null ],
    [ "nodemask_t", "numa_8h.html#structnodemask__t", null ],
    [ "foedus::soc::NodeMemoryAnchors", "structfoedus_1_1soc_1_1NodeMemoryAnchors.html", null ],
    [ "foedus::memory::NumaNodeMemoryRef", "classfoedus_1_1memory_1_1NumaNodeMemoryRef.html", null ],
    [ "foedus::thread::NumaThreadScope", "structfoedus_1_1thread_1_1NumaThreadScope.html", null ],
    [ "foedus::memory::PagePoolOffsetAndEpochChunk::OffsetAndEpoch", "group__MEMORY.html#structfoedus_1_1memory_1_1PagePoolOffsetAndEpochChunk_1_1OffsetAndEpoch", null ],
    [ "foedus::log::ThreadLogBuffer::OffsetRange", "structfoedus_1_1log_1_1ThreadLogBuffer_1_1OffsetRange.html", null ],
    [ "foedus::storage::masstree::OwnerSamples", "structfoedus_1_1storage_1_1masstree_1_1OwnerSamples.html", null ],
    [ "foedus::storage::Page", "structfoedus_1_1storage_1_1Page.html", null ],
    [ "foedus::storage::masstree::MasstreeComposeContext::PageBoundaryInfo", "structfoedus_1_1storage_1_1masstree_1_1MasstreeComposeContext_1_1PageBoundaryInfo.html", null ],
    [ "foedus::storage::masstree::MasstreeComposeContext::PageBoundarySort", "structfoedus_1_1storage_1_1masstree_1_1MasstreeComposeContext_1_1PageBoundarySort.html", null ],
    [ "foedus::xct::PageComparator", "structfoedus_1_1xct_1_1PageComparator.html", null ],
    [ "foedus::storage::PageHeader", "structfoedus_1_1storage_1_1PageHeader.html", null ],
    [ "foedus::memory::PagePoolControlBlock", "structfoedus_1_1memory_1_1PagePoolControlBlock.html", null ],
    [ "foedus::memory::PagePoolOffsetAndEpochChunk", "classfoedus_1_1memory_1_1PagePoolOffsetAndEpochChunk.html", null ],
    [ "foedus::memory::PagePoolOffsetChunk", "classfoedus_1_1memory_1_1PagePoolOffsetChunk.html", null ],
    [ "foedus::memory::PagePoolOffsetDynamicChunk", "classfoedus_1_1memory_1_1PagePoolOffsetDynamicChunk.html", null ],
    [ "foedus::memory::PageReleaseBatch", "classfoedus_1_1memory_1_1PageReleaseBatch.html", null ],
    [ "foedus::storage::PageVersion", "structfoedus_1_1storage_1_1PageVersion.html", null ],
    [ "foedus::xct::PageVersionAccess", "structfoedus_1_1xct_1_1PageVersionAccess.html", null ],
    [ "foedus::storage::PageVersionStatus", "structfoedus_1_1storage_1_1PageVersionStatus.html", null ],
    [ "foedus::debugging::DebuggingSupports::PapiCounters", "group__DEBUGGING.html#structfoedus_1_1debugging_1_1DebuggingSupports_1_1PapiCounters", null ],
    [ "foedus::storage::Partitioner::PartitionBatchArguments", "group__STORAGE.html#structfoedus_1_1storage_1_1Partitioner_1_1PartitionBatchArguments", null ],
    [ "foedus::storage::PartitionerMetadata", "structfoedus_1_1storage_1_1PartitionerMetadata.html", null ],
    [ "foedus::fs::Path", "classfoedus_1_1fs_1_1Path.html", null ],
    [ "foedus::storage::masstree::MasstreeComposeContext::PathLevel", "structfoedus_1_1storage_1_1masstree_1_1MasstreeComposeContext_1_1PathLevel.html", null ],
    [ "foedus::storage::masstree::MasstreeStorage::PeekBoundariesArguments", "group__MASSTREE.html#structfoedus_1_1storage_1_1masstree_1_1MasstreeStorage_1_1PeekBoundariesArguments", null ],
    [ "foedus::snapshot::LogGleanerResource::PerNodeResource", "structfoedus_1_1snapshot_1_1LogGleanerResource_1_1PerNodeResource.html", null ],
    [ "foedus::xct::PointerAccess", "structfoedus_1_1xct_1_1PointerAccess.html", null ],
    [ "foedus::storage::sequential::SequentialStoragePimpl::PointerPage", "group__SEQUENTIAL.html#structfoedus_1_1storage_1_1sequential_1_1SequentialStoragePimpl_1_1PointerPage", null ],
    [ "foedus::snapshot::MergeSort::PositionEntry", "structfoedus_1_1snapshot_1_1MergeSort_1_1PositionEntry.html", null ],
    [ "foedus::assorted::ProbCounter", "structfoedus_1_1assorted_1_1ProbCounter.html", null ],
    [ "foedus::proc::ProcArguments", "group__PROC.html#structfoedus_1_1proc_1_1ProcArguments", null ],
    [ "foedus::proc::ProcManagerControlBlock", "structfoedus_1_1proc_1_1ProcManagerControlBlock.html", null ],
    [ "foedus::assorted::ProtectedBoundary", "structfoedus_1_1assorted_1_1ProtectedBoundary.html", null ],
    [ "foedus::debugging::RdtscWatch", "classfoedus_1_1debugging_1_1RdtscWatch.html", null ],
    [ "foedus::storage::hash::HashTmpBin::Record", "structfoedus_1_1storage_1_1hash_1_1HashTmpBin_1_1Record.html", null ],
    [ "foedus::storage::Record", "structfoedus_1_1storage_1_1Record.html", null ],
    [ "foedus::storage::masstree::MasstreeCommonLogType::RecordAddresses", "group__MASSTREE.html#structfoedus_1_1storage_1_1masstree_1_1MasstreeCommonLogType_1_1RecordAddresses", null ],
    [ "foedus::storage::hash::RecordLocation", "structfoedus_1_1storage_1_1hash_1_1RecordLocation.html", null ],
    [ "foedus::storage::masstree::RecordLocation", "structfoedus_1_1storage_1_1masstree_1_1RecordLocation.html", null ],
    [ "foedus::xct::RecordXctAccess", "structfoedus_1_1xct_1_1RecordXctAccess.html", [
      [ "foedus::xct::ReadXctAccess", "structfoedus_1_1xct_1_1ReadXctAccess.html", null ],
      [ "foedus::xct::WriteXctAccess", "structfoedus_1_1xct_1_1WriteXctAccess.html", null ]
    ] ],
    [ "foedus::snapshot::ReducerBufferStatus", "unionfoedus_1_1snapshot_1_1ReducerBufferStatus.html", null ],
    [ "foedus::thread::Rendezvous", "classfoedus_1_1thread_1_1Rendezvous.html", null ],
    [ "foedus::restart::RestartManagerControlBlock", "structfoedus_1_1restart_1_1RestartManagerControlBlock.html", null ],
    [ "foedus::xct::RetrospectiveLockList", "classfoedus_1_1xct_1_1RetrospectiveLockList.html", null ],
    [ "foedus::storage::sequential::SequentialComposer::RootInfoPage", "group__SEQUENTIAL.html#structfoedus_1_1storage_1_1sequential_1_1SequentialComposer_1_1RootInfoPage", null ],
    [ "foedus::memory::RoundRobinPageGrabBatch", "classfoedus_1_1memory_1_1RoundRobinPageGrabBatch.html", null ],
    [ "foedus::storage::masstree::MasstreeCursor::Route", "structfoedus_1_1storage_1_1masstree_1_1MasstreeCursor_1_1Route.html", null ],
    [ "foedus::xct::RwLockableXctId", "structfoedus_1_1xct_1_1RwLockableXctId.html", null ],
    [ "foedus::savepoint::SavepointManagerControlBlock", "structfoedus_1_1savepoint_1_1SavepointManagerControlBlock.html", null ],
    [ "foedus::memory::ScopedNumaPreferred", "structfoedus_1_1memory_1_1ScopedNumaPreferred.html", null ],
    [ "foedus::xct::McsRwSimpleBlock::Self", "structfoedus_1_1xct_1_1McsRwSimpleBlock.html#unionfoedus_1_1xct_1_1McsRwSimpleBlock_1_1Self", null ],
    [ "foedus::storage::sequential::SequentialComposer", "classfoedus_1_1storage_1_1sequential_1_1SequentialComposer.html", null ],
    [ "foedus::storage::sequential::SequentialCursor", "classfoedus_1_1storage_1_1sequential_1_1SequentialCursor.html", null ],
    [ "foedus::storage::sequential::SequentialPage", "classfoedus_1_1storage_1_1sequential_1_1SequentialPage.html", null ],
    [ "foedus::storage::sequential::SequentialPartitioner", "classfoedus_1_1storage_1_1sequential_1_1SequentialPartitioner.html", null ],
    [ "foedus::storage::sequential::SequentialRecordBatch", "structfoedus_1_1storage_1_1sequential_1_1SequentialRecordBatch.html", null ],
    [ "foedus::storage::sequential::SequentialRecordIterator", "classfoedus_1_1storage_1_1sequential_1_1SequentialRecordIterator.html", null ],
    [ "foedus::storage::sequential::SequentialRootPage", "classfoedus_1_1storage_1_1sequential_1_1SequentialRootPage.html", null ],
    [ "foedus::storage::sequential::SequentialStorageControlBlock", "structfoedus_1_1storage_1_1sequential_1_1SequentialStorageControlBlock.html", null ],
    [ "foedus::soc::SharedCond", "classfoedus_1_1soc_1_1SharedCond.html", null ],
    [ "foedus::proc::ProcManagerPimpl::SharedData", "structfoedus_1_1proc_1_1ProcManagerPimpl_1_1SharedData.html", null ],
    [ "foedus::memory::SharedMemory", "classfoedus_1_1memory_1_1SharedMemory.html", null ],
    [ "foedus::soc::SharedMemoryRepo", "classfoedus_1_1soc_1_1SharedMemoryRepo.html", null ],
    [ "foedus::soc::SharedMutex", "classfoedus_1_1soc_1_1SharedMutex.html", null ],
    [ "foedus::soc::SharedMutexScope", "classfoedus_1_1soc_1_1SharedMutexScope.html", null ],
    [ "foedus::soc::SharedPolling", "classfoedus_1_1soc_1_1SharedPolling.html", null ],
    [ "foedus::soc::SharedRendezvous", "classfoedus_1_1soc_1_1SharedRendezvous.html", null ],
    [ "foedus::storage::hash::HashDataPage::Slot", "structfoedus_1_1storage_1_1hash_1_1HashDataPage_1_1Slot.html", null ],
    [ "foedus::storage::masstree::MasstreeBorderPage::Slot", "structfoedus_1_1storage_1_1masstree_1_1MasstreeBorderPage_1_1Slot.html", null ],
    [ "foedus::storage::masstree::MasstreeBorderPage::SlotLengthPart", "group__MASSTREE.html#structfoedus_1_1storage_1_1masstree_1_1MasstreeBorderPage_1_1SlotLengthPart", null ],
    [ "foedus::storage::masstree::MasstreeBorderPage::SlotLengthUnion", "group__MASSTREE.html#unionfoedus_1_1storage_1_1masstree_1_1MasstreeBorderPage_1_1SlotLengthUnion", null ],
    [ "foedus::memory::NumaCoreMemory::SmallThreadLocalMemoryPieces", "group__MEMHIERARCHY.html#structfoedus_1_1memory_1_1NumaCoreMemory_1_1SmallThreadLocalMemoryPieces", null ],
    [ "foedus::snapshot::Snapshot", "structfoedus_1_1snapshot_1_1Snapshot.html", null ],
    [ "foedus::snapshot::SnapshotManagerControlBlock", "structfoedus_1_1snapshot_1_1SnapshotManagerControlBlock.html", null ],
    [ "foedus::storage::Metadata::SnapshotThresholds", "structfoedus_1_1storage_1_1Metadata_1_1SnapshotThresholds.html", null ],
    [ "foedus::snapshot::SnapshotWriter", "classfoedus_1_1snapshot_1_1SnapshotWriter.html", null ],
    [ "foedus::storage::Partitioner::SortBatchArguments", "group__STORAGE.html#structfoedus_1_1storage_1_1Partitioner_1_1SortBatchArguments", null ],
    [ "foedus::snapshot::SortedBuffer", "classfoedus_1_1snapshot_1_1SortedBuffer.html", [
      [ "foedus::snapshot::DumpFileSortedBuffer", "classfoedus_1_1snapshot_1_1DumpFileSortedBuffer.html", null ],
      [ "foedus::snapshot::InMemorySortedBuffer", "classfoedus_1_1snapshot_1_1InMemorySortedBuffer.html", null ]
    ] ],
    [ "foedus::storage::hash::SortEntry", "structfoedus_1_1storage_1_1hash_1_1SortEntry.html", null ],
    [ "foedus::snapshot::MergeSort::SortEntry", "structfoedus_1_1snapshot_1_1MergeSort_1_1SortEntry.html", null ],
    [ "foedus::storage::array::SortEntry", "structfoedus_1_1storage_1_1array_1_1SortEntry.html", null ],
    [ "foedus::storage::masstree::SortEntry", "structfoedus_1_1storage_1_1masstree_1_1SortEntry.html", null ],
    [ "foedus::fs::SpaceInfo", "structfoedus_1_1fs_1_1SpaceInfo.html", null ],
    [ "foedus::assorted::SpinlockStat", "structfoedus_1_1assorted_1_1SpinlockStat.html", null ],
    [ "foedus::storage::masstree::SplitBorder::SplitStrategy", "group__MASSTREE.html#structfoedus_1_1storage_1_1masstree_1_1SplitBorder_1_1SplitStrategy", null ],
    [ "foedus::storage::masstree::SplitIntermediate::SplitStrategy", "group__MASSTREE.html#structfoedus_1_1storage_1_1masstree_1_1SplitIntermediate_1_1SplitStrategy", null ],
    [ "foedus::cache::CacheHashtable::Stat", "group__CACHE.html#structfoedus_1_1cache_1_1CacheHashtable_1_1Stat", null ],
    [ "foedus::memory::PagePool::Stat", "group__MEMORY.html#structfoedus_1_1memory_1_1PagePool_1_1Stat", null ],
    [ "foedus::thread::StoppableThread", "classfoedus_1_1thread_1_1StoppableThread.html", null ],
    [ "foedus::debugging::StopWatch", "classfoedus_1_1debugging_1_1StopWatch.html", null ],
    [ "foedus::storage::StorageControlBlock", "structfoedus_1_1storage_1_1StorageControlBlock.html", null ],
    [ "foedus::storage::StorageManagerControlBlock", "structfoedus_1_1storage_1_1StorageManagerControlBlock.html", null ],
    [ "foedus::storage::sequential::StreamStatus", "structfoedus_1_1storage_1_1sequential_1_1StreamStatus.html", null ],
    [ "foedus::xct::SysxctFunctor", "structfoedus_1_1xct_1_1SysxctFunctor.html", [
      [ "foedus::storage::hash::ReserveRecords", "structfoedus_1_1storage_1_1hash_1_1ReserveRecords.html", null ],
      [ "foedus::storage::masstree::Adopt", "structfoedus_1_1storage_1_1masstree_1_1Adopt.html", null ],
      [ "foedus::storage::masstree::GrowFirstLayerRoot", "structfoedus_1_1storage_1_1masstree_1_1GrowFirstLayerRoot.html", null ],
      [ "foedus::storage::masstree::GrowNonFirstLayerRoot", "structfoedus_1_1storage_1_1masstree_1_1GrowNonFirstLayerRoot.html", null ],
      [ "foedus::storage::masstree::ReserveRecords", "structfoedus_1_1storage_1_1masstree_1_1ReserveRecords.html", null ],
      [ "foedus::storage::masstree::SplitBorder", "structfoedus_1_1storage_1_1masstree_1_1SplitBorder.html", null ],
      [ "foedus::storage::masstree::SplitIntermediate", "structfoedus_1_1storage_1_1masstree_1_1SplitIntermediate.html", null ]
    ] ],
    [ "foedus::xct::SysxctLockEntry", "structfoedus_1_1xct_1_1SysxctLockEntry.html", null ],
    [ "foedus::xct::SysxctLockList", "classfoedus_1_1xct_1_1SysxctLockList.html", null ],
    [ "foedus::xct::SysxctWorkspace", "structfoedus_1_1xct_1_1SysxctWorkspace.html", null ],
    [ "foedus::thread::ThreadControlBlock", "structfoedus_1_1thread_1_1ThreadControlBlock.html", null ],
    [ "foedus::log::ThreadEpockMark", "structfoedus_1_1log_1_1ThreadEpockMark.html", null ],
    [ "foedus::thread::ThreadGroupRef", "classfoedus_1_1thread_1_1ThreadGroupRef.html", null ],
    [ "foedus::log::ThreadLogBufferMeta", "structfoedus_1_1log_1_1ThreadLogBufferMeta.html", null ],
    [ "foedus::soc::ThreadMemoryAnchors", "structfoedus_1_1soc_1_1ThreadMemoryAnchors.html", null ],
    [ "foedus::thread::ThreadPimplCllReleaseAllFunctor", "structfoedus_1_1thread_1_1ThreadPimplCllReleaseAllFunctor.html", null ],
    [ "foedus::thread::ThreadPimplMcsAdaptor< RW_BLOCK >", "classfoedus_1_1thread_1_1ThreadPimplMcsAdaptor.html", null ],
    [ "foedus::thread::ThreadRef", "classfoedus_1_1thread_1_1ThreadRef.html", null ],
    [ "foedus::externalize::TinyxmlGetter< T >", "structfoedus_1_1externalize_1_1TinyxmlGetter.html", null ],
    [ "foedus::externalize::TinyxmlGetter< assorted::FixedString< MAXLEN, CHAR > >", "structfoedus_1_1externalize_1_1TinyxmlGetter_3_01assorted_1_1FixedString_3_01MAXLEN_00_01CHAR_01_4_01_4.html", null ],
    [ "foedus::externalize::TinyxmlGetter< bool >", "structfoedus_1_1externalize_1_1TinyxmlGetter_3_01bool_01_4.html", null ],
    [ "foedus::externalize::TinyxmlGetter< double >", "structfoedus_1_1externalize_1_1TinyxmlGetter_3_01double_01_4.html", null ],
    [ "foedus::externalize::TinyxmlGetter< float >", "structfoedus_1_1externalize_1_1TinyxmlGetter_3_01float_01_4.html", null ],
    [ "foedus::externalize::TinyxmlGetter< int16_t >", "structfoedus_1_1externalize_1_1TinyxmlGetter_3_01int16__t_01_4.html", null ],
    [ "foedus::externalize::TinyxmlGetter< int32_t >", "structfoedus_1_1externalize_1_1TinyxmlGetter_3_01int32__t_01_4.html", null ],
    [ "foedus::externalize::TinyxmlGetter< int64_t >", "structfoedus_1_1externalize_1_1TinyxmlGetter_3_01int64__t_01_4.html", null ],
    [ "foedus::externalize::TinyxmlGetter< int8_t >", "structfoedus_1_1externalize_1_1TinyxmlGetter_3_01int8__t_01_4.html", null ],
    [ "foedus::externalize::TinyxmlGetter< std::string >", "structfoedus_1_1externalize_1_1TinyxmlGetter_3_01std_1_1string_01_4.html", null ],
    [ "foedus::externalize::TinyxmlGetter< uint16_t >", "structfoedus_1_1externalize_1_1TinyxmlGetter_3_01uint16__t_01_4.html", null ],
    [ "foedus::externalize::TinyxmlGetter< uint32_t >", "structfoedus_1_1externalize_1_1TinyxmlGetter_3_01uint32__t_01_4.html", null ],
    [ "foedus::externalize::TinyxmlGetter< uint64_t >", "structfoedus_1_1externalize_1_1TinyxmlGetter_3_01uint64__t_01_4.html", null ],
    [ "foedus::externalize::TinyxmlGetter< uint8_t >", "structfoedus_1_1externalize_1_1TinyxmlGetter_3_01uint8__t_01_4.html", null ],
    [ "foedus::externalize::TinyxmlSetter< T >", "structfoedus_1_1externalize_1_1TinyxmlSetter.html", null ],
    [ "foedus::externalize::TinyxmlSetter< assorted::FixedString< MAXLEN, CHAR > >", "structfoedus_1_1externalize_1_1TinyxmlSetter_3_01assorted_1_1FixedString_3_01MAXLEN_00_01CHAR_01_4_01_4.html", null ],
    [ "foedus::externalize::TinyxmlSetter< std::string >", "structfoedus_1_1externalize_1_1TinyxmlSetter_3_01std_1_1string_01_4.html", null ],
    [ "foedus::storage::hash::TmpSnashotPage", "structfoedus_1_1storage_1_1hash_1_1TmpSnashotPage.html", null ],
    [ "foedus::assorted::Top", "structfoedus_1_1assorted_1_1Top.html", null ],
    [ "foedus::xct::TrackMovedRecordResult", "structfoedus_1_1xct_1_1TrackMovedRecordResult.html", null ],
    [ "foedus::assorted::UniformRandom", "classfoedus_1_1assorted_1_1UniformRandom.html", null ],
    [ "foedus::UninitializeGuard", "classfoedus_1_1UninitializeGuard.html", null ],
    [ "foedus::storage::VolatilePageInitArguments", "group__STORAGE.html#structfoedus_1_1storage_1_1VolatilePageInitArguments", null ],
    [ "foedus::storage::VolatilePagePointer", "structfoedus_1_1storage_1_1VolatilePagePointer.html", null ],
    [ "foedus::xct::Xct", "classfoedus_1_1xct_1_1Xct.html", null ],
    [ "foedus::xct::XctId", "structfoedus_1_1xct_1_1XctId.html", null ],
    [ "foedus::xct::XctManagerControlBlock", "structfoedus_1_1xct_1_1XctManagerControlBlock.html", null ],
    [ "foedus::assorted::ZipfianRandom", "classfoedus_1_1assorted_1_1ZipfianRandom.html", null ]
];