var namespacefoedus =
[
    [ "assorted", "namespacefoedus_1_1assorted.html", "namespacefoedus_1_1assorted" ],
    [ "cache", "namespacefoedus_1_1cache.html", "namespacefoedus_1_1cache" ],
    [ "debugging", "namespacefoedus_1_1debugging.html", "namespacefoedus_1_1debugging" ],
    [ "externalize", "namespacefoedus_1_1externalize.html", "namespacefoedus_1_1externalize" ],
    [ "fs", "namespacefoedus_1_1fs.html", "namespacefoedus_1_1fs" ],
    [ "log", "namespacefoedus_1_1log.html", "namespacefoedus_1_1log" ],
    [ "memory", "namespacefoedus_1_1memory.html", "namespacefoedus_1_1memory" ],
    [ "proc", "namespacefoedus_1_1proc.html", "namespacefoedus_1_1proc" ],
    [ "restart", "namespacefoedus_1_1restart.html", "namespacefoedus_1_1restart" ],
    [ "savepoint", "namespacefoedus_1_1savepoint.html", "namespacefoedus_1_1savepoint" ],
    [ "snapshot", "namespacefoedus_1_1snapshot.html", "namespacefoedus_1_1snapshot" ],
    [ "soc", "namespacefoedus_1_1soc.html", "namespacefoedus_1_1soc" ],
    [ "storage", "namespacefoedus_1_1storage.html", "namespacefoedus_1_1storage" ],
    [ "thread", "namespacefoedus_1_1thread.html", "namespacefoedus_1_1thread" ],
    [ "xct", "namespacefoedus_1_1xct.html", "namespacefoedus_1_1xct" ],
    [ "Attachable", "classfoedus_1_1Attachable.html", "classfoedus_1_1Attachable" ],
    [ "DefaultInitializable", "classfoedus_1_1DefaultInitializable.html", "classfoedus_1_1DefaultInitializable" ],
    [ "Engine", "classfoedus_1_1Engine.html", "classfoedus_1_1Engine" ],
    [ "EngineOptions", "structfoedus_1_1EngineOptions.html", "structfoedus_1_1EngineOptions" ],
    [ "EnginePimpl", "classfoedus_1_1EnginePimpl.html", "classfoedus_1_1EnginePimpl" ],
    [ "Epoch", "classfoedus_1_1Epoch.html", "classfoedus_1_1Epoch" ],
    [ "ErrorStack", "classfoedus_1_1ErrorStack.html", "classfoedus_1_1ErrorStack" ],
    [ "ErrorStackBatch", "classfoedus_1_1ErrorStackBatch.html", "classfoedus_1_1ErrorStackBatch" ],
    [ "FixedErrorStack", "classfoedus_1_1FixedErrorStack.html", "classfoedus_1_1FixedErrorStack" ],
    [ "Initializable", "classfoedus_1_1Initializable.html", "classfoedus_1_1Initializable" ],
    [ "UninitializeGuard", "classfoedus_1_1UninitializeGuard.html", "classfoedus_1_1UninitializeGuard" ]
];