var namespacefoedus_1_1storage =
[
    [ "array", "namespacefoedus_1_1storage_1_1array.html", "namespacefoedus_1_1storage_1_1array" ],
    [ "hash", "namespacefoedus_1_1storage_1_1hash.html", "namespacefoedus_1_1storage_1_1hash" ],
    [ "masstree", "namespacefoedus_1_1storage_1_1masstree.html", "namespacefoedus_1_1storage_1_1masstree" ],
    [ "sequential", "namespacefoedus_1_1storage_1_1sequential.html", "namespacefoedus_1_1storage_1_1sequential" ],
    [ "Composer", "classfoedus_1_1storage_1_1Composer.html", "classfoedus_1_1storage_1_1Composer" ],
    [ "CreateLogType", "structfoedus_1_1storage_1_1CreateLogType.html", "structfoedus_1_1storage_1_1CreateLogType" ],
    [ "DropLogType", "structfoedus_1_1storage_1_1DropLogType.html", "structfoedus_1_1storage_1_1DropLogType" ],
    [ "DualPagePointer", "structfoedus_1_1storage_1_1DualPagePointer.html", "structfoedus_1_1storage_1_1DualPagePointer" ],
    [ "Metadata", "structfoedus_1_1storage_1_1Metadata.html", "structfoedus_1_1storage_1_1Metadata" ],
    [ "MetadataSerializer", "structfoedus_1_1storage_1_1MetadataSerializer.html", "structfoedus_1_1storage_1_1MetadataSerializer" ],
    [ "Page", "structfoedus_1_1storage_1_1Page.html", "structfoedus_1_1storage_1_1Page" ],
    [ "PageHeader", "structfoedus_1_1storage_1_1PageHeader.html", "structfoedus_1_1storage_1_1PageHeader" ],
    [ "PageVersion", "structfoedus_1_1storage_1_1PageVersion.html", "structfoedus_1_1storage_1_1PageVersion" ],
    [ "PageVersionStatus", "structfoedus_1_1storage_1_1PageVersionStatus.html", "structfoedus_1_1storage_1_1PageVersionStatus" ],
    [ "Partitioner", "classfoedus_1_1storage_1_1Partitioner.html", "classfoedus_1_1storage_1_1Partitioner" ],
    [ "PartitionerMetadata", "structfoedus_1_1storage_1_1PartitionerMetadata.html", "structfoedus_1_1storage_1_1PartitionerMetadata" ],
    [ "Record", "structfoedus_1_1storage_1_1Record.html", "structfoedus_1_1storage_1_1Record" ],
    [ "Storage", "classfoedus_1_1storage_1_1Storage.html", "classfoedus_1_1storage_1_1Storage" ],
    [ "StorageControlBlock", "structfoedus_1_1storage_1_1StorageControlBlock.html", "structfoedus_1_1storage_1_1StorageControlBlock" ],
    [ "StorageManager", "classfoedus_1_1storage_1_1StorageManager.html", "classfoedus_1_1storage_1_1StorageManager" ],
    [ "StorageManagerControlBlock", "structfoedus_1_1storage_1_1StorageManagerControlBlock.html", "structfoedus_1_1storage_1_1StorageManagerControlBlock" ],
    [ "StorageManagerPimpl", "classfoedus_1_1storage_1_1StorageManagerPimpl.html", "classfoedus_1_1storage_1_1StorageManagerPimpl" ],
    [ "StorageOptions", "structfoedus_1_1storage_1_1StorageOptions.html", "structfoedus_1_1storage_1_1StorageOptions" ],
    [ "VolatilePageInitArguments", "group__STORAGE.html#structfoedus_1_1storage_1_1VolatilePageInitArguments", "group__STORAGE_structfoedus_1_1storage_1_1VolatilePageInitArguments" ],
    [ "VolatilePagePointer", "structfoedus_1_1storage_1_1VolatilePagePointer.html", "structfoedus_1_1storage_1_1VolatilePagePointer" ]
];