libfoedus-core: foedus::storage::masstree::ReserveRecords Struct Reference
foedus::storage::masstree::ReserveRecords Struct Reference final
FOEDUS Components » Storage Manager » Masstree Storage
A system transaction to reserve a physical record(s) in a border page.
Detailed Description
A system transaction to reserve a physical record(s) in a border page.
See also
Physical-only, short-living system transactions.
A record insertion happens in two steps:
During Execution: Physically inserts a deleted record for the key in the border page.
During Commit: Logically flips the delete-bit and installs the payload.
This system transaction does the former.
This does nothing and returns kErrorCodeOk in the following cases:
The page turns out to already contain a satisfying physical record for the key.
The page turns out to be already moved.
The page turns out to need page-split to accomodate the record.
When the 2nd or 3rd case (or 1st case with too-short payload space) happens, the caller will do something else (e.g. split/follow-foster) and retry.
Locks taken in this sysxct (in order of taking):
Page-lock of the target page.
Record-lock of an existing, matching record. Only when we have to expand the record.
So far this sysxct installs only one physical record at a time. TASK(Hideaki): Probably it helps by batching several records.
Definition at line 57 of file masstree_reserve_impl.hpp.
#include <masstree_reserve_impl.hpp>
Public Member Functions
ReserveRecords (thread::Thread *context, MasstreeBorderPage *target, KeySlice slice, KeyLength remainder_length, const void *suffix, PayloadLength payload_count, bool should_aggresively_create_next_layer, SlotIndex hint_check_from)
virtual ErrorCode run (xct::SysxctWorkspace *sysxct_workspace) override
Execute the system transaction.
Public Attributes
thread::Thread *const context_
Thread context.
MasstreeBorderPage *const target_
The page to install a new physical record.
const KeySlice slice_
The slice of the key.
const void *const suffix_
Suffix of the key.
const KeyLength remainder_length_
Length of the remainder.
const PayloadLength payload_count_
Minimal required length of the payload.
const SlotIndex hint_check_from_
The in-page location from which this sysxct will look for matching records.
const bool should_aggresively_create_next_layer_
When we CAN create a next layer for the new record, whether to make it a next-layer from the beginning, or make it as a usual record first.
bool out_split_needed_
[Out]
Constructor & Destructor Documentation
foedus::storage::masstree::ReserveRecords::ReserveRecords (thread::Thread * context, MasstreeBorderPage * target, KeySlice slice, KeyLength remainder_length, const void * suffix, PayloadLength payload_count, bool should_aggresively_create_next_layer, SlotIndex hint_check_from) inline
Definition at line 91 of file masstree_reserve_impl.hpp.
     : xct::SysxctFunctor(),
       context_(context),
       target_(target),
       slice_(slice),
       suffix_(suffix),
       remainder_length_(remainder_length),
       payload_count_(payload_count),
       hint_check_from_(hint_check_from),
       should_aggresively_create_next_layer_(should_aggresively_create_next_layer),
       out_split_needed_(false) {
   }
Member Function Documentation
ErrorCode foedus::storage::masstree::ReserveRecords::run (xct::SysxctWorkspace * sysxct_workspace) override virtual
Execute the system transaction.
You should override this method.
Implements foedus::xct::SysxctFunctor.
Definition at line 55 of file masstree_reserve_impl.cpp.
References foedus::storage::masstree::allocate_new_border_page(), foedus::storage::masstree::MasstreeBorderPage::assert_entries(), ASSERT_ND, foedus::storage::masstree::MasstreeBorderPage::can_accomodate(), CHECK_ERROR_CODE, context_, foedus::storage::masstree::MasstreeBorderPage::does_point_to_layer(), foedus::storage::masstree::MasstreeBorderPage::find_key_for_reserve(), foedus::storage::masstree::get_initial_xid(), foedus::storage::masstree::MasstreePage::get_key_count(), foedus::storage::masstree::MasstreePage::get_layer(), foedus::thread::Thread::get_local_volatile_page_resolver(), foedus::storage::masstree::MasstreeBorderPage::get_max_payload_length(), foedus::storage::masstree::MasstreeBorderPage::get_next_layer(), foedus::thread::Thread::get_numa_node(), foedus::storage::masstree::MasstreeBorderPage::get_owner_id(), foedus::thread::Thread::get_thread_memory(), foedus::storage::masstree::MasstreePage::get_volatile_page_id(), foedus::memory::NumaCoreMemory::grab_free_volatile_page(), foedus::storage::masstree::MasstreePage::header(), hint_check_from_, foedus::storage::masstree::MasstreePage::increment_key_count(), foedus::storage::masstree::MasstreeBorderPage::initialize_as_layer_root_physical(), foedus::storage::masstree::MasstreeBorderPage::initialize_volatile_page(), foedus::storage::masstree::MasstreePage::is_locked(), foedus::storage::masstree::MasstreePage::is_moved(), foedus::storage::masstree::MasstreePage::is_retired(), foedus::storage::masstree::kBorderPageMaxSlots, foedus::storage::masstree::MasstreeBorderPage::kConflictingLocalRecord, foedus::kErrorCodeMemoryNoFreePages, foedus::kErrorCodeOk, foedus::storage::masstree::MasstreeBorderPage::kExactMatchLayerPointer, foedus::storage::masstree::MasstreeBorderPage::kExactMatchLocalRecord, foedus::storage::masstree::kInfimumSlice, foedus::storage::masstree::MasstreeBorderPage::kNotFound, foedus::storage::masstree::kSupremumSlice, foedus::assorted::memory_fence_release(), out_split_needed_, foedus::storage::PageHeader::page_id_, payload_count_, remainder_length_, foedus::storage::masstree::MasstreeBorderPage::reserve_initially_next_layer(), foedus::storage::masstree::MasstreeBorderPage::reserve_record_space(), foedus::memory::LocalPageResolver::resolve_offset_newpage(), foedus::storage::VolatilePagePointer::set(), should_aggresively_create_next_layer_, slice_, foedus::storage::PageHeader::snapshot_, foedus::storage::DualPagePointer::snapshot_pointer_, foedus::storage::PageHeader::storage_id_, suffix_, foedus::thread::Thread::sysxct_page_lock(), foedus::thread::Thread::sysxct_record_lock(), target_, foedus::storage::masstree::MasstreeBorderPage::try_expand_record_in_page_physical(), and foedus::storage::DualPagePointer::volatile_pointer_.
{
   out_split_needed_ = false;
   ASSERT_ND(!should_aggresively_create_next_layer_ || remainder_length_ > sizeof(KeySlice));
   ASSERT_ND(!target_->header().snapshot_);
   CHECK_ERROR_CODE(context_->sysxct_page_lock(sysxct_workspace, reinterpret_cast<Page*>(target_)));
   ASSERT_ND(target_->is_locked());
   // After page-lock, key-count and record-keys (not payloads) are fixed. Check them now!
   if (target_->is_moved()) {
     DVLOG(0) << "Interesting. this page has been split";
     return kErrorCodeOk;
   }
   ASSERT_ND(!target_->is_retired());
   const SlotIndex key_count = target_->get_key_count();
   const VolatilePagePointer page_id(target_->header().page_id_);
   MasstreeBorderPage::FindKeyForReserveResult match = target_->find_key_for_reserve(
     hint_check_from_,
     key_count,
     slice_,
     suffix_,
     remainder_length_);
   // Let's check whether we need to split this page.
   // If we can accomodate it without splitting the page, complete it within here.
   if (match.match_type_ == MasstreeBorderPage::kExactMatchLayerPointer) {
     // Definitelly done. The caller must folllow the next-layer
     ASSERT_ND(match.index_ < kBorderPageMaxSlots);
     return kErrorCodeOk;
   } else if (match.match_type_ == MasstreeBorderPage::kExactMatchLocalRecord) {
     // Is it enough spacious?
     ASSERT_ND(match.index_ < kBorderPageMaxSlots);
     if (target_->get_max_payload_length(match.index_) >= payload_count_) {
       return kErrorCodeOk;  // Yes! done.
     }
     DVLOG(2) << "Need to expand the record.";
     auto* record = target_->get_owner_id(match.index_);
     CHECK_ERROR_CODE(context_->sysxct_record_lock(sysxct_workspace, page_id, record));
     ASSERT_ND(record->is_keylocked());
     // Now the state of the record is finalized. Let's check it again.
     ASSERT_ND(!record->is_moved());  // can't be moved as target_ is not moved.
     if (target_->get_max_payload_length(match.index_) >= payload_count_) {
       return kErrorCodeOk;  // Yes! done.
     } else if (record->is_next_layer()) {
       DVLOG(0) << "Interesting. the record now points to next layer";
       return kErrorCodeOk;  // same kExactMatchLayerPointer
     }
     bool expanded = target_->try_expand_record_in_page_physical(payload_count_, match.index_);
     if (expanded) {
       ASSERT_ND(target_->get_max_payload_length(match.index_) >= payload_count_);
       return kErrorCodeOk;
     }
     DVLOG(0) << "Ouch. need to split for allocating a space for record expansion";
   } else if (match.match_type_ == MasstreeBorderPage::kConflictingLocalRecord) {
     // We will create a next layer.
     // In this case, page-lock was actually an overkill because of key-immutability,
     // However, doing it after page-lock makes the code simpler.
     // In most cases, the caller finds the conflicting local record before calling this
     // sysxct. No need to optimize for this rare case.
     ASSERT_ND(match.index_ < kBorderPageMaxSlots);
     auto* record = target_->get_owner_id(match.index_);
     CHECK_ERROR_CODE(context_->sysxct_record_lock(sysxct_workspace, page_id, record));
     ASSERT_ND(record->is_keylocked());
     // Now the state of the record is finalized. Let's check it again.
     ASSERT_ND(!record->is_moved());  // can't be moved as target_ is not moved.
     if (record->is_next_layer()) {
       DVLOG(0) << "Interesting. the record now points to next layer";
       return kErrorCodeOk;  // same kExactMatchLayerPointer
     }
     // Can we trivially turn this into a next-layer record?
     if (target_->get_max_payload_length(match.index_) < sizeof(DualPagePointer)) {
       DVLOG(1) << "We need to expand the record to make it a next-layer."
         " If this happens too often and is the bottleneck, "
         " you should have used physical_payload_hint when you initially inserted the record.";
       bool expanded
         = target_->try_expand_record_in_page_physical(sizeof(DualPagePointer), match.index_);
       if (expanded) {
         ASSERT_ND(target_->get_max_payload_length(match.index_) >= sizeof(DualPagePointer));
       }
     }
     if (target_->get_max_payload_length(match.index_) >= sizeof(DualPagePointer)) {
       // Turn it into a next-layer
       memory::NumaCoreMemory* memory = context_->get_thread_memory();
       memory::PagePoolOffset offset = memory->grab_free_volatile_page();
       if (offset == 0) {
         return kErrorCodeMemoryNoFreePages;
       }
       MasstreeBorderPage* new_layer_root = reinterpret_cast<MasstreeBorderPage*>(
         context_->get_local_volatile_page_resolver().resolve_offset_newpage(offset));
       VolatilePagePointer new_page_id;
       new_page_id.set(context_->get_numa_node(), offset);
       new_layer_root->initialize_as_layer_root_physical(new_page_id, target_, match.index_);
       return kErrorCodeOk;
     }
     DVLOG(0) << "Ouch. need to split for allocating a space for next-layer";
   } else {
     ASSERT_ND(match.match_type_ == MasstreeBorderPage::kNotFound);
     if (should_aggresively_create_next_layer_ &&
       target_->can_accomodate(key_count, sizeof(KeySlice), sizeof(DualPagePointer))) {
       DVLOG(1) << "Aggressively creating a next-layer.";
       MasstreeBorderPage* root = allocate_new_border_page(context_);
       if (root == nullptr) {
         return kErrorCodeMemoryNoFreePages;
       }
       DualPagePointer pointer;
       pointer.snapshot_pointer_ = 0;
       pointer.volatile_pointer_ = root->get_volatile_page_id();
       root->initialize_volatile_page(
         target_->header().storage_id_,
         pointer.volatile_pointer_,
         target_->get_layer() + 1U,
         kInfimumSlice,    // infimum slice
         kSupremumSlice);   // high-fence is supremum
       ASSERT_ND(!root->is_locked());
       ASSERT_ND(!root->is_moved());
       ASSERT_ND(!root->is_retired());
       ASSERT_ND(root->get_key_count() == 0);
       xct::XctId initial_id = get_initial_xid();
       initial_id.set_next_layer();
       target_->reserve_initially_next_layer(key_count, initial_id, slice_, pointer);
       assorted::memory_fence_release();
       target_->increment_key_count();
       ASSERT_ND(target_->does_point_to_layer(key_count));
       ASSERT_ND(target_->get_next_layer(key_count)->volatile_pointer_ == pointer.volatile_pointer_);
       ASSERT_ND(!target_->is_moved());
       ASSERT_ND(!target_->is_retired());
       target_->assert_entries();
       return kErrorCodeOk;
     }
     if (target_->can_accomodate(key_count, remainder_length_, payload_count_)) {
       ASSERT_ND(target_->get_key_count() < kBorderPageMaxSlots);
       xct::XctId initial_id = get_initial_xid();
       initial_id.set_deleted();
       target_->reserve_record_space(
         key_count,
         initial_id,
         slice_,
         suffix_,
         remainder_length_,
         payload_count_);
       // we increment key count AFTER installing the key because otherwise the optimistic read
       // might see the record but find that the key doesn't match. we need a fence to prevent it.
       assorted::memory_fence_release();
       target_->increment_key_count();
       ASSERT_ND(target_->get_key_count() <= kBorderPageMaxSlots);
       ASSERT_ND(!target_->is_moved());
       ASSERT_ND(!target_->is_retired());
       target_->assert_entries();
       return kErrorCodeOk;
     }
     DVLOG(1) << "Ouch. need to split for allocating a space for new record";
   }
   // If we are here, we need to split the page for some reason.
   out_split_needed_ = true;
   return kErrorCodeOk;
 }
Member Data Documentation
thread::Thread* const foedus::storage::masstree::ReserveRecords::context_
Thread context.
Definition at line 59 of file masstree_reserve_impl.hpp.
Referenced by run().
const SlotIndex foedus::storage::masstree::ReserveRecords::hint_check_from_
The in-page location from which this sysxct will look for matching records.
The caller is sure that no record before this position can match the slice. Thanks to append-only writes in border pages, the caller can guarantee that the records it observed are final.
In most cases, this is same as key_count after locking, thus completely avoiding the re-check.
Definition at line 78 of file masstree_reserve_impl.hpp.
Referenced by run().
bool foedus::storage::masstree::ReserveRecords::out_split_needed_
[Out]
Definition at line 89 of file masstree_reserve_impl.hpp.
Referenced by foedus::storage::masstree::MasstreeStoragePimpl::reserve_record(), foedus::storage::masstree::MasstreeStoragePimpl::reserve_record_normalized(), and run().
const PayloadLength foedus::storage::masstree::ReserveRecords::payload_count_
Minimal required length of the payload.
Definition at line 69 of file masstree_reserve_impl.hpp.
Referenced by run().
const KeyLength foedus::storage::masstree::ReserveRecords::remainder_length_
Length of the remainder.
Definition at line 67 of file masstree_reserve_impl.hpp.
Referenced by run().
const bool foedus::storage::masstree::ReserveRecords::should_aggresively_create_next_layer_
When we CAN create a next layer for the new record, whether to make it a next-layer from the beginning, or make it as a usual record first.
See also
MasstreeMetadata::should_aggresively_create_next_layer()
Definition at line 85 of file masstree_reserve_impl.hpp.
Referenced by run().
const KeySlice foedus::storage::masstree::ReserveRecords::slice_
The slice of the key.
Definition at line 63 of file masstree_reserve_impl.hpp.
Referenced by run().
const void* const foedus::storage::masstree::ReserveRecords::suffix_
Suffix of the key.
Definition at line 65 of file masstree_reserve_impl.hpp.
Referenced by run().
MasstreeBorderPage* const foedus::storage::masstree::ReserveRecords::target_
The page to install a new physical record.
Definition at line 61 of file masstree_reserve_impl.hpp.
Referenced by run().
The documentation for this struct was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/storage/masstree/masstree_reserve_impl.hpp
/home/shino/foedus_code/foedus-core/src/foedus/storage/masstree/masstree_reserve_impl.cpp