libfoedus-core: foedus::xct::McsMockNode< RW_BLOCK > Struct Template Reference
foedus::xct::McsMockNode< RW_BLOCK > Struct Template Reference
Analogous to one thread-group/socket/node.
Detailed Description
template<typename RW_BLOCK>
struct foedus::xct::McsMockNode< RW_BLOCK >
Analogous to one thread-group/socket/node.
Note
completely header-only
Definition at line 206 of file xct_mcs_adapter_impl.hpp.
#include <xct_mcs_adapter_impl.hpp>
Public Member Functions
void init (storage::StorageId dummy_storage_id, uint16_t node_id, uint32_t threads_per_node, uint32_t max_block_count, uint32_t pages_per_node)
Public Attributes
uint16_t node_id_
uint32_t max_block_count_
std::vector< McsMockThread< RW_BLOCK > > threads_
McsMockDataPage * pages_
Locks assigned to this node are stored in these memory.
memory::AlignedMemory page_memory_
Member Function Documentation
template<typename RW_BLOCK > void foedus::xct::McsMockNode< RW_BLOCK >::init (storage::StorageId dummy_storage_id, uint16_t node_id, uint32_t threads_per_node, uint32_t max_block_count, uint32_t pages_per_node) inline
Definition at line 207 of file xct_mcs_adapter_impl.hpp.
References foedus::memory::AlignedMemory::alloc_onnode(), ASSERT_ND, foedus::memory::AlignedMemory::get_block(), foedus::xct::McsMockDataPage::init(), foedus::memory::AlignedMemory::is_null(), foedus::xct::McsMockNode< RW_BLOCK >::max_block_count_, foedus::xct::McsMockNode< RW_BLOCK >::node_id_, foedus::xct::McsMockNode< RW_BLOCK >::page_memory_, foedus::xct::McsMockNode< RW_BLOCK >::pages_, and foedus::xct::McsMockNode< RW_BLOCK >::threads_.
{
     node_id_ = node_id;
     max_block_count_ = max_block_count;
     threads_.resize(threads_per_node);
     for (uint32_t t = 0; t < threads_per_node; ++t) {
       threads_[t].init(max_block_count);
     }
     page_memory_.alloc_onnode(
       sizeof(McsMockDataPage) * pages_per_node,
       sizeof(McsMockDataPage),
       node_id);
     ASSERT_ND(!page_memory_.is_null());
     pages_ = reinterpret_cast<McsMockDataPage*>(page_memory_.get_block());
     for (uint32_t i = 0; i < pages_per_node; ++i) {
       pages_[i].init(dummy_storage_id, node_id, i);
     }
   }
Member Data Documentation
template<typename RW_BLOCK > uint32_t foedus::xct::McsMockNode< RW_BLOCK >::max_block_count_
Definition at line 232 of file xct_mcs_adapter_impl.hpp.
Referenced by foedus::xct::McsMockNode< RW_BLOCK >::init().
template<typename RW_BLOCK > uint16_t foedus::xct::McsMockNode< RW_BLOCK >::node_id_
Definition at line 231 of file xct_mcs_adapter_impl.hpp.
Referenced by foedus::xct::McsMockNode< RW_BLOCK >::init().
template<typename RW_BLOCK > memory::AlignedMemory foedus::xct::McsMockNode< RW_BLOCK >::page_memory_
Definition at line 239 of file xct_mcs_adapter_impl.hpp.
Referenced by foedus::xct::McsMockNode< RW_BLOCK >::init().
template<typename RW_BLOCK > McsMockDataPage* foedus::xct::McsMockNode< RW_BLOCK >::pages_
Locks assigned to this node are stored in these memory.
Definition at line 238 of file xct_mcs_adapter_impl.hpp.
Referenced by foedus::xct::McsMockNode< RW_BLOCK >::init().
template<typename RW_BLOCK > std::vector< McsMockThread<RW_BLOCK> > foedus::xct::McsMockNode< RW_BLOCK >::threads_
Definition at line 233 of file xct_mcs_adapter_impl.hpp.
Referenced by foedus::xct::McsMockNode< RW_BLOCK >::init().
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/xct/xct_mcs_adapter_impl.hpp