libfoedus-core: foedus::fs::FileStatus Struct Reference
foedus::fs::FileStatus Struct Reference
FOEDUS Programming Idioms » Filesystem wrapper
Analogue of boost::filesystem::file_status.
Detailed Description
Analogue of boost::filesystem::file_status.
Definition at line 89 of file filesystem.hpp.
#include <filesystem.hpp>
Public Member Functions
FileStatus ()
FileStatus (FileType type, FilePermission permissions=kPermsNotKnown)
bool type_present () const
bool permissions_present () const
bool status_known () const
bool exists () const
bool is_regular_file () const
bool is_directory () const
Public Attributes
FileType type_
FilePermission permissions_
Constructor & Destructor Documentation
foedus::fs::FileStatus::FileStatus () inline
Definition at line 90 of file filesystem.hpp.
 : type_(kStatusError), permissions_(kPermsNotKnown) {}
foedus::fs::FileStatus::FileStatus (FileType type, FilePermission permissions = kPermsNotKnown) inline explicit
Definition at line 91 of file filesystem.hpp.
                     : type_(type), permissions_(permissions) {}
Member Function Documentation
bool foedus::fs::FileStatus::exists () const inline
Definition at line 97 of file filesystem.hpp.
References foedus::fs::kFileNotFound, foedus::fs::kStatusError, and type_.
Referenced by foedus::fs::exists(), and foedus::fs::remove().
 { return type_ != kStatusError && type_ != kFileNotFound; }
bool foedus::fs::FileStatus::is_directory () const inline
Definition at line 99 of file filesystem.hpp.
References foedus::fs::kDirectoryFile, and type_.
Referenced by foedus::fs::is_directory().
 { return type_ == kDirectoryFile; }
bool foedus::fs::FileStatus::is_regular_file () const inline
Definition at line 98 of file filesystem.hpp.
References foedus::fs::kRegularFile, and type_.
Referenced by foedus::fs::is_regular_file(), and foedus::fs::remove().
 { return type_ == kRegularFile; }
bool foedus::fs::FileStatus::permissions_present () const inline
Definition at line 95 of file filesystem.hpp.
References foedus::fs::kPermsNotKnown, and permissions_.
Referenced by status_known().
 { return permissions_ != kPermsNotKnown;}
bool foedus::fs::FileStatus::status_known () const inline
Definition at line 96 of file filesystem.hpp.
References permissions_present(), and type_present().
 { return type_present() && permissions_present(); }
bool foedus::fs::FileStatus::type_present () const inline
Definition at line 94 of file filesystem.hpp.
References foedus::fs::kStatusError, and type_.
Referenced by status_known().
 { return type_ != kStatusError; }
Member Data Documentation
FilePermission foedus::fs::FileStatus::permissions_
Definition at line 102 of file filesystem.hpp.
Referenced by permissions_present().
FileType foedus::fs::FileStatus::type_
Definition at line 101 of file filesystem.hpp.
Referenced by exists(), is_directory(), is_regular_file(), and type_present().
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/fs/filesystem.hpp