libfoedus-core: foedus::thread::NumaThreadScope Struct Reference
foedus::thread::NumaThreadScope Struct Reference
FOEDUS Components » Thread and Thread-GroupFOEDUS Components » Memory Manager » | Memory Hierarchy
Pin the current thread to the given NUMA node in this object's scope.
Detailed Description
Pin the current thread to the given NUMA node in this object's scope.
Declare this object as soon as the thread starts.
Definition at line 33 of file numa_thread_scope.hpp.
#include <numa_thread_scope.hpp>
Public Member Functions
NumaThreadScope (int numa_node)
~NumaThreadScope ()
Constructor & Destructor Documentation
foedus::thread::NumaThreadScope::NumaThreadScope (int numa_node) inline explicit
Definition at line 34 of file numa_thread_scope.hpp.
References foedus::assorted::mod_numa_node(), numa_available(), numa_run_on_node(), and numa_set_localalloc().
{
     if (::numa_available() >= 0) {
       numa_node = assorted::mod_numa_node(numa_node);
       ::numa_run_on_node(numa_node);
       ::numa_set_localalloc();
     }
   }
foedus::thread::NumaThreadScope::~NumaThreadScope () inline
Definition at line 41 of file numa_thread_scope.hpp.
References numa_all_nodes_ptr, numa_available(), and numa_run_on_node_mask().
                      {
     if (::numa_available() >= 0) {
       ::numa_run_on_node_mask(::numa_all_nodes_ptr);
     }
   }
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/thread/numa_thread_scope.hpp