libfoedus-core: foedus::storage::Composer::DropVolatilesArguments Struct Reference
foedus::storage::Composer::DropVolatilesArguments Struct Reference
FOEDUS Components » Storage ManagerFOEDUS Components » | Snapshot Manager
Arguments for drop_volatiles()
Detailed Description
Arguments for drop_volatiles()
Definition at line 148 of file composer.hpp.
#include <composer.hpp>
Public Member Functions
void drop (Engine *engine, VolatilePagePointer pointer) const
Returns (might cache) the given pointer to volatile pool.
Public Attributes
snapshot::Snapshot snapshot_
The new snapshot.
uint16_t my_partition_
if partitioned_drop_ is true, the partition this thread should drop volatile pages from
bool partitioned_drop_
if true, one thread for each partition will invoke drop_volatiles()
memory::PagePoolOffsetChunk * dropped_chunks_
Caches dropped pages to avoid returning every single page.
uint64_t * dropped_count_
[OUT] Number of volatile pages that were dropped
Member Function Documentation
void foedus::storage::Composer::DropVolatilesArguments::drop (Engine * engine, VolatilePagePointer pointer) const
Returns (might cache) the given pointer to volatile pool.
Definition at line 114 of file composer.cpp.
References ASSERT_ND, dropped_chunks_, foedus::memory::PagePoolOffsetChunk::empty(), foedus::memory::PagePoolOffsetChunk::full(), foedus::memory::EngineMemory::get_global_volatile_page_resolver(), foedus::Engine::get_memory_manager(), foedus::memory::EngineMemory::get_node_memory(), foedus::storage::VolatilePagePointer::get_numa_node(), foedus::storage::VolatilePagePointer::get_offset(), foedus::memory::NumaNodeMemoryRef::get_volatile_pool(), foedus::storage::VolatilePagePointer::is_null(), foedus::memory::PagePoolOffsetChunk::push_back(), foedus::memory::PagePool::release(), foedus::memory::GlobalVolatilePageResolver::resolve_offset(), and foedus::memory::PagePoolOffsetChunk::size().
Referenced by foedus::storage::sequential::SequentialComposer::drop_volatiles().
{
   uint16_t node = pointer.get_numa_node();
   ASSERT_ND(node < engine->get_soc_count());
   ASSERT_ND(!pointer.is_null());
 #ifndef NDEBUG
   // let's fill the page with garbage to help debugging
   std::memset(
     engine->get_memory_manager()->get_global_volatile_page_resolver().resolve_offset(pointer),
     0xDA,
     sizeof(Page));
 #endif  // NDEBUG
   memory::PagePoolOffsetChunk* chunk = dropped_chunks_ + node;
   if (chunk->full()) {
     memory::PagePool* pool
       = engine->get_memory_manager()->get_node_memory(node)->get_volatile_pool();
     pool->release(chunk->size(), chunk);
     ASSERT_ND(chunk->empty());
   }
   ASSERT_ND(!chunk->full());
   chunk->push_back(pointer.get_offset());
   ++(*dropped_count_);
 }
Member Data Documentation
memory::PagePoolOffsetChunk* foedus::storage::Composer::DropVolatilesArguments::dropped_chunks_
Caches dropped pages to avoid returning every single page.
This is an array of PagePoolOffsetChunk whose index is node ID. For each dropped page, we add it to this chunk and batch-return them to the volatile pool when it becomes full or after processing all storages.
Definition at line 161 of file composer.hpp.
Referenced by drop().
uint64_t* foedus::storage::Composer::DropVolatilesArguments::dropped_count_
[OUT] Number of volatile pages that were dropped
Definition at line 163 of file composer.hpp.
uint16_t foedus::storage::Composer::DropVolatilesArguments::my_partition_
if partitioned_drop_ is true, the partition this thread should drop volatile pages from
Definition at line 152 of file composer.hpp.
Referenced by foedus::storage::array::ArrayComposer::drop_volatiles(), foedus::storage::hash::HashComposer::drop_volatiles(), foedus::storage::masstree::MasstreeComposer::drop_volatiles(), and foedus::storage::sequential::SequentialComposer::drop_volatiles().
bool foedus::storage::Composer::DropVolatilesArguments::partitioned_drop_
if true, one thread for each partition will invoke drop_volatiles()
Definition at line 154 of file composer.hpp.
Referenced by foedus::storage::array::ArrayComposer::drop_volatiles(), foedus::storage::hash::HashComposer::drop_volatiles(), foedus::storage::masstree::MasstreeComposer::drop_volatiles(), and foedus::storage::sequential::SequentialComposer::drop_volatiles().
snapshot::Snapshot foedus::storage::Composer::DropVolatilesArguments::snapshot_
The new snapshot.
All newly created snapshot pages are of this snapshot
Definition at line 150 of file composer.hpp.
Referenced by foedus::storage::array::ArrayComposer::drop_root_volatile(), foedus::storage::sequential::SequentialComposer::drop_volatiles(), and foedus::storage::Composer::DropResult::DropResult().
The documentation for this struct was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/storage/composer.hpp
/home/shino/foedus_code/foedus-core/src/foedus/storage/composer.cpp