libfoedus-core: foedus::storage::hash::HashCommonLogType Struct Reference
foedus::storage::hash::HashCommonLogType Struct Reference
FOEDUS Components » Storage Manager » Hashtable StorageFOEDUS Components » Log Manager » | Log Types
A base class for HashInsertLogType/HashDeleteLogType/HashOverwriteLogType.
Detailed Description
A base class for HashInsertLogType/HashDeleteLogType/HashOverwriteLogType.
This defines a common layout for the log types so that composer/partitioner can easier handle these log types. This means we waste a bit (eg delete log type doesn't need payload offset/count), but we anyway have extra space if we want to have data_ 8-byte aligned. data_ always starts with the key, followed by payload for insert/overwrite.
Definition at line 75 of file hash_log_types.hpp.
#include <hash_log_types.hpp>
Public Member Functions
HashCommonLogType ()=delete
HashCommonLogType (const HashCommonLogType &other)=delete
~HashCommonLogType ()=delete
char * get_key ()
const char * get_key () const
uint16_t get_key_length_aligned () const
char * get_payload ()
const char * get_payload () const
void populate_base (log::LogCode type, StorageId storage_id, const void *key, uint16_t key_length, uint8_t bin_bits, HashValue hash, const void *payload=nullptr, uint16_t payload_offset=0, uint16_t payload_count=0) __attribute__((always_inline))
void assert_record_and_log_keys (xct::RwLockableXctId *owner_id, const char *data) const
used only for sanity check.
void assert_type () const __attribute__((always_inline))
Public Member Functions inherited from foedus::log::RecordLogType
bool is_engine_log () const
bool is_storage_log () const
bool is_record_log () const
void apply_engine (thread::Thread *)
void apply_storage (Engine *, storage::StorageId)
void assert_valid_generic () const __attribute__((always_inline))
Verifies the log contains essential fields set.
Static Public Member Functions
static uint16_t calculate_log_length (uint16_t key_length, uint16_t payload_count) __attribute__((always_inline))
static int compare_logs (const HashCommonLogType *left, const HashCommonLogType *right) __attribute__((always_inline))
Returns -1, 0, 1 when left is less than, same, larger than right in terms of bin and xct_id.
Public Attributes
uint16_t key_length_
uint16_t payload_offset_
uint16_t payload_count_
uint8_t bin_bits_
this is not strictly needed here, but helps a bit.
uint8_t reserved_
HashValue hash_
Hash value of the key.
char aligned_data_ [8]
Full key and (if exists) payload data, both of which are padded to 8 bytes.
Public Attributes inherited from foedus::log::BaseLogType
LogHeader header_
Constructor & Destructor Documentation
foedus::storage::hash::HashCommonLogType::HashCommonLogType () delete
foedus::storage::hash::HashCommonLogType::HashCommonLogType (const HashCommonLogType & other) delete
foedus::storage::hash::HashCommonLogType::~HashCommonLogType () delete
Member Function Documentation
void foedus::storage::hash::HashCommonLogType::assert_record_and_log_keys (xct::RwLockableXctId * owner_id, const char * data) const inline
used only for sanity check.
checks if the record's and log's keys are equal
Definition at line 142 of file hash_log_types.hpp.
References foedus::assorted::align8(), ASSERT_ND, and foedus::storage::hash::hashinate().
Referenced by foedus::storage::hash::HashStoragePimpl::track_moved_record().
{
     const char* log_key = get_key();
     ASSERT_ND(hash_ == hashinate(log_key, key_length_));
     uint16_t log_key_length_aligned = get_key_length_aligned();
     // In HashDataPage::Slot, offset_ etc comes after owner_id. Let's do sanity checks.
     uint16_t* lengthes = reinterpret_cast<uint16_t*>(owner_id + 1);
     // physical length enough long?
     ASSERT_ND(lengthes[1] >= log_key_length_aligned + assorted::align8(payload_count_));
     ASSERT_ND(lengthes[2] == key_length_);  // key length correct?
     // and then HashValue follows.
     ASSERT_ND(hash_ == reinterpret_cast<HashValue*>(owner_id + 1)[1]);
     // finally, does the key really match?
     ASSERT_ND(std::memcmp(log_key, data, log_key_length_aligned) == 0);
   }
void foedus::storage::hash::HashCommonLogType::assert_type () const inline
Definition at line 162 of file hash_log_types.hpp.
References ASSERT_ND, foedus::storage::hash::hashinate(), foedus::log::BaseLogType::header_, foedus::log::kLogCodeHashDelete, foedus::log::kLogCodeHashInsert, foedus::log::kLogCodeHashOverwrite, foedus::log::kLogCodeHashUpdate, and foedus::log::LogHeader::log_type_code_.
Referenced by foedus::snapshot::MergeSort::assert_sorted(), foedus::storage::hash::HashPartitioner::partition_batch(), and foedus::storage::hash::prepare_sort_entries().
{
     ASSERT_ND(header_.log_type_code_ == log::kLogCodeHashOverwrite
       || header_.log_type_code_ == log::kLogCodeHashInsert
       || header_.log_type_code_ == log::kLogCodeHashDelete
       || header_.log_type_code_ == log::kLogCodeHashUpdate);
     ASSERT_ND(hash_ == hashinate(get_key(), key_length_));
   }
static uint16_t foedus::storage::hash::HashCommonLogType::calculate_log_length (uint16_t key_length, uint16_t payload_count) inline static
Definition at line 95 of file hash_log_types.hpp.
References foedus::assorted::align8().
Referenced by foedus::storage::hash::HashStoragePimpl::delete_record(), foedus::storage::hash::HashStoragePimpl::increment_record(), foedus::storage::hash::HashStoragePimpl::insert_record(), foedus::storage::hash::HashStoragePimpl::overwrite_record(), and foedus::storage::hash::HashStoragePimpl::upsert_record().
{
     return 32U + assorted::align8(key_length) + assorted::align8(payload_count);
   }
static int foedus::storage::hash::HashCommonLogType::compare_logs (const HashCommonLogType * left, const HashCommonLogType * right) inline static
Returns -1, 0, 1 when left is less than, same, larger than right in terms of bin and xct_id.
Precondition
this->is_valid(), other.is_valid()
this->get_ordinal() != 0, other.get_ordinal() != 0
Note
This does NOT fully compare the key. Only bins. this method is used in merge-sort code to batch-sort logs. Hash doesn't need to fully sort logs on keys. We probably should rename this method to avoid confusion later.
Definition at line 178 of file hash_log_types.hpp.
References ASSERT_ND, and foedus::storage::hash::hashinate().
{
     ASSERT_ND(left->header_.storage_id_ == right->header_.storage_id_);
     ASSERT_ND(left->bin_bits_ == right->bin_bits_);
     ASSERT_ND(left->hash_ == hashinate(left->get_key(), left->key_length_));
     ASSERT_ND(right->hash_ == hashinate(right->get_key(), right->key_length_));
     if (left == right) {
       return 0;
     }
     HashBin   left_bin = left->hash_ >> (64U - left->bin_bits_);
     HashBin   right_bin = right->hash_ >> (64U - right->bin_bits_);
     if (left_bin != right_bin) {
       if (left_bin < right_bin) {
         return -1;
       } else {
         return 1;
       }
     }
     return left->header_.xct_id_.compare_epoch_and_orginal(right->header_.xct_id_);
   }
char* foedus::storage::hash::HashCommonLogType::get_key () inline
Definition at line 99 of file hash_log_types.hpp.
Referenced by foedus::storage::hash::operator<<().
 { return aligned_data_; }
const char* foedus::storage::hash::HashCommonLogType::get_key () const inline
Definition at line 100 of file hash_log_types.hpp.
 { return aligned_data_; }
uint16_t foedus::storage::hash::HashCommonLogType::get_key_length_aligned () const inline
Definition at line 101 of file hash_log_types.hpp.
References foedus::assorted::align8().
 { return assorted::align8(key_length_); }
char* foedus::storage::hash::HashCommonLogType::get_payload () inline
Definition at line 102 of file hash_log_types.hpp.
Referenced by foedus::storage::hash::operator<<().
 { return aligned_data_ + get_key_length_aligned(); }
const char* foedus::storage::hash::HashCommonLogType::get_payload () const inline
Definition at line 103 of file hash_log_types.hpp.
 { return aligned_data_ + get_key_length_aligned(); }
void foedus::storage::hash::HashCommonLogType::populate_base (log::LogCode type, StorageId storage_id, const void * key, uint16_t key_length, uint8_t bin_bits, HashValue hash, const void * payload = nullptr, uint16_t payload_offset = 0, uint16_t payload_count = 0) inline
Definition at line 104 of file hash_log_types.hpp.
References foedus::assorted::align8(), ASSERT_ND, foedus::storage::hash::hashinate(), foedus::log::BaseLogType::header_, foedus::log::LogHeader::log_length_, foedus::log::LogHeader::log_type_code_, and foedus::log::LogHeader::storage_id_.
{
     header_.log_type_code_ = type;
     header_.log_length_ = calculate_log_length(key_length, payload_count);
     header_.storage_id_ = storage_id;
     key_length_ = key_length;
     payload_offset_ = payload_offset;
     payload_count_ = payload_count;
     bin_bits_ = bin_bits;
     reserved_ = 0;
     ASSERT_ND(hash == hashinate(key, key_length));
     hash_ = hash;
     std::memcpy(aligned_data_, key, key_length);
     uint16_t aligned_key_length = assorted::align8(key_length);
     if (aligned_key_length != key_length) {
       std::memset(aligned_data_ + key_length, 0, aligned_key_length - key_length);
     }
     if (payload_count > 0) {
       uint16_t aligned_payload_count = assorted::align8(payload_count);
       char* payload_base = aligned_data_ + aligned_key_length;
       std::memcpy(payload_base, payload, payload_count);
       if (aligned_payload_count != payload_count) {
         std::memset(payload_base + payload_count, 0, aligned_payload_count - payload_count);
       }
     }
   }
Member Data Documentation
char foedus::storage::hash::HashCommonLogType::aligned_data_[8]
Full key and (if exists) payload data, both of which are padded to 8 bytes.
By padding key part to 8 bytes, slicing becomes more efficient.
Definition at line 93 of file hash_log_types.hpp.
uint8_t foedus::storage::hash::HashCommonLogType::bin_bits_
this is not strictly needed here, but helps a bit.
Definition at line 81 of file hash_log_types.hpp.
Referenced by foedus::storage::hash::operator<<().
HashValue foedus::storage::hash::HashCommonLogType::hash_
Hash value of the key.
We can always re-calculate this from the key, but it can be quite expensive. Instead, we pay extra 8 bytes to save CPU cost.
Definition at line 87 of file hash_log_types.hpp.
Referenced by foedus::storage::hash::operator<<(), foedus::storage::hash::HashPartitioner::partition_batch(), and foedus::storage::hash::prepare_sort_entries().
uint16_t foedus::storage::hash::HashCommonLogType::key_length_
Definition at line 77 of file hash_log_types.hpp.
Referenced by foedus::storage::hash::operator<<(), and foedus::snapshot::update_key_lengthes().
uint16_t foedus::storage::hash::HashCommonLogType::payload_count_
Definition at line 79 of file hash_log_types.hpp.
Referenced by foedus::storage::hash::operator<<().
uint16_t foedus::storage::hash::HashCommonLogType::payload_offset_
Definition at line 78 of file hash_log_types.hpp.
Referenced by foedus::storage::hash::operator<<().
uint8_t foedus::storage::hash::HashCommonLogType::reserved_
Definition at line 82 of file hash_log_types.hpp.
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/storage/hash/hash_log_types.hpp