libfoedus-core: foedus::storage::hash::DataPageBloomFilter Struct Reference
foedus::storage::hash::DataPageBloomFilter Struct Reference final
FOEDUS Components » Storage Manager » Hashtable Storage
To quickly check whether a HashDataPage might contain a specific hash value, we maintain a non-counting bloom filter in each page.
Detailed Description
To quickly check whether a HashDataPage might contain a specific hash value, we maintain a non-counting bloom filter in each page.
Getting Index
The index is determined from the hash value. Higher bits are already used for bins, so all entries in this page have the same value there. We avoid those bits and take lower bits as hash functions for the Bloom Filter.
Size of table (m)
Slot is 32 bytes, so each tuple is probably 50-100 bytes or more. I guess each page would contain n=30-50 records. http://corte.si/%2Fposts/code/bloom-filter-rules-of-thumb/index.html Here we reserve 64 bytes (m=8*64=512) for the bloom filter, more than one-byte per item.
Number of Hash Funcs (k)
http://pages.cs.wisc.edu/~cao/papers/summary-cache/node8.html In our case, m/n is around 8~10. so, 3 hash functions should be practically enough. 512 entries can be expressed in 9 bits. *3= 27 bits. In most cases bin-bits should be within 64-27=37 bits. So, we simply take the lower 27 bits of the full hash.
Definition at line 143 of file hash_hashinate.hpp.
#include <hash_hashinate.hpp>
Public Member Functions
void clear ()
usually zero-cleared as part of a data page, but in case of specifically clearing this
bool contains (const BloomFilterFingerprint &fingerprint) const __attribute__((always_inline))
void add (const BloomFilterFingerprint &fingerprint) __attribute__((always_inline))
Adds the fingerprint to this bloom filter.
Static Public Member Functions
static BloomFilterFingerprint extract_fingerprint (HashValue fullhash)
Public Attributes
uint8_t values_ [kHashDataPageBloomFilterBytes]
Friends
std::ostream & operator<< (std::ostream &o, const DataPageBloomFilter &v)
Member Function Documentation
void foedus::storage::hash::DataPageBloomFilter::add (const BloomFilterFingerprint & fingerprint) inline
Adds the fingerprint to this bloom filter.
This must be called with page lock
Definition at line 165 of file hash_hashinate.hpp.
References ASSERT_ND, and foedus::storage::hash::kHashDataPageBloomFilterHashes.
Referenced by foedus::storage::hash::ReserveRecords::append_record_to_page(), foedus::storage::hash::HashDataPage::assert_entries_impl(), foedus::storage::hash::HashDataPage::create_record_in_snapshot(), and foedus::storage::hash::HashDataPage::reserve_record().
{
     for (uint8_t k = 0; k < kHashDataPageBloomFilterHashes; ++k) {
       ASSERT_ND(fingerprint.indexes_[k] < kHashDataPageBloomFilterBits);
       uint8_t byte_index = fingerprint.indexes_[k] / 8U;
       uint8_t bit_index = fingerprint.indexes_[k] % 8U;
       values_[byte_index] |= (1U << bit_index);
     }
   }
void foedus::storage::hash::DataPageBloomFilter::clear () inline
usually zero-cleared as part of a data page, but in case of specifically clearing this
Definition at line 147 of file hash_hashinate.hpp.
Referenced by foedus::storage::hash::HashDataPage::assert_entries_impl().
                {
     std::memset(values_, 0, sizeof(values_));
   }
bool foedus::storage::hash::DataPageBloomFilter::contains (const BloomFilterFingerprint & fingerprint) const inline
Returns
whether this page might contain the fingerprint
Definition at line 152 of file hash_hashinate.hpp.
References ASSERT_ND, and foedus::storage::hash::kHashDataPageBloomFilterHashes.
Referenced by foedus::storage::hash::HashStoragePimpl::insert_record(), foedus::storage::hash::HashDataPage::search_key_physical(), and foedus::storage::hash::HashStoragePimpl::upsert_record().
{
     for (uint8_t k = 0; k < kHashDataPageBloomFilterHashes; ++k) {
       ASSERT_ND(fingerprint.indexes_[k] < kHashDataPageBloomFilterBits);
       uint8_t byte_index = fingerprint.indexes_[k] / 8U;
       uint8_t bit_index = fingerprint.indexes_[k] % 8U;
       if ((values_[byte_index] & (1U << bit_index)) == 0) {
         return false;
       }
     }
     return true;
   }
static BloomFilterFingerprint foedus::storage::hash::DataPageBloomFilter::extract_fingerprint (HashValue fullhash) inline static
Returns
The indexes for bloom filter extracted from a hash value.
Definition at line 175 of file hash_hashinate.hpp.
References foedus::storage::hash::BloomFilterFingerprint::indexes_, foedus::storage::hash::kHashDataPageBloomFilterHashes, foedus::storage::hash::kHashDataPageBloomFilterIndexMask, and foedus::storage::hash::kHashDataPageBloomFilterIndexSize.
Referenced by foedus::storage::hash::HashDataPage::assert_entries_impl(), foedus::storage::hash::HashCombo::HashCombo(), foedus::storage::hash::operator<<(), and foedus::storage::hash::HashDataPage::search_key_physical().
{
     BloomFilterFingerprint ret;
     for (uint8_t k = 0; k < kHashDataPageBloomFilterHashes; ++k) {
       uint64_t index = fullhash >> (k * kHashDataPageBloomFilterIndexSize);
       // as kHashDataPageBloomFilterBits is power of 2, this is a bit simpler, but not much.
       ret.indexes_[k] = index & kHashDataPageBloomFilterIndexMask;
     }
     return ret;
   }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const DataPageBloomFilter & v) friend
Definition at line 73 of file hash_hashinate.cpp.
{
   o << "<DataPageBloomFilter>" << std::endl;
   // one line for 8 bytes
   for (uint16_t i = 0; i * 8U < kHashDataPageBloomFilterBytes; ++i) {
     o << "  <Bytes row=\"" << i << "\">";
     for (uint16_t j = i * 8U; j < (i + 1U) * 8U && j < kHashDataPageBloomFilterBytes; ++j) {
       o << assorted::Hex(v.values_[j], 2) << " ";
     }
     o << "</Bytes>" << std::endl;
   }
   o << "</DataPageBloomFilter>";
   return o;
 }
Member Data Documentation
uint8_t foedus::storage::hash::DataPageBloomFilter::values_[kHashDataPageBloomFilterBytes]
Definition at line 144 of file hash_hashinate.hpp.
Referenced by foedus::storage::hash::HashDataPage::assert_entries_impl(), and foedus::storage::hash::operator<<().
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/storage/hash/hash_hashinate.hpp