libfoedus-core: foedus::storage::masstree::RecordLocation Struct Reference
foedus::storage::masstree::RecordLocation Struct Reference
return value of MasstreeStoragePimpl::locate_record()/reserve_record().
Detailed Description
return value of MasstreeStoragePimpl::locate_record()/reserve_record().
See foedus::storage::hash::RecordLocation regarding observed_. Masstree's locate_record() is also now a logical operation.
See also
foedus::storage::hash::RecordLocation
Definition at line 39 of file masstree_record_location.hpp.
#include <masstree_record_location.hpp>
Public Member Functions
bool is_found () const
void clear ()
ErrorCode populate_logical (xct::Xct *cur_xct, MasstreeBorderPage *page, SlotIndex index, bool intended_for_write)
Populates the result with XID and possibly readset.
Public Attributes
MasstreeBorderPage * page_
The border page containing the record.
SlotIndex index_
Index of the record in the page.
xct::XctId observed_
TID as of locate_record() identifying the record.
xct::ReadXctAccess * readset_
If this method took a read-set on the returned record, points to the corresponding read-set.
Member Function Documentation
void foedus::storage::masstree::RecordLocation::clear () inline
Definition at line 57 of file masstree_record_location.hpp.
References CXX11_NULLPTR, foedus::xct::XctId::data_, and foedus::storage::masstree::kBorderPageMaxSlots.
Referenced by foedus::storage::masstree::MasstreeStoragePimpl::locate_record(), foedus::storage::masstree::MasstreeStoragePimpl::locate_record_normalized(), foedus::storage::masstree::MasstreeCursor::MasstreeCursor(), foedus::storage::masstree::MasstreeStoragePimpl::reserve_record(), and foedus::storage::masstree::MasstreeStoragePimpl::reserve_record_normalized().
                {
     page_ = CXX11_NULLPTR;
     index_ = kBorderPageMaxSlots;
     observed_.data_ = 0;
     readset_ = CXX11_NULLPTR;
   }
bool foedus::storage::masstree::RecordLocation::is_found () const inline
Definition at line 56 of file masstree_record_location.hpp.
References foedus::storage::masstree::kBorderPageMaxSlots.
Referenced by foedus::storage::masstree::MasstreeStorage::insert_record(), foedus::storage::masstree::MasstreeStorage::insert_record_normalized(), foedus::storage::masstree::MasstreeStorage::upsert_record(), and foedus::storage::masstree::MasstreeStorage::upsert_record_normalized().
 { return index_ != kBorderPageMaxSlots; }
ErrorCode foedus::storage::masstree::RecordLocation::populate_logical (xct::Xct * cur_xct, MasstreeBorderPage * page, SlotIndex index, bool intended_for_write)
Populates the result with XID and possibly readset.
This is a logical operation that might take a readset.
Definition at line 27 of file masstree_record_location.cpp.
References ASSERT_ND, CHECK_ERROR_CODE, foedus::storage::masstree::MasstreeBorderPage::get_owner_id(), index_, foedus::xct::XctId::is_being_written(), foedus::xct::XctId::is_moved(), foedus::xct::XctId::is_next_layer(), foedus::xct::XctId::is_valid(), foedus::kErrorCodeOk, observed_, foedus::xct::Xct::on_record_read(), page_, and readset_.
Referenced by foedus::storage::masstree::MasstreeStoragePimpl::locate_record(), foedus::storage::masstree::MasstreeStoragePimpl::locate_record_normalized(), foedus::storage::masstree::MasstreeStoragePimpl::reserve_record(), and foedus::storage::masstree::MasstreeStoragePimpl::reserve_record_normalized().
{
   page_ = page;
   index_ = index;
   readset_ = nullptr;
   // [Logical check]: Read XID in a finalized fashion. If we found it "moved",
   // then we don't need to remember it as read-set.
   CHECK_ERROR_CODE(cur_xct->on_record_read(
     intended_for_write,
     page->get_owner_id(index),
     &observed_,
     &readset_,
     true,       // no_readset_if_moved. see below
     true));     // no_readset_if_next_layer. see below
   ASSERT_ND(!observed_.is_being_written());
   ASSERT_ND(observed_.is_valid());
   if (observed_.is_moved() || observed_.is_next_layer()) {
     // Once it becomes a next-layer or moved pointer, it never goes back to a normal record.
     // so, there is no point to keep the read-set acquired in on_record_read().
     // We thus give parameters above that tell on_record_read() to not take read-set in the case.
     ASSERT_ND(readset_ == nullptr);  // let's confirm it
   }
   return kErrorCodeOk;
 }
Member Data Documentation
SlotIndex foedus::storage::masstree::RecordLocation::index_
Index of the record in the page.
kBorderPageMaxSlots if not found.
Definition at line 43 of file masstree_record_location.hpp.
Referenced by foedus::storage::masstree::MasstreeStoragePimpl::increment_general(), foedus::storage::masstree::MasstreeStoragePimpl::insert_general(), foedus::storage::masstree::MasstreeStoragePimpl::overwrite_general(), populate_logical(), foedus::storage::masstree::MasstreeStoragePimpl::register_record_write_log(), foedus::storage::masstree::MasstreeStoragePimpl::retrieve_general(), foedus::storage::masstree::MasstreeStoragePimpl::retrieve_part_general(), and foedus::storage::masstree::MasstreeStoragePimpl::upsert_general().
xct::XctId foedus::storage::masstree::RecordLocation::observed_
TID as of locate_record() identifying the record.
See foedus::storage::hash::RecordLocation.
Definition at line 48 of file masstree_record_location.hpp.
Referenced by foedus::storage::masstree::MasstreeStoragePimpl::delete_general(), foedus::storage::masstree::MasstreeStoragePimpl::increment_general(), foedus::storage::masstree::MasstreeStoragePimpl::insert_general(), foedus::storage::masstree::MasstreeCursor::next(), foedus::storage::masstree::MasstreeCursor::open(), foedus::storage::masstree::MasstreeStoragePimpl::overwrite_general(), populate_logical(), foedus::storage::masstree::MasstreeStoragePimpl::reserve_record(), foedus::storage::masstree::MasstreeStoragePimpl::reserve_record_normalized(), foedus::storage::masstree::MasstreeStoragePimpl::retrieve_general(), foedus::storage::masstree::MasstreeStoragePimpl::retrieve_part_general(), and foedus::storage::masstree::MasstreeStoragePimpl::upsert_general().
MasstreeBorderPage* foedus::storage::masstree::RecordLocation::page_
The border page containing the record.
Definition at line 41 of file masstree_record_location.hpp.
Referenced by foedus::storage::masstree::MasstreeStoragePimpl::delete_general(), foedus::storage::masstree::MasstreeStoragePimpl::increment_general(), foedus::storage::masstree::MasstreeStoragePimpl::insert_general(), foedus::storage::masstree::MasstreeStoragePimpl::overwrite_general(), populate_logical(), foedus::storage::masstree::MasstreeStoragePimpl::register_record_write_log(), foedus::storage::masstree::MasstreeStoragePimpl::retrieve_general(), foedus::storage::masstree::MasstreeStoragePimpl::retrieve_part_general(), and foedus::storage::masstree::MasstreeStoragePimpl::upsert_general().
xct::ReadXctAccess* foedus::storage::masstree::RecordLocation::readset_
If this method took a read-set on the returned record, points to the corresponding read-set.
Otherwise nullptr.
Definition at line 54 of file masstree_record_location.hpp.
Referenced by populate_logical(), and foedus::storage::masstree::MasstreeStoragePimpl::register_record_write_log().
The documentation for this struct was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/storage/masstree/masstree_record_location.hpp
/home/shino/foedus_code/foedus-core/src/foedus/storage/masstree/masstree_record_location.cpp