libfoedus-core: foedus::storage::hash::RecordLocation Struct Reference
foedus::storage::hash::RecordLocation Struct Reference
return value of locate_record().
Detailed Description
return value of locate_record().
Notes on XID, MOCC Locking, read-set, and "physical_only"
This object also contains observed_, which is guaranteed to be the XID at or before the return from locate_record(). There is a notable contract here. When locking in MOCC kicks in, we want to make sure we return the value of XID after the lock to eliminate a chance of false verification failure. However, this means we need to take lock and register read-set within locate_record(). This caused us headaches for the following reason.
Logical vs Physical search in hash pages
Physically finding a record for given key in our hash page has the following guarantees.
When it finds a record, the record was at least at some point a valid (non-moved/non-being-written) record of the given key.
When it doesn't find any record, the page(s) at least at some point didn't contain any valid record of the given key.
On the other hand, it still allows the following behaviors:
The found record is now being moved or modified.
The page or its next page(s) is now newly inserting a physical record of the given key.
Logically finding a record provides additional guarantee to protect against the above at pre-commit time. It additionally takes read-set, page-version set, or even MOCC locks.
locate_record(): Logical or Physical
We initially designed locate_record() as a physical-only search operation separated from logical operations (e.g., get_record/overwrite_record, or the caller). Separation makes each of them simpler and more flexible. The logical side can separately decide, using an operation-specific logic, whether/when it will add the XID observed in locate_record() to read-set or not. The physical side (locate_record()) can be dumb simple, too.
But, seems like this is now unavoidable. Hence now locate_record() is a logical operation. To allow the caller to choose what to do logically, we receive a paramter physical_only. When false, locate_record might take logical lock and add the XID to readset, hence what locate_record() observed is protected. When true, locate_record never takes lock or adds it to readset. It just physically locates a record that was at least at some point a valid record. In this case, the caller is responsible to do appropriate thing to protect from concurrent modifications.
Definition at line 76 of file hash_record_location.hpp.
#include <hash_record_location.hpp>
Public Member Functions
bool is_found () const
uint16_t get_aligned_key_length () const
uint16_t get_max_payload () const
void clear ()
ErrorCode populate_logical (xct::Xct *cur_xct, HashDataPage *page, DataPageSlotIndex index, bool intended_for_write)
Populates the result with XID and possibly readset.
void populate_physical (HashDataPage *page, DataPageSlotIndex index)
Populates fields other than readset_.
Public Attributes
HashDataPage * page_
The data page (might not be bin-head) containing the record.
DataPageSlotIndex index_
Index of the record in the page.
uint16_t cur_payload_length_
Logical payload length as-of the observed XID.
uint16_t key_length_
Key length of the slot, which is immutable.
uint16_t physical_record_length_
Byte count the record of the slot occupies, which is immutable.
char * record_
Address of the record.
xct::XctId observed_
TID as of locate_record() identifying the record.
xct::ReadXctAccess * readset_
If this method took a read-set on the returned record, points to the corresponding read-set.
Member Function Documentation
void foedus::storage::hash::RecordLocation::clear () inline
Definition at line 114 of file hash_record_location.hpp.
References CXX11_NULLPTR, foedus::xct::XctId::data_, and foedus::storage::hash::kSlotNotFound.
Referenced by foedus::storage::hash::HashStoragePimpl::locate_record(), and foedus::storage::hash::HashStoragePimpl::locate_record_in_snapshot().
                {
     page_ = CXX11_NULLPTR;
     index_ = kSlotNotFound;
     cur_payload_length_ = 0;
     key_length_ = 0;
     physical_record_length_ = 0;
     record_ = CXX11_NULLPTR;
     observed_.data_ = 0;
     readset_ = CXX11_NULLPTR;
   }
uint16_t foedus::storage::hash::RecordLocation::get_aligned_key_length () const inline
Definition at line 109 of file hash_record_location.hpp.
References foedus::assorted::align8().
Referenced by get_max_payload(), foedus::storage::hash::HashStoragePimpl::get_record(), foedus::storage::hash::HashStoragePimpl::get_record_part(), and foedus::storage::hash::HashStoragePimpl::increment_record().
 { return assorted::align8(key_length_); }
uint16_t foedus::storage::hash::RecordLocation::get_max_payload () const inline
Definition at line 110 of file hash_record_location.hpp.
References get_aligned_key_length().
Referenced by foedus::storage::hash::HashStoragePimpl::insert_record(), and foedus::storage::hash::HashStoragePimpl::upsert_record().
{
     return physical_record_length_ - get_aligned_key_length();
   }
bool foedus::storage::hash::RecordLocation::is_found () const inline
Definition at line 108 of file hash_record_location.hpp.
References foedus::storage::hash::kSlotNotFound.
Referenced by foedus::storage::hash::HashStoragePimpl::delete_record(), foedus::storage::hash::HashStoragePimpl::get_record(), foedus::storage::hash::HashStoragePimpl::get_record_part(), foedus::storage::hash::HashStoragePimpl::increment_record(), foedus::storage::hash::HashStoragePimpl::insert_record(), foedus::storage::hash::HashStoragePimpl::overwrite_record(), foedus::storage::hash::HashStoragePimpl::register_record_write_log(), and foedus::storage::hash::HashStoragePimpl::upsert_record().
 { return index_ != kSlotNotFound; }
ErrorCode foedus::storage::hash::RecordLocation::populate_logical (xct::Xct * cur_xct, HashDataPage * page, DataPageSlotIndex index, bool intended_for_write)
Populates the result with XID and possibly readset.
This is a logical operation that might take a readset.
Definition at line 27 of file hash_record_location.cpp.
References ASSERT_ND, CHECK_ERROR_CODE, cur_payload_length_, foedus::storage::hash::HashDataPage::get_slot_address(), index_, foedus::xct::XctId::is_being_written(), foedus::xct::XctId::is_moved(), foedus::xct::XctId::is_next_layer(), foedus::xct::XctId::is_valid(), foedus::kErrorCodeOk, key_length_, foedus::storage::hash::HashDataPage::Slot::key_length_, foedus::assorted::memory_fence_consume(), observed_, foedus::storage::hash::HashDataPage::Slot::offset_, foedus::xct::Xct::on_record_read(), page_, foedus::storage::hash::HashDataPage::Slot::payload_length_, physical_record_length_, foedus::storage::hash::HashDataPage::Slot::physical_record_length_, readset_, record_, foedus::storage::hash::HashDataPage::record_from_offset(), foedus::storage::hash::HashDataPage::Slot::tid_, and foedus::xct::RwLockableXctId::xct_id_.
Referenced by foedus::storage::hash::HashStoragePimpl::locate_record().
{
   page_ = page;
   index_ = index;
   readset_ = nullptr;
   HashDataPage::Slot* slot = page->get_slot_address(index);
   record_ = page->record_from_offset(slot->offset_);
   key_length_ = slot->key_length_;  // key_length is immutable, so just read it.
   physical_record_length_ = slot->physical_record_length_;  // immutable, too.
   // cur_payload_length_ is mutable, so must be retrieved _as of_ the XID.
   // we thus need a retry loop.
   while (true) {
     xct::XctId before = slot->tid_.xct_id_;
     assorted::memory_fence_consume();
     cur_payload_length_ = slot->payload_length_;
     assorted::memory_fence_consume();
     // [Logical check]: Read XID in a finalized fashion. If we found it "moved",
     // then we don't need to remember it as read-set.
     CHECK_ERROR_CODE(cur_xct->on_record_read(
       intended_for_write,
       &slot->tid_,
       &observed_,
       &readset_,
       true,       // no_readset_if_moved. see below
       true));     // no_readset_if_next_layer. see below
     ASSERT_ND(!observed_.is_being_written());
     ASSERT_ND(!observed_.is_next_layer());  // we don't use this flag in hash. never occurs
     ASSERT_ND(observed_.is_valid());
     if (observed_ == before) {
       // The consume fences make sure we are seeing in this order.
       // 1. read "before"
       // 2. read payload_length_
       // 3. read observed_
       // thus, observed==before guarantees that payload_length_ is *as of* observed_.
       break;
     }
   }
   if (observed_.is_moved()) {
     ASSERT_ND(readset_ == nullptr);
   }
   return kErrorCodeOk;
 }
void foedus::storage::hash::RecordLocation::populate_physical (HashDataPage * page, DataPageSlotIndex index)
Populates fields other than readset_.
This is a physical-only operation that never takes readset/locks.
Definition at line 79 of file hash_record_location.cpp.
References ASSERT_ND, cur_payload_length_, foedus::storage::hash::HashDataPage::get_slot_address(), index_, foedus::xct::XctId::is_being_written(), foedus::xct::XctId::is_next_layer(), foedus::xct::XctId::is_valid(), key_length_, foedus::storage::hash::HashDataPage::Slot::key_length_, observed_, foedus::storage::hash::HashDataPage::Slot::offset_, page_, foedus::storage::hash::HashDataPage::Slot::payload_length_, physical_record_length_, foedus::storage::hash::HashDataPage::Slot::physical_record_length_, readset_, record_, foedus::storage::hash::HashDataPage::record_from_offset(), foedus::xct::XctId::spin_while_being_written(), foedus::storage::hash::HashDataPage::Slot::tid_, and foedus::xct::RwLockableXctId::xct_id_.
Referenced by foedus::storage::hash::HashStoragePimpl::locate_record(), and foedus::storage::hash::HashStoragePimpl::locate_record_in_snapshot().
{
   page_ = page;
   index_ = index;
   readset_ = nullptr;
   HashDataPage::Slot* slot = page->get_slot_address(index);
   cur_payload_length_ = slot->payload_length_;  // no worry on physical-only read.
   key_length_ = slot->key_length_;
   physical_record_length_ = slot->physical_record_length_;
   record_ = page->record_from_offset(slot->offset_);
   observed_ = slot->tid_.xct_id_.spin_while_being_written();
   ASSERT_ND(!observed_.is_being_written());
   ASSERT_ND(!observed_.is_next_layer());  // we don't use this flag in hash. never occurs
   ASSERT_ND(observed_.is_valid());
 }
Member Data Documentation
uint16_t foedus::storage::hash::RecordLocation::cur_payload_length_
Logical payload length as-of the observed XID.
payload_length_ in hash page slot is mutable, so this must be paired with observed_ in serializable transactions.
Definition at line 86 of file hash_record_location.hpp.
Referenced by foedus::storage::hash::HashStoragePimpl::get_record(), foedus::storage::hash::HashStoragePimpl::get_record_part(), foedus::storage::hash::HashStoragePimpl::increment_record(), foedus::storage::hash::HashStoragePimpl::overwrite_record(), populate_logical(), populate_physical(), and foedus::storage::hash::HashStoragePimpl::upsert_record().
DataPageSlotIndex foedus::storage::hash::RecordLocation::index_
Index of the record in the page.
kSlotNotFound if not found.
Definition at line 80 of file hash_record_location.hpp.
Referenced by foedus::storage::hash::HashStoragePimpl::insert_record(), populate_logical(), populate_physical(), foedus::storage::hash::HashStoragePimpl::register_record_write_log(), and foedus::storage::hash::HashStoragePimpl::upsert_record().
uint16_t foedus::storage::hash::RecordLocation::key_length_
Key length of the slot, which is immutable.
Definition at line 88 of file hash_record_location.hpp.
Referenced by populate_logical(), and populate_physical().
xct::XctId foedus::storage::hash::RecordLocation::observed_
TID as of locate_record() identifying the record.
guaranteed to be not is_moved (then automatically retried), though the current TID might be now moved, in which case pre-commit will catch it. See the class comment.
Definition at line 100 of file hash_record_location.hpp.
Referenced by foedus::storage::hash::HashStoragePimpl::delete_record(), foedus::storage::hash::HashStoragePimpl::increment_record(), foedus::storage::hash::HashStoragePimpl::insert_record(), foedus::storage::hash::HashStoragePimpl::locate_record(), foedus::storage::hash::HashStoragePimpl::locate_record_in_snapshot(), foedus::storage::hash::HashStoragePimpl::overwrite_record(), populate_logical(), populate_physical(), and foedus::storage::hash::HashStoragePimpl::upsert_record().
HashDataPage* foedus::storage::hash::RecordLocation::page_
The data page (might not be bin-head) containing the record.
Definition at line 78 of file hash_record_location.hpp.
Referenced by foedus::storage::hash::HashStoragePimpl::insert_record(), populate_logical(), populate_physical(), foedus::storage::hash::HashStoragePimpl::register_record_write_log(), and foedus::storage::hash::HashStoragePimpl::upsert_record().
uint16_t foedus::storage::hash::RecordLocation::physical_record_length_
Byte count the record of the slot occupies, which is immutable.
Definition at line 90 of file hash_record_location.hpp.
Referenced by populate_logical(), and populate_physical().
xct::ReadXctAccess* foedus::storage::hash::RecordLocation::readset_
If this method took a read-set on the returned record, points to the corresponding read-set.
Otherwise nullptr.
Definition at line 106 of file hash_record_location.hpp.
Referenced by populate_logical(), populate_physical(), and foedus::storage::hash::HashStoragePimpl::register_record_write_log().
char* foedus::storage::hash::RecordLocation::record_
Address of the record.
null if not found.
Definition at line 93 of file hash_record_location.hpp.
Referenced by foedus::storage::hash::HashStoragePimpl::get_record(), foedus::storage::hash::HashStoragePimpl::get_record_part(), foedus::storage::hash::HashStoragePimpl::increment_record(), foedus::storage::hash::HashStoragePimpl::insert_record(), populate_logical(), populate_physical(), foedus::storage::hash::HashStoragePimpl::register_record_write_log(), and foedus::storage::hash::HashStoragePimpl::upsert_record().
The documentation for this struct was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/storage/hash/hash_record_location.hpp
/home/shino/foedus_code/foedus-core/src/foedus/storage/hash/hash_record_location.cpp