libfoedus-core: foedus::memory::AlignedMemorySlice Struct Reference
foedus::memory::AlignedMemorySlice Struct Reference final
FOEDUS Components » Memory Manager
A slice of foedus::memory::AlignedMemory.
Detailed Description
A slice of foedus::memory::AlignedMemory.
This class is used to split a single (often large) foedus::memory::AlignedMemory to be used by multiple consumers. Such use has a performance advantage because many smaller memory pieces are consolidated to one large piece from the viewpoint of OS. In particular, it might be that allocating a consolidated memory triggers transparent hugepage while allocating individual memory does not.
This object is a POD.
Definition at line 210 of file aligned_memory.hpp.
#include <aligned_memory.hpp>
Public Member Functions
AlignedMemorySlice ()
Empty constructor.
AlignedMemorySlice (AlignedMemory *memory)
A dummy slice that covers the memory entirely.
AlignedMemorySlice (AlignedMemory *memory, uint64_t offset, uint64_t count)
A slice that covers the specified region of the memory.
AlignedMemorySlice (const AlignedMemorySlice &slice, uint64_t offset, uint64_t count)
A slice that covers the specified region of another slice.
void clear ()
bool is_valid () const
uint64_t get_size () const
void * get_block () const
Public Attributes
AlignedMemory * memory_
The wrapped memory.
uint64_t offset_
Byte offset of this slice in memory_.
uint64_t count_
Byte count of this slice in memory_.
Friends
std::ostream & operator<< (std::ostream &o, const AlignedMemorySlice &v)
Constructor & Destructor Documentation
foedus::memory::AlignedMemorySlice::AlignedMemorySlice () inline
Empty constructor.
Definition at line 212 of file aligned_memory.hpp.
 : memory_(CXX11_NULLPTR), offset_(0), count_(0) {}
foedus::memory::AlignedMemorySlice::AlignedMemorySlice (AlignedMemory * memory) inline explicit
A dummy slice that covers the memory entirely.
Definition at line 215 of file aligned_memory.hpp.
     : memory_(memory), offset_(0), count_(memory->get_size()) {}
foedus::memory::AlignedMemorySlice::AlignedMemorySlice (AlignedMemory * memory, uint64_t offset, uint64_t count) inline
A slice that covers the specified region of the memory.
Definition at line 219 of file aligned_memory.hpp.
References ASSERT_ND, and foedus::memory::AlignedMemory::get_size().
     : memory_(memory), offset_(offset), count_(count) {
     ASSERT_ND(memory->get_size() >= count + offset);
   }
foedus::memory::AlignedMemorySlice::AlignedMemorySlice (const AlignedMemorySlice & slice, uint64_t offset, uint64_t count) inline
A slice that covers the specified region of another slice.
Definition at line 225 of file aligned_memory.hpp.
References ASSERT_ND, and get_size().
     : memory_(slice.memory_), offset_(slice.offset_ + offset), count_(count) {
     ASSERT_ND(slice.get_size() >= count + offset);
   }
Member Function Documentation
void foedus::memory::AlignedMemorySlice::clear () inline
Definition at line 232 of file aligned_memory.hpp.
References CXX11_NULLPTR, and memory_.
Referenced by foedus::memory::NumaCoreMemory::uninitialize_once().
 { memory_ = CXX11_NULLPTR; }
void* foedus::memory::AlignedMemorySlice::get_block () const inline
Definition at line 235 of file aligned_memory.hpp.
References foedus::memory::AlignedMemory::get_block(), memory_, and offset_.
Referenced by foedus::log::ThreadLogBuffer::initialize_once(), foedus::fs::DirectIoFile::read(), and foedus::fs::DirectIoFile::write().
 { return reinterpret_cast<char*>(memory_->get_block()) + offset_; }
uint64_t foedus::memory::AlignedMemorySlice::get_size () const inline
Definition at line 234 of file aligned_memory.hpp.
References count_.
Referenced by AlignedMemorySlice(), and foedus::log::ThreadLogBuffer::initialize_once().
 { return count_; }
bool foedus::memory::AlignedMemorySlice::is_valid () const inline
Definition at line 233 of file aligned_memory.hpp.
References memory_.
Referenced by foedus::fs::DirectIoFile::write().
 { return memory_; }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const AlignedMemorySlice & v) friend
Definition at line 282 of file aligned_memory.cpp.
{
   o << "<AlignedMemorySlice>";
   o << "<offset>" << v.offset_ << "</offset>";
   o << "<count>" << v.count_ << "</count>";
   if (v.memory_) {
     o << *v.memory_;
   }
   o << "</AlignedMemorySlice>";
   return o;
 }
Member Data Documentation
uint64_t foedus::memory::AlignedMemorySlice::count_
Byte count of this slice in memory_.
Definition at line 242 of file aligned_memory.hpp.
Referenced by get_size(), foedus::memory::operator<<(), foedus::fs::DirectIoFile::read(), and foedus::fs::DirectIoFile::write().
AlignedMemory* foedus::memory::AlignedMemorySlice::memory_
The wrapped memory.
This object is just a view. It doesn't release the block.
Definition at line 238 of file aligned_memory.hpp.
Referenced by clear(), get_block(), is_valid(), foedus::memory::operator<<(), foedus::fs::DirectIoFile::read(), and foedus::fs::DirectIoFile::write().
uint64_t foedus::memory::AlignedMemorySlice::offset_
Byte offset of this slice in memory_.
Definition at line 240 of file aligned_memory.hpp.
Referenced by get_block(), and foedus::memory::operator<<().
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/memory/aligned_memory.hpp