libfoedus-core: foedus::assorted::BacktraceContext Struct Reference
foedus::assorted::BacktraceContext Struct Reference
Detailed Description
Definition at line 36 of file rich_backtrace.cpp.
Classes
struct GlibcBacktraceInfo
struct LibBacktraceInfo
Public Types
enum Constants { kMaxDepth = 64 }
Public Member Functions
BacktraceContext ()
~BacktraceContext ()
void release ()
void call_glibc_backtrace ()
void on_libbt_create_state_error (const char *msg, int errnum)
void on_libbt_full_error (const char *msg, int errnum)
void on_libbt_full (uintptr_t pc, const char *filename, int lineno, const char *function)
std::vector< std::string > get_results (uint16_t skip)
Public Attributes
std::string error_
std::vector< GlibcBacktraceInfo > glibc_bt_info_
std::vector< LibBacktraceInfo > libbt_info_
Class Documentation
struct foedus::assorted::BacktraceContext::LibBacktraceInfo
Definition at line 48 of file rich_backtrace.cpp.
Class Members
uintptr_t address_
string function_
string srcfile_
int srclineno_
Member Enumeration Documentation
enum foedus::assorted::BacktraceContext::Constants
Enumerator
kMaxDepth
Definition at line 37 of file rich_backtrace.cpp.
                  {
     kMaxDepth = 64,
   };
Constructor & Destructor Documentation
foedus::assorted::BacktraceContext::BacktraceContext () inline
Definition at line 55 of file rich_backtrace.cpp.
 {}
foedus::assorted::BacktraceContext::~BacktraceContext () inline
Definition at line 56 of file rich_backtrace.cpp.
References release().
 { release(); }
Member Function Documentation
void foedus::assorted::BacktraceContext::call_glibc_backtrace () inline
Definition at line 63 of file rich_backtrace.cpp.
References foedus::assorted::BacktraceContext::GlibcBacktraceInfo::address_, glibc_bt_info_, kMaxDepth, foedus::assorted::BacktraceContext::GlibcBacktraceInfo::parse_symbol(), release(), and foedus::assorted::BacktraceContext::GlibcBacktraceInfo::symbol_.
Referenced by foedus::assorted::get_backtrace().
{
     release();
     void* addresses[kMaxDepth];
     int depth = ::backtrace(addresses, kMaxDepth);
     char** symbols = ::backtrace_symbols(addresses, depth);
     for (int i = 1; i < depth; ++i) {  // start from 1 to skip this method (call_glibc_backtrace)
       GlibcBacktraceInfo info;
       info.address_ = addresses[i];
       info.symbol_ = symbols[i];
       info.parse_symbol();
       glibc_bt_info_.emplace_back(info);
     }
     ::free(symbols);
   }
std::vector< std::string > foedus::assorted::BacktraceContext::get_results (uint16_t skip)
Definition at line 217 of file rich_backtrace.cpp.
References foedus::assorted::BacktraceContext::GlibcBacktraceInfo::address_, foedus::assorted::BacktraceContext::LibBacktraceInfo::address_, foedus::assorted::BacktraceContext::GlibcBacktraceInfo::binary_path_, foedus::assorted::demangle_type_name(), error_, foedus::assorted::BacktraceContext::GlibcBacktraceInfo::function_, foedus::assorted::BacktraceContext::LibBacktraceInfo::function_, glibc_bt_info_, libbt_info_, foedus::assorted::BacktraceContext::LibBacktraceInfo::srcfile_, foedus::assorted::BacktraceContext::LibBacktraceInfo::srclineno_, and foedus::assorted::BacktraceContext::GlibcBacktraceInfo::symbol_.
Referenced by foedus::assorted::get_backtrace().
{
   std::vector< std::string > ret;
   if (!error_.empty()) {
     // If error happened, add it as the first entry.
     ret.emplace_back(error_);
     // still outputs the following as best-effort
   }
   for (uint16_t i = skip; i < glibc_bt_info_.size(); ++i) {
     std::stringstream str;
     const GlibcBacktraceInfo& libc = glibc_bt_info_[i];
     bool has_libbt = i < libbt_info_.size();
     str << "in ";
     std::string function;
     if (has_libbt && !libbt_info_[i].function_.empty()) {
       const LibBacktraceInfo& libbt = libbt_info_[i];
       // libbacktrace successfully got the information. it can provide the most helpful info
       str << demangle_type_name(libbt.function_.c_str())
         << " " << libbt.srcfile_ << ":" << libbt.srclineno_
         << "  (" << libc.binary_path_ << ")"
         << "  [" << assorted::Hex(libbt.address_) << "]";
       // also append glibc backtrace info.
       str << " (glibc: " << assorted::Hex(reinterpret_cast<uintptr_t>(libc.address_)) << ")";
     } else {
       // sometimes libbacktrace fails to parse a stack even glibc can parse.. probably a bug
       if (!libc.function_.empty()) {
         str << demangle_type_name(libc.function_.c_str());
       } else {
         str << "???";
       }
       str << " : " << libc.symbol_;
       if (has_libbt) {
         // also append libbacktrace info.
         const LibBacktraceInfo& libbt = libbt_info_[i];
         str << " (libbacktrace:";
         if (!libbt.srcfile_.empty() || libbt.srclineno_ != 0) {
           str << " " << libbt.srcfile_ << ":" << libbt.srclineno_;
         }
         str << " [" << assorted::Hex(libbt.address_) << "]" << ")";
       }
     }
     ret.emplace_back(str.str());
   }
   return ret;
 }
void foedus::assorted::BacktraceContext::on_libbt_create_state_error (const char * msg, int errnum) inline
Definition at line 77 of file rich_backtrace.cpp.
References error_, and foedus::assorted::os_error().
{
     std::stringstream message;
     message << "libbacktrace failed to create state. msg=" << msg << ", err=" << os_error(errnum);
     error_ = message.str();
   }
void foedus::assorted::BacktraceContext::on_libbt_full (uintptr_t pc, const char * filename, int lineno, const char * function) inline
Definition at line 90 of file rich_backtrace.cpp.
References foedus::assorted::BacktraceContext::LibBacktraceInfo::address_, foedus::assorted::BacktraceContext::LibBacktraceInfo::function_, libbt_info_, foedus::assorted::BacktraceContext::LibBacktraceInfo::srcfile_, and foedus::assorted::BacktraceContext::LibBacktraceInfo::srclineno_.
{
     if (pc == -1ULL && filename == nullptr && function == nullptr) {
       // not sure why this happens, but libbacktrace occasionally gives such a dummy entry
       return;
     }
     LibBacktraceInfo info;
     info.address_ = pc;
     if (filename) {
       info.srcfile_ = filename;
     }
     info.srclineno_ = lineno;
     if (function) {
       info.function_ = function;
     }
     libbt_info_.emplace_back(info);
   }
void foedus::assorted::BacktraceContext::on_libbt_full_error (const char * msg, int errnum) inline
Definition at line 83 of file rich_backtrace.cpp.
References error_, and foedus::assorted::os_error().
{
     std::stringstream message;
     std::cerr << "libbacktrace failed to obtain backtrace. msg=" << msg
       << ", err=" << os_error(errnum);
     error_ = message.str();
   }
void foedus::assorted::BacktraceContext::release () inline
Definition at line 57 of file rich_backtrace.cpp.
References error_, glibc_bt_info_, and libbt_info_.
Referenced by call_glibc_backtrace(), and ~BacktraceContext().
                  {
     error_.clear();
     glibc_bt_info_.clear();
     libbt_info_.clear();
   }
Member Data Documentation
std::string foedus::assorted::BacktraceContext::error_
Definition at line 113 of file rich_backtrace.cpp.
Referenced by get_results(), on_libbt_create_state_error(), on_libbt_full_error(), and release().
std::vector<GlibcBacktraceInfo> foedus::assorted::BacktraceContext::glibc_bt_info_
Definition at line 114 of file rich_backtrace.cpp.
Referenced by call_glibc_backtrace(), get_results(), and release().
std::vector<LibBacktraceInfo> foedus::assorted::BacktraceContext::libbt_info_
Definition at line 115 of file rich_backtrace.cpp.
Referenced by get_results(), on_libbt_full(), and release().
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/src/foedus/assorted/rich_backtrace.cpp