libfoedus-core: foedus::storage::masstree::OwnerSamples Struct Reference
foedus::storage::masstree::OwnerSamples Struct Reference
Number of vol pages in each node sampled per pointer in the root page.
Detailed Description
Number of vol pages in each node sampled per pointer in the root page.
Will be probably used in other partitioners, too.
Definition at line 155 of file masstree_partitioner_impl.hpp.
#include <masstree_partitioner_impl.hpp>
Public Member Functions
OwnerSamples (uint32_t nodes, uint32_t subtrees)
~OwnerSamples ()
void increment (uint32_t node, uint32_t subtree_id)
uint32_t at (uint32_t node, uint32_t subtree_id) const
uint32_t get_assignment (uint32_t subtree_id) const
void assign_owners ()
Determine assignments based on the samples.
Public Attributes
const uint32_t nodes_
number of nodes
const uint32_t subtrees_
number of pointers to children in the root page
uint32_t * occurrences_
number of occurences of a volatile page in the node.
uint32_t * assignments_
node_id to be the owner of the subtree
Friends
std::ostream & operator<< (std::ostream &o, const OwnerSamples &v)
Constructor & Destructor Documentation
foedus::storage::masstree::OwnerSamples::OwnerSamples (uint32_t nodes, uint32_t subtrees) inline
Definition at line 156 of file masstree_partitioner_impl.hpp.
References assignments_, and occurrences_.
                                                   : nodes_(nodes), subtrees_(subtrees) {
     occurrences_ = new uint32_t[nodes * subtrees];
     std::memset(occurrences_, 0, sizeof(uint32_t) * nodes * subtrees);
     assignments_ = new uint32_t[subtrees];
     std::memset(assignments_, 0, sizeof(uint32_t) * subtrees);
   }
foedus::storage::masstree::OwnerSamples::~OwnerSamples () inline
Definition at line 162 of file masstree_partitioner_impl.hpp.
References assignments_, and occurrences_.
                   {
     delete[] occurrences_;
     occurrences_ = nullptr;
     delete[] assignments_;
     assignments_ = nullptr;
   }
Member Function Documentation
void foedus::storage::masstree::OwnerSamples::assign_owners ()
Determine assignments based on the samples.
Definition at line 216 of file masstree_partitioner_impl.cpp.
References assignments_, at(), nodes_, and subtrees_.
{
   // so far simply the node that has majority. but we might want to balance out
   for (uint32_t subtree_id = 0; subtree_id < subtrees_; ++subtree_id) {
     uint32_t max_node = 0;
     uint32_t max_count = at(0, subtree_id);
     for (uint32_t node = 1; node < nodes_; ++node) {
       if (at(node, subtree_id) > max_count) {
         max_node = node;
         max_count = at(node, subtree_id);
       }
     }
     assignments_[subtree_id] = max_node;
   }
 }
uint32_t foedus::storage::masstree::OwnerSamples::at (uint32_t node, uint32_t subtree_id) const inline
Definition at line 183 of file masstree_partitioner_impl.hpp.
References ASSERT_ND.
Referenced by assign_owners(), and foedus::storage::masstree::operator<<().
{
     ASSERT_ND(node < nodes_);
     ASSERT_ND(subtree_id < subtrees_);
     return occurrences_[subtree_id * nodes_ + node];
   }
uint32_t foedus::storage::masstree::OwnerSamples::get_assignment (uint32_t subtree_id) const inline
Definition at line 189 of file masstree_partitioner_impl.hpp.
Referenced by foedus::storage::masstree::operator<<().
 { return assignments_[subtree_id]; }
void foedus::storage::masstree::OwnerSamples::increment (uint32_t node, uint32_t subtree_id) inline
Definition at line 178 of file masstree_partitioner_impl.hpp.
References ASSERT_ND.
Referenced by foedus::storage::masstree::design_partition_first_parallel_recurse().
{
     ASSERT_ND(node < nodes_);
     ASSERT_ND(subtree_id < subtrees_);
     ++occurrences_[subtree_id * nodes_ + node];
   }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const OwnerSamples & v) friend
Definition at line 231 of file masstree_partitioner_impl.cpp.
{
   o << "<OwnerSamples nodes=\"" << v.nodes_
     << "\" subtrees=\"" << v.subtrees_ << "\">" << std::endl;
   o << "<!-- legend id=\"x\" assignment=\"x\">";
   for (uint32_t node = 0; node < v.nodes_; ++node) {
     o << "[Node-" << node << "] ";
   }
   o << " -->" << std::endl;
   for (uint32_t subtree_id = 0; subtree_id < v.subtrees_; ++subtree_id) {
     o << "  <subtree id=\"" << subtree_id
       << "\" assignment=\"" << v.get_assignment(subtree_id) << "\">";
     for (uint32_t node = 0; node < v.nodes_; ++node) {
       o << assorted::Hex(v.at(node, subtree_id), 6) << " ";
     }
     o << "</subtree>" << std::endl;
   }
   o << std::endl << "</OwnerSamples>";
   return o;
 }
Member Data Documentation
uint32_t* foedus::storage::masstree::OwnerSamples::assignments_
node_id to be the owner of the subtree
Definition at line 176 of file masstree_partitioner_impl.hpp.
Referenced by assign_owners(), OwnerSamples(), and ~OwnerSamples().
const uint32_t foedus::storage::masstree::OwnerSamples::nodes_
number of nodes
Definition at line 170 of file masstree_partitioner_impl.hpp.
Referenced by assign_owners(), and foedus::storage::masstree::operator<<().
uint32_t* foedus::storage::masstree::OwnerSamples::occurrences_
number of occurences of a volatile page in the node.
See also
at()
Definition at line 174 of file masstree_partitioner_impl.hpp.
Referenced by OwnerSamples(), and ~OwnerSamples().
const uint32_t foedus::storage::masstree::OwnerSamples::subtrees_
number of pointers to children in the root page
Definition at line 172 of file masstree_partitioner_impl.hpp.
Referenced by assign_owners(), and foedus::storage::masstree::operator<<().
The documentation for this struct was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/storage/masstree/masstree_partitioner_impl.hpp
/home/shino/foedus_code/foedus-core/src/foedus/storage/masstree/masstree_partitioner_impl.cpp