libfoedus-core: foedus::storage::masstree::MasstreeOverwriteLogType Struct Reference
foedus::storage::masstree::MasstreeOverwriteLogType Struct Reference
FOEDUS Components » Storage Manager » Masstree StorageFOEDUS Components » Log Manager » | Log Types
Log type of masstree-storage's overwrite operation.
Detailed Description
Log type of masstree-storage's overwrite operation.
Same as insert log.
Definition at line 433 of file masstree_log_types.hpp.
#include <masstree_log_types.hpp>
Public Member Functions
MasstreeOverwriteLogType ()=delete
MasstreeOverwriteLogType (const MasstreeOverwriteLogType &other)=delete
~MasstreeOverwriteLogType ()=delete
void populate (StorageId storage_id, const void *key, KeyLength key_length, const void *payload, PayloadLength payload_offset, PayloadLength payload_count) __attribute__((always_inline))
void apply_record (thread::Thread *, StorageId, xct::RwLockableXctId *owner_id, char *data) const __attribute__((always_inline))
void assert_valid () const __attribute__((always_inline))
Public Member Functions inherited from foedus::storage::masstree::MasstreeCommonLogType
MasstreeCommonLogType ()=delete
MasstreeCommonLogType (const MasstreeCommonLogType &other)=delete
~MasstreeCommonLogType ()=delete
char * get_key ()
const char * get_key () const
KeySlice get_first_slice () const
KeyLength get_key_length_aligned () const
char * get_payload ()
const char * get_payload () const
void populate_base (log::LogCode type, StorageId storage_id, const void *key, KeyLength key_length, const void *payload=nullptr, PayloadLength payload_offset=0, PayloadLength payload_count=0) __attribute__((always_inline))
bool equal_record_and_log_suffixes (const char *data) const
used only for sanity check.
RecordAddresses apply_record_prepare (xct::RwLockableXctId *owner_id, char *record) const
Common parts of apply_record() in these log types that extract relevant addresses from the record header.
Public Member Functions inherited from foedus::log::RecordLogType
bool is_engine_log () const
bool is_storage_log () const
bool is_record_log () const
void apply_engine (thread::Thread *)
void apply_storage (Engine *, storage::StorageId)
void assert_valid_generic () const __attribute__((always_inline))
Verifies the log contains essential fields set.
Friends
std::ostream & operator<< (std::ostream &o, const MasstreeOverwriteLogType &v)
Additional Inherited Members
Static Public Member Functions inherited from foedus::storage::masstree::MasstreeCommonLogType
static uint16_t calculate_log_length (KeyLength key_length, PayloadLength payload_count) __attribute__((always_inline))
static int compare_logs (const MasstreeCommonLogType *left, const MasstreeCommonLogType *right) __attribute__((always_inline))
Returns -1, 0, 1 when left is less than, same, larger than right in terms of key and xct_id.
Public Attributes inherited from foedus::storage::masstree::MasstreeCommonLogType
KeyLength key_length_
PayloadLength payload_offset_
PayloadLength payload_count_
uint16_t reserved_
char aligned_data_ [8]
Full key and (if exists) payload data, both of which are padded to 8 bytes.
Public Attributes inherited from foedus::log::BaseLogType
LogHeader header_
Constructor & Destructor Documentation
foedus::storage::masstree::MasstreeOverwriteLogType::MasstreeOverwriteLogType () delete
foedus::storage::masstree::MasstreeOverwriteLogType::MasstreeOverwriteLogType (const MasstreeOverwriteLogType & other) delete
foedus::storage::masstree::MasstreeOverwriteLogType::~MasstreeOverwriteLogType () delete
Member Function Documentation
void foedus::storage::masstree::MasstreeOverwriteLogType::apply_record (thread::Thread * , StorageId , xct::RwLockableXctId * owner_id, char * data) const inline
Definition at line 449 of file masstree_log_types.hpp.
References ASSERT_ND, foedus::storage::masstree::MasstreeCommonLogType::RecordAddresses::record_payload_, and foedus::storage::masstree::MasstreeCommonLogType::RecordAddresses::record_payload_count_.
{
     RecordAddresses addresses = apply_record_prepare(owner_id, data);
     ASSERT_ND(!owner_id->xct_id_.is_deleted());
     ASSERT_ND(*addresses.record_payload_count_ >= payload_count_ + payload_offset_);
     if (payload_count_ > 0U) {
       const char* log_payload = get_payload();
       std::memcpy(
         addresses.record_payload_ + payload_offset_,
         log_payload,
         payload_count_);
     }
   }
void foedus::storage::masstree::MasstreeOverwriteLogType::assert_valid () const inline
Definition at line 466 of file masstree_log_types.hpp.
References ASSERT_ND, foedus::log::StorageLogType::assert_valid_generic(), foedus::log::LogHeader::get_type(), foedus::log::BaseLogType::header_, foedus::log::kLogCodeMasstreeOverwrite, and foedus::log::LogHeader::log_length_.
{
     assert_valid_generic();
     ASSERT_ND(header_.log_length_ == calculate_log_length(key_length_, payload_count_));
     ASSERT_ND(header_.get_type() == log::kLogCodeMasstreeOverwrite);
   }
void foedus::storage::masstree::MasstreeOverwriteLogType::populate (StorageId storage_id, const void * key, KeyLength key_length, const void * payload, PayloadLength payload_offset, PayloadLength payload_count) inline
Definition at line 436 of file masstree_log_types.hpp.
References ASSERT_ND, and foedus::log::kLogCodeMasstreeOverwrite.
Referenced by foedus::storage::masstree::MasstreeStoragePimpl::increment_general(), foedus::storage::masstree::MasstreeStoragePimpl::overwrite_general(), and foedus::storage::masstree::MasstreeStoragePimpl::upsert_general().
{
     log::LogCode type = log::kLogCodeMasstreeOverwrite;
     ASSERT_ND(payload_count > 0U);
     ASSERT_ND(key_length > 0U);
     populate_base(type, storage_id, key, key_length, payload, payload_offset, payload_count);
   }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const MasstreeOverwriteLogType & v) friend
Definition at line 83 of file masstree_log_types.cpp.
{
   o << "<MasstreeOverwriteLog>"
     << "<key_length_>" << v.key_length_ << "</key_length_>"
     << "<key_>" << assorted::Top(v.get_key(), v.key_length_) << "</key_>"
     << "<payload_offset_>" << v.payload_offset_ << "</payload_offset_>"
     << "<payload_count_>" << v.payload_count_ << "</payload_count_>"
     << "<payload_>" << assorted::Top(v.get_payload(), v.payload_count_) << "</payload_>"
     << "</MasstreeOverwriteLog>";
   return o;
 }
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/storage/masstree/masstree_log_types.hpp