libfoedus-core: foedus::assorted::ProtectedBoundary Struct Reference
foedus::assorted::ProtectedBoundary Struct Reference
FOEDUS Programming Idioms » Assorted Methods/Classes
A 4kb dummy data placed between separate memory regions so that we can check if/where a bogus memory access happens.
Detailed Description
A 4kb dummy data placed between separate memory regions so that we can check if/where a bogus memory access happens.
As a middleware, we often allocate a large chunk of memory and internally split it into smaller data regions. While it reduces overheads, that means a lack of memory boundary check. Instead, we place this dummy block to achieve it. When we shut down the system, we check if there happened any unexpected overrun between memory regions. In addition, we also use mprotect() to prohibit accesses to these dummy blocks, which would immediately fire up SIGSEGV for bogus access, making debugging easier.
mprotect() limit: max_map_count
mprotect() has one limitation: it could use up max_map_count. What you might observe is after around 64k mprotect() calls, it starts failing with ENOMEM. Moreover, all following memory allocations (eg mmap) also fail with ENOMEM once this starts happening. The issue goes away by increasing max_map_count : sudo sysctl -w vm.max_map_count=2147483647
Definition at line 56 of file protected_boundary.hpp.
#include <protected_boundary.hpp>
Public Types
enum Constants { kByteSize = 1 << 12, kMaxBoundaryNameLength = 128, kWordCount = (kByteSize - kMaxBoundaryNameLength) / 8 }
Public Member Functions
ErrorCode acquire_protect ()
Puts a strict access prohibition via mprotect().
ErrorCode release_protect ()
Removes all access restrictions via mprotect().
void reset (const std::string &boundary_name)
Fills the block with magic words.
void assert_boundary () const
Called at shutdown to check whether these boundaries were not accessed.
std::string get_boundary_name () const
Public Attributes
char boundary_name_ [kMaxBoundaryNameLength]
uint64_t data_ [kWordCount]
Member Enumeration Documentation
enum foedus::assorted::ProtectedBoundary::Constants
Enumerator
kByteSize
kMaxBoundaryNameLength
kWordCount
Definition at line 57 of file protected_boundary.hpp.
                  {
     kByteSize = 1 << 12,
     kMaxBoundaryNameLength = 128,
     kWordCount = (kByteSize - kMaxBoundaryNameLength) / 8,
   };
Member Function Documentation
ErrorCode foedus::assorted::ProtectedBoundary::acquire_protect ()
Puts a strict access prohibition via mprotect().
Attention
This method might cause severe performance degradation. Use in appropriate places. We use hugepages in most places, but mprotect() most likely splits the TLB entries to achieve the protection, throwing away the performance benefits of hugepages.
Note
this method is idempotent. safe to call multiple times
Returns
The only possible error is kErrorCodeOsMProtectFailed
Definition at line 25 of file protected_boundary.cpp.
References foedus::kErrorCodeOk, and foedus::kErrorCodeOsMProtectFailed.
Referenced by foedus::memory::PagePoolPimpl::initialize_once().
{
   int ret = ::mprotect(this, sizeof(ProtectedBoundary), PROT_NONE);
   if (ret != 0) {
     return kErrorCodeOsMProtectFailed;
   }
   return kErrorCodeOk;
 }
void foedus::assorted::ProtectedBoundary::assert_boundary () const inline
Called at shutdown to check whether these boundaries were not accessed.
Attention
This must be invoked AFTER release_protect()
Definition at line 103 of file protected_boundary.hpp.
References ASSERT_ND, and kWordCount.
Referenced by foedus::soc::SharedMemoryRepo::deallocate_shared_memories(), and foedus::memory::PagePoolPimpl::uninitialize_once().
{
     for (uint32_t i = 0; i < kWordCount; ++i) {
       ASSERT_ND(data_[i] == kProtectedBoundaryMagicWord);
     }
   }
std::string foedus::assorted::ProtectedBoundary::get_boundary_name () const inline
Definition at line 109 of file protected_boundary.hpp.
References ASSERT_ND, and kMaxBoundaryNameLength.
Referenced by foedus::memory::PagePoolPimpl::uninitialize_once().
{
     uint16_t len;
     for (len = 0; len < kMaxBoundaryNameLength; ++len) {
       if (boundary_name_[len] == 0) {
         break;
       }
     }
     ASSERT_ND(len < kMaxBoundaryNameLength);
     return std::string(boundary_name_, len);
   }
ErrorCode foedus::assorted::ProtectedBoundary::release_protect ()
Removes all access restrictions via mprotect().
Attention
This method might cause severe performance hit. Use in appropriate places.
Note
this method is idempotent. safe to call multiple times
Returns
The only possible error is kErrorCodeOsMProtectFailed
Definition at line 33 of file protected_boundary.cpp.
References foedus::kErrorCodeOk, and foedus::kErrorCodeOsMProtectFailed.
Referenced by foedus::soc::SharedMemoryRepo::deallocate_shared_memories(), and foedus::memory::PagePoolPimpl::uninitialize_once().
{
   int ret = ::mprotect(this, sizeof(ProtectedBoundary), PROT_READ | PROT_WRITE);
   if (ret != 0) {
     return kErrorCodeOsMProtectFailed;
   }
   return kErrorCodeOk;
 }
void foedus::assorted::ProtectedBoundary::reset (const std::string & boundary_name) inline
Fills the block with magic words.
Attention
This must be invoked BEFORE acquire_protect()
Definition at line 88 of file protected_boundary.hpp.
References kMaxBoundaryNameLength, foedus::assorted::kProtectedBoundaryMagicWord, and kWordCount.
Referenced by foedus::memory::PagePoolPimpl::initialize_once().
{
     uint16_t copy_len = std::min<uint64_t>(boundary_name.length(), kMaxBoundaryNameLength);
     boundary_name.copy(boundary_name_, copy_len, 0);
     if (copy_len < kMaxBoundaryNameLength) {
       std::memset(boundary_name_ + copy_len, 0, kMaxBoundaryNameLength- copy_len);
     }
     for (uint32_t i = 0; i < kWordCount; ++i) {
       data_[i] = kProtectedBoundaryMagicWord;
     }
   }
Member Data Documentation
char foedus::assorted::ProtectedBoundary::boundary_name_[kMaxBoundaryNameLength]
Definition at line 63 of file protected_boundary.hpp.
uint64_t foedus::assorted::ProtectedBoundary::data_[kWordCount]
Definition at line 64 of file protected_boundary.hpp.
The documentation for this struct was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/assorted/protected_boundary.hpp
/home/shino/foedus_code/foedus-core/src/foedus/assorted/protected_boundary.cpp