libfoedus-core: foedus::externalize::Externalizable Struct Reference
foedus::externalize::Externalizable Struct Reference abstract
FOEDUS Programming Idioms » Object Externalization
Represents an object that can be written to and read from files/bytes in XML format.
Detailed Description
Represents an object that can be written to and read from files/bytes in XML format.
Derived classes must implement load() and save().
Definition at line 53 of file externalizable.hpp.
#include <externalizable.hpp>
Public Member Functions
virtual ErrorStack load (tinyxml2::XMLElement *element)=0
Reads the content of this object from the given XML element.
virtual ErrorStack save (tinyxml2::XMLElement *element) const =0
Writes the content of this object to the given XML element.
virtual const char * get_tag_name () const =0
Returns an XML tag name for this object as a root element.
virtual void assign (const foedus::externalize::Externalizable *other)=0
Polymorphic assign operator.
ErrorStack load_from_string (const std::string &xml)
Load the content of this object from the given XML string.
void save_to_stream (std::ostream *ptr) const
Invokes save() and directs the resulting XML text to the given stream.
ErrorStack load_from_file (const fs::Path &path)
Load the content of this object from the specified XML file.
ErrorStack save_to_file (const fs::Path &path) const
Atomically and durably writes out this object to the specified XML file.
Static Public Member Functions
static ErrorStack insert_comment (tinyxml2::XMLElement *element, const std::string &comment)
static ErrorStack append_comment (tinyxml2::XMLElement *parent, const std::string &comment)
static ErrorStack create_element (tinyxml2::XMLElement *parent, const std::string &name, tinyxml2::XMLElement **out)
template<typename T >
static ErrorStack add_element (tinyxml2::XMLElement *parent, const std::string &tag, const std::string &comment, T value)
Only declaration in header.
template<uint MAXLEN, typename CHAR >
static ErrorStack add_element (tinyxml2::XMLElement *parent, const std::string &tag, const std::string &comment, const assorted::FixedString< MAXLEN, CHAR > &value)
template<typename T >
static ErrorStack add_element (tinyxml2::XMLElement *parent, const std::string &tag, const std::string &comment, const std::vector< T > &value)
vector version
template<typename ENUM >
static ErrorStack add_enum_element (tinyxml2::XMLElement *parent, const std::string &tag, const std::string &comment, ENUM value)
enum version
static ErrorStack add_child_element (tinyxml2::XMLElement *parent, const std::string &tag, const std::string &comment, const Externalizable &child)
child Externalizable version
template<typename T >
static ErrorStack get_element (tinyxml2::XMLElement *parent, const std::string &tag, T *out, bool optional=false, T value=0)
Only declaration in header.
static ErrorStack get_element (tinyxml2::XMLElement *parent, const std::string &tag, std::string *out, bool optional=false, const char *value="")
string type is bit special.
template<uint MAXLEN, typename CHAR >
static ErrorStack get_element (tinyxml2::XMLElement *parent, const std::string &tag, assorted::FixedString< MAXLEN, CHAR > *out, bool optional=false, const assorted::FixedString< MAXLEN, CHAR > &value=assorted::FixedString< MAXLEN, CHAR >())
template<typename ENUM >
static ErrorStack get_enum_element (tinyxml2::XMLElement *parent, const std::string &tag, ENUM *out, bool optional=false, ENUM default_value=static_cast< ENUM >(0))
enum version
template<typename T >
static ErrorStack get_element (tinyxml2::XMLElement *parent, const std::string &tag, std::vector< T > *out, bool optional=false)
vector version.
static ErrorStack get_child_element (tinyxml2::XMLElement *parent, const std::string &tag, Externalizable *child, bool optional=false)
child Externalizable version
Member Function Documentation
ErrorStack foedus::externalize::Externalizable::add_child_element (tinyxml2::XMLElement * parent, const std::string & tag, const std::string & comment, const Externalizable & child) static
child Externalizable version
Definition at line 221 of file externalizable.cpp.
References CHECK_ERROR, CHECK_OUTOFMEMORY, foedus::externalize::insert_comment_impl(), foedus::kRetOk, and save().
Referenced by foedus::log::LogOptions::save(), foedus::EngineOptions::save(), foedus::snapshot::SnapshotOptions::save(), foedus::storage::save_to_xml_array(), foedus::storage::save_to_xml_hash(), foedus::storage::save_to_xml_masstree(), and foedus::storage::save_to_xml_sequential().
{
   tinyxml2::XMLElement* element = parent->GetDocument()->NewElement(tag.c_str());
   CHECK_OUTOFMEMORY(element);
   parent->InsertEndChild(element);
   CHECK_ERROR(insert_comment_impl(element, comment));
   CHECK_ERROR(child.save(element));
   return kRetOk;
 }
template<typename T > ErrorStack foedus::externalize::Externalizable::add_element (tinyxml2::XMLElement * parent, const std::string & tag, const std::string & comment, T value) static
Only declaration in header.
Explicitly instantiated in cpp for each type this func handles.
Definition at line 200 of file externalizable.cpp.
References CHECK_ERROR, CHECK_OUTOFMEMORY, foedus::externalize::insert_comment_impl(), and foedus::kRetOk.
Referenced by add_element(), add_enum_element(), foedus::storage::sequential::SequentialMetadataSerializer::save(), foedus::storage::hash::HashMetadataSerializer::save(), foedus::storage::array::ArrayMetadataSerializer::save(), foedus::storage::masstree::MasstreeMetadataSerializer::save(), and foedus::storage::MetadataSerializer::save_base().
{
   tinyxml2::XMLElement* element = parent->GetDocument()->NewElement(tag.c_str());
   CHECK_OUTOFMEMORY(element);
   TinyxmlSetter<T> tinyxml_setter;
   tinyxml_setter(element, value);
   parent->InsertEndChild(element);
   if (comment.size() > 0) {
     CHECK_ERROR(insert_comment_impl(element,
             tag + " (type=" + assorted::get_pretty_type_name<T>() + "): " + comment));
   }
   return kRetOk;
 }
template<uint MAXLEN, typename CHAR > static ErrorStack foedus::externalize::Externalizable::add_element (tinyxml2::XMLElement * parent, const std::string & tag, const std::string & comment, const assorted::FixedString< MAXLEN, CHAR > & value) inline static
Definition at line 134 of file externalizable.hpp.
References foedus::assorted::FixedString< MAXLEN, CHAR >::str().
{
     return add_element< std::string >(parent, tag, comment, value.str());
   }
template<typename T > static ErrorStack foedus::externalize::Externalizable::add_element (tinyxml2::XMLElement * parent, const std::string & tag, const std::string & comment, const std::vector< T > & value) inline static
vector version
Definition at line 144 of file externalizable.hpp.
References add_element(), append_comment(), CHECK_ERROR, foedus::assorted::get_pretty_type_name(), and foedus::kRetOk.
{
     if (comment.size() > 0) {
       CHECK_ERROR(append_comment(parent,
         tag + " (type=" + assorted::get_pretty_type_name< std::vector< T > >()
           + "): " + comment));
     }
     for (std::size_t i = 0; i < value.size(); ++i) {
       CHECK_ERROR(add_element(parent, tag, "", value[i]));
     }
     return kRetOk;
   }
template<typename ENUM > static ErrorStack foedus::externalize::Externalizable::add_enum_element (tinyxml2::XMLElement * parent, const std::string & tag, const std::string & comment, ENUM value) inline static
enum version
Definition at line 159 of file externalizable.hpp.
References add_element().
Referenced by foedus::storage::MetadataSerializer::save_base().
{
     return add_element(parent, tag, comment, static_cast<int64_t>(value));
   }
ErrorStack foedus::externalize::Externalizable::append_comment (tinyxml2::XMLElement * parent, const std::string & comment) static
Definition at line 181 of file externalizable.cpp.
References CHECK_OUTOFMEMORY, and foedus::kRetOk.
Referenced by add_element().
{
   if (comment.size() > 0) {
     tinyxml2::XMLComment* cm = parent->GetDocument()->NewComment(comment.c_str());
     CHECK_OUTOFMEMORY(cm);
     parent->InsertEndChild(cm);
   }
   return kRetOk;
 }
virtual void foedus::externalize::Externalizable::assign (const foedus::externalize::Externalizable * other) pure virtual
Polymorphic assign operator.
This should invoke operator= of the derived class.
Parameters
[in] other assigned value. It must be dynamic-castable to the assignee class.
Implemented in foedus::snapshot::SnapshotOptions, foedus::EngineOptions, foedus::storage::masstree::MasstreeMetadataSerializer, foedus::memory::MemoryOptions, foedus::savepoint::Savepoint, foedus::log::LogOptions, foedus::debugging::DebuggingOptions, foedus::cache::CacheOptions, foedus::soc::SocOptions, foedus::storage::array::ArrayMetadataSerializer, foedus::storage::hash::HashMetadataSerializer, foedus::storage::sequential::SequentialMetadataSerializer, foedus::proc::ProcOptions, foedus::fs::DeviceEmulationOptions, foedus::thread::ThreadOptions, foedus::xct::XctOptions, foedus::storage::StorageOptions, foedus::snapshot::SnapshotMetadata, foedus::savepoint::SavepointOptions, and foedus::restart::RestartOptions.
ErrorStack foedus::externalize::Externalizable::create_element (tinyxml2::XMLElement * parent, const std::string & name, tinyxml2::XMLElement ** out) static
Definition at line 191 of file externalizable.cpp.
References CHECK_OUTOFMEMORY, and foedus::kRetOk.
{
   *out = parent->GetDocument()->NewElement(name.c_str());
   CHECK_OUTOFMEMORY(*out);
   parent->InsertEndChild(*out);
   return kRetOk;
 }
ErrorStack foedus::externalize::Externalizable::get_child_element (tinyxml2::XMLElement * parent, const std::string & tag, Externalizable * child, bool optional = false) static
child Externalizable version
Definition at line 293 of file externalizable.cpp.
References ERROR_STACK_MSG, foedus::kErrorCodeConfMissingElement, foedus::kRetOk, and load().
Referenced by foedus::log::LogOptions::load(), foedus::EngineOptions::load(), and foedus::snapshot::SnapshotOptions::load().
{
   tinyxml2::XMLElement* element = parent->FirstChildElement(tag.c_str());
   if (element) {
     return child->load(element);
   } else {
     if (optional) {
       return kRetOk;
     } else {
       return ERROR_STACK_MSG(kErrorCodeConfMissingElement, tag.c_str());
     }
   }
 }
template<typename T > ErrorStack foedus::externalize::Externalizable::get_element (tinyxml2::XMLElement * parent, const std::string & tag, T * out, bool optional = false, T value = 0) static
Only declaration in header.
Explicitly instantiated in cpp for each type this func handles.
Definition at line 232 of file externalizable.cpp.
References ERROR_STACK_MSG, foedus::kErrorCodeConfInvalidElement, foedus::kErrorCodeConfMissingElement, and foedus::kRetOk.
Referenced by get_element(), foedus::storage::sequential::SequentialMetadataSerializer::load(), foedus::storage::hash::HashMetadataSerializer::load(), foedus::storage::array::ArrayMetadataSerializer::load(), foedus::storage::masstree::MasstreeMetadataSerializer::load(), foedus::storage::MetadataSerializer::load_all_storages_from_xml(), and foedus::storage::MetadataSerializer::load_base().
{
   TinyxmlGetter<T> tinyxml_getter;
   tinyxml2::XMLElement* element = parent->FirstChildElement(tag.c_str());
   if (element) {
     tinyxml2::XMLError xml_error = tinyxml_getter(element, out);
     if (xml_error == tinyxml2::XML_SUCCESS) {
       return kRetOk;
     } else {
       return ERROR_STACK_MSG(kErrorCodeConfInvalidElement, tag.c_str());
     }
   } else {
     if (optional) {
       *out = default_value;
       return kRetOk;
     } else {
       return ERROR_STACK_MSG(kErrorCodeConfMissingElement, tag.c_str());
     }
   }
 }
ErrorStack foedus::externalize::Externalizable::get_element (tinyxml2::XMLElement * parent, const std::string & tag, std::string * out, bool optional = false, const char * value = "") static
string type is bit special.
Definition at line 260 of file externalizable.cpp.
{
   return get_element<std::string>(parent, tag, out, optional, std::string(default_value));
 }
template<uint MAXLEN, typename CHAR > static ErrorStack foedus::externalize::Externalizable::get_element (tinyxml2::XMLElement * parent, const std::string & tag, assorted::FixedString< MAXLEN, CHAR > * out, bool optional = false, const assorted::FixedString< MAXLEN, CHAR > & value = assorted::FixedString<MAXLEN, CHAR>()) inline static
Definition at line 178 of file externalizable.hpp.
References foedus::assorted::FixedString< MAXLEN, CHAR >::assign(), CHECK_ERROR, get_element(), and foedus::kRetOk.
{
     std::string tmp_out;
     CHECK_ERROR(get_element(parent, tag, &tmp_out, optional, value.str().c_str()));
     out->assign(tmp_out.data(), tmp_out.size());
     return kRetOk;
   }
template<typename T> ErrorStack foedus::externalize::Externalizable::get_element (tinyxml2::XMLElement * parent, const std::string & tag, std::vector< T > * out, bool optional = false) static
vector version.
Only declaration in header. Explicitly instantiated in cpp for each type this func handles.
Definition at line 266 of file externalizable.cpp.
References ERROR_STACK_MSG, foedus::kErrorCodeConfInvalidElement, foedus::kErrorCodeConfMissingElement, and foedus::kRetOk.
{
   out->clear();
   TinyxmlGetter<T> tinyxml_getter;
   for (tinyxml2::XMLElement* element = parent->FirstChildElement(tag.c_str());
      element; element = element->NextSiblingElement(tag.c_str())) {
     T tmp;
     tinyxml2::XMLError xml_error = tinyxml_getter(element, &tmp);
     if (xml_error == tinyxml2::XML_SUCCESS) {
       out->push_back(tmp);  // vector<bool> doesn't support emplace_back!
     } else {
       return ERROR_STACK_MSG(kErrorCodeConfInvalidElement, tag.c_str());
     }
   }
   if (out->size() == 0 && !optional) {
     return ERROR_STACK_MSG(kErrorCodeConfMissingElement, tag.c_str());
   }
   return kRetOk;
 }
template<typename ENUM > static ErrorStack foedus::externalize::Externalizable::get_enum_element (tinyxml2::XMLElement * parent, const std::string & tag, ENUM * out, bool optional = false, ENUM default_value = static_cast<ENUM>(0)) inline static
enum version
Definition at line 192 of file externalizable.hpp.
References CHECK_ERROR, ERROR_STACK_MSG, foedus::kErrorCodeConfValueOutofrange, and foedus::kRetOk.
Referenced by foedus::storage::MetadataSerializer::load_all_storages_from_xml(), and foedus::storage::MetadataSerializer::load_base().
{
     // enum might be signged or unsigned, 1 byte, 2 byte, or 4 byte.
     // But surely it won't exceed int64_t range.
     int64_t tmp;
     CHECK_ERROR(get_element<int64_t>(parent, tag, &tmp, optional, default_value));
     if (static_cast<int64_t>(static_cast<ENUM>(tmp)) != tmp) {
       return ERROR_STACK_MSG(kErrorCodeConfValueOutofrange, tag.c_str());
     }
     *out = static_cast<ENUM>(tmp);
     return kRetOk;
   }
virtual const char* foedus::externalize::Externalizable::get_tag_name () const pure virtual
Returns an XML tag name for this object as a root element.
We might want to give a different name for same externalizable objects, so this is used only when it is the root element of xml.
Implemented in foedus::snapshot::SnapshotOptions, foedus::EngineOptions, foedus::storage::masstree::MasstreeMetadataSerializer, foedus::memory::MemoryOptions, foedus::savepoint::Savepoint, foedus::log::LogOptions, foedus::debugging::DebuggingOptions, foedus::cache::CacheOptions, foedus::soc::SocOptions, foedus::storage::array::ArrayMetadataSerializer, foedus::storage::hash::HashMetadataSerializer, foedus::storage::sequential::SequentialMetadataSerializer, foedus::proc::ProcOptions, foedus::fs::DeviceEmulationOptions, foedus::thread::ThreadOptions, foedus::xct::XctOptions, foedus::storage::StorageOptions, foedus::snapshot::SnapshotMetadata, foedus::savepoint::SavepointOptions, and foedus::restart::RestartOptions.
Referenced by save_to_file(), and save_to_stream().
ErrorStack foedus::externalize::Externalizable::insert_comment (tinyxml2::XMLElement * element, const std::string & comment) static
Definition at line 177 of file externalizable.cpp.
References foedus::externalize::insert_comment_impl().
Referenced by foedus::restart::RestartOptions::save(), foedus::savepoint::SavepointOptions::save(), foedus::snapshot::SnapshotMetadata::save(), foedus::storage::StorageOptions::save(), foedus::xct::XctOptions::save(), foedus::thread::ThreadOptions::save(), foedus::proc::ProcOptions::save(), foedus::soc::SocOptions::save(), foedus::cache::CacheOptions::save(), foedus::debugging::DebuggingOptions::save(), foedus::log::LogOptions::save(), foedus::savepoint::Savepoint::save(), foedus::memory::MemoryOptions::save(), foedus::EngineOptions::save(), and foedus::snapshot::SnapshotOptions::save().
{
   return insert_comment_impl(element, comment);
 }
virtual ErrorStack foedus::externalize::Externalizable::load (tinyxml2::XMLElement * element) pure virtual
Reads the content of this object from the given XML element.
Parameters
[in] element the XML element that represents this object
Expect errors due to missing-elements, out-of-range values, etc.
Implemented in foedus::snapshot::SnapshotOptions, foedus::EngineOptions, foedus::storage::masstree::MasstreeMetadataSerializer, foedus::memory::MemoryOptions, foedus::savepoint::Savepoint, foedus::log::LogOptions, foedus::debugging::DebuggingOptions, foedus::cache::CacheOptions, foedus::soc::SocOptions, foedus::storage::array::ArrayMetadataSerializer, foedus::storage::hash::HashMetadataSerializer, foedus::storage::sequential::SequentialMetadataSerializer, foedus::proc::ProcOptions, foedus::fs::DeviceEmulationOptions, foedus::thread::ThreadOptions, foedus::xct::XctOptions, foedus::storage::StorageOptions, foedus::snapshot::SnapshotMetadata, foedus::savepoint::SavepointOptions, and foedus::restart::RestartOptions.
Referenced by get_child_element(), load_from_file(), and load_from_string().
ErrorStack foedus::externalize::Externalizable::load_from_file (const fs::Path & path)
Load the content of this object from the specified XML file.
Parameters
[in] path path of the XML file.
Expect errors due to missing-elements, out-of-range values, etc.
Definition at line 75 of file externalizable.cpp.
References foedus::fs::Path::c_str(), CHECK_ERROR, ERROR_STACK_MSG, foedus::fs::exists(), foedus::kErrorCodeConfEmptyXml, foedus::kErrorCodeConfFileNotFount, foedus::kErrorCodeConfParseFailed, foedus::kRetOk, and load().
Referenced by foedus::savepoint::SavepointManagerPimpl::initialize_once(), and foedus::snapshot::SnapshotManagerPimpl::read_snapshot_metadata().
{
   tinyxml2::XMLDocument document;
   if (!fs::exists(path)) {
     return ERROR_STACK_MSG(kErrorCodeConfFileNotFount, path.c_str());
   }
   tinyxml2::XMLError load_error = document.LoadFile(path.c_str());
   if (load_error != tinyxml2::XML_SUCCESS) {
     std::stringstream custom_message;
     custom_message << "problemtic file=" << path << ", tinyxml2 error=" << load_error
        << ", GetErrorStr1()=" << document.GetErrorStr1()
        << ", GetErrorStr2()=" << document.GetErrorStr2();
     return ERROR_STACK_MSG(kErrorCodeConfParseFailed, custom_message.str().c_str());
   } else if (!document.RootElement()) {
     return ERROR_STACK_MSG(kErrorCodeConfEmptyXml, path.c_str());
   } else {
     CHECK_ERROR(load(document.RootElement()));
   }
   return kRetOk;
 }
ErrorStack foedus::externalize::Externalizable::load_from_string (const std::string & xml)
Load the content of this object from the given XML string.
Parameters
[in] xml XML string.
Expect errors due to missing-elements, out-of-range values, etc.
Definition at line 38 of file externalizable.cpp.
References CHECK_ERROR, ERROR_STACK_MSG, foedus::kErrorCodeConfEmptyXml, foedus::kErrorCodeConfParseFailed, foedus::kRetOk, and load().
Referenced by foedus::soc::SharedMemoryRepo::attach_shared_memories().
{
   tinyxml2::XMLDocument document;
   tinyxml2::XMLError load_error = document.Parse(xml.data(), xml.size());
   if (load_error != tinyxml2::XML_SUCCESS) {
     std::stringstream custom_message;
     custom_message << "xml=" << xml << ", tinyxml2 error=" << load_error
        << ", GetErrorStr1()=" << document.GetErrorStr1()
        << ", GetErrorStr2()=" << document.GetErrorStr2();
     return ERROR_STACK_MSG(kErrorCodeConfParseFailed, custom_message.str().c_str());
   } else if (!document.RootElement()) {
     return ERROR_STACK_MSG(kErrorCodeConfEmptyXml, xml.c_str());
   } else {
     CHECK_ERROR(load(document.RootElement()));
   }
   return kRetOk;
 }
virtual ErrorStack foedus::externalize::Externalizable::save (tinyxml2::XMLElement * element) const pure virtual
Writes the content of this object to the given XML element.
Parameters
[in] element the XML element that represents this object
Expect only out-of-memory error. We receive the XML element this object will represent, so this method does not determine the XML element name of itself. The parent object determines children's tag names because one parent object might have multiple child objects of the same type with different XML element name.
Implemented in foedus::snapshot::SnapshotOptions, foedus::EngineOptions, foedus::storage::masstree::MasstreeMetadataSerializer, foedus::memory::MemoryOptions, foedus::savepoint::Savepoint, foedus::log::LogOptions, foedus::debugging::DebuggingOptions, foedus::cache::CacheOptions, foedus::soc::SocOptions, foedus::storage::array::ArrayMetadataSerializer, foedus::storage::hash::HashMetadataSerializer, foedus::storage::sequential::SequentialMetadataSerializer, foedus::proc::ProcOptions, foedus::fs::DeviceEmulationOptions, foedus::thread::ThreadOptions, foedus::xct::XctOptions, foedus::storage::StorageOptions, foedus::snapshot::SnapshotMetadata, foedus::savepoint::SavepointOptions, and foedus::restart::RestartOptions.
Referenced by add_child_element(), save_to_file(), and save_to_stream().
ErrorStack foedus::externalize::Externalizable::save_to_file (const fs::Path & path) const
Atomically and durably writes out this object to the specified XML file.
Parameters
[in] path path of the XML file.
If the file exists, this method atomically overwrites it via POSIX's atomic rename semantics. If the parent folder doesn't exist, this method automatically creates the folder. Expect errors due to file-permission (and other file I/O issue), out-of-memory, etc.
Definition at line 96 of file externalizable.cpp.
References foedus::memory::AlignedMemory::alloc(), CHECK_ERROR, CHECK_OUTOFMEMORY, foedus::fs::DirectIoFile::close(), foedus::fs::create_directories(), foedus::fs::durable_atomic_rename(), ERROR_STACK_MSG, foedus::fs::exists(), foedus::fs::fsync(), get_tag_name(), foedus::kErrorCodeConfCouldNotRename, foedus::kErrorCodeConfCouldNotWrite, foedus::kErrorCodeConfMkdirsFailed, foedus::memory::AlignedMemory::kPosixMemalign, foedus::kRetOk, foedus::fs::DirectIoFile::open(), foedus::assorted::os_error(), foedus::fs::Path::parent_path(), save(), foedus::fs::unique_name(), WRAP_ERROR_CODE, and foedus::fs::DirectIoFile::write().
Referenced by foedus::savepoint::SavepointManagerPimpl::initialize_once(), foedus::savepoint::SavepointManagerPimpl::savepoint_main(), and foedus::snapshot::SnapshotManagerPimpl::snapshot_metadata().
{
   // construct the XML in memory
   tinyxml2::XMLDocument document;
   tinyxml2::XMLElement* root = document.NewElement(get_tag_name());
   CHECK_OUTOFMEMORY(root);
   document.InsertFirstChild(root);
   CHECK_ERROR(save(root));
   fs::Path folder = path.parent_path();
   // create the folder if not exists
   if (!fs::exists(folder)) {
     if (!fs::create_directories(folder, true)) {
       std::stringstream custom_message;
       custom_message << "file=" << path << ", folder=" << folder
         << ", err=" << assorted::os_error();
       return ERROR_STACK_MSG(kErrorCodeConfMkdirsFailed, custom_message.str().c_str());
     }
   }
   // Retrieve an XML representation. We initially used document.SaveFile(), but
   // it is not ideal as it uses non-aligned non-O_DIRECT APIs.
   // This caused a data loss in our NVDIMM environment.
   tinyxml2::XMLPrinter xml_stream;
   document.Print(&xml_stream);
   const uint32_t non_aligned_size = xml_stream.CStrSize();
   const uint32_t aligned_size = assorted::align<uint32_t, 1U << 12>(non_aligned_size);
   memory::AlignedMemory xml_memory;
   xml_memory.alloc(aligned_size, 1U << 12, memory::AlignedMemory::kPosixMemalign, 0);
   if (xml_memory.is_null()) {
     return ERROR_STACK_MSG(kErrorCodeConfCouldNotWrite, "Out of memory in posix_memalign");
   }
   char* buffer = reinterpret_cast<char*>(xml_memory.get_block());
   std::memcpy(buffer, xml_stream.CStr(), non_aligned_size);
   std::memset(buffer + non_aligned_size, '\n', aligned_size - non_aligned_size);  // LF padding
   // To atomically save a file, we write to a temporary file and call sync, then use POSIX rename.
   fs::Path tmp_path(path);
   tmp_path += ".tmp_";
   tmp_path += fs::unique_name("%%%%%%%%");
   {
     // Use Direct I/O to save this file. For all critical files, we always use
     // open/write with O_DIRECT.
     fs::DirectIoFile tmp_file(tmp_path);
     WRAP_ERROR_CODE(tmp_file.open(false, true, true, true));
     WRAP_ERROR_CODE(tmp_file.write(aligned_size, xml_memory));
     tmp_file.close();
     // TASK(Hideaki) We should not need the following fsync. Let's test this later.
     // For now, do a safer thing.
     fs::fsync(tmp_path, true);
   }
   if (!fs::durable_atomic_rename(tmp_path, path)) {
     std::stringstream custom_message;
     custom_message << "dest file=" << path << ", src file=" << tmp_path
       << ", err=" << assorted::os_error();
     return ERROR_STACK_MSG(kErrorCodeConfCouldNotRename, custom_message.str().c_str());
   }
   return kRetOk;
 }
void foedus::externalize::Externalizable::save_to_stream (std::ostream * ptr) const
Invokes save() and directs the resulting XML text to the given stream.
Parameters
[in] ptr ostream to write to.
Definition at line 55 of file externalizable.cpp.
References get_tag_name(), foedus::ErrorStack::is_error(), and save().
Referenced by foedus::soc::SharedMemoryRepo::allocate_shared_memories().
{
   std::ostream &o = *ptr;
   tinyxml2::XMLDocument doc;
   // root element name is class name.
   tinyxml2::XMLElement* element = doc.NewElement(get_tag_name());
   if (!element) {
     o << "Out-of-memory during Externalizable::save_to_stream()";
     return;
   }
   doc.InsertFirstChild(element);
   ErrorStack error_stack = save(element);
   if (error_stack.is_error()) {
     o << "Failed during Externalizable::save_to_stream(): " << error_stack;
     return;
   }
   tinyxml2::XMLPrinter printer;
   doc.Print(&printer);
   o << printer.CStr();
 }
The documentation for this struct was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/externalize/externalizable.hpp
/home/shino/foedus_code/foedus-core/src/foedus/externalize/externalizable.cpp