libfoedus-core: foedus::storage::array::SortEntry Struct Reference
foedus::storage::array::SortEntry Struct Reference
Used in sort_batch().
Detailed Description
Used in sort_batch().
0-5 bytes: ArrayOffset, the most significant.
6-7 bytes: compressed epoch (difference from base_epoch)
8-11 bytes: in-epoch-ordinal
12-15 bytes: BufferPosition (doesn't have to be sorted together, but for simplicity) Be careful on endian! We use uint128_t to make it easier and faster.
Definition at line 204 of file array_partitioner_impl.cpp.
Public Member Functions
void set (ArrayOffset offset, uint16_t compressed_epoch, uint32_t in_epoch_ordinal, snapshot::BufferPosition position) __attribute__((always_inline))
ArrayOffset get_offset () const __attribute__((always_inline))
snapshot::BufferPosition get_position () const __attribute__((always_inline))
Public Attributes
__uint128_t data_
Member Function Documentation
ArrayOffset foedus::storage::array::SortEntry::get_offset () const inline
Definition at line 217 of file array_partitioner_impl.cpp.
References data_.
Referenced by foedus::storage::array::compact_logs().
{
     return static_cast<ArrayOffset>(data_ >> 80);
   }
snapshot::BufferPosition foedus::storage::array::SortEntry::get_position () const inline
Definition at line 220 of file array_partitioner_impl.cpp.
References data_.
Referenced by foedus::storage::array::compact_logs().
{
     return static_cast<snapshot::BufferPosition>(data_);
   }
void foedus::storage::array::SortEntry::set (ArrayOffset offset, uint16_t compressed_epoch, uint32_t in_epoch_ordinal, snapshot::BufferPosition position) inline
Definition at line 205 of file array_partitioner_impl.cpp.
References ASSERT_ND, data_, and foedus::storage::array::kMaxArrayOffset.
Referenced by foedus::storage::array::prepare_sort_entries().
{
     ASSERT_ND(offset < kMaxArrayOffset);
     data_
       = static_cast<__uint128_t>(offset) << 80
         | static_cast<__uint128_t>(compressed_epoch) << 64
         | static_cast<__uint128_t>(in_epoch_ordinal) << 32
         | static_cast<__uint128_t>(position);
   }
Member Data Documentation
__uint128_t foedus::storage::array::SortEntry::data_
Definition at line 223 of file array_partitioner_impl.cpp.
Referenced by get_offset(), get_position(), and set().
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/src/foedus/storage/array/array_partitioner_impl.cpp