libfoedus-core: foedus::storage::DropLogType Struct Reference
foedus::storage::DropLogType Struct Reference
FOEDUS Components » Storage ManagerFOEDUS Components » Log Manager » | Log Types
Log type of DROP STORAGE operation.
Detailed Description
Log type of DROP STORAGE operation.
This log corresponds to StorageManager::drop_storage() opereation. DROP STORAGE has no in-epoch transaction order. It is always processed in a separate epoch from operations for the storage. Thus, we advance epoch before and after dropping a storage.
Definition at line 46 of file storage_log_types.hpp.
#include <storage_log_types.hpp>
Public Member Functions
DropLogType ()=delete
DropLogType (const DropLogType &other)=delete
~DropLogType ()=delete
void populate (StorageId storage_id)
void apply_storage (Engine *engine, StorageId storage_id)
void assert_valid ()
Public Member Functions inherited from foedus::log::StorageLogType
bool is_engine_log () const
bool is_storage_log () const
bool is_record_log () const
void apply_engine (thread::Thread *)
void apply_record (thread::Thread *, storage::StorageId, xct::RwLockableXctId *, char *)
void assert_valid_generic () __attribute__((always_inline))
Verifies the log contains essential fields set.
Friends
std::ostream & operator<< (std::ostream &o, const DropLogType &v)
Additional Inherited Members
Public Attributes inherited from foedus::log::BaseLogType
LogHeader header_
Constructor & Destructor Documentation
foedus::storage::DropLogType::DropLogType () delete
Referenced by populate().
foedus::storage::DropLogType::DropLogType (const DropLogType & other) delete
foedus::storage::DropLogType::~DropLogType () delete
Member Function Documentation
void foedus::storage::DropLogType::apply_storage (Engine * engine, StorageId storage_id)
Definition at line 44 of file storage_log_types.cpp.
References ASSERT_ND, foedus::storage::StorageManager::drop_storage_apply(), and foedus::Engine::get_storage_manager().
{
   ASSERT_ND(storage_id > 0);
   LOG(INFO) << "Applying DROP STORAGE log: " << *this;
   engine->get_storage_manager()->drop_storage_apply(storage_id);
   LOG(INFO) << "Applied DROP STORAGE log: " << *this;
 }
void foedus::storage::DropLogType::assert_valid ()
Definition at line 51 of file storage_log_types.cpp.
References ASSERT_ND, foedus::log::StorageLogType::assert_valid_generic(), foedus::log::LogHeader::get_type(), foedus::log::BaseLogType::header_, and foedus::log::LogHeader::log_length_.
{
   assert_valid_generic();
   ASSERT_ND(header_.log_length_ == sizeof(DropLogType));
   ASSERT_ND(header_.get_type() == log::get_log_code<DropLogType>());
 }
void foedus::storage::DropLogType::populate (StorageId storage_id)
Definition at line 38 of file storage_log_types.cpp.
References ASSERT_ND, DropLogType(), foedus::log::BaseLogType::header_, foedus::log::LogHeader::log_length_, foedus::log::LogHeader::log_type_code_, and foedus::log::LogHeader::storage_id_.
Referenced by foedus::storage::StorageManagerPimpl::drop_storage().
{
   ASSERT_ND(storage_id > 0);
   header_.log_type_code_ = log::get_log_code<DropLogType>();
   header_.log_length_ = sizeof(DropLogType);
   header_.storage_id_ = storage_id;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const DropLogType & v) friend
Definition at line 56 of file storage_log_types.cpp.
{
   o << "<StorageDropLog>"
     << "<storage_id_>" << v.header_.storage_id_ << "</storage_id_>"
     << "</StorageDropLog>";
   return o;
 }
The documentation for this struct was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/storage/storage_log_types.hpp
/home/shino/foedus_code/foedus-core/src/foedus/storage/storage_log_types.cpp