libfoedus-core: foedus::soc::ChildEngineStatus Struct Reference
foedus::soc::ChildEngineStatus Struct Reference final
FOEDUS Components » SOC and IPC
Current status of a child SOC engine.
Detailed Description
Current status of a child SOC engine.
This object is placed in shared memory, so this must not have a heap-allocated member.
Definition at line 142 of file shared_memory_repo.hpp.
#include <shared_memory_repo.hpp>
Public Types
enum StatusCode {
kInitial = 0, kSharedMemoryAttached, kWaitingForMasterInitialization, kRunning,
kTerminated, kFatalError
}
These statuses represent each step described in SocManager comment.
Public Member Functions
ChildEngineStatus ()=delete
~ChildEngineStatus ()=delete
ChildEngineStatus (const ChildEngineStatus &other)=delete
ChildEngineStatus & operator= (const ChildEngineStatus &other)=delete
void change_status_atomic (StatusCode new_status)
Update the value of status_code_ with fence.
StatusCode read_status_atomic () const
Read status_code_ with fence.
void change_init_atomic (ModuleType value)
void change_uninit_atomic (ModuleType value)
Public Attributes
StatusCode status_code_
ModuleType initialized_modules_
The module that has been most recently initialized in this node.
ModuleType uninitialized_modules_
The module that has been most recently closed in this node.
Member Enumeration Documentation
enum foedus::soc::ChildEngineStatus::StatusCode
These statuses represent each step described in SocManager comment.
The status always increases one-by-one or jumps to kFatalError.
Enumerator
kInitial
Child engine has just started.
kSharedMemoryAttached
Child engine successfully attached shared memory and waiting for master's kWaitingForChildInitialization status.
kWaitingForMasterInitialization
Child engine has successfully initialized all modules and is now waiting for master's kRunning status.
kRunning
Done all initialization and running transactions.
kTerminated
The child engine has normally terminated.
This is a final status.
kFatalError
The child engine observed some unrecoverable error and has exit.
This is a final status.
Definition at line 147 of file shared_memory_repo.hpp.
                   {
     kInitial = 0,
     kSharedMemoryAttached,
     kWaitingForMasterInitialization,
     kRunning,
     kTerminated,
     kFatalError,
   };
Constructor & Destructor Documentation
foedus::soc::ChildEngineStatus::ChildEngineStatus () delete
foedus::soc::ChildEngineStatus::~ChildEngineStatus () delete
foedus::soc::ChildEngineStatus::ChildEngineStatus (const ChildEngineStatus & other) delete
Member Function Documentation
void foedus::soc::ChildEngineStatus::change_init_atomic (ModuleType value) inline
Definition at line 192 of file shared_memory_repo.hpp.
References ASSERT_ND, initialized_modules_, and foedus::assorted::memory_fence_acq_rel().
Referenced by foedus::EnginePimpl::on_module_initialized().
{
     ASSERT_ND(static_cast<int>(initialized_modules_) == static_cast<int>(value) - 1);
     assorted::memory_fence_acq_rel();
     initialized_modules_ = value;
     assorted::memory_fence_acq_rel();
   }
void foedus::soc::ChildEngineStatus::change_status_atomic (StatusCode new_status) inline
Update the value of status_code_ with fence.
Definition at line 179 of file shared_memory_repo.hpp.
References ASSERT_ND, kFatalError, foedus::assorted::memory_fence_acq_rel(), and status_code_.
Referenced by foedus::soc::SharedMemoryRepo::change_child_status(), and foedus::soc::SocManagerPimpl::report_engine_fatal_error().
{
     ASSERT_ND(new_status == kFatalError ||
       static_cast<int>(new_status) == static_cast<int>(status_code_) + 1);
     assorted::memory_fence_acq_rel();
     status_code_ = new_status;
     assorted::memory_fence_acq_rel();
   }
void foedus::soc::ChildEngineStatus::change_uninit_atomic (ModuleType value) inline
Definition at line 198 of file shared_memory_repo.hpp.
References ASSERT_ND, foedus::assorted::memory_fence_acq_rel(), and uninitialized_modules_.
Referenced by foedus::EnginePimpl::on_module_uninitialized().
{
     ASSERT_ND(static_cast<int>(uninitialized_modules_) == static_cast<int>(value) + 1);
     assorted::memory_fence_acq_rel();
     uninitialized_modules_ = value;
     assorted::memory_fence_acq_rel();
   }
ChildEngineStatus& foedus::soc::ChildEngineStatus::operator= (const ChildEngineStatus & other) delete
StatusCode foedus::soc::ChildEngineStatus::read_status_atomic () const inline
Read status_code_ with fence.
Definition at line 187 of file shared_memory_repo.hpp.
References foedus::assorted::memory_fence_acq_rel(), and status_code_.
Referenced by foedus::soc::SharedMemoryRepo::get_child_status().
{
     assorted::memory_fence_acq_rel();
     return status_code_;
   }
Member Data Documentation
ModuleType foedus::soc::ChildEngineStatus::initialized_modules_
The module that has been most recently initialized in this node.
Used to synchronize init.
Definition at line 207 of file shared_memory_repo.hpp.
Referenced by change_init_atomic(), foedus::soc::SocManagerPimpl::initialize_master(), and foedus::soc::SocManagerPimpl::wait_for_children_module().
StatusCode foedus::soc::ChildEngineStatus::status_code_
Definition at line 205 of file shared_memory_repo.hpp.
Referenced by change_status_atomic(), foedus::soc::SocManagerPimpl::initialize_master(), foedus::EnginePimpl::initialize_once(), read_status_atomic(), and foedus::soc::SocManagerPimpl::wait_for_children_module().
ModuleType foedus::soc::ChildEngineStatus::uninitialized_modules_
The module that has been most recently closed in this node.
Used to synchronize uninit.
Definition at line 209 of file shared_memory_repo.hpp.
Referenced by change_uninit_atomic(), foedus::soc::SocManagerPimpl::initialize_master(), and foedus::soc::SocManagerPimpl::wait_for_children_module().
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/soc/shared_memory_repo.hpp