libfoedus-core: foedus::storage::hash::HashMetadata Struct Reference
foedus::storage::hash::HashMetadata Struct Reference final
FOEDUS Components » Storage Manager » Hashtable Storage
Metadata of an hash storage.
Detailed Description
Metadata of an hash storage.
Definition at line 40 of file hash_metadata.hpp.
#include <hash_metadata.hpp>
Public Member Functions
HashMetadata ()
HashMetadata (StorageId id, const StorageName &name, uint8_t bin_bits)
HashMetadata (const StorageName &name, uint8_t bin_bits=kHashMinBinBits)
This one is for newly creating a storage.
void set_capacity (uint64_t expected_records, double preferred_records_per_bin=5.0)
Use this method to set an appropriate value for bin_bits_.
uint64_t get_bin_count () const
Number of bins in this hash storage.
uint8_t get_bin_shifts () const
HashBin extract_bin (HashValue hash) const
std::string describe () const
Public Member Functions inherited from foedus::storage::Metadata
Metadata ()
Metadata (StorageId id, StorageType type, const StorageName &name)
Metadata (StorageId id, StorageType type, const StorageName &name, SnapshotPagePointer root_snapshot_page_id)
bool keeps_all_volatile_pages () const
Public Attributes
uint8_t bin_bits_
Number of bins in exponent of two.
uint8_t pad1_
uint16_t pad2_
uint32_t pad3_
Public Attributes inherited from foedus::storage::Metadata
StorageId id_
the unique ID of this storage.
StorageType type_
type of the storage.
StorageName name_
the unique name of this storage.
SnapshotPagePointer root_snapshot_page_id_
Pointer to a snapshotted page this storage is rooted at.
SnapshotThresholds snapshot_thresholds_
Friends
std::ostream & operator<< (std::ostream &o, const HashMetadata &v)
Additional Inherited Members
Static Public Member Functions inherited from foedus::storage::Metadata
static std::string describe (const Metadata &metadata)
to_string operator of all Metadata objects.
Constructor & Destructor Documentation
foedus::storage::hash::HashMetadata::HashMetadata () inline
Definition at line 41 of file hash_metadata.hpp.
     : Metadata(0, kHashStorage, ""), bin_bits_(kHashMinBinBits), pad1_(0), pad2_(0), pad3_(0) {}
foedus::storage::hash::HashMetadata::HashMetadata (StorageId id, const StorageName & name, uint8_t bin_bits) inline
Definition at line 43 of file hash_metadata.hpp.
     : Metadata(id, kHashStorage, name), bin_bits_(bin_bits), pad1_(0), pad2_(0), pad3_(0) {
   }
foedus::storage::hash::HashMetadata::HashMetadata (const StorageName & name, uint8_t bin_bits = kHashMinBinBits) inline
This one is for newly creating a storage.
Definition at line 47 of file hash_metadata.hpp.
     : Metadata(0, kHashStorage, name), bin_bits_(bin_bits), pad1_(0), pad2_(0), pad3_(0) {
   }
Member Function Documentation
std::string foedus::storage::hash::HashMetadata::describe () const
Definition at line 29 of file hash_metadata.cpp.
{
   std::stringstream o;
   o << HashMetadataSerializer(const_cast<HashMetadata*>(this));
   return o.str();
 }
HashBin foedus::storage::hash::HashMetadata::extract_bin (HashValue hash) const inline
Definition at line 65 of file hash_metadata.hpp.
References get_bin_shifts().
 { return hash >> get_bin_shifts(); }
uint64_t foedus::storage::hash::HashMetadata::get_bin_count () const inline
Number of bins in this hash storage.
Always power of two.
Definition at line 62 of file hash_metadata.hpp.
References bin_bits_.
Referenced by foedus::storage::hash::HashStoragePimpl::create(), and foedus::storage::hash::HashStoragePimpl::get_bin_count().
 { return 1ULL << bin_bits_; }
uint8_t foedus::storage::hash::HashMetadata::get_bin_shifts () const inline
Returns
how many bits we should shift down to extract bins from hashes
Definition at line 64 of file hash_metadata.hpp.
References bin_bits_.
Referenced by extract_bin(), foedus::storage::hash::HashStoragePimpl::get_bin_shifts(), and foedus::storage::hash::HashCombo::HashCombo().
 { return 64U - bin_bits_; }
void foedus::storage::hash::HashMetadata::set_capacity (uint64_t expected_records, double preferred_records_per_bin = 5.0)
Use this method to set an appropriate value for bin_bits_.
Parameters
[in] expected_records how many records do you expect to store in this storage
[in] preferred_records_per_bin average records per a hash bin. 5-30 are recommended. If this number is too large, many bins have a linked-list rather than just one page.
Definition at line 51 of file hash_metadata.cpp.
References ASSERT_ND, bin_bits_, foedus::storage::hash::kHashMaxBinBits, and foedus::storage::hash::kHashMinBinBits.
{
   if (expected_records == 0) {
     expected_records = 1;
   }
   if (preferred_records_per_bin < 1) {
     preferred_records_per_bin = 1;
   }
   uint64_t bin_count = expected_records / preferred_records_per_bin;
   uint8_t bits;
   for (bits = 0; bits < kHashMaxBinBits && ((1ULL << bits) < bin_count); ++bits) {
     continue;
   }
   if (bits < kHashMinBinBits) {
     bits = kHashMinBinBits;
   }
   bin_bits_ = bits;
   ASSERT_ND(bin_bits_ >= kHashMinBinBits);
   ASSERT_ND(bin_bits_ <= kHashMaxBinBits);
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const HashMetadata & v) friend
Definition at line 34 of file hash_metadata.cpp.
{
   o << HashMetadataSerializer(const_cast<HashMetadata*>(&v));
   return o;
 }
Member Data Documentation
uint8_t foedus::storage::hash::HashMetadata::bin_bits_
Number of bins in exponent of two.
Recommended to use set_capacity() to set this value.
Invariant
kHashMinBinBits <= bin_bits_ <= kHashMaxBinBits
Definition at line 75 of file hash_metadata.hpp.
Referenced by foedus::storage::hash::HashStoragePimpl::get_bin_bits(), get_bin_count(), get_bin_shifts(), foedus::storage::hash::HashMetadataSerializer::load(), foedus::storage::hash::operator<<(), foedus::storage::hash::HashMetadataSerializer::save(), and set_capacity().
uint8_t foedus::storage::hash::HashMetadata::pad1_
Definition at line 78 of file hash_metadata.hpp.
uint16_t foedus::storage::hash::HashMetadata::pad2_
Definition at line 79 of file hash_metadata.hpp.
uint32_t foedus::storage::hash::HashMetadata::pad3_
Definition at line 80 of file hash_metadata.hpp.
The documentation for this struct was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/storage/hash/hash_metadata.hpp
/home/shino/foedus_code/foedus-core/src/foedus/storage/hash/hash_metadata.cpp