libfoedus-core: foedus::xct::McsMockDataPage Struct Reference
foedus::xct::McsMockDataPage Struct Reference
A dummy page layout to store RwLockableXctId.
Detailed Description
A dummy page layout to store RwLockableXctId.
We need to fake a valid page layout because that's what our UniversalLockId conversion logic assumes.
Definition at line 184 of file xct_mcs_adapter_impl.hpp.
#include <xct_mcs_adapter_impl.hpp>
Public Member Functions
void init (storage::StorageId dummy_storage_id, uint16_t node_id, uint32_t in_node_index)
Public Attributes
storage::PageHeader header_
char header_pad_ [kMcsMockDataPageHeaderPad]
RwLockableXctId tid_ [kMcsMockDataPageLocksPerPage]
McsWwLock ww_ [kMcsMockDataPageLocksPerPage]
char filler_ [kMcsMockDataPageFiller]
Member Function Documentation
void foedus::xct::McsMockDataPage::init (storage::StorageId dummy_storage_id, uint16_t node_id, uint32_t in_node_index) inline
Definition at line 185 of file xct_mcs_adapter_impl.hpp.
References header_, foedus::storage::PageHeader::init_volatile(), foedus::storage::kArrayPageType, foedus::xct::kMcsMockDataPageLocksPerPage, foedus::xct::McsWwLock::reset(), foedus::xct::RwLockableXctId::reset(), foedus::storage::VolatilePagePointer::set(), tid_, and ww_.
Referenced by foedus::xct::McsMockNode< RW_BLOCK >::init().
{
     storage::VolatilePagePointer page_id;
     page_id.set(node_id, in_node_index);
     header_.init_volatile(page_id, dummy_storage_id, storage::kArrayPageType);
     for (uint32_t i = 0; i < kMcsMockDataPageLocksPerPage; ++i) {
       tid_[i].reset();
       ww_[i].reset();
     }
   }
Member Data Documentation
char foedus::xct::McsMockDataPage::filler_[kMcsMockDataPageFiller]
Definition at line 198 of file xct_mcs_adapter_impl.hpp.
storage::PageHeader foedus::xct::McsMockDataPage::header_
Definition at line 194 of file xct_mcs_adapter_impl.hpp.
Referenced by init().
char foedus::xct::McsMockDataPage::header_pad_[kMcsMockDataPageHeaderPad]
Definition at line 195 of file xct_mcs_adapter_impl.hpp.
RwLockableXctId foedus::xct::McsMockDataPage::tid_[kMcsMockDataPageLocksPerPage]
Definition at line 196 of file xct_mcs_adapter_impl.hpp.
Referenced by foedus::xct::McsMockContext< RW_BLOCK >::get_rw_lock_address(), and init().
McsWwLock foedus::xct::McsMockDataPage::ww_[kMcsMockDataPageLocksPerPage]
Definition at line 197 of file xct_mcs_adapter_impl.hpp.
Referenced by foedus::xct::McsMockContext< RW_BLOCK >::get_ww_lock_address(), and init().
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/xct/xct_mcs_adapter_impl.hpp