libfoedus-core: foedus::xct::McsWwBlock Struct Reference
foedus::xct::McsWwBlock Struct Reference
Pre-allocated MCS block for WW-locks.
Detailed Description
Pre-allocated MCS block for WW-locks.
we so far pre-allocate at most 2^16 nodes per thread.
Definition at line 274 of file xct_id.hpp.
#include <xct_id.hpp>
Public Member Functions
bool has_successor_relaxed () const __attribute__((always_inline))
setter/getter for successor_.
bool has_successor_consume () const __attribute__((always_inline))
bool has_successor_acquire () const __attribute__((always_inline))
bool has_successor_atomic () const __attribute__((always_inline))
uint32_t get_successor_thread_id_relaxed () const __attribute__((always_inline))
Carefully use this! In some places you must call copy_once() then call this on the copy.
McsBlockIndex get_successor_block_relaxed () const __attribute__((always_inline))
Carefully use this! In some places you must call copy_once() then call this on the copy.
void clear_successor_atomic () __attribute__((always_inline))
void clear_successor_release () __attribute__((always_inline))
void set_successor_atomic (thread::ThreadId thread_id, McsBlockIndex block) __attribute__((always_inline))
void set_successor_release (thread::ThreadId thread_id, McsBlockIndex block) __attribute__((always_inline))
Public Attributes
McsWwBlockData successor_
The successor of MCS lock queue after this thread (in other words, the thread that is waiting for this thread).
Member Function Documentation
void foedus::xct::McsWwBlock::clear_successor_atomic () inline
Definition at line 301 of file xct_id.hpp.
References foedus::xct::McsWwBlockData::clear_atomic().
 { successor_.clear_atomic(); }
void foedus::xct::McsWwBlock::clear_successor_release () inline
Definition at line 302 of file xct_id.hpp.
References foedus::xct::McsWwBlockData::clear_release().
Referenced by foedus::xct::McsWwImpl< ADAPTOR >::acquire_try(), foedus::xct::McsWwImpl< ADAPTOR >::acquire_unconditional(), and foedus::xct::McsWwImpl< ADAPTOR >::initial().
 { successor_.clear_release(); }
McsBlockIndex foedus::xct::McsWwBlock::get_successor_block_relaxed () const inline
Carefully use this! In some places you must call copy_once() then call this on the copy.
We thus put "_relaxed" as suffix.
Definition at line 298 of file xct_id.hpp.
References foedus::xct::McsWwBlockData::get_block_relaxed().
{
     return successor_.get_block_relaxed();
   }
uint32_t foedus::xct::McsWwBlock::get_successor_thread_id_relaxed () const inline
Carefully use this! In some places you must call copy_once() then call this on the copy.
We thus put "_relaxed" as suffix.
Definition at line 291 of file xct_id.hpp.
References foedus::xct::McsWwBlockData::get_thread_id_relaxed().
Referenced by foedus::xct::McsWwImpl< ADAPTOR >::release().
{
     return successor_.get_thread_id_relaxed();
   }
bool foedus::xct::McsWwBlock::has_successor_acquire () const inline
Definition at line 285 of file xct_id.hpp.
References foedus::xct::McsWwBlockData::is_valid_acquire().
Referenced by foedus::xct::McsWwImpl< ADAPTOR >::release().
 { return successor_.is_valid_acquire(); }
bool foedus::xct::McsWwBlock::has_successor_atomic () const inline
Definition at line 286 of file xct_id.hpp.
References foedus::xct::McsWwBlockData::is_valid_atomic().
 { return successor_.is_valid_atomic(); }
bool foedus::xct::McsWwBlock::has_successor_consume () const inline
Definition at line 284 of file xct_id.hpp.
References foedus::xct::McsWwBlockData::is_valid_consume().
 { return successor_.is_valid_consume(); }
bool foedus::xct::McsWwBlock::has_successor_relaxed () const inline
setter/getter for successor_.
Definition at line 283 of file xct_id.hpp.
References foedus::xct::McsWwBlockData::is_valid_relaxed().
 { return successor_.is_valid_relaxed(); }
void foedus::xct::McsWwBlock::set_successor_atomic (thread::ThreadId thread_id, McsBlockIndex block) inline
Definition at line 303 of file xct_id.hpp.
References foedus::xct::McsWwBlockData::set_atomic().
{
     successor_.set_atomic(thread_id, block);
   }
void foedus::xct::McsWwBlock::set_successor_release (thread::ThreadId thread_id, McsBlockIndex block) inline
Definition at line 306 of file xct_id.hpp.
References foedus::xct::McsWwBlockData::set_release().
{
     successor_.set_release(thread_id, block);
   }
Member Data Documentation
McsWwBlockData foedus::xct::McsWwBlock::successor_
The successor of MCS lock queue after this thread (in other words, the thread that is waiting for this thread).
Successor is represented by thread ID and block, the index in mcs_blocks_.
Definition at line 280 of file xct_id.hpp.
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/xct/xct_id.hpp