libfoedus-core: foedus::storage::masstree::MasstreeDeleteLogType Struct Reference
foedus::storage::masstree::MasstreeDeleteLogType Struct Reference
FOEDUS Components » Storage Manager » Masstree StorageFOEDUS Components » Log Manager » | Log Types
Log type of masstree-storage's delete operation.
Detailed Description
Log type of masstree-storage's delete operation.
This one does nothing but flipping delete bit.
Definition at line 351 of file masstree_log_types.hpp.
#include <masstree_log_types.hpp>
Public Member Functions
MasstreeDeleteLogType ()=delete
MasstreeDeleteLogType (const MasstreeDeleteLogType &other)=delete
~MasstreeDeleteLogType ()=delete
void populate (StorageId storage_id, const void *key, KeyLength key_length) __attribute__((always_inline))
void apply_record (thread::Thread *, StorageId, xct::RwLockableXctId *owner_id, char *data) const __attribute__((always_inline))
void assert_valid () const __attribute__((always_inline))
Public Member Functions inherited from foedus::storage::masstree::MasstreeCommonLogType
MasstreeCommonLogType ()=delete
MasstreeCommonLogType (const MasstreeCommonLogType &other)=delete
~MasstreeCommonLogType ()=delete
char * get_key ()
const char * get_key () const
KeySlice get_first_slice () const
KeyLength get_key_length_aligned () const
char * get_payload ()
const char * get_payload () const
void populate_base (log::LogCode type, StorageId storage_id, const void *key, KeyLength key_length, const void *payload=nullptr, PayloadLength payload_offset=0, PayloadLength payload_count=0) __attribute__((always_inline))
bool equal_record_and_log_suffixes (const char *data) const
used only for sanity check.
RecordAddresses apply_record_prepare (xct::RwLockableXctId *owner_id, char *record) const
Common parts of apply_record() in these log types that extract relevant addresses from the record header.
Public Member Functions inherited from foedus::log::RecordLogType
bool is_engine_log () const
bool is_storage_log () const
bool is_record_log () const
void apply_engine (thread::Thread *)
void apply_storage (Engine *, storage::StorageId)
void assert_valid_generic () const __attribute__((always_inline))
Verifies the log contains essential fields set.
Static Public Member Functions
static uint16_t calculate_log_length (KeyLength key_length) __attribute__((always_inline))
Static Public Member Functions inherited from foedus::storage::masstree::MasstreeCommonLogType
static uint16_t calculate_log_length (KeyLength key_length, PayloadLength payload_count) __attribute__((always_inline))
static int compare_logs (const MasstreeCommonLogType *left, const MasstreeCommonLogType *right) __attribute__((always_inline))
Returns -1, 0, 1 when left is less than, same, larger than right in terms of key and xct_id.
Friends
std::ostream & operator<< (std::ostream &o, const MasstreeDeleteLogType &v)
Additional Inherited Members
Public Attributes inherited from foedus::storage::masstree::MasstreeCommonLogType
KeyLength key_length_
PayloadLength payload_offset_
PayloadLength payload_count_
uint16_t reserved_
char aligned_data_ [8]
Full key and (if exists) payload data, both of which are padded to 8 bytes.
Public Attributes inherited from foedus::log::BaseLogType
LogHeader header_
Constructor & Destructor Documentation
foedus::storage::masstree::MasstreeDeleteLogType::MasstreeDeleteLogType () delete
foedus::storage::masstree::MasstreeDeleteLogType::MasstreeDeleteLogType (const MasstreeDeleteLogType & other) delete
foedus::storage::masstree::MasstreeDeleteLogType::~MasstreeDeleteLogType () delete
Member Function Documentation
void foedus::storage::masstree::MasstreeDeleteLogType::apply_record (thread::Thread * , StorageId , xct::RwLockableXctId * owner_id, char * data) const inline
Definition at line 366 of file masstree_log_types.hpp.
References ASSERT_ND.
{
     apply_record_prepare(owner_id, data);  // In this log type, just for sanity checks
     ASSERT_ND(!owner_id->xct_id_.is_deleted());
     owner_id->xct_id_.set_deleted();
   }
void foedus::storage::masstree::MasstreeDeleteLogType::assert_valid () const inline
Definition at line 376 of file masstree_log_types.hpp.
References ASSERT_ND, foedus::log::StorageLogType::assert_valid_generic(), foedus::log::LogHeader::get_type(), foedus::log::BaseLogType::header_, foedus::log::kLogCodeMasstreeDelete, and foedus::log::LogHeader::log_length_.
{
     assert_valid_generic();
     ASSERT_ND(header_.log_length_ == calculate_log_length(key_length_));
     ASSERT_ND(header_.get_type() == log::kLogCodeMasstreeDelete);
   }
static uint16_t foedus::storage::masstree::MasstreeDeleteLogType::calculate_log_length (KeyLength key_length) inline static
Definition at line 354 of file masstree_log_types.hpp.
References foedus::storage::masstree::MasstreeCommonLogType::calculate_log_length().
Referenced by foedus::storage::masstree::MasstreeStoragePimpl::delete_general().
{
     return MasstreeCommonLogType::calculate_log_length(key_length, 0);
   }
void foedus::storage::masstree::MasstreeDeleteLogType::populate (StorageId storage_id, const void * key, KeyLength key_length) inline
Definition at line 358 of file masstree_log_types.hpp.
References foedus::log::kLogCodeMasstreeDelete.
Referenced by foedus::storage::masstree::MasstreeStoragePimpl::delete_general().
{
     log::LogCode type = log::kLogCodeMasstreeDelete;
     populate_base(type, storage_id, key, key_length);
   }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const MasstreeDeleteLogType & v) friend
Definition at line 65 of file masstree_log_types.cpp.
{
   o << "<MasstreeDeleteLogType>"
     << "<key_length_>" << v.key_length_ << "</key_length_>"
     << "<key_>" << assorted::Top(v.get_key(), v.key_length_) << "</key_>"
     << "</MasstreeDeleteLogType>";
   return o;
 }
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/storage/masstree/masstree_log_types.hpp