libfoedus-core: foedus::storage::masstree::MasstreeIntermediatePointerIterator Struct Reference
foedus::storage::masstree::MasstreeIntermediatePointerIterator Struct Reference final
Handy iterator for MasstreeIntermediate.
Detailed Description
Handy iterator for MasstreeIntermediate.
Note that this object is not thread safe. Use it only where it's safe (eg snapshot page).
Definition at line 1047 of file masstree_page_impl.hpp.
#include <masstree_page_impl.hpp>
Public Member Functions
MasstreeIntermediatePointerIterator (const MasstreeIntermediatePage *page)
void next ()
bool is_valid () const
KeySlice get_low_key () const
KeySlice get_high_key () const
const DualPagePointer & get_pointer () const
Public Attributes
const MasstreeIntermediatePage *const page_
uint16_t index_
uint16_t index_mini_
Constructor & Destructor Documentation
foedus::storage::masstree::MasstreeIntermediatePointerIterator::MasstreeIntermediatePointerIterator (const MasstreeIntermediatePage * page) inline explicit
Definition at line 1048 of file masstree_page_impl.hpp.
References ASSERT_ND, foedus::storage::masstree::MasstreePage::header(), index_, foedus::storage::masstree::MasstreePage::is_empty_range(), and foedus::storage::PageHeader::snapshot_.
     : page_(page), index_(0), index_mini_(0) {
       if (page->is_empty_range()) {
         // Empty-range page has zero pointers, which is special.
         ASSERT_ND(!page->header().snapshot_);
         index_ = 1;  // so that initial is_valid returns false.
       }
     }
Member Function Documentation
KeySlice foedus::storage::masstree::MasstreeIntermediatePointerIterator::get_high_key () const inline
Definition at line 1082 of file masstree_page_impl.hpp.
References ASSERT_ND, foedus::storage::masstree::MasstreePage::get_high_fence(), foedus::storage::masstree::MasstreeIntermediatePage::get_minipage(), foedus::storage::masstree::MasstreeIntermediatePage::get_separator(), index_, index_mini_, is_valid(), foedus::storage::masstree::MasstreeIntermediatePage::MiniPage::key_count_, page_, and foedus::storage::masstree::MasstreeIntermediatePage::MiniPage::separators_.
{
     ASSERT_ND(is_valid());
     const MasstreeIntermediatePage::MiniPage& minipage = page_->get_minipage(index_);
     if (index_mini_ < minipage.key_count_) {
       return minipage.separators_[index_mini_];
     } else if (index_ < page_->get_key_count()) {
       return page_->get_separator(index_ );
     } else {
       return page_->get_high_fence();
     }
   }
KeySlice foedus::storage::masstree::MasstreeIntermediatePointerIterator::get_low_key () const inline
Definition at line 1071 of file masstree_page_impl.hpp.
References ASSERT_ND, foedus::storage::masstree::MasstreePage::get_low_fence(), foedus::storage::masstree::MasstreeIntermediatePage::get_minipage(), foedus::storage::masstree::MasstreeIntermediatePage::get_separator(), index_, index_mini_, is_valid(), page_, and foedus::storage::masstree::MasstreeIntermediatePage::MiniPage::separators_.
Referenced by foedus::storage::masstree::MasstreeStoragePimpl::peek_volatile_page_boundaries_this_layer_recurse().
{
     ASSERT_ND(is_valid());
     const MasstreeIntermediatePage::MiniPage& minipage = page_->get_minipage(index_);
     if (index_mini_ > 0) {
       return minipage.separators_[index_mini_ - 1];
     } else if (index_ > 0) {
       return page_->get_separator(index_ - 1);
     } else {
       return page_->get_low_fence();
     }
   }
const DualPagePointer& foedus::storage::masstree::MasstreeIntermediatePointerIterator::get_pointer () const inline
Definition at line 1093 of file masstree_page_impl.hpp.
References ASSERT_ND, foedus::storage::masstree::MasstreeIntermediatePage::get_minipage(), index_, index_mini_, is_valid(), page_, and foedus::storage::masstree::MasstreeIntermediatePage::MiniPage::pointers_.
Referenced by foedus::storage::masstree::MasstreeStoragePimpl::peek_volatile_page_boundaries_this_layer_recurse().
{
     ASSERT_ND(is_valid());
     const MasstreeIntermediatePage::MiniPage& minipage = page_->get_minipage(index_);
     return minipage.pointers_[index_mini_];
   }
bool foedus::storage::masstree::MasstreeIntermediatePointerIterator::is_valid () const inline
Definition at line 1067 of file masstree_page_impl.hpp.
References foedus::storage::masstree::MasstreePage::get_key_count(), foedus::storage::masstree::MasstreeIntermediatePage::get_minipage(), index_, index_mini_, foedus::storage::masstree::MasstreeIntermediatePage::MiniPage::key_count_, and page_.
Referenced by foedus::storage::masstree::MasstreeComposer::construct_root(), foedus::storage::masstree::MasstreeStoragePimpl::debugout_single_thread_recurse(), foedus::storage::masstree::SplitIntermediate::decide_strategy(), foedus::storage::masstree::MasstreePartitioner::design_partition(), foedus::storage::masstree::MasstreeComposer::drop_volatiles(), get_high_key(), get_low_key(), get_pointer(), foedus::storage::masstree::MasstreeStoragePimpl::hcc_reset_all_temperature_stat_recurse(), next(), and foedus::storage::masstree::MasstreeStoragePimpl::peek_volatile_page_boundaries_this_layer_recurse().
{
     return index_ <= page_->get_key_count()
       && index_mini_ <= page_->get_minipage(index_).key_count_;
   }
void foedus::storage::masstree::MasstreeIntermediatePointerIterator::next () inline
Definition at line 1057 of file masstree_page_impl.hpp.
References foedus::storage::masstree::MasstreeIntermediatePage::get_minipage(), index_, index_mini_, is_valid(), foedus::storage::masstree::MasstreeIntermediatePage::MiniPage::key_count_, and page_.
Referenced by foedus::storage::masstree::MasstreeStoragePimpl::peek_volatile_page_boundaries_this_layer_recurse().
               {
     if (!is_valid()) {
       return;
     }
     ++index_mini_;
     if (index_mini_ > page_->get_minipage(index_).key_count_) {
       ++index_;
       index_mini_ = 0;
     }
   }
Member Data Documentation
uint16_t foedus::storage::masstree::MasstreeIntermediatePointerIterator::index_
Definition at line 1100 of file masstree_page_impl.hpp.
Referenced by get_high_key(), get_low_key(), get_pointer(), is_valid(), MasstreeIntermediatePointerIterator(), next(), and foedus::storage::masstree::MasstreeStoragePimpl::peek_volatile_page_boundaries_this_layer_recurse().
uint16_t foedus::storage::masstree::MasstreeIntermediatePointerIterator::index_mini_
Definition at line 1101 of file masstree_page_impl.hpp.
Referenced by get_high_key(), get_low_key(), get_pointer(), is_valid(), next(), and foedus::storage::masstree::MasstreeStoragePimpl::peek_volatile_page_boundaries_this_layer_recurse().
const MasstreeIntermediatePage* const foedus::storage::masstree::MasstreeIntermediatePointerIterator::page_
Definition at line 1099 of file masstree_page_impl.hpp.
Referenced by get_high_key(), get_low_key(), get_pointer(), is_valid(), and next().
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/storage/masstree/masstree_page_impl.hpp