libfoedus-core: foedus::storage::array::ArrayIncrementLogType Struct Reference
foedus::storage::array::ArrayIncrementLogType Struct Reference
FOEDUS Components » Storage Manager » Array StorageFOEDUS Components » Log Manager » | Log Types
Log type of array-storage's increment operation.
Detailed Description
Log type of array-storage's increment operation.
This is similar to overwrite, but different in a sense that this can do value-increment without relying on the current value. For that, we remember the addendum in primitive format.
Definition at line 183 of file array_log_types.hpp.
#include <array_log_types.hpp>
Public Member Functions
ArrayIncrementLogType ()=delete
ArrayIncrementLogType (const ArrayIncrementLogType &other)=delete
~ArrayIncrementLogType ()=delete
template<typename T >
void populate (StorageId storage_id, ArrayOffset offset, T payload, uint16_t payload_offset) __attribute__((always_inline))
ValueType get_value_type () const __attribute__((always_inline))
bool is_64b_type () const __attribute__((always_inline))
void * addendum_64 ()
const void * addendum_64 () const
void apply_record (thread::Thread *context, StorageId storage_id, xct::RwLockableXctId *owner_id, char *payload) const __attribute__((always_inline))
void merge (const ArrayIncrementLogType &other) __attribute__((always_inline))
A special optimization for increment logs in log gleaner.
void assert_valid () const __attribute__((always_inline))
Public Member Functions inherited from foedus::storage::array::ArrayCommonUpdateLogType
ArrayCommonUpdateLogType ()=delete
ArrayCommonUpdateLogType (const ArrayCommonUpdateLogType &other)=delete
~ArrayCommonUpdateLogType ()=delete
Public Member Functions inherited from foedus::log::RecordLogType
bool is_engine_log () const
bool is_storage_log () const
bool is_record_log () const
void apply_engine (thread::Thread *)
void apply_storage (Engine *, storage::StorageId)
void assert_valid_generic () const __attribute__((always_inline))
Verifies the log contains essential fields set.
Static Public Member Functions
static uint16_t calculate_log_length (ValueType value_type) __attribute__((always_inline))
Static Public Member Functions inherited from foedus::storage::array::ArrayCommonUpdateLogType
static int compare_logs (const ArrayCommonUpdateLogType *left, const ArrayCommonUpdateLogType *right) __attribute__((always_inline))
Returns -1, 0, 1 when left is less than, same, larger than right in terms of key and xct_id.
Public Attributes
uint16_t payload_offset_
uint16_t value_type_
char addendum_ [4]
Public Attributes inherited from foedus::storage::array::ArrayCommonUpdateLogType
ArrayOffset offset_
Public Attributes inherited from foedus::log::BaseLogType
LogHeader header_
Friends
std::ostream & operator<< (std::ostream &o, const ArrayIncrementLogType &v)
Constructor & Destructor Documentation
foedus::storage::array::ArrayIncrementLogType::ArrayIncrementLogType () delete
foedus::storage::array::ArrayIncrementLogType::ArrayIncrementLogType (const ArrayIncrementLogType & other) delete
foedus::storage::array::ArrayIncrementLogType::~ArrayIncrementLogType () delete
Member Function Documentation
void* foedus::storage::array::ArrayIncrementLogType::addendum_64 () inline
Definition at line 206 of file array_log_types.hpp.
Referenced by merge().
 { return addendum_ + 4; }
const void* foedus::storage::array::ArrayIncrementLogType::addendum_64 () const inline
Definition at line 207 of file array_log_types.hpp.
 { return addendum_ + 4; }
void foedus::storage::array::ArrayIncrementLogType::apply_record (thread::Thread * context, StorageId storage_id, xct::RwLockableXctId * owner_id, char * payload) const inline
Definition at line 303 of file array_log_types.hpp.
References ASSERT_ND, foedus::storage::array::kBool, foedus::storage::array::kDouble, foedus::storage::array::kFloat, foedus::storage::array::kI16, foedus::storage::array::kI32, foedus::storage::array::kI64, foedus::storage::array::kI8, foedus::storage::array::kU16, foedus::storage::array::kU32, foedus::storage::array::kU64, and foedus::storage::array::kU8.
{
   switch (get_value_type()) {
     // 32 bit data types
     case kI8:
       increment<int8_t>(
         reinterpret_cast<int8_t*>(payload + payload_offset_),
         reinterpret_cast<const int8_t*>(addendum_));
       break;
     case kI16:
       increment<int16_t>(
         reinterpret_cast<int16_t*>(payload + payload_offset_),
         reinterpret_cast<const int16_t*>(addendum_));
       break;
     case kI32:
       increment<int32_t>(
         reinterpret_cast<int32_t*>(payload + payload_offset_),
         reinterpret_cast<const int32_t*>(addendum_));
       break;
     case kBool:
     case kU8:
       increment<uint8_t>(
         reinterpret_cast<uint8_t*>(payload + payload_offset_),
         reinterpret_cast<const uint8_t*>(addendum_));
       break;
     case kU16:
       increment<uint16_t>(
         reinterpret_cast<uint16_t*>(payload + payload_offset_),
         reinterpret_cast<const uint16_t*>(addendum_));
       break;
     case kU32:
       increment<uint32_t>(
         reinterpret_cast<uint32_t*>(payload + payload_offset_),
         reinterpret_cast<const uint32_t*>(addendum_));
       break;
     case kFloat:
       increment<float>(
         reinterpret_cast<float*>(payload + payload_offset_),
         reinterpret_cast<const float*>(addendum_));
       break;
     // 64 bit data types
     case kI64:
       increment<int64_t>(
         reinterpret_cast<int64_t*>(payload + payload_offset_),
         reinterpret_cast<const int64_t*>(addendum_ + 4));
       break;
     case kU64:
       increment<uint64_t>(
         reinterpret_cast<uint64_t*>(payload + payload_offset_),
         reinterpret_cast<const uint64_t*>(addendum_ + 4));
       break;
     case kDouble:
       increment<double>(
         reinterpret_cast<double*>(payload + payload_offset_),
         reinterpret_cast<const double*>(addendum_ + 4));
       break;
     default:
       ASSERT_ND(false);
       break;
   }
 }
void foedus::storage::array::ArrayIncrementLogType::assert_valid () const inline
Definition at line 419 of file array_log_types.hpp.
References ASSERT_ND, foedus::log::StorageLogType::assert_valid_generic(), foedus::log::LogHeader::get_type(), foedus::log::BaseLogType::header_, foedus::storage::array::kDouble, foedus::storage::array::kI8, foedus::log::kLogCodeArrayIncrement, and foedus::log::LogHeader::log_length_.
{
   assert_valid_generic();
   ASSERT_ND(header_.log_length_ == calculate_log_length(get_value_type()));
   ASSERT_ND(header_.get_type() == log::kLogCodeArrayIncrement);
   ASSERT_ND(get_value_type() >= kI8 && get_value_type() <= kDouble);
 }
static uint16_t foedus::storage::array::ArrayIncrementLogType::calculate_log_length (ValueType value_type) inline static
Definition at line 189 of file array_log_types.hpp.
References foedus::storage::array::kI64.
Referenced by foedus::storage::array::ArrayStoragePimpl::increment_record_oneshot().
{
     if (value_type < kI64) {
       return 32;  // in this case we store it in first bytes of addendum
     } else {
       return 40;  // in this case we store it in 32th-bytes (28-32th bytes are not used)
     }
   }
ValueType foedus::storage::array::ArrayIncrementLogType::get_value_type () const inline
Definition at line 204 of file array_log_types.hpp.
Referenced by foedus::storage::array::operator<<().
 { return static_cast<ValueType>(value_type_); }
bool foedus::storage::array::ArrayIncrementLogType::is_64b_type () const inline
Definition at line 205 of file array_log_types.hpp.
References foedus::storage::array::kI64.
 { return get_value_type() >= kI64; }
void foedus::storage::array::ArrayIncrementLogType::merge (const ArrayIncrementLogType & other) inline
A special optimization for increment logs in log gleaner.
Two increment logs on the same array offset can be merged to reduce # of log entries.
Precondition
storage_id_ == other.storage_id_
value_type_ == other.value_type_
payload_offset_ == other.payload_offset_
Definition at line 374 of file array_log_types.hpp.
References addendum_, addendum_64(), ASSERT_ND, foedus::log::BaseLogType::header_, foedus::storage::array::kBool, foedus::storage::array::kDouble, foedus::storage::array::kFloat, foedus::storage::array::kI16, foedus::storage::array::kI32, foedus::storage::array::kI64, foedus::storage::array::kI8, foedus::storage::array::kU16, foedus::storage::array::kU32, foedus::storage::array::kU64, foedus::storage::array::kU8, payload_offset_, foedus::log::LogHeader::storage_id_, and value_type_.
Referenced by foedus::storage::array::compact_logs().
{
   ASSERT_ND(header_.storage_id_ == other.header_.storage_id_);
   ASSERT_ND(value_type_ == other.value_type_);
   ASSERT_ND(payload_offset_ == other.payload_offset_);
   switch (get_value_type()) {
     // 32 bit data types
     case kI8:
       add_to<int8_t>(addendum_, other.addendum_);
       break;
     case kI16:
       add_to<int16_t>(addendum_, other.addendum_);
       break;
     case kI32:
       add_to<int32_t>(addendum_, other.addendum_);
       break;
     case kBool:
     case kU8:
       add_to<uint8_t>(addendum_, other.addendum_);
       break;
     case kU16:
       add_to<uint16_t>(addendum_, other.addendum_);
       break;
     case kU32:
       add_to<uint32_t>(addendum_, other.addendum_);
       break;
     case kFloat:
       add_to<float>(addendum_, other.addendum_);
       break;
     // 64 bit data types
     case kI64:
       add_to<int64_t>(addendum_64(), other.addendum_64());
       break;
     case kU64:
       add_to<uint64_t>(addendum_64(), other.addendum_64());
       break;
     case kDouble:
       add_to<double>(addendum_64(), other.addendum_64());
       break;
     default:
       ASSERT_ND(false);
       break;
   }
 }
template<typename T > void foedus::storage::array::ArrayIncrementLogType::populate (StorageId storage_id, ArrayOffset offset, T payload, uint16_t payload_offset) inline
Definition at line 277 of file array_log_types.hpp.
References foedus::log::BaseLogType::header_, foedus::log::kLogCodeArrayIncrement, foedus::log::LogHeader::log_length_, foedus::log::LogHeader::log_type_code_, and foedus::log::LogHeader::storage_id_.
Referenced by foedus::storage::array::ArrayStoragePimpl::increment_record_oneshot().
{
   header_.log_type_code_ = log::kLogCodeArrayIncrement;
   ValueType type = to_value_type<T>();
   header_.log_length_ = calculate_log_length(type);
   header_.storage_id_ = storage_id;
   offset_ = offset;
   payload_offset_ = payload_offset;
   value_type_ = type;
   if (is_64b_type()) {
     T* address = reinterpret_cast<T*>(addendum_ + 4);
     *address = payload;
   } else {
     T* address = reinterpret_cast<T*>(addendum_);
     *address = payload;
   }
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const ArrayIncrementLogType & v) friend
Definition at line 75 of file array_log_types.cpp.
{
   o << "<ArrayIncrementLog>"
     << "<offset_>" << v.offset_ << "</offset_>"
     << "<payload_offset_>" << v.payload_offset_ << "</payload_offset_>"
     << "<type_>";
   switch (v.get_value_type()) {
     // 32 bit data types
     case kI8:
       o << "int8_t</type><addendum_>" << static_cast<int16_t>(as<int8_t>(v.addendum_));
       break;
     case kI16:
       o << "int16_t</type><addendum_>" << as<int16_t>(v.addendum_);
       break;
     case kI32:
       o << "int32_t</type><addendum_>" << as<int32_t>(v.addendum_);
       break;
     case kBool:
     case kU8:
       o << "uint8_t</type><addendum_>" << static_cast<uint16_t>(as<uint8_t>(v.addendum_));
       break;
     case kU16:
       o << "uint16_t</type><addendum_>" << as<uint16_t>(v.addendum_);
       break;
     case kU32:
       o << "uint32_t</type><addendum_>" << as<uint32_t>(v.addendum_);
       break;
     case kFloat:
       o << "float</type><addendum_>" << as<float>(v.addendum_);
       break;
     // 64 bit data types
     case kI64:
       o << "int64_t</type><addendum_>" << as<int64_t>(v.addendum_ + 4);
       break;
     case kU64:
       o << "uint64_t</type><addendum_>" << as<uint64_t>(v.addendum_ + 4);
       break;
     case kDouble:
       o << "double</type><addendum_>" << as<double>(v.addendum_ + 4);
       break;
     default:
       o << "UNKNOWN(" << v.get_value_type() << ")</type><addendum_>";
       ASSERT_ND(false);
       break;
   }
   o << "</addendum_>";
   o << "</ArrayIncrementLog>";
   return o;
 }
Member Data Documentation
char foedus::storage::array::ArrayIncrementLogType::addendum_[4]
Definition at line 187 of file array_log_types.hpp.
Referenced by merge(), and foedus::storage::array::operator<<().
uint16_t foedus::storage::array::ArrayIncrementLogType::payload_offset_
Definition at line 185 of file array_log_types.hpp.
Referenced by foedus::storage::array::compact_logs(), merge(), and foedus::storage::array::operator<<().
uint16_t foedus::storage::array::ArrayIncrementLogType::value_type_
Definition at line 186 of file array_log_types.hpp.
Referenced by foedus::storage::array::compact_logs(), and merge().
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/storage/array/array_log_types.hpp