libfoedus-core: foedus::storage::masstree::MasstreeCommonLogType Struct Reference
foedus::storage::masstree::MasstreeCommonLogType Struct Reference
FOEDUS Components » Storage Manager » Masstree StorageFOEDUS Components » Log Manager » | Log Types
A base class for MasstreeInsertLogType/MasstreeDeleteLogType/MasstreeOverwriteLogType.
Detailed Description
A base class for MasstreeInsertLogType/MasstreeDeleteLogType/MasstreeOverwriteLogType.
This defines a common layout for the log types so that composer/partitioner can easier handle these log types. This means we waste a bit (eg delete log type doesn't need payload offset/count), but we anyway have extra space if we want to have data_ 8-byte aligned. data_ always starts with the key, followed by payload for insert/overwrite.
Definition at line 86 of file masstree_log_types.hpp.
#include <masstree_log_types.hpp>
Classes
struct RecordAddresses
Public Member Functions
MasstreeCommonLogType ()=delete
MasstreeCommonLogType (const MasstreeCommonLogType &other)=delete
~MasstreeCommonLogType ()=delete
char * get_key ()
const char * get_key () const
KeySlice get_first_slice () const
KeyLength get_key_length_aligned () const
char * get_payload ()
const char * get_payload () const
void populate_base (log::LogCode type, StorageId storage_id, const void *key, KeyLength key_length, const void *payload=nullptr, PayloadLength payload_offset=0, PayloadLength payload_count=0) __attribute__((always_inline))
bool equal_record_and_log_suffixes (const char *data) const
used only for sanity check.
RecordAddresses apply_record_prepare (xct::RwLockableXctId *owner_id, char *record) const
Common parts of apply_record() in these log types that extract relevant addresses from the record header.
Public Member Functions inherited from foedus::log::RecordLogType
bool is_engine_log () const
bool is_storage_log () const
bool is_record_log () const
void apply_engine (thread::Thread *)
void apply_storage (Engine *, storage::StorageId)
void assert_valid_generic () const __attribute__((always_inline))
Verifies the log contains essential fields set.
Static Public Member Functions
static uint16_t calculate_log_length (KeyLength key_length, PayloadLength payload_count) __attribute__((always_inline))
static int compare_logs (const MasstreeCommonLogType *left, const MasstreeCommonLogType *right) __attribute__((always_inline))
Returns -1, 0, 1 when left is less than, same, larger than right in terms of key and xct_id.
Public Attributes
KeyLength key_length_
PayloadLength payload_offset_
PayloadLength payload_count_
uint16_t reserved_
char aligned_data_ [8]
Full key and (if exists) payload data, both of which are padded to 8 bytes.
Public Attributes inherited from foedus::log::BaseLogType
LogHeader header_
Constructor & Destructor Documentation
foedus::storage::masstree::MasstreeCommonLogType::MasstreeCommonLogType () delete
foedus::storage::masstree::MasstreeCommonLogType::MasstreeCommonLogType (const MasstreeCommonLogType & other) delete
foedus::storage::masstree::MasstreeCommonLogType::~MasstreeCommonLogType () delete
Member Function Documentation
RecordAddresses foedus::storage::masstree::MasstreeCommonLogType::apply_record_prepare (xct::RwLockableXctId * owner_id, char * record) const inline
Common parts of apply_record() in these log types that extract relevant addresses from the record header.
Parameters
[in,out] owner_id TID of the record
[out] record data-region of the record AS OF taking the write-set.
Precondition
This record must be locked by this thread.
Returns
RecordAddresses, to which the type-specific logic applies the change
This method mostly consists of assertions and straightforward calculations of offsets. The only notable thing is the handling of records whose offsets have changed since we took it as write-set.
When it happens
When the record must contain more space, expand_record() runs a system transaction that might migrate the record in the same page. When it happens, it keeps the same TID because the sysxct does nothing logically and the new page layout keeps the previous record intact. Reading xcts are safe to read either new or old records, and don't have to abort unless the TID actually changes when writing xcts update the TID.
What to do then
Remember, both old and new record regions are complete and correct. The only thing we have to be careful is that writing xcts write to the new record region. If they write to the old place, we lose the change. Fortunately, it is trivial for writing xcts because they always lock the records first. We can safely retrieve the new offset in apply_record() because lock implies full barriers. We just overwrite "record" pointer.
Other approches considered
We also tried a simpler approach, in sysxct increments TID when it migrates the record in-page. While it is "correct", we of course observed unnecessary aborts especially in transactions that caused the migration themselves. So, we
Definition at line 248 of file masstree_log_types.hpp.
References foedus::assorted::align8(), ASSERT_ND, ASSUME_ALIGNED, foedus::storage::masstree::extract_page_layer(), foedus::xct::RwLockableXctId::is_keylocked(), foedus::xct::XctId::is_moved(), foedus::xct::XctId::is_next_layer(), foedus::storage::masstree::kBorderPageDataPartOffset, foedus::storage::kPageSize, foedus::storage::to_page(), and foedus::xct::RwLockableXctId::xct_id_.
{
     ASSERT_ND(owner_id->is_keylocked());
     ASSERT_ND(!owner_id->xct_id_.is_next_layer());
     ASSERT_ND(!owner_id->xct_id_.is_moved());
     const uint8_t layer = extract_page_layer(owner_id);
     const KeyLength skipped = (layer + 1U) * sizeof(KeySlice);
     const KeyLength key_length_aligned = this->get_key_length_aligned();
     ASSERT_ND(key_length_aligned >= skipped);
     const KeyLength suffix_length_aligned = key_length_aligned - skipped;
     // no need to set key in apply(). it's already set when the record is physically inserted
     // (or in other places if this is recovery).
     ASSERT_ND(equal_record_and_log_suffixes(record));
     // In the MasstreeBorderPage Slot, lengthes come right after TID.
     // [0]: offset, [1]: physical_record_length_, [3]: payload_length_, [4]: remainder_length_
     // [5]: original_physical_record_length_, [6]: original_offset_
     uint16_t* lengthes = reinterpret_cast<uint16_t*>(owner_id + 1);
     const DataOffset offset = lengthes[0];
     ASSERT_ND(reinterpret_cast<uint64_t>(reinterpret_cast<uintptr_t>(record)) % kPageSize
       == static_cast<uint64_t>(offset + kBorderPageDataPartOffset));
     ASSERT_ND(lengthes[1] >= suffix_length_aligned + assorted::align8(this->payload_count_));
     ASSERT_ND(lengthes[1] + offset + kBorderPageDataPartOffset <= kPageSize);
     ASSERT_ND(lengthes[1] >= suffix_length_aligned + assorted::align8(lengthes[3]));
     ASSERT_ND(lengthes[4] == this->key_length_ - (layer * sizeof(KeySlice)));
     Page* page = to_page(record);
     char* page_char = reinterpret_cast<char*>(page);
     ASSERT_ND(record == page_char + offset + kBorderPageDataPartOffset);
     const DataOffset old_offset = (record - page_char) - kBorderPageDataPartOffset;
     if (old_offset != offset) {
       // This happens only when we expanded the record
       ASSERT_ND(lengthes[5] > lengthes[1]);
       // Data-region grows forward, so the new offset must be larger
       ASSERT_ND(lengthes[6] < offset);
       ASSERT_ND(old_offset < offset);
       record = page_char + kBorderPageDataPartOffset + offset;
       ASSERT_ND(equal_record_and_log_suffixes(record));
     }
     PayloadLength* record_payload_count = lengthes + 3;
     // record's payload is also 8-byte aligned, so copy multiply of 8 bytes.
     // if the compiler is smart enough, it will do some optimization here.
     char* record_payload = reinterpret_cast<char*>(
       ASSUME_ALIGNED(record + suffix_length_aligned, 8U));
     RecordAddresses ret = { record_payload_count, record_payload };
     return ret;
   }
static uint16_t foedus::storage::masstree::MasstreeCommonLogType::calculate_log_length (KeyLength key_length, PayloadLength payload_count) inline static
Definition at line 98 of file masstree_log_types.hpp.
References foedus::assorted::align8().
Referenced by foedus::storage::masstree::MasstreeDeleteLogType::calculate_log_length(), foedus::storage::masstree::MasstreeStoragePimpl::increment_general(), foedus::storage::masstree::MasstreeStoragePimpl::insert_general(), foedus::storage::masstree::MasstreeStoragePimpl::overwrite_general(), and foedus::storage::masstree::MasstreeStoragePimpl::upsert_general().
{
     return 24U + assorted::align8(key_length) + assorted::align8(payload_count);
   }
static int foedus::storage::masstree::MasstreeCommonLogType::compare_logs (const MasstreeCommonLogType * left, const MasstreeCommonLogType * right) inline static
Returns -1, 0, 1 when left is less than, same, larger than right in terms of key and xct_id.
Precondition
this->is_valid(), other.is_valid()
this->get_ordinal() != 0, other.get_ordinal() != 0
Definition at line 170 of file masstree_log_types.hpp.
References ASSERT_ND, foedus::storage::masstree::is_key_aligned_and_zero_padded(), foedus::storage::masstree::kSliceLen, LIKELY, and foedus::storage::masstree::normalize_be_bytes_full_aligned().
Referenced by foedus::snapshot::MergeSort::AdjustComparatorMasstree::operator()().
{
     ASSERT_ND(left->header_.storage_id_ == right->header_.storage_id_);
     if (left == right) {
       return 0;
     }
     if (LIKELY(left->key_length_ > 0 && right->key_length_ > 0)) {
       // Compare the first slice. This should be enough to differentiate most logs
       const char* left_key = left->get_key();
       const char* right_key = right->get_key();
       ASSERT_ND(is_key_aligned_and_zero_padded(left_key, left->key_length_));
       ASSERT_ND(is_key_aligned_and_zero_padded(right_key, right->key_length_));
       KeySlice left_slice = normalize_be_bytes_full_aligned(left_key);
       KeySlice right_slice = normalize_be_bytes_full_aligned(right_key);
       if (left_slice < right_slice) {
         return -1;
       } else if (left_slice > right_slice) {
         return 1;
       }
       // compare the rest with memcmp.
       KeyLength min_length = std::min(left->key_length_, right->key_length_);
       if (min_length > kSliceLen) {
         KeyLength remainder = min_length - kSliceLen;
         int key_result = std::memcmp(left_key + kSliceLen, right_key + kSliceLen, remainder);
         if (key_result != 0) {
           return key_result;
         }
       }
     }
     if (left->key_length_ < right->key_length_) {
       return -1;
     } else if (left->key_length_ < right->key_length_) {
       return 1;
     }
     // same key, now compare xct_id
     return left->header_.xct_id_.compare_epoch_and_orginal(right->header_.xct_id_);
   }
bool foedus::storage::masstree::MasstreeCommonLogType::equal_record_and_log_suffixes (const char * data) const inline
used only for sanity check.
returns if the record's and log's suffix keys are equal
Definition at line 148 of file masstree_log_types.hpp.
References foedus::assorted::align8(), ASSERT_ND, and foedus::storage::masstree::extract_page_layer().
{
     uint8_t layer = extract_page_layer(data);
     // Keys shorter than 8h+8 bytes are stored at layer <= h
     ASSERT_ND(layer <= key_length_ / sizeof(KeySlice));
     // both record and log keep 8-byte padded keys. so we can simply compare keys
     KeyLength skipped = (layer + 1U) * sizeof(KeySlice);
     if (key_length_ > skipped) {
       const char* key = get_key();
       KeyLength suffix_length = key_length_ - skipped;
       KeyLength suffix_length_aligned = assorted::align8(suffix_length);
       // both record and log's suffix keys are 8-byte aligned with zero-padding, so we can
       // compare multiply of 8 bytes
       return std::memcmp(data, key + skipped, suffix_length_aligned) == 0;
     }
     return true;
   }
KeySlice foedus::storage::masstree::MasstreeCommonLogType::get_first_slice () const inline
Definition at line 106 of file masstree_log_types.hpp.
References foedus::storage::masstree::normalize_be_bytes_full_aligned().
 { return normalize_be_bytes_full_aligned(aligned_data_); }
char* foedus::storage::masstree::MasstreeCommonLogType::get_key () inline
Definition at line 104 of file masstree_log_types.hpp.
Referenced by foedus::storage::masstree::MasstreeComposeContext::execute(), foedus::storage::masstree::operator<<(), foedus::storage::masstree::MasstreePartitioner::partition_batch(), and foedus::storage::masstree::prepare_sort_entries().
 { return aligned_data_; }
const char* foedus::storage::masstree::MasstreeCommonLogType::get_key () const inline
Definition at line 105 of file masstree_log_types.hpp.
 { return aligned_data_; }
KeyLength foedus::storage::masstree::MasstreeCommonLogType::get_key_length_aligned () const inline
Definition at line 107 of file masstree_log_types.hpp.
References foedus::assorted::align8().
 { return assorted::align8(key_length_); }
char* foedus::storage::masstree::MasstreeCommonLogType::get_payload () inline
Definition at line 108 of file masstree_log_types.hpp.
References ASSUME_ALIGNED.
Referenced by foedus::storage::masstree::operator<<().
{
     return reinterpret_cast<char*>(ASSUME_ALIGNED(aligned_data_ + get_key_length_aligned(), 8U));
   }
const char* foedus::storage::masstree::MasstreeCommonLogType::get_payload () const inline
Definition at line 111 of file masstree_log_types.hpp.
References ASSUME_ALIGNED.
{
     return reinterpret_cast<const char*>(
       ASSUME_ALIGNED(aligned_data_ + get_key_length_aligned(), 8U));
   }
void foedus::storage::masstree::MasstreeCommonLogType::populate_base (log::LogCode type, StorageId storage_id, const void * key, KeyLength key_length, const void * payload = nullptr, PayloadLength payload_offset = 0, PayloadLength payload_count = 0) inline
Definition at line 116 of file masstree_log_types.hpp.
References foedus::assorted::align8(), foedus::log::BaseLogType::header_, foedus::log::LogHeader::log_length_, foedus::log::LogHeader::log_type_code_, and foedus::log::LogHeader::storage_id_.
{
     header_.log_type_code_ = type;
     header_.log_length_ = calculate_log_length(key_length, payload_count);
     header_.storage_id_ = storage_id;
     key_length_ = key_length;
     payload_offset_ = payload_offset;
     payload_count_ = payload_count;
     reserved_ = 0;
     std::memcpy(aligned_data_, key, key_length);
     KeyLength aligned_key_length = assorted::align8(key_length);
     if (aligned_key_length != key_length) {
       std::memset(aligned_data_ + key_length, 0, aligned_key_length - key_length);
     }
     if (payload_count > 0) {
       PayloadLength aligned_payload_count = assorted::align8(payload_count);
       char* payload_base = aligned_data_ + aligned_key_length;
       std::memcpy(payload_base, payload, payload_count);
       if (aligned_payload_count != payload_count) {
         std::memset(payload_base + payload_count, 0, aligned_payload_count - payload_count);
       }
     }
   }
Member Data Documentation
char foedus::storage::masstree::MasstreeCommonLogType::aligned_data_[8]
Full key and (if exists) payload data, both of which are padded to 8 bytes.
By padding key part to 8 bytes, slicing becomes more efficient.
Definition at line 96 of file masstree_log_types.hpp.
KeyLength foedus::storage::masstree::MasstreeCommonLogType::key_length_
Definition at line 88 of file masstree_log_types.hpp.
Referenced by foedus::storage::masstree::MasstreeComposeContext::execute(), foedus::storage::masstree::operator<<(), foedus::storage::masstree::MasstreePartitioner::partition_batch(), foedus::storage::masstree::prepare_sort_entries(), and foedus::snapshot::update_key_lengthes().
PayloadLength foedus::storage::masstree::MasstreeCommonLogType::payload_count_
Definition at line 90 of file masstree_log_types.hpp.
Referenced by foedus::storage::masstree::operator<<().
PayloadLength foedus::storage::masstree::MasstreeCommonLogType::payload_offset_
Definition at line 89 of file masstree_log_types.hpp.
Referenced by foedus::storage::masstree::operator<<().
uint16_t foedus::storage::masstree::MasstreeCommonLogType::reserved_
Definition at line 91 of file masstree_log_types.hpp.
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/storage/masstree/masstree_log_types.hpp