libfoedus-core: foedus::storage::MetadataSerializer Struct Reference
foedus::storage::MetadataSerializer Struct Reference
Detailed Description
Definition at line 117 of file metadata.hpp.
#include <metadata.hpp>
Public Member Functions
MetadataSerializer ()
MetadataSerializer (Metadata *data)
virtual ~MetadataSerializer ()
ErrorStack load_base (tinyxml2::XMLElement *element)
common routine for the implementation of load()
ErrorStack save_base (tinyxml2::XMLElement *element) const
common routine for the implementation of save()
Public Member Functions inherited from foedus::externalize::Externalizable
virtual ErrorStack load (tinyxml2::XMLElement *element)=0
Reads the content of this object from the given XML element.
virtual ErrorStack save (tinyxml2::XMLElement *element) const =0
Writes the content of this object to the given XML element.
virtual const char * get_tag_name () const =0
Returns an XML tag name for this object as a root element.
virtual void assign (const foedus::externalize::Externalizable *other)=0
Polymorphic assign operator.
ErrorStack load_from_string (const std::string &xml)
Load the content of this object from the given XML string.
void save_to_stream (std::ostream *ptr) const
Invokes save() and directs the resulting XML text to the given stream.
ErrorStack load_from_file (const fs::Path &path)
Load the content of this object from the specified XML file.
ErrorStack save_to_file (const fs::Path &path) const
Atomically and durably writes out this object to the specified XML file.
Static Public Member Functions
static ErrorStack load_all_storages_from_xml (storage::StorageId largest_storage_id, tinyxml2::XMLElement *element, StorageControlBlock *blocks)
static ErrorStack save_all_storages_to_xml (storage::StorageId largest_storage_id, tinyxml2::XMLElement *element, StorageControlBlock *blocks)
Static Public Member Functions inherited from foedus::externalize::Externalizable
static ErrorStack insert_comment (tinyxml2::XMLElement *element, const std::string &comment)
static ErrorStack append_comment (tinyxml2::XMLElement *parent, const std::string &comment)
static ErrorStack create_element (tinyxml2::XMLElement *parent, const std::string &name, tinyxml2::XMLElement **out)
template<typename T >
static ErrorStack add_element (tinyxml2::XMLElement *parent, const std::string &tag, const std::string &comment, T value)
Only declaration in header.
template<uint MAXLEN, typename CHAR >
static ErrorStack add_element (tinyxml2::XMLElement *parent, const std::string &tag, const std::string &comment, const assorted::FixedString< MAXLEN, CHAR > &value)
template<typename T >
static ErrorStack add_element (tinyxml2::XMLElement *parent, const std::string &tag, const std::string &comment, const std::vector< T > &value)
vector version
template<typename ENUM >
static ErrorStack add_enum_element (tinyxml2::XMLElement *parent, const std::string &tag, const std::string &comment, ENUM value)
enum version
static ErrorStack add_child_element (tinyxml2::XMLElement *parent, const std::string &tag, const std::string &comment, const Externalizable &child)
child Externalizable version
template<typename T >
static ErrorStack get_element (tinyxml2::XMLElement *parent, const std::string &tag, T *out, bool optional=false, T value=0)
Only declaration in header.
static ErrorStack get_element (tinyxml2::XMLElement *parent, const std::string &tag, std::string *out, bool optional=false, const char *value="")
string type is bit special.
template<uint MAXLEN, typename CHAR >
static ErrorStack get_element (tinyxml2::XMLElement *parent, const std::string &tag, assorted::FixedString< MAXLEN, CHAR > *out, bool optional=false, const assorted::FixedString< MAXLEN, CHAR > &value=assorted::FixedString< MAXLEN, CHAR >())
template<typename ENUM >
static ErrorStack get_enum_element (tinyxml2::XMLElement *parent, const std::string &tag, ENUM *out, bool optional=false, ENUM default_value=static_cast< ENUM >(0))
enum version
template<typename T >
static ErrorStack get_element (tinyxml2::XMLElement *parent, const std::string &tag, std::vector< T > *out, bool optional=false)
vector version.
static ErrorStack get_child_element (tinyxml2::XMLElement *parent, const std::string &tag, Externalizable *child, bool optional=false)
child Externalizable version
Public Attributes
Metadata * data_
Constructor & Destructor Documentation
foedus::storage::MetadataSerializer::MetadataSerializer () inline
Definition at line 118 of file metadata.hpp.
 : data_(CXX11_NULLPTR) {}
foedus::storage::MetadataSerializer::MetadataSerializer (Metadata * data) inline explicit
Definition at line 119 of file metadata.hpp.
 : data_(data) {}
virtual foedus::storage::MetadataSerializer::~MetadataSerializer () inline virtual
Definition at line 120 of file metadata.hpp.
 {}
Member Function Documentation
ErrorStack foedus::storage::MetadataSerializer::load_all_storages_from_xml (storage::StorageId largest_storage_id, tinyxml2::XMLElement * element, StorageControlBlock * blocks) static
Definition at line 125 of file metadata.cpp.
References ASSERT_ND, CHECK_ERROR, ERROR_STACK, foedus::externalize::Externalizable::get_element(), foedus::externalize::Externalizable::get_enum_element(), foedus::storage::kArrayStorage, foedus::kErrorCodeStrUnsupportedMetadata, foedus::storage::kExists, foedus::storage::kHashStorage, foedus::storage::kInvalidStorage, foedus::storage::kMasstreeStorage, foedus::storage::kNotExists, foedus::kRetOk, foedus::storage::kSequentialStorage, foedus::storage::load_from_xml_array(), foedus::storage::load_from_xml_hash(), foedus::storage::load_from_xml_masstree(), foedus::storage::load_from_xml_sequential(), foedus::storage::StorageControlBlock::meta_, and foedus::storage::StorageControlBlock::status_.
Referenced by foedus::snapshot::SnapshotMetadata::load().
{
   uint32_t loaded_count = 0;
   for (tinyxml2::XMLElement* element = parent->FirstChildElement(kChildTagName);
     element;
     element = element->NextSiblingElement(kChildTagName)) {
     StorageId id;
     CHECK_ERROR(get_element(element, "id_", &id))
     ASSERT_ND(id > 0);
     ASSERT_ND(id <= largest_storage_id);
     StorageType type = kInvalidStorage;
     CHECK_ERROR(get_enum_element(element, "type_", &type));
     VLOG(0) << "Loading metadata of storage-" << id << " from xml";
     ASSERT_ND(blocks[id].status_ == kNotExists);
     Metadata* data = &blocks[id].meta_;
     blocks[id].status_ = kExists;
     switch (type) {
     case kArrayStorage:
       CHECK_ERROR(load_from_xml_array(element, data));
       break;
     case kHashStorage:
       CHECK_ERROR(load_from_xml_hash(element, data));
       break;
     case kMasstreeStorage:
       CHECK_ERROR(load_from_xml_masstree(element, data));
       break;
     case kSequentialStorage:
       CHECK_ERROR(load_from_xml_sequential(element, data));
       break;
     default:
       return ERROR_STACK(kErrorCodeStrUnsupportedMetadata);
     }
     ++loaded_count;
   }
   LOG(INFO) << "Loaded metadata of " << loaded_count << " storages";
   return kRetOk;
 }
ErrorStack foedus::storage::MetadataSerializer::load_base (tinyxml2::XMLElement * element)
common routine for the implementation of load()
Definition at line 50 of file metadata.cpp.
References CHECK_ERROR, data_, foedus::externalize::Externalizable::get_element(), foedus::externalize::Externalizable::get_enum_element(), foedus::storage::Metadata::id_, foedus::kRetOk, foedus::storage::Metadata::name_, foedus::storage::Metadata::root_snapshot_page_id_, foedus::storage::Metadata::SnapshotThresholds::snapshot_keep_threshold_, foedus::storage::Metadata::snapshot_thresholds_, foedus::storage::Metadata::SnapshotThresholds::snapshot_trigger_threshold_, and foedus::storage::Metadata::type_.
Referenced by foedus::storage::sequential::SequentialMetadataSerializer::load(), foedus::storage::hash::HashMetadataSerializer::load(), foedus::storage::array::ArrayMetadataSerializer::load(), and foedus::storage::masstree::MasstreeMetadataSerializer::load().
{
   CHECK_ERROR(get_element(element, "id_", &data_->id_))
   CHECK_ERROR(get_enum_element(element, "type_", &data_->type_))
   CHECK_ERROR(get_element(element, "name_", &data_->name_))
   CHECK_ERROR(get_element(element, "root_snapshot_page_id_", &data_->root_snapshot_page_id_))
   CHECK_ERROR(get_element(
     element,
     "snapshot_trigger_threshold_",
     &data_->snapshot_thresholds_.snapshot_trigger_threshold_));
   CHECK_ERROR(get_element(
     element,
     "snapshot_keep_threshold_",
     &data_->snapshot_thresholds_.snapshot_keep_threshold_));
   return kRetOk;
 }
ErrorStack foedus::storage::MetadataSerializer::save_all_storages_to_xml (storage::StorageId largest_storage_id, tinyxml2::XMLElement * element, StorageControlBlock * blocks) static
Definition at line 166 of file metadata.cpp.
References ASSERT_ND, CHECK_ERROR, ERROR_STACK, foedus::fs::exists(), foedus::storage::kArrayStorage, foedus::kErrorCodeStrUnsupportedMetadata, foedus::storage::kHashStorage, foedus::storage::kMasstreeStorage, foedus::kRetOk, foedus::storage::kSequentialStorage, foedus::storage::StorageControlBlock::meta_, foedus::storage::save_to_xml_array(), foedus::storage::save_to_xml_hash(), foedus::storage::save_to_xml_masstree(), foedus::storage::save_to_xml_sequential(), and foedus::storage::Metadata::type_.
Referenced by foedus::snapshot::SnapshotMetadata::save().
{
   uint32_t saved_count = 0;
   for (storage::StorageId id = 1; id <= largest_storage_id; ++id) {
     ASSERT_ND(blocks[id].is_valid_status());
     if (!blocks[id].exists()) {
       continue;
     }
     StorageType type = blocks[id].meta_.type_;
     Metadata* data = &blocks[id].meta_;
     switch (type) {
     case kArrayStorage:
       CHECK_ERROR(save_to_xml_array(parent, data));
       break;
     case kHashStorage:
       CHECK_ERROR(save_to_xml_hash(parent, data));
       break;
     case kMasstreeStorage:
       CHECK_ERROR(save_to_xml_masstree(parent, data));
       break;
     case kSequentialStorage:
       CHECK_ERROR(save_to_xml_sequential(parent, data));
       break;
     default:
       return ERROR_STACK(kErrorCodeStrUnsupportedMetadata);
     }
     ++saved_count;
   }
   LOG(INFO) << "Written metadata of " << saved_count << " storages";
   return kRetOk;
 }
ErrorStack foedus::storage::MetadataSerializer::save_base (tinyxml2::XMLElement * element) const
common routine for the implementation of save()
Definition at line 66 of file metadata.cpp.
References foedus::externalize::Externalizable::add_element(), foedus::externalize::Externalizable::add_enum_element(), CHECK_ERROR, data_, foedus::storage::Metadata::id_, foedus::kRetOk, foedus::storage::Metadata::name_, foedus::storage::Metadata::root_snapshot_page_id_, foedus::storage::Metadata::SnapshotThresholds::snapshot_keep_threshold_, foedus::storage::Metadata::snapshot_thresholds_, foedus::storage::Metadata::SnapshotThresholds::snapshot_trigger_threshold_, and foedus::storage::Metadata::type_.
Referenced by foedus::storage::sequential::SequentialMetadataSerializer::save(), foedus::storage::hash::HashMetadataSerializer::save(), foedus::storage::array::ArrayMetadataSerializer::save(), and foedus::storage::masstree::MasstreeMetadataSerializer::save().
{
   CHECK_ERROR(add_element(element, "id_", "", data_->id_));
   CHECK_ERROR(add_enum_element(element, "type_", "", data_->type_));
   CHECK_ERROR(add_element(element, "name_", "", data_->name_));
   CHECK_ERROR(add_element(element, "root_snapshot_page_id_", "", data_->root_snapshot_page_id_));
   CHECK_ERROR(add_element(
     element,
     "snapshot_trigger_threshold_",
     "",
     data_->snapshot_thresholds_.snapshot_trigger_threshold_));
   CHECK_ERROR(add_element(
     element,
     "snapshot_keep_threshold_",
     "",
     data_->snapshot_thresholds_.snapshot_keep_threshold_));
   return kRetOk;
 }
Member Data Documentation
Metadata* foedus::storage::MetadataSerializer::data_
Definition at line 136 of file metadata.hpp.
Referenced by load_base(), and save_base().
The documentation for this struct was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/storage/metadata.hpp
/home/shino/foedus_code/foedus-core/src/foedus/storage/metadata.cpp