libfoedus-core: foedus::storage::hash::TmpSnashotPage Struct Reference
foedus::storage::hash::TmpSnashotPage Struct Reference
Detailed Description
Definition at line 36 of file hash_storage_debug.cpp.
Public Member Functions
ErrorStack init (cache::SnapshotFileSet *files, SnapshotPagePointer pointer)
HashIntermediatePage * as_intermediate ()
HashDataPage * as_data ()
Public Attributes
memory::AlignedMemory buf_
Page * page_
Member Function Documentation
HashDataPage* foedus::storage::hash::TmpSnashotPage::as_data () inline
Definition at line 47 of file hash_storage_debug.cpp.
References page_.
Referenced by foedus::storage::hash::HashStoragePimpl::debugout_single_thread_data(), and foedus::storage::hash::HashStoragePimpl::debugout_single_thread_intermediate().
 { return reinterpret_cast<HashDataPage*>(page_); }
HashIntermediatePage* foedus::storage::hash::TmpSnashotPage::as_intermediate () inline
Definition at line 46 of file hash_storage_debug.cpp.
References page_.
Referenced by foedus::storage::hash::HashStoragePimpl::debugout_single_thread(), and foedus::storage::hash::HashStoragePimpl::debugout_single_thread_intermediate().
 { return reinterpret_cast<HashIntermediatePage*>(page_); }
ErrorStack foedus::storage::hash::TmpSnashotPage::init (cache::SnapshotFileSet * files, SnapshotPagePointer pointer) inline
Definition at line 37 of file hash_storage_debug.cpp.
References foedus::memory::AlignedMemory::alloc(), buf_, foedus::memory::AlignedMemory::get_block(), foedus::memory::AlignedMemory::get_size(), foedus::memory::AlignedMemory::is_null(), foedus::memory::AlignedMemory::kNumaAllocOnnode, foedus::kRetOk, page_, foedus::cache::SnapshotFileSet::read_page(), and WRAP_ERROR_CODE.
Referenced by foedus::storage::hash::HashStoragePimpl::debugout_single_thread(), foedus::storage::hash::HashStoragePimpl::debugout_single_thread_data(), and foedus::storage::hash::HashStoragePimpl::debugout_single_thread_intermediate().
{
     if (buf_.is_null() || buf_.get_size() < 1 << 12U) {
       buf_.alloc(1 << 12U, 1 << 12U, memory::AlignedMemory::kNumaAllocOnnode, 0);
     }
     page_ = reinterpret_cast<Page*>(buf_.get_block());
     WRAP_ERROR_CODE(files->read_page(pointer, page_));
     return kRetOk;
   }
Member Data Documentation
memory::AlignedMemory foedus::storage::hash::TmpSnashotPage::buf_
Definition at line 49 of file hash_storage_debug.cpp.
Referenced by init().
Page* foedus::storage::hash::TmpSnashotPage::page_
Definition at line 50 of file hash_storage_debug.cpp.
Referenced by as_data(), as_intermediate(), and init().
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/src/foedus/storage/hash/hash_storage_debug.cpp