libfoedus-core: foedus::storage::sequential::StreamStatus Struct Reference
foedus::storage::sequential::StreamStatus Struct Reference
Unlike other composers, this one doesn't need merge sort.
Detailed Description
Unlike other composers, this one doesn't need merge sort.
It's dumb simple.
Definition at line 52 of file sequential_composer_impl.cpp.
Public Member Functions
ErrorCode init (snapshot::SortedBuffer *stream)
ErrorCode next ()
ErrorCode wind_stream ()
void read_entry ()
const SequentialAppendLogType * get_entry () const
Public Attributes
snapshot::SortedBuffer * stream_
const char * buffer_
uint64_t buffer_size_
uint64_t cur_absolute_pos_
uint64_t cur_relative_pos_
uint64_t end_absolute_pos_
uint32_t cur_length_
const void * cur_payload_
xct::XctId cur_owner_id_
bool ended_
Member Function Documentation
const SequentialAppendLogType* foedus::storage::sequential::StreamStatus::get_entry () const inline
Definition at line 107 of file sequential_composer_impl.cpp.
References buffer_, and cur_relative_pos_.
Referenced by foedus::storage::sequential::SequentialComposer::compose(), and read_entry().
{
     return reinterpret_cast<const SequentialAppendLogType*>(buffer_ + cur_relative_pos_);
   }
ErrorCode foedus::storage::sequential::StreamStatus::init (snapshot::SortedBuffer * stream) inline
Definition at line 53 of file sequential_composer_impl.cpp.
References foedus::snapshot::SortedBuffer::assert_checks(), ASSERT_ND, buffer_, buffer_size_, CHECK_ERROR_CODE, cur_absolute_pos_, cur_length_, cur_relative_pos_, end_absolute_pos_, ended_, foedus::snapshot::SortedBuffer::get_buffer(), foedus::snapshot::SortedBuffer::get_buffer_size(), foedus::snapshot::SortedBuffer::get_cur_block_abosulte_begin(), foedus::snapshot::SortedBuffer::get_cur_block_abosulte_end(), foedus::snapshot::SortedBuffer::get_offset(), foedus::kErrorCodeOk, read_entry(), stream_, and wind_stream().
Referenced by foedus::storage::sequential::SequentialComposer::compose().
{
     stream_ = stream;
     stream_->assert_checks();
     buffer_ = stream->get_buffer();
     buffer_size_ = stream->get_buffer_size();
     cur_absolute_pos_ = stream->get_cur_block_abosulte_begin();
     ASSERT_ND(cur_absolute_pos_ >= stream->get_offset());
     cur_relative_pos_ = cur_absolute_pos_ - stream->get_offset();
     end_absolute_pos_ = stream->get_cur_block_abosulte_end();
     ended_ = false;
     read_entry();
     if (cur_absolute_pos_ >= end_absolute_pos_) {
       ended_ = true;
     } else if (cur_relative_pos_ + cur_length_ > buffer_size_) {
       LOG(INFO) << "interesting, super unlucky case. wind immediately";
       CHECK_ERROR_CODE(wind_stream());
       read_entry();
       ASSERT_ND(cur_relative_pos_ + cur_length_ <= buffer_size_);
     }
     return kErrorCodeOk;
   }
ErrorCode foedus::storage::sequential::StreamStatus::next () inline
Definition at line 74 of file sequential_composer_impl.cpp.
References ASSERT_ND, buffer_size_, CHECK_ERROR_CODE, cur_absolute_pos_, cur_length_, cur_relative_pos_, end_absolute_pos_, ended_, foedus::kErrorCodeOk, read_entry(), UNLIKELY, and wind_stream().
Referenced by foedus::storage::sequential::SequentialComposer::compose().
                    {
     ASSERT_ND(!ended_);
     ASSERT_ND(cur_relative_pos_ + cur_length_ <= buffer_size_);
     cur_absolute_pos_ += cur_length_;
     cur_relative_pos_ += cur_length_;
     if (UNLIKELY(cur_absolute_pos_ >= end_absolute_pos_)) {
       ended_ = true;
       return kErrorCodeOk;
     } else if (UNLIKELY(cur_relative_pos_ >= buffer_size_)) {
       CHECK_ERROR_CODE(wind_stream());
     }
     read_entry();
     if (UNLIKELY(cur_relative_pos_ + cur_length_ > buffer_size_)) {
       CHECK_ERROR_CODE(wind_stream());
       read_entry();
     }
     ASSERT_ND(cur_relative_pos_ + cur_length_ <= buffer_size_);
     return kErrorCodeOk;
   }
void foedus::storage::sequential::StreamStatus::read_entry () inline
Definition at line 99 of file sequential_composer_impl.cpp.
References ASSERT_ND, cur_length_, cur_owner_id_, cur_payload_, get_entry(), foedus::log::LogHeader::get_type(), foedus::log::BaseLogType::header_, foedus::log::kLogCodeSequentialAppend, foedus::log::LogHeader::log_length_, foedus::storage::sequential::SequentialAppendLogType::payload_, and foedus::log::LogHeader::xct_id_.
Referenced by init(), and next().
                     {
     const SequentialAppendLogType* entry = get_entry();
     ASSERT_ND(entry->header_.get_type() == log::kLogCodeSequentialAppend);
     ASSERT_ND(entry->header_.log_length_ > 0);
     cur_length_ = entry->header_.log_length_;
     cur_payload_ = entry->payload_;
     cur_owner_id_ = entry->header_.xct_id_;
   }
ErrorCode foedus::storage::sequential::StreamStatus::wind_stream () inline
Definition at line 94 of file sequential_composer_impl.cpp.
References CHECK_ERROR_CODE, cur_absolute_pos_, cur_relative_pos_, foedus::kErrorCodeOk, stream_, foedus::snapshot::SortedBuffer::to_relative_pos(), and foedus::snapshot::SortedBuffer::wind().
Referenced by init(), and next().
{
     CHECK_ERROR_CODE(stream_->wind(cur_absolute_pos_));
     cur_relative_pos_ = stream_->to_relative_pos(cur_absolute_pos_);
     return kErrorCodeOk;
   }
Member Data Documentation
const char* foedus::storage::sequential::StreamStatus::buffer_
Definition at line 112 of file sequential_composer_impl.cpp.
Referenced by get_entry(), and init().
uint64_t foedus::storage::sequential::StreamStatus::buffer_size_
Definition at line 113 of file sequential_composer_impl.cpp.
Referenced by init(), and next().
uint64_t foedus::storage::sequential::StreamStatus::cur_absolute_pos_
Definition at line 114 of file sequential_composer_impl.cpp.
Referenced by init(), next(), and wind_stream().
uint32_t foedus::storage::sequential::StreamStatus::cur_length_
Definition at line 117 of file sequential_composer_impl.cpp.
Referenced by init(), next(), and read_entry().
xct::XctId foedus::storage::sequential::StreamStatus::cur_owner_id_
Definition at line 119 of file sequential_composer_impl.cpp.
Referenced by foedus::storage::sequential::SequentialComposer::compose(), and read_entry().
const void* foedus::storage::sequential::StreamStatus::cur_payload_
Definition at line 118 of file sequential_composer_impl.cpp.
Referenced by foedus::storage::sequential::SequentialComposer::compose(), and read_entry().
uint64_t foedus::storage::sequential::StreamStatus::cur_relative_pos_
Definition at line 115 of file sequential_composer_impl.cpp.
Referenced by get_entry(), init(), next(), and wind_stream().
uint64_t foedus::storage::sequential::StreamStatus::end_absolute_pos_
Definition at line 116 of file sequential_composer_impl.cpp.
Referenced by init(), and next().
bool foedus::storage::sequential::StreamStatus::ended_
Definition at line 120 of file sequential_composer_impl.cpp.
Referenced by foedus::storage::sequential::SequentialComposer::compose(), init(), and next().
snapshot::SortedBuffer* foedus::storage::sequential::StreamStatus::stream_
Definition at line 111 of file sequential_composer_impl.cpp.
Referenced by init(), and wind_stream().
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/src/foedus/storage/sequential/sequential_composer_impl.cpp