libfoedus-core: foedus::storage::hash::HashTmpBin::Record Struct Reference
foedus::storage::hash::HashTmpBin::Record Struct Reference
FOEDUS Components » Storage Manager » Hashtable Storage
Represents a record with a unique key.
Detailed Description
Represents a record with a unique key.
Here, we consume memory super generously. one-page for one record. This makes sure that we don't need any record expansion. We reuse memory for each bin, and we should have at most hundreds of tuples in each bin, so should be fine.
Definition at line 78 of file hash_tmpbin.hpp.
#include <hash_tmpbin.hpp>
Public Member Functions
char * get_key () __attribute__((always_inline))
char * get_payload () __attribute__((always_inline))
Record * get_record_next (const HashTmpBin *enclosure) const __attribute__((always_inline))
void set_all (xct::XctId xct_id, const void *key, uint16_t key_length, HashValue hash, const void *payload, uint16_t payload_length) __attribute__((always_inline))
void set_payload (const void *payload, uint16_t payload_length) __attribute__((always_inline))
void overwrite_payload (const void *payload, uint16_t payload_offset, uint16_t payload_count) __attribute__((always_inline))
Public Attributes
xct::XctId xct_id_
uint16_t key_length_
uint16_t payload_length_
uint16_t aligned_key_length_
uint16_t aligned_payload_length_
HashValue hash_
RecordIndex next_
constitutes a singly-linked list in each bucket
uint32_t unused_
char data_ [kPageSize-32]
key and payload, like the log entry, key part is 8-byte aligned.
Member Function Documentation
char* foedus::storage::hash::HashTmpBin::Record::get_key () inline
Definition at line 91 of file hash_tmpbin.hpp.
References data_.
Referenced by foedus::storage::hash::operator<<(), and set_all().
 { return data_; }
char* foedus::storage::hash::HashTmpBin::Record::get_payload () inline
Definition at line 92 of file hash_tmpbin.hpp.
References aligned_key_length_.
Referenced by foedus::storage::hash::operator<<(), overwrite_payload(), set_all(), and set_payload().
 { return data_ + aligned_key_length_; }
Record* foedus::storage::hash::HashTmpBin::Record::get_record_next (const HashTmpBin * enclosure) const inline
Definition at line 93 of file hash_tmpbin.hpp.
{
       return enclosure->get_record(next_);
     }
void foedus::storage::hash::HashTmpBin::Record::overwrite_payload (const void * payload, uint16_t payload_offset, uint16_t payload_count) inline
Definition at line 133 of file hash_tmpbin.hpp.
References get_payload().
Referenced by foedus::storage::hash::HashTmpBin::overwrite_record().
{
       std::memcpy(get_payload() + payload_offset, payload, payload_count);
     }
void foedus::storage::hash::HashTmpBin::Record::set_all (xct::XctId xct_id, const void * key, uint16_t key_length, HashValue hash, const void * payload, uint16_t payload_length) inline
Definition at line 97 of file hash_tmpbin.hpp.
References foedus::assorted::align8(), ASSERT_ND, get_key(), and get_payload().
Referenced by foedus::storage::hash::HashTmpBin::insert_record().
{
       xct_id_ = xct_id;
       ASSERT_ND(!xct_id.is_deleted());
       key_length_ = key_length;
       payload_length_ = payload_length;
       aligned_key_length_ = assorted::align8(key_length);
       aligned_payload_length_ = assorted::align8(payload_length);
       hash_ = hash;
       next_ = 0;
       std::memcpy(get_key(), key, key_length);
       if (key_length != aligned_key_length_) {
         std::memset(get_key() + key_length, 0, aligned_key_length_ - key_length);
       }
       std::memcpy(get_payload(), payload, payload_length);
       if (payload_length != aligned_payload_length_) {
         std::memset(get_payload() + payload_length, 0, aligned_payload_length_ - payload_length);
       }
     }
void foedus::storage::hash::HashTmpBin::Record::set_payload (const void * payload, uint16_t payload_length) inline
Definition at line 124 of file hash_tmpbin.hpp.
References foedus::assorted::align8(), and get_payload().
Referenced by foedus::storage::hash::HashTmpBin::insert_record(), and foedus::storage::hash::HashTmpBin::update_record().
{
       payload_length_ = payload_length;
       aligned_payload_length_ = assorted::align8(payload_length);
       std::memcpy(get_payload(), payload, payload_length);
       if (payload_length != aligned_payload_length_) {
         std::memset(get_payload() + payload_length, 0, aligned_payload_length_ - payload_length);
       }
     }
Member Data Documentation
uint16_t foedus::storage::hash::HashTmpBin::Record::aligned_key_length_
Definition at line 82 of file hash_tmpbin.hpp.
Referenced by get_payload().
uint16_t foedus::storage::hash::HashTmpBin::Record::aligned_payload_length_
Definition at line 83 of file hash_tmpbin.hpp.
char foedus::storage::hash::HashTmpBin::Record::data_[kPageSize-32]
key and payload, like the log entry, key part is 8-byte aligned.
Definition at line 89 of file hash_tmpbin.hpp.
Referenced by get_key().
HashValue foedus::storage::hash::HashTmpBin::Record::hash_
Definition at line 84 of file hash_tmpbin.hpp.
Referenced by foedus::storage::hash::HashTmpBin::clean_quick(), foedus::storage::hash::HashTmpBin::delete_record(), foedus::storage::hash::HashTmpBin::insert_record(), foedus::storage::hash::operator<<(), foedus::storage::hash::HashTmpBin::overwrite_record(), and foedus::storage::hash::HashTmpBin::update_record().
uint16_t foedus::storage::hash::HashTmpBin::Record::key_length_
Definition at line 80 of file hash_tmpbin.hpp.
Referenced by foedus::storage::hash::operator<<().
RecordIndex foedus::storage::hash::HashTmpBin::Record::next_
constitutes a singly-linked list in each bucket
Definition at line 86 of file hash_tmpbin.hpp.
Referenced by foedus::storage::hash::HashTmpBin::insert_record(), and foedus::storage::hash::operator<<().
uint16_t foedus::storage::hash::HashTmpBin::Record::payload_length_
Definition at line 81 of file hash_tmpbin.hpp.
Referenced by foedus::storage::hash::operator<<(), and foedus::storage::hash::HashTmpBin::overwrite_record().
uint32_t foedus::storage::hash::HashTmpBin::Record::unused_
Definition at line 87 of file hash_tmpbin.hpp.
xct::XctId foedus::storage::hash::HashTmpBin::Record::xct_id_
Definition at line 79 of file hash_tmpbin.hpp.
Referenced by foedus::storage::hash::HashTmpBin::delete_record(), foedus::storage::hash::HashTmpBin::insert_record(), foedus::storage::hash::operator<<(), foedus::storage::hash::HashTmpBin::overwrite_record(), and foedus::storage::hash::HashTmpBin::update_record().
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/storage/hash/hash_tmpbin.hpp