libfoedus-core: foedus::log::StorageLogType Struct Reference
foedus::log::StorageLogType Struct Reference
FOEDUS Components » Log Manager » Log Types
Base class for log type of storage-wide operation.
Detailed Description
Base class for log type of storage-wide operation.
Definition at line 151 of file common_log_types.hpp.
#include <common_log_types.hpp>
Public Member Functions
bool is_engine_log () const
bool is_storage_log () const
bool is_record_log () const
void apply_engine (thread::Thread *)
void apply_record (thread::Thread *, storage::StorageId, xct::RwLockableXctId *, char *)
void assert_valid_generic () __attribute__((always_inline))
Verifies the log contains essential fields set.
Additional Inherited Members
Public Attributes inherited from foedus::log::BaseLogType
LogHeader header_
Member Function Documentation
void foedus::log::StorageLogType::apply_engine (thread::Thread *) inline
Definition at line 155 of file common_log_types.hpp.
References ASSERT_ND.
{
     ASSERT_ND(false);
   }
void foedus::log::StorageLogType::apply_record (thread::Thread * , storage::StorageId , xct::RwLockableXctId * , char *) inline
Definition at line 158 of file common_log_types.hpp.
References ASSERT_ND.
              {
     ASSERT_ND(false);
   }
void foedus::log::StorageLogType::assert_valid_generic () inline
Verifies the log contains essential fields set.
Definition at line 168 of file common_log_types.hpp.
References ASSERT_ND.
Referenced by foedus::storage::DropLogType::assert_valid(), foedus::storage::CreateLogType::assert_valid(), foedus::storage::sequential::SequentialAppendLogType::assert_valid(), foedus::storage::array::ArrayOverwriteLogType::assert_valid(), foedus::storage::array::ArrayIncrementLogType::assert_valid(), foedus::storage::hash::HashInsertLogType::assert_valid(), foedus::storage::hash::HashDeleteLogType::assert_valid(), foedus::storage::masstree::MasstreeInsertLogType::assert_valid(), foedus::storage::hash::HashUpdateLogType::assert_valid(), foedus::storage::masstree::MasstreeDeleteLogType::assert_valid(), foedus::storage::masstree::MasstreeUpdateLogType::assert_valid(), foedus::storage::hash::HashOverwriteLogType::assert_valid(), and foedus::storage::masstree::MasstreeOverwriteLogType::assert_valid().
{
     ASSERT_ND(header_.is_valid_type());
     ASSERT_ND(header_.log_length_ != 0);
     ASSERT_ND(header_.log_length_ % 8 == 0);  // must be 8 byte aligned
     ASSERT_ND(header_.storage_id_ > 0);
   }
bool foedus::log::StorageLogType::is_engine_log () const inline
Definition at line 152 of file common_log_types.hpp.
 { return false; }
bool foedus::log::StorageLogType::is_record_log () const inline
Definition at line 154 of file common_log_types.hpp.
 { return false; }
bool foedus::log::StorageLogType::is_storage_log () const inline
Definition at line 153 of file common_log_types.hpp.
 { return true; }
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/log/common_log_types.hpp