libfoedus-core: foedus::storage::masstree::GrowNonFirstLayerRoot Struct Reference
foedus::storage::masstree::GrowNonFirstLayerRoot Struct Reference final
FOEDUS Components » Storage Manager » Masstree Storage
A system transaction to grow a second- or depper-layer root.
Detailed Description
A system transaction to grow a second- or depper-layer root.
See also
Physical-only, short-living system transactions.
This does nothing and returns kErrorCodeOk in the following cases:
The root turns out to be not moved (already grown).
The parent turns out to be moved (split).
Grow is a non-mandatory operation. We can delay it.
Locks taken in this sysxct:
Record lock on the pointer in parent page.
Page-lock of the current root (will be retired).
Definition at line 79 of file masstree_grow_impl.hpp.
#include <masstree_grow_impl.hpp>
Public Member Functions
GrowNonFirstLayerRoot (thread::Thread *context, MasstreeBorderPage *parent, uint16_t pointer_index)
virtual ErrorCode run (xct::SysxctWorkspace *sysxct_workspace) override
Execute the system transaction.
Public Attributes
thread::Thread *const context_
Thread context.
MasstreeBorderPage *const parent_
The border page of the parent layer.
const uint16_t pointer_index_
Index of the pointer in parent.
Constructor & Destructor Documentation
foedus::storage::masstree::GrowNonFirstLayerRoot::GrowNonFirstLayerRoot (thread::Thread * context, MasstreeBorderPage * parent, uint16_t pointer_index) inline
Definition at line 91 of file masstree_grow_impl.hpp.
     : xct::SysxctFunctor(),
       context_(context),
       parent_(parent),
       pointer_index_(pointer_index) {
   }
Member Function Documentation
ErrorCode foedus::storage::masstree::GrowNonFirstLayerRoot::run (xct::SysxctWorkspace * sysxct_workspace) override virtual
Execute the system transaction.
You should override this method.
Implements foedus::xct::SysxctFunctor.
Definition at line 167 of file masstree_grow_impl.cpp.
References ASSERT_ND, CHECK_ERROR_CODE, context_, foedus::storage::masstree::MasstreeBorderPage::does_point_to_layer(), foedus::storage::masstree::MasstreePage::get_foster_fence(), foedus::thread::Thread::get_global_volatile_page_resolver(), foedus::storage::masstree::MasstreePage::get_high_fence(), foedus::storage::masstree::MasstreePage::get_low_fence(), foedus::storage::masstree::MasstreeBorderPage::get_next_layer(), foedus::storage::masstree::MasstreeBorderPage::get_owner_id(), foedus::storage::masstree::MasstreePage::get_volatile_page_id(), foedus::storage::masstree::grow_case_a_common(), foedus::storage::masstree::grow_case_b_common(), foedus::storage::masstree::MasstreePage::header(), foedus::storage::masstree::MasstreePage::is_border(), foedus::xct::RwLockableXctId::is_keylocked(), foedus::storage::masstree::MasstreePage::is_layer_root(), foedus::storage::masstree::MasstreePage::is_locked(), foedus::storage::masstree::MasstreePage::is_moved(), foedus::storage::VolatilePagePointer::is_null(), foedus::storage::masstree::MasstreePage::is_retired(), foedus::kErrorCodeOk, parent_, pointer_index_, foedus::storage::PageHeader::snapshot_, foedus::storage::PageHeader::storage_id_, foedus::thread::Thread::sysxct_page_lock(), foedus::thread::Thread::sysxct_record_lock(), and foedus::storage::DualPagePointer::volatile_pointer_.
{
   ASSERT_ND(parent_->is_border());
   ASSERT_ND(!parent_->header().snapshot_);
   // Once it becomes a next-layer pointer, it never goes back to a normal record, thus this is safe.
   ASSERT_ND(parent_->does_point_to_layer(pointer_index_));
   auto* record = parent_->get_owner_id(pointer_index_);
   auto parent_page_id = parent_->get_volatile_page_id();
   CHECK_ERROR_CODE(context_->sysxct_record_lock(sysxct_workspace, parent_page_id, record));
   ASSERT_ND(parent_->get_owner_id(pointer_index_)->is_keylocked());
   // After locking the record, check the state of the pointer
   if (record->is_moved()) {
     DVLOG(0) << "Interesting. concurrent thread has split or is splitting the parent page.";
     return kErrorCodeOk;  // no hurry. root-grow can be delayed
   }
   ASSERT_ND(!record->is_deleted());
   ASSERT_ND(record->is_next_layer());
   const auto& resolver = context_->get_global_volatile_page_resolver();
   DualPagePointer* pointer = parent_->get_next_layer(pointer_index_);
   ASSERT_ND(!pointer->volatile_pointer_.is_null());
   Page* cur_root_page = resolver.resolve_offset(pointer->volatile_pointer_);
   MasstreePage* cur_root = reinterpret_cast<MasstreePage*>(cur_root_page);
   ASSERT_ND(cur_root->is_layer_root());
   CHECK_ERROR_CODE(context_->sysxct_page_lock(sysxct_workspace, cur_root_page));
   ASSERT_ND(cur_root->is_locked());
   // After locking the page, check the state of the page
   if (!cur_root->is_moved()) {
     DVLOG(0) << "Interesting. concurrent thread has already grown it.";
     return kErrorCodeOk;
   }
   // But, is_retired is impossible because we locked the parent record before following
   ASSERT_ND(!cur_root->is_retired());
   if (cur_root->get_foster_fence() == cur_root->get_low_fence()
     || cur_root->get_foster_fence() == cur_root->get_high_fence()) {
     DVLOG(1) << "Easier. Empty-range foster child for non-first layer root."
       "storage_id=" << parent_->header().storage_id_;
     grow_case_a_common(context_, pointer, cur_root);
   } else {
     DVLOG(0) << "Growing non-first layer root. storage_id=" << parent_->header().storage_id_;
     CHECK_ERROR_CODE(grow_case_b_common(context_, pointer, cur_root));
   }
   return kErrorCodeOk;
 }
Member Data Documentation
thread::Thread* const foedus::storage::masstree::GrowNonFirstLayerRoot::context_
Thread context.
Definition at line 81 of file masstree_grow_impl.hpp.
Referenced by run().
MasstreeBorderPage* const foedus::storage::masstree::GrowNonFirstLayerRoot::parent_
The border page of the parent layer.
Definition at line 85 of file masstree_grow_impl.hpp.
Referenced by run().
const uint16_t foedus::storage::masstree::GrowNonFirstLayerRoot::pointer_index_
Index of the pointer in parent.
Definition at line 89 of file masstree_grow_impl.hpp.
Referenced by run().
The documentation for this struct was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/storage/masstree/masstree_grow_impl.hpp
/home/shino/foedus_code/foedus-core/src/foedus/storage/masstree/masstree_grow_impl.cpp