libfoedus-core: foedus::storage::hash::HashInsertLogType Struct Reference
foedus::storage::hash::HashInsertLogType Struct Reference
FOEDUS Components » Storage Manager » Hashtable StorageFOEDUS Components » Log Manager » | Log Types
Log type of hash-storage's insert operation.
Detailed Description
Log type of hash-storage's insert operation.
Applying this log just flips the delete flag and installs the payload. Allocating the slot and modifying the bloom filter is already done by a system transaction.
Definition at line 209 of file hash_log_types.hpp.
#include <hash_log_types.hpp>
Public Member Functions
HashInsertLogType ()=delete
HashInsertLogType (const HashInsertLogType &other)=delete
~HashInsertLogType ()=delete
void populate (StorageId storage_id, const void *key, uint16_t key_length, uint8_t bin_bits, HashValue hash, const void *payload, uint16_t payload_count) __attribute__((always_inline))
void apply_record (thread::Thread *, StorageId, xct::RwLockableXctId *owner_id, char *data) const __attribute__((always_inline))
void assert_valid () __attribute__((always_inline))
Public Member Functions inherited from foedus::storage::hash::HashCommonLogType
HashCommonLogType ()=delete
HashCommonLogType (const HashCommonLogType &other)=delete
~HashCommonLogType ()=delete
char * get_key ()
const char * get_key () const
uint16_t get_key_length_aligned () const
char * get_payload ()
const char * get_payload () const
void populate_base (log::LogCode type, StorageId storage_id, const void *key, uint16_t key_length, uint8_t bin_bits, HashValue hash, const void *payload=nullptr, uint16_t payload_offset=0, uint16_t payload_count=0) __attribute__((always_inline))
void assert_record_and_log_keys (xct::RwLockableXctId *owner_id, const char *data) const
used only for sanity check.
void assert_type () const __attribute__((always_inline))
Public Member Functions inherited from foedus::log::RecordLogType
bool is_engine_log () const
bool is_storage_log () const
bool is_record_log () const
void apply_engine (thread::Thread *)
void apply_storage (Engine *, storage::StorageId)
void assert_valid_generic () const __attribute__((always_inline))
Verifies the log contains essential fields set.
Friends
std::ostream & operator<< (std::ostream &o, const HashInsertLogType &v)
Additional Inherited Members
Static Public Member Functions inherited from foedus::storage::hash::HashCommonLogType
static uint16_t calculate_log_length (uint16_t key_length, uint16_t payload_count) __attribute__((always_inline))
static int compare_logs (const HashCommonLogType *left, const HashCommonLogType *right) __attribute__((always_inline))
Returns -1, 0, 1 when left is less than, same, larger than right in terms of bin and xct_id.
Public Attributes inherited from foedus::storage::hash::HashCommonLogType
uint16_t key_length_
uint16_t payload_offset_
uint16_t payload_count_
uint8_t bin_bits_
this is not strictly needed here, but helps a bit.
uint8_t reserved_
HashValue hash_
Hash value of the key.
char aligned_data_ [8]
Full key and (if exists) payload data, both of which are padded to 8 bytes.
Public Attributes inherited from foedus::log::BaseLogType
LogHeader header_
Constructor & Destructor Documentation
foedus::storage::hash::HashInsertLogType::HashInsertLogType () delete
foedus::storage::hash::HashInsertLogType::HashInsertLogType (const HashInsertLogType & other) delete
foedus::storage::hash::HashInsertLogType::~HashInsertLogType () delete
Member Function Documentation
void foedus::storage::hash::HashInsertLogType::apply_record (thread::Thread * , StorageId , xct::RwLockableXctId * owner_id, char * data) const inline
Definition at line 224 of file hash_log_types.hpp.
References foedus::assorted::align8(), ASSERT_ND, and ASSUME_ALIGNED.
{
     ASSERT_ND(owner_id->xct_id_.is_deleted());  // the physical record should be in 'deleted' status
     ASSERT_ND(!owner_id->xct_id_.is_next_layer());
     ASSERT_ND(!owner_id->xct_id_.is_moved());
     // no need to set key in apply(). it's already set when the record is physically inserted
     // (or in other places if this is recovery).
     assert_record_and_log_keys(owner_id, data);
     uint16_t* lengthes = reinterpret_cast<uint16_t*>(owner_id + 1);
     // physical_record_length_ (lengthes[1]) is immutable, so this is
     // guaranteed regardless of isolation levels. let's check.
     ASSERT_ND(lengthes[1] >= assorted::align8(payload_count_) + lengthes[2]);
     lengthes[3] = payload_count_;  // set payload length
     if (payload_count_ > 0U) {
       // record's payload is also 8-byte aligned, so copy multiply of 8 bytes.
       // if the compiler is smart enough, it will do some optimization here.
       uint16_t key_length_aligned = get_key_length_aligned();
       void* data_payload = ASSUME_ALIGNED(data + key_length_aligned, 8U);
       const void* log_payload = ASSUME_ALIGNED(get_payload(), 8U);
       std::memcpy(data_payload, log_payload, assorted::align8(payload_count_));
     }
     assert_record_and_log_keys(owner_id, data);
     owner_id->xct_id_.set_notdeleted();
   }
void foedus::storage::hash::HashInsertLogType::assert_valid () inline
Definition at line 255 of file hash_log_types.hpp.
References ASSERT_ND, foedus::log::StorageLogType::assert_valid_generic(), foedus::log::LogHeader::get_type(), foedus::log::BaseLogType::header_, foedus::log::kLogCodeHashInsert, and foedus::log::LogHeader::log_length_.
{
     assert_valid_generic();
     assert_type();
     ASSERT_ND(header_.log_length_ == calculate_log_length(key_length_, payload_count_));
     ASSERT_ND(header_.get_type() == log::kLogCodeHashInsert);
   }
void foedus::storage::hash::HashInsertLogType::populate (StorageId storage_id, const void * key, uint16_t key_length, uint8_t bin_bits, HashValue hash, const void * payload, uint16_t payload_count) inline
Definition at line 212 of file hash_log_types.hpp.
References foedus::log::kLogCodeHashInsert.
Referenced by foedus::storage::hash::HashStoragePimpl::insert_record(), and foedus::storage::hash::HashStoragePimpl::upsert_record().
{
     log::LogCode type = log::kLogCodeHashInsert;
     populate_base(type, storage_id, key, key_length, bin_bits, hash, payload, 0, payload_count);
   }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const HashInsertLogType & v) friend
Definition at line 52 of file hash_log_types.cpp.
{
   o << "<HashInsertLogType>"
     << "<key_length_>" << v.key_length_ << "</key_length_>"
     << "<key_>" << assorted::Top(v.get_key(), v.key_length_) << "</key_>"
     << "<bin_bits_>" << static_cast<int>(v.bin_bits_) << "</bin_bits_>"
     << "<hash_>" << assorted::Hex(v.hash_, 16) << "</hash_>"
     << "<payload_count_>" << v.payload_count_ << "</payload_count_>"
     << "<payload_>" << assorted::Top(v.get_payload(), v.payload_count_) << "</payload_>"
     << "</HashInsertLogType>";
   return o;
 }
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/storage/hash/hash_log_types.hpp