libfoedus-core: foedus::assorted::SpinlockStat Struct Reference
foedus::assorted::SpinlockStat Struct Reference
Helper for SPINLOCK_WHILE.
Detailed Description
Helper for SPINLOCK_WHILE.
Definition at line 233 of file assorted_func.hpp.
#include <assorted_func.hpp>
Public Member Functions
SpinlockStat ()
void yield_backoff ()
Public Attributes
uint32_t spins_
UniformRandom rnd_
Constructor & Destructor Documentation
foedus::assorted::SpinlockStat::SpinlockStat () inline
Definition at line 234 of file assorted_func.hpp.
 : spins_(0) {}
Member Function Documentation
void foedus::assorted::SpinlockStat::yield_backoff ()
Definition at line 206 of file assorted_func.cpp.
References foedus::assorted::UniformRandom::next_uint32(), rnd_, foedus::assorted::UniformRandom::set_current_seed(), foedus::assorted::spinlock_yield(), spins_, and foedus::debugging::wait_rdtsc_cycles().
{
   if (spins_ == 0) {
     // do the real initialization only when we couldn't get a lock.
     // hopefully 99% cases we don't hit here.
     std::hash<std::thread::id> h;
     rnd_.set_current_seed(h(std::this_thread::get_id()));
     rnd_.next_uint32();
   }
   ++spins_;
   // valgrind is single-threaded. so, we must yield as much as possible to let it run reasonably.
   if (RUNNING_ON_VALGRIND) {
     spinlock_yield();
     return;
   }
   // exponential backoff. also do yielding occasionally.
   const uint64_t kMinSleepCycles = 1ULL << 7;  // one atomic CAS
   const uint64_t kMaxSleepCycles = 1ULL << 12;  // even this might be too long..
   uint64_t wait_cycles_max = spins_ < 5U ? kMinSleepCycles << spins_ : kMaxSleepCycles;
   uint32_t wait_cycles = kMinSleepCycles + rnd_.next_uint32() % (wait_cycles_max - kMinSleepCycles);
   debugging::wait_rdtsc_cycles(wait_cycles);
   if (spins_ % 256U == 0) {
     spinlock_yield();
   }
 }
Member Data Documentation
UniformRandom foedus::assorted::SpinlockStat::rnd_
Definition at line 238 of file assorted_func.hpp.
Referenced by yield_backoff().
uint32_t foedus::assorted::SpinlockStat::spins_
Definition at line 237 of file assorted_func.hpp.
Referenced by yield_backoff().
The documentation for this struct was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/assorted/assorted_func.hpp
/home/shino/foedus_code/foedus-core/src/foedus/assorted/assorted_func.cpp