libfoedus-core: foedus::memory::ScopedNumaPreferred Struct Reference
foedus::memory::ScopedNumaPreferred Struct Reference
FOEDUS Components » Memory ManagerFOEDUS Components » Memory Manager » | Memory Hierarchy
Automatically sets and resets numa_set_preferred().
Detailed Description
Automatically sets and resets numa_set_preferred().
Use this in a place you want to direct all memory allocation to a specific NUMA node.
Definition at line 58 of file memory_id.hpp.
#include <memory_id.hpp>
Public Member Functions
ScopedNumaPreferred (int numa_node, bool retain_old=false)
~ScopedNumaPreferred ()
Public Attributes
int old_value_
bool numa_enabled_
Constructor & Destructor Documentation
foedus::memory::ScopedNumaPreferred::ScopedNumaPreferred (int numa_node, bool retain_old = false) inline
Definition at line 59 of file memory_id.hpp.
References foedus::assorted::mod_numa_node(), numa_available(), numa_enabled_, numa_preferred(), numa_set_preferred(), and old_value_.
{
     // if the machine is not a NUMA machine (1-socket), then avoid calling libnuma functions.
     numa_enabled_ = (::numa_available() >= 0);
     if (!numa_enabled_) {
       numa_node = 0;
       return;
     }
     if (retain_old) {
       old_value_ = ::numa_preferred();
     } else {
       old_value_ = -1;
     }
     // in order to run even on a non-numa machine or a machine with fewer sockets,
     // we allow specifying arbitrary numa_node. we just take rem.
     numa_node = assorted::mod_numa_node(numa_node);
     ::numa_set_preferred(numa_node);
   }
foedus::memory::ScopedNumaPreferred::~ScopedNumaPreferred () inline
Definition at line 76 of file memory_id.hpp.
References numa_enabled_, numa_set_preferred(), and old_value_.
{
     if (numa_enabled_) {
       ::numa_set_preferred(old_value_);
     }
   }
Member Data Documentation
bool foedus::memory::ScopedNumaPreferred::numa_enabled_
Definition at line 82 of file memory_id.hpp.
Referenced by ScopedNumaPreferred(), and ~ScopedNumaPreferred().
int foedus::memory::ScopedNumaPreferred::old_value_
Definition at line 81 of file memory_id.hpp.
Referenced by ScopedNumaPreferred(), and ~ScopedNumaPreferred().
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/memory/memory_id.hpp