libfoedus-core: foedus::storage::masstree::MasstreeMetadataSerializer Struct Reference
foedus::storage::masstree::MasstreeMetadataSerializer Struct Reference final
Detailed Description
Definition at line 140 of file masstree_metadata.hpp.
#include <masstree_metadata.hpp>
Public Member Functions
MasstreeMetadataSerializer ()
MasstreeMetadataSerializer (MasstreeMetadata *data)
ErrorStack load (tinyxml2::XMLElement *element) override
Reads the content of this object from the given XML element.
ErrorStack save (tinyxml2::XMLElement *element) const override
Writes the content of this object to the given XML element.
const char * get_tag_name () const override
Returns an XML tag name for this object as a root element.
void assign (const foedus::externalize::Externalizable *other) override
Polymorphic assign operator.
Public Member Functions inherited from foedus::storage::MetadataSerializer
MetadataSerializer ()
MetadataSerializer (Metadata *data)
virtual ~MetadataSerializer ()
ErrorStack load_base (tinyxml2::XMLElement *element)
common routine for the implementation of load()
ErrorStack save_base (tinyxml2::XMLElement *element) const
common routine for the implementation of save()
Public Member Functions inherited from foedus::externalize::Externalizable
ErrorStack load_from_string (const std::string &xml)
Load the content of this object from the given XML string.
void save_to_stream (std::ostream *ptr) const
Invokes save() and directs the resulting XML text to the given stream.
ErrorStack load_from_file (const fs::Path &path)
Load the content of this object from the specified XML file.
ErrorStack save_to_file (const fs::Path &path) const
Atomically and durably writes out this object to the specified XML file.
Public Attributes
MasstreeMetadata * data_casted_
Public Attributes inherited from foedus::storage::MetadataSerializer
Metadata * data_
Friends
std::ostream & operator<< (std::ostream &o, const MasstreeMetadataSerializer &v)
Additional Inherited Members
Static Public Member Functions inherited from foedus::storage::MetadataSerializer
static ErrorStack load_all_storages_from_xml (storage::StorageId largest_storage_id, tinyxml2::XMLElement *element, StorageControlBlock *blocks)
static ErrorStack save_all_storages_to_xml (storage::StorageId largest_storage_id, tinyxml2::XMLElement *element, StorageControlBlock *blocks)
Static Public Member Functions inherited from foedus::externalize::Externalizable
static ErrorStack insert_comment (tinyxml2::XMLElement *element, const std::string &comment)
static ErrorStack append_comment (tinyxml2::XMLElement *parent, const std::string &comment)
static ErrorStack create_element (tinyxml2::XMLElement *parent, const std::string &name, tinyxml2::XMLElement **out)
template<typename T >
static ErrorStack add_element (tinyxml2::XMLElement *parent, const std::string &tag, const std::string &comment, T value)
Only declaration in header.
template<uint MAXLEN, typename CHAR >
static ErrorStack add_element (tinyxml2::XMLElement *parent, const std::string &tag, const std::string &comment, const assorted::FixedString< MAXLEN, CHAR > &value)
template<typename T >
static ErrorStack add_element (tinyxml2::XMLElement *parent, const std::string &tag, const std::string &comment, const std::vector< T > &value)
vector version
template<typename ENUM >
static ErrorStack add_enum_element (tinyxml2::XMLElement *parent, const std::string &tag, const std::string &comment, ENUM value)
enum version
static ErrorStack add_child_element (tinyxml2::XMLElement *parent, const std::string &tag, const std::string &comment, const Externalizable &child)
child Externalizable version
template<typename T >
static ErrorStack get_element (tinyxml2::XMLElement *parent, const std::string &tag, T *out, bool optional=false, T value=0)
Only declaration in header.
static ErrorStack get_element (tinyxml2::XMLElement *parent, const std::string &tag, std::string *out, bool optional=false, const char *value="")
string type is bit special.
template<uint MAXLEN, typename CHAR >
static ErrorStack get_element (tinyxml2::XMLElement *parent, const std::string &tag, assorted::FixedString< MAXLEN, CHAR > *out, bool optional=false, const assorted::FixedString< MAXLEN, CHAR > &value=assorted::FixedString< MAXLEN, CHAR >())
template<typename ENUM >
static ErrorStack get_enum_element (tinyxml2::XMLElement *parent, const std::string &tag, ENUM *out, bool optional=false, ENUM default_value=static_cast< ENUM >(0))
enum version
template<typename T >
static ErrorStack get_element (tinyxml2::XMLElement *parent, const std::string &tag, std::vector< T > *out, bool optional=false)
vector version.
static ErrorStack get_child_element (tinyxml2::XMLElement *parent, const std::string &tag, Externalizable *child, bool optional=false)
child Externalizable version
Constructor & Destructor Documentation
foedus::storage::masstree::MasstreeMetadataSerializer::MasstreeMetadataSerializer () inline
Definition at line 141 of file masstree_metadata.hpp.
 : MetadataSerializer() {}
foedus::storage::masstree::MasstreeMetadataSerializer::MasstreeMetadataSerializer (MasstreeMetadata * data) inline explicit
Definition at line 142 of file masstree_metadata.hpp.
     : MetadataSerializer(data), data_casted_(data) {}
Member Function Documentation
void foedus::storage::masstree::MasstreeMetadataSerializer::assign (const foedus::externalize::Externalizable * other) inline override virtual
Polymorphic assign operator.
This should invoke operator= of the derived class.
Parameters
[in] other assigned value. It must be dynamic-castable to the assignee class.
Implements foedus::externalize::Externalizable.
Definition at line 144 of file masstree_metadata.hpp.
const char* foedus::storage::masstree::MasstreeMetadataSerializer::get_tag_name () const inline override virtual
Returns an XML tag name for this object as a root element.
We might want to give a different name for same externalizable objects, so this is used only when it is the root element of xml.
Implements foedus::externalize::Externalizable.
Definition at line 144 of file masstree_metadata.hpp.
ErrorStack foedus::storage::masstree::MasstreeMetadataSerializer::load (tinyxml2::XMLElement * element) override virtual
Reads the content of this object from the given XML element.
Parameters
[in] element the XML element that represents this object
Expect errors due to missing-elements, out-of-range values, etc.
Implements foedus::externalize::Externalizable.
Definition at line 39 of file masstree_metadata.cpp.
References foedus::storage::masstree::MasstreeMetadata::border_early_split_threshold_, CHECK_ERROR, data_casted_, foedus::externalize::Externalizable::get_element(), foedus::kRetOk, foedus::storage::MetadataSerializer::load_base(), foedus::storage::masstree::MasstreeMetadata::min_layer_hint_, foedus::storage::masstree::MasstreeMetadata::snapshot_drop_volatile_pages_btree_levels_, and foedus::storage::masstree::MasstreeMetadata::snapshot_drop_volatile_pages_layer_threshold_.
Referenced by foedus::storage::load_from_xml_masstree().
{
   CHECK_ERROR(load_base(element));
   CHECK_ERROR(get_element(
     element, "border_early_split_threshold_", &data_casted_->border_early_split_threshold_))
   CHECK_ERROR(get_element(
     element,
     "snapshot_drop_volatile_pages_layer_threshold_",
     &data_casted_->snapshot_drop_volatile_pages_layer_threshold_))
   CHECK_ERROR(get_element(
     element,
     "snapshot_drop_volatile_pages_btree_levels_",
     &data_casted_->snapshot_drop_volatile_pages_btree_levels_))
   CHECK_ERROR(get_element(element, "min_layer_hint_", &data_casted_->min_layer_hint_))
   return kRetOk;
 }
ErrorStack foedus::storage::masstree::MasstreeMetadataSerializer::save (tinyxml2::XMLElement * element) const override virtual
Writes the content of this object to the given XML element.
Parameters
[in] element the XML element that represents this object
Expect only out-of-memory error. We receive the XML element this object will represent, so this method does not determine the XML element name of itself. The parent object determines children's tag names because one parent object might have multiple child objects of the same type with different XML element name.
Implements foedus::externalize::Externalizable.
Definition at line 55 of file masstree_metadata.cpp.
References foedus::externalize::Externalizable::add_element(), foedus::storage::masstree::MasstreeMetadata::border_early_split_threshold_, CHECK_ERROR, data_casted_, foedus::kRetOk, foedus::storage::masstree::MasstreeMetadata::min_layer_hint_, foedus::storage::MetadataSerializer::save_base(), foedus::storage::masstree::MasstreeMetadata::snapshot_drop_volatile_pages_btree_levels_, and foedus::storage::masstree::MasstreeMetadata::snapshot_drop_volatile_pages_layer_threshold_.
{
   CHECK_ERROR(save_base(element));
   CHECK_ERROR(add_element(
     element, "border_early_split_threshold_", "", data_casted_->border_early_split_threshold_));
   CHECK_ERROR(add_element(
     element,
     "snapshot_drop_volatile_pages_layer_threshold_",
     "",
     data_casted_->snapshot_drop_volatile_pages_layer_threshold_));
   CHECK_ERROR(add_element(
     element,
     "snapshot_drop_volatile_pages_btree_levels_",
     "",
     data_casted_->snapshot_drop_volatile_pages_btree_levels_));
   CHECK_ERROR(add_element(element, "min_layer_hint_", "", data_casted_->min_layer_hint_));
   return kRetOk;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const MasstreeMetadataSerializer & v) friend
Definition at line 144 of file masstree_metadata.hpp.
Member Data Documentation
MasstreeMetadata* foedus::storage::masstree::MasstreeMetadataSerializer::data_casted_
Definition at line 144 of file masstree_metadata.hpp.
Referenced by load(), and save().
The documentation for this struct was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/storage/masstree/masstree_metadata.hpp
/home/shino/foedus_code/foedus-core/src/foedus/storage/masstree/masstree_metadata.cpp