libfoedus-core: foedus::cache::CacheRefCount Struct Reference
foedus::cache::CacheRefCount Struct Reference final
A loosely maintained reference count for CLOCK algorithm.
Detailed Description
A loosely maintained reference count for CLOCK algorithm.
Definition at line 163 of file cache_hashtable.hpp.
#include <cache_hashtable.hpp>
Public Member Functions
void increment () __attribute__((always_inline))
bool decrement (uint16_t subtract) __attribute__((always_inline))
returns whether the counter is still non-zero
Public Attributes
uint16_t count_
Member Function Documentation
bool foedus::cache::CacheRefCount::decrement (uint16_t subtract) inline
returns whether the counter is still non-zero
Definition at line 172 of file cache_hashtable.hpp.
Referenced by foedus::cache::CacheHashtable::evict_main_loop(), and foedus::cache::CacheHashtable::evict_overflow_loop().
{
     if (count_ >= subtract) {
       count_ -= subtract;
     } else {
       count_ = 0;
     }
     return (count_ > 0);
   }
void foedus::cache::CacheRefCount::increment () inline
Definition at line 166 of file cache_hashtable.hpp.
References count_.
Referenced by foedus::cache::CacheHashtable::find(), and foedus::cache::CacheHashtable::find_batch().
{
     if (count_ < 0xFFFFU) {
       ++count_;
     }
   }
Member Data Documentation
uint16_t foedus::cache::CacheRefCount::count_
Definition at line 164 of file cache_hashtable.hpp.
Referenced by foedus::cache::CacheHashtable::CacheHashtable(), increment(), and foedus::cache::CacheHashtable::install().
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/cache/cache_hashtable.hpp