libfoedus-core: foedus::xct::LockableXctId Struct Reference
foedus::xct::LockableXctId Struct Reference
FOEDUS Components » Transaction Manager
Transaction ID, a 128-bit data to manage record versions and provide locking mechanism.
Detailed Description
Transaction ID, a 128-bit data to manage record versions and provide locking mechanism.
This object contains a quite more information compared to SILO [TU13]'s TID. We spend more bits on ordinals and epochs for larger environments, and also employ MCS-locking to be more scalable. Thus, now it's 128-bits. It's not a negligible size, but still compact. Also, 16-bytes sometimes reduce false cacheline sharing (well, then you might ask making it 64 bytes... but that's too much).
McsWwLock and XctId
McsWwLock provides the locking mechanism, namely MCS locking. XctId provides the record version information protected by the lock.
POD
This is a POD struct. Default destructor/copy-constructor/assignment operator work fine.
Definition at line 1107 of file xct_id.hpp.
#include <xct_id.hpp>
Public Member Functions
McsWwLock * get_key_lock () __attribute__((always_inline))
bool is_keylocked () const __attribute__((always_inline))
bool is_deleted () const __attribute__((always_inline))
bool is_moved () const __attribute__((always_inline))
bool is_next_layer () const __attribute__((always_inline))
bool needs_track_moved () const __attribute__((always_inline))
bool is_being_written () const __attribute__((always_inline))
void reset () __attribute__((always_inline))
used only while page initialization
Public Attributes
McsWwLock lock_
the first 64bit: Locking part of TID
XctId xct_id_
the second 64bit: Persistent status part of TID.
Friends
std::ostream & operator<< (std::ostream &o, const LockableXctId &v)
Member Function Documentation
McsWwLock* foedus::xct::LockableXctId::get_key_lock () inline
Definition at line 1113 of file xct_id.hpp.
References lock_.
 { return &lock_; }
bool foedus::xct::LockableXctId::is_being_written () const inline
Definition at line 1119 of file xct_id.hpp.
References foedus::xct::XctId::is_being_written().
 { return xct_id_.is_being_written(); }
bool foedus::xct::LockableXctId::is_deleted () const inline
Definition at line 1115 of file xct_id.hpp.
References foedus::xct::XctId::is_deleted().
 { return xct_id_.is_deleted(); }
bool foedus::xct::LockableXctId::is_keylocked () const inline
Definition at line 1114 of file xct_id.hpp.
References foedus::xct::McsWwLock::is_locked().
 { return lock_.is_locked(); }
bool foedus::xct::LockableXctId::is_moved () const inline
Definition at line 1116 of file xct_id.hpp.
References foedus::xct::XctId::is_moved().
 { return xct_id_.is_moved(); }
bool foedus::xct::LockableXctId::is_next_layer () const inline
Definition at line 1117 of file xct_id.hpp.
References foedus::xct::XctId::is_next_layer().
 { return xct_id_.is_next_layer(); }
bool foedus::xct::LockableXctId::needs_track_moved () const inline
Definition at line 1118 of file xct_id.hpp.
References foedus::xct::XctId::needs_track_moved().
 { return xct_id_.needs_track_moved(); }
void foedus::xct::LockableXctId::reset () inline
used only while page initialization
Definition at line 1122 of file xct_id.hpp.
References foedus::xct::XctId::data_, and foedus::xct::McsWwLock::reset().
{
     lock_.reset();
     xct_id_.data_ = 0;
   }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const LockableXctId & v) friend
Definition at line 190 of file xct_id.cpp.
{
   o << "<LockableXctId>" << v.xct_id_ << v.lock_ << "</LockableXctId>";
   return o;
 }
Member Data Documentation
McsWwLock foedus::xct::LockableXctId::lock_
the first 64bit: Locking part of TID
Definition at line 1109 of file xct_id.hpp.
Referenced by get_key_lock(), and foedus::xct::operator<<().
XctId foedus::xct::LockableXctId::xct_id_
the second 64bit: Persistent status part of TID.
Definition at line 1111 of file xct_id.hpp.
Referenced by foedus::xct::operator<<().
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/xct/xct_id.hpp