libfoedus-core: foedus::storage::CreateLogType Struct Reference
foedus::storage::CreateLogType Struct Reference final
FOEDUS Components » Storage ManagerFOEDUS Components » Log Manager » | Log Types
Base type for CREATE STORAGE operation.
Detailed Description
Base type for CREATE STORAGE operation.
This is not an actual log type that is used. Individual storages have their own create-log type, which is compatible, not derived, to this. Just like Metadata and individual metadata types, this is just to provide a common view.
Definition at line 63 of file storage_log_types.hpp.
#include <storage_log_types.hpp>
Public Member Functions
CreateLogType ()=delete
CreateLogType (const CreateLogType &other)=delete
~CreateLogType ()=delete
void apply_storage (Engine *engine, StorageId storage_id)
void assert_valid ()
Public Member Functions inherited from foedus::log::StorageLogType
bool is_engine_log () const
bool is_storage_log () const
bool is_record_log () const
void apply_engine (thread::Thread *)
void apply_record (thread::Thread *, storage::StorageId, xct::RwLockableXctId *, char *)
void assert_valid_generic () __attribute__((always_inline))
Verifies the log contains essential fields set.
Public Attributes
Metadata metadata_
Public Attributes inherited from foedus::log::BaseLogType
LogHeader header_
Friends
std::ostream & operator<< (std::ostream &o, const CreateLogType &v)
Constructor & Destructor Documentation
foedus::storage::CreateLogType::CreateLogType () delete
foedus::storage::CreateLogType::CreateLogType (const CreateLogType & other) delete
foedus::storage::CreateLogType::~CreateLogType () delete
Member Function Documentation
void foedus::storage::CreateLogType::apply_storage (Engine * engine, StorageId storage_id)
Definition at line 68 of file storage_log_types.cpp.
References ASSERT_ND, foedus::storage::StorageManager::create_storage_apply(), foedus::Engine::get_storage_manager(), foedus::storage::Metadata::id_, and metadata_.
{
   ASSERT_ND(metadata_.id_ == storage_id);
   LOG(INFO) << "Applying CREATE STORAGE log: " << *this;
   engine->get_storage_manager()->create_storage_apply(metadata_);
   LOG(INFO) << "Applied CREATE STORAGE log: " << *this;
 }
void foedus::storage::CreateLogType::assert_valid ()
Definition at line 63 of file storage_log_types.cpp.
References ASSERT_ND, foedus::log::StorageLogType::assert_valid_generic(), foedus::log::BaseLogType::header_, foedus::storage::Metadata::id_, metadata_, and foedus::log::LogHeader::storage_id_.
{
   assert_valid_generic();
   ASSERT_ND(header_.storage_id_ == metadata_.id_);
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const CreateLogType & v) friend
Definition at line 75 of file storage_log_types.cpp.
{
   switch (v.metadata_.type_) {
     case kArrayStorage:
       o << reinterpret_cast<const array::ArrayCreateLogType&>(v);
       break;
     case kHashStorage:
       o << reinterpret_cast<const hash::HashCreateLogType&>(v);
       break;
     case kMasstreeStorage:
       o << reinterpret_cast<const masstree::MasstreeCreateLogType&>(v);
       break;
     case kSequentialStorage:
       o << reinterpret_cast<const sequential::SequentialCreateLogType&>(v);
       break;
     default:
       o << "Unexpected metadata type:" << v.metadata_.type_;
   }
   return o;
 }
Member Data Documentation
Metadata foedus::storage::CreateLogType::metadata_
Definition at line 65 of file storage_log_types.hpp.
Referenced by apply_storage(), assert_valid(), and foedus::storage::operator<<().
The documentation for this struct was generated from the following files:
/home/shino/foedus_code/foedus-core/include/foedus/storage/storage_log_types.hpp
/home/shino/foedus_code/foedus-core/src/foedus/storage/storage_log_types.cpp