libfoedus-core: foedus::storage::array::ArrayOverwriteLogType Struct Reference
foedus::storage::array::ArrayOverwriteLogType Struct Reference
FOEDUS Components » Storage Manager » Array StorageFOEDUS Components » Log Manager » | Log Types
Log type of array-storage's overwrite operation.
Detailed Description
Log type of array-storage's overwrite operation.
This is a modification operation in array. It simply invokes memcpy to the payload.
Definition at line 109 of file array_log_types.hpp.
#include <array_log_types.hpp>
Public Member Functions
ArrayOverwriteLogType ()=delete
ArrayOverwriteLogType (const ArrayOverwriteLogType &other)=delete
~ArrayOverwriteLogType ()=delete
void populate (StorageId storage_id, ArrayOffset offset, const void *payload, uint16_t payload_offset, uint16_t payload_count) __attribute__((always_inline))
template<typename T >
void populate_primitive (StorageId storage_id, ArrayOffset offset, T payload, uint16_t payload_offset) __attribute__((always_inline))
For primitive types.
void apply_record (thread::Thread *context, StorageId storage_id, xct::RwLockableXctId *owner_id, char *payload) const __attribute__((always_inline))
void assert_valid () const __attribute__((always_inline))
Public Member Functions inherited from foedus::storage::array::ArrayCommonUpdateLogType
ArrayCommonUpdateLogType ()=delete
ArrayCommonUpdateLogType (const ArrayCommonUpdateLogType &other)=delete
~ArrayCommonUpdateLogType ()=delete
Public Member Functions inherited from foedus::log::RecordLogType
bool is_engine_log () const
bool is_storage_log () const
bool is_record_log () const
void apply_engine (thread::Thread *)
void apply_storage (Engine *, storage::StorageId)
void assert_valid_generic () const __attribute__((always_inline))
Verifies the log contains essential fields set.
Static Public Member Functions
static uint16_t calculate_log_length (uint16_t payload_count) __attribute__((always_inline))
Static Public Member Functions inherited from foedus::storage::array::ArrayCommonUpdateLogType
static int compare_logs (const ArrayCommonUpdateLogType *left, const ArrayCommonUpdateLogType *right) __attribute__((always_inline))
Returns -1, 0, 1 when left is less than, same, larger than right in terms of key and xct_id.
Public Attributes
uint16_t payload_offset_
uint16_t payload_count_
char payload_ [4]
Public Attributes inherited from foedus::storage::array::ArrayCommonUpdateLogType
ArrayOffset offset_
Public Attributes inherited from foedus::log::BaseLogType
LogHeader header_
Friends
std::ostream & operator<< (std::ostream &o, const ArrayOverwriteLogType &v)
Constructor & Destructor Documentation
foedus::storage::array::ArrayOverwriteLogType::ArrayOverwriteLogType () delete
foedus::storage::array::ArrayOverwriteLogType::ArrayOverwriteLogType (const ArrayOverwriteLogType & other) delete
foedus::storage::array::ArrayOverwriteLogType::~ArrayOverwriteLogType () delete
Member Function Documentation
void foedus::storage::array::ArrayOverwriteLogType::apply_record (thread::Thread * context, StorageId storage_id, xct::RwLockableXctId * owner_id, char * payload) const inline
Definition at line 261 of file array_log_types.hpp.
References ASSERT_ND, and foedus::storage::array::kDataSize.
{
   ASSERT_ND(payload_count_ < kDataSize);
   std::memcpy(payload + payload_offset_, payload_, payload_count_);
 }
void foedus::storage::array::ArrayOverwriteLogType::assert_valid () const inline
Definition at line 270 of file array_log_types.hpp.
References ASSERT_ND, foedus::log::StorageLogType::assert_valid_generic(), foedus::log::LogHeader::get_type(), foedus::log::BaseLogType::header_, foedus::log::kLogCodeArrayOverwrite, and foedus::log::LogHeader::log_length_.
{
   assert_valid_generic();
   ASSERT_ND(header_.log_length_ == calculate_log_length(payload_count_));
   ASSERT_ND(header_.get_type() == log::kLogCodeArrayOverwrite);
 }
static uint16_t foedus::storage::array::ArrayOverwriteLogType::calculate_log_length (uint16_t payload_count) inline static
Definition at line 115 of file array_log_types.hpp.
References foedus::assorted::align8().
Referenced by foedus::storage::array::ArrayStoragePimpl::increment_record(), foedus::storage::array::ArrayStoragePimpl::overwrite_record(), and foedus::storage::array::ArrayStoragePimpl::overwrite_record_primitive().
{
     // we pad to 8 bytes so that we always have a room for FillerLogType to align.
     return assorted::align8(28 + payload_count);
   }
void foedus::storage::array::ArrayOverwriteLogType::populate (StorageId storage_id, ArrayOffset offset, const void * payload, uint16_t payload_offset, uint16_t payload_count) inline
Definition at line 230 of file array_log_types.hpp.
References foedus::log::BaseLogType::header_, foedus::log::kLogCodeArrayOverwrite, foedus::log::LogHeader::log_length_, foedus::log::LogHeader::log_type_code_, and foedus::log::LogHeader::storage_id_.
Referenced by foedus::storage::array::ArrayStoragePimpl::overwrite_record().
{
   header_.log_type_code_ = log::kLogCodeArrayOverwrite;
   header_.log_length_ = calculate_log_length(payload_count);
   header_.storage_id_ = storage_id;
   offset_ = offset;
   payload_offset_ = payload_offset;
   payload_count_ = payload_count;
   std::memcpy(payload_, payload, payload_count);
 }
template<typename T > void foedus::storage::array::ArrayOverwriteLogType::populate_primitive (StorageId storage_id, ArrayOffset offset, T payload, uint16_t payload_offset) inline
For primitive types.
A bit more efficient.
Definition at line 246 of file array_log_types.hpp.
References foedus::log::BaseLogType::header_, foedus::log::kLogCodeArrayOverwrite, foedus::log::LogHeader::log_length_, foedus::log::LogHeader::log_type_code_, and foedus::log::LogHeader::storage_id_.
Referenced by foedus::storage::array::ArrayStoragePimpl::increment_record(), and foedus::storage::array::ArrayStoragePimpl::overwrite_record_primitive().
{
   header_.log_type_code_ = log::kLogCodeArrayOverwrite;
   header_.log_length_ = calculate_log_length(sizeof(T));
   header_.storage_id_ = storage_id;
   offset_ = offset;
   payload_offset_ = payload_offset;
   payload_count_ = sizeof(T);
   T* address = reinterpret_cast<T*>(payload_);
   *address = payload;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const ArrayOverwriteLogType & v) friend
Definition at line 53 of file array_log_types.cpp.
{
   o << "<ArrayOverwriteLog>"
     << "<offset_>" << v.offset_ << "</offset_>"
     << "<payload_offset_>" << v.payload_offset_ << "</payload_offset_>"
     << "<payload_count_>" << v.payload_count_ << "</payload_count_>";
   // show first few bytes
   o << "<data_>";
   for (uint16_t i = 0; i < std::min<uint16_t>(8, v.payload_count_); ++i) {
     o << i << ":" << static_cast<int>(v.payload_[i]) << " ";
   }
   o << "...</data_>";
   o << "</ArrayOverwriteLog>";
   return o;
 }
Member Data Documentation
char foedus::storage::array::ArrayOverwriteLogType::payload_[4]
Definition at line 113 of file array_log_types.hpp.
Referenced by foedus::storage::array::operator<<().
uint16_t foedus::storage::array::ArrayOverwriteLogType::payload_count_
Definition at line 112 of file array_log_types.hpp.
Referenced by foedus::storage::array::compact_logs(), and foedus::storage::array::operator<<().
uint16_t foedus::storage::array::ArrayOverwriteLogType::payload_offset_
Definition at line 111 of file array_log_types.hpp.
Referenced by foedus::storage::array::compact_logs(), and foedus::storage::array::operator<<().
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/storage/array/array_log_types.hpp