libfoedus-core: foedus::soc::MasterEngineStatus Struct Reference
foedus::soc::MasterEngineStatus Struct Reference final
FOEDUS Components » SOC and IPC
Current status of master engine.
Detailed Description
Current status of master engine.
This object is placed in shared memory, so this must not have a heap-allocated member.
Definition at line 60 of file shared_memory_repo.hpp.
#include <shared_memory_repo.hpp>
Public Types
enum StatusCode {
kInitial = 0, kSharedMemoryAllocated, kSharedMemoryReservedReclamation, kRunning,
kWaitingForChildTerminate, kTerminated, kFatalError
}
These statuses represent each step described in SocManager comment.
Public Member Functions
MasterEngineStatus ()=delete
~MasterEngineStatus ()=delete
MasterEngineStatus (const MasterEngineStatus &other)=delete
MasterEngineStatus & operator= (const MasterEngineStatus &other)=delete
void change_status_atomic (StatusCode new_status)
Update the value of status_code_ with fence.
StatusCode read_status_atomic () const
Read status_code_ with fence.
void change_init_atomic (ModuleType value)
void change_uninit_atomic (ModuleType value)
Public Attributes
StatusCode status_code_
ModuleType initialized_modules_
The module that has been most recently initialized in master.
ModuleType uninitialized_modules_
The module that has been most recently closed in master.
Member Enumeration Documentation
enum foedus::soc::MasterEngineStatus::StatusCode
These statuses represent each step described in SocManager comment.
The status always increases one-by-one or jumps to kFatalError.
Enumerator
kInitial
Master engine has just started.
kSharedMemoryAllocated
Master engine successfully allocated shared memory and waiting for child's attach.
kSharedMemoryReservedReclamation
Master engine successfully confirmed child's attach and reserved the reclamation of the shared memories.
No more attach to the memories is possible after this. Child SOCs resume their initialization after observing this status.
kRunning
Done all initialization and running transactions.
kWaitingForChildTerminate
The master is waiting for child engines to terminate.
As soon as child observes this, they will start termination in normal steps.
kTerminated
The master engine has normally terminated.
This is a final status.
kFatalError
Whenever child observes this, they will call _exit() asap.
This is a final status.
Definition at line 65 of file shared_memory_repo.hpp.
                   {
     kInitial = 0,
     kSharedMemoryAllocated,
     kSharedMemoryReservedReclamation,
     kRunning,
     kWaitingForChildTerminate,
     kTerminated,
     kFatalError,
   };
Constructor & Destructor Documentation
foedus::soc::MasterEngineStatus::MasterEngineStatus () delete
foedus::soc::MasterEngineStatus::~MasterEngineStatus () delete
foedus::soc::MasterEngineStatus::MasterEngineStatus (const MasterEngineStatus & other) delete
Member Function Documentation
void foedus::soc::MasterEngineStatus::change_init_atomic (ModuleType value) inline
Definition at line 115 of file shared_memory_repo.hpp.
References ASSERT_ND, initialized_modules_, and foedus::assorted::memory_fence_acq_rel().
Referenced by foedus::EnginePimpl::on_module_initialized().
{
     ASSERT_ND(static_cast<int>(initialized_modules_) == static_cast<int>(value) - 1);
     assorted::memory_fence_acq_rel();
     initialized_modules_ = value;
     assorted::memory_fence_acq_rel();
   }
void foedus::soc::MasterEngineStatus::change_status_atomic (StatusCode new_status) inline
Update the value of status_code_ with fence.
Definition at line 102 of file shared_memory_repo.hpp.
References ASSERT_ND, kFatalError, kWaitingForChildTerminate, foedus::assorted::memory_fence_acq_rel(), and status_code_.
Referenced by foedus::soc::SharedMemoryRepo::change_master_status(), and foedus::soc::SocManagerPimpl::report_engine_fatal_error().
{
     ASSERT_ND(new_status == kFatalError || new_status == kWaitingForChildTerminate ||
       static_cast<int>(new_status) == static_cast<int>(status_code_) + 1);
     assorted::memory_fence_acq_rel();
     status_code_ = new_status;
     assorted::memory_fence_acq_rel();
   }
void foedus::soc::MasterEngineStatus::change_uninit_atomic (ModuleType value) inline
Definition at line 121 of file shared_memory_repo.hpp.
References ASSERT_ND, foedus::assorted::memory_fence_acq_rel(), and uninitialized_modules_.
Referenced by foedus::EnginePimpl::on_module_uninitialized().
{
     ASSERT_ND(static_cast<int>(uninitialized_modules_) == static_cast<int>(value) + 1);
     assorted::memory_fence_acq_rel();
     uninitialized_modules_ = value;
     assorted::memory_fence_acq_rel();
   }
MasterEngineStatus& foedus::soc::MasterEngineStatus::operator= (const MasterEngineStatus & other) delete
StatusCode foedus::soc::MasterEngineStatus::read_status_atomic () const inline
Read status_code_ with fence.
Definition at line 110 of file shared_memory_repo.hpp.
References foedus::assorted::memory_fence_acq_rel(), and status_code_.
Referenced by foedus::soc::SharedMemoryRepo::get_master_status().
{
     assorted::memory_fence_acq_rel();
     return status_code_;
   }
Member Data Documentation
ModuleType foedus::soc::MasterEngineStatus::initialized_modules_
The module that has been most recently initialized in master.
Used to synchronize init.
Definition at line 130 of file shared_memory_repo.hpp.
Referenced by change_init_atomic(), foedus::soc::SocManagerPimpl::initialize_master(), and foedus::soc::SocManagerPimpl::wait_for_master_module().
StatusCode foedus::soc::MasterEngineStatus::status_code_
Definition at line 128 of file shared_memory_repo.hpp.
Referenced by foedus::soc::SharedMemoryRepo::allocate_shared_memories(), change_status_atomic(), foedus::soc::SocManagerPimpl::initialize_master(), read_status_atomic(), and foedus::soc::SocManagerPimpl::wait_for_master_module().
ModuleType foedus::soc::MasterEngineStatus::uninitialized_modules_
The module that has been most recently closed in master.
Used to synchronize uninit.
Definition at line 132 of file shared_memory_repo.hpp.
Referenced by change_uninit_atomic(), foedus::soc::SocManagerPimpl::initialize_master(), and foedus::soc::SocManagerPimpl::wait_for_master_module().
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/soc/shared_memory_repo.hpp