libfoedus-core: foedus::storage::array::ArrayRange Struct Reference
foedus::storage::array::ArrayRange Struct Reference
FOEDUS Components » Storage Manager » Array Storage
Represents an offset range in an array storage.
Detailed Description
Represents an offset range in an array storage.
Begin is inclusive, end is exclusive.
Definition at line 62 of file array_id.hpp.
#include <array_id.hpp>
Public Member Functions
ArrayRange ()
ArrayRange (ArrayOffset begin, ArrayOffset end)
ArrayRange (ArrayOffset begin, ArrayOffset end, ArrayOffset array_size)
this one adjusts the case where end might be larger than the whole array size (right-most)
bool overlaps (const ArrayRange &other) const
Returns if there is any overlap with the other range.
bool contains (ArrayOffset offset) const
bool operator== (const ArrayRange &other) const
bool operator!= (const ArrayRange &other) const
Public Attributes
ArrayOffset begin_
Inclusive beginning of the offset range.
ArrayOffset end_
Exclusive end of the offset range.
Constructor & Destructor Documentation
foedus::storage::array::ArrayRange::ArrayRange () inline
Definition at line 63 of file array_id.hpp.
 : begin_(0), end_(0) {}
foedus::storage::array::ArrayRange::ArrayRange (ArrayOffset begin, ArrayOffset end) inline
Definition at line 64 of file array_id.hpp.
 : begin_(begin), end_(end) {}
foedus::storage::array::ArrayRange::ArrayRange (ArrayOffset begin, ArrayOffset end, ArrayOffset array_size) inline
this one adjusts the case where end might be larger than the whole array size (right-most)
Definition at line 66 of file array_id.hpp.
References end_.
     : begin_(begin), end_(end) {
     if (end > array_size) {
       end_ = array_size;
     }
   }
Member Function Documentation
bool foedus::storage::array::ArrayRange::contains (ArrayOffset offset) const inline
Definition at line 79 of file array_id.hpp.
References begin_, and end_.
Referenced by foedus::storage::array::ArrayComposeContext::execute(), foedus::storage::array::ArrayStoragePimpl::locate_record_for_read(), foedus::storage::array::ArrayStoragePimpl::locate_record_for_write(), foedus::storage::array::ArrayStoragePimpl::lookup_for_read(), foedus::storage::array::ArrayStoragePimpl::lookup_for_write(), and overlaps().
 { return offset >= begin_ && offset < end_; }
bool foedus::storage::array::ArrayRange::operator!= (const ArrayRange & other) const inline
Definition at line 83 of file array_id.hpp.
References operator==().
 { return !(this->operator==(other)); }
bool foedus::storage::array::ArrayRange::operator== (const ArrayRange & other) const inline
Definition at line 80 of file array_id.hpp.
References begin_, and end_.
Referenced by operator!=().
{
     return begin_ == other.begin_ && end_ == other.end_;
   }
bool foedus::storage::array::ArrayRange::overlaps (const ArrayRange & other) const inline
Returns if there is any overlap with the other range.
Definition at line 74 of file array_id.hpp.
References begin_, contains(), and end_.
Referenced by foedus::storage::array::ArrayStoragePimpl::prefetch_pages_recurse().
{
     // Case 1: contains(other.begin) or contains(other.end)
     // Case 2: not case 1, but other.contains(begin)
     return contains(other.begin_) || contains(other.end_) || other.contains(begin_);
   }
Member Data Documentation
ArrayOffset foedus::storage::array::ArrayRange::begin_
Inclusive beginning of the offset range.
Definition at line 86 of file array_id.hpp.
Referenced by foedus::storage::array::array_volatile_page_init(), foedus::storage::array::LookupRoute::calculate_page_range(), contains(), foedus::storage::array::ArrayComposeContext::execute(), foedus::storage::array::ArrayStoragePimpl::lookup_for_read(), foedus::storage::array::ArrayStoragePimpl::lookup_for_write(), operator==(), overlaps(), and foedus::storage::array::ArrayStoragePimpl::prefetch_pages_recurse().
ArrayOffset foedus::storage::array::ArrayRange::end_
Exclusive end of the offset range.
Definition at line 88 of file array_id.hpp.
Referenced by foedus::storage::array::array_volatile_page_init(), ArrayRange(), foedus::storage::array::LookupRoute::calculate_page_range(), contains(), foedus::storage::array::ArrayComposeContext::execute(), operator==(), overlaps(), and foedus::storage::array::ArrayStoragePimpl::prefetch_pages_recurse().
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/storage/array/array_id.hpp