libfoedus-core: foedus::snapshot::LogBuffer Struct Reference
foedus::snapshot::LogBuffer Struct Reference
FOEDUS Components » Snapshot Manager
Packages handling of 4-bytes representation of position in log buffers.
Detailed Description
Packages handling of 4-bytes representation of position in log buffers.
Definition at line 38 of file log_buffer.hpp.
#include <log_buffer.hpp>
Public Member Functions
LogBuffer (char *base_address)
log::RecordLogType * resolve (BufferPosition position) const
BufferPosition compact (const log::RecordLogType *address) const
Public Attributes
char *const base_address_
Constructor & Destructor Documentation
foedus::snapshot::LogBuffer::LogBuffer (char * base_address) inline explicit
Definition at line 39 of file log_buffer.hpp.
 : base_address_(base_address) {}
Member Function Documentation
BufferPosition foedus::snapshot::LogBuffer::compact (const log::RecordLogType * address) const inline
Definition at line 46 of file log_buffer.hpp.
References foedus::snapshot::to_buffer_position().
{
     return to_buffer_position(reinterpret_cast<const char*>(address) - base_address_);
   }
log::RecordLogType* foedus::snapshot::LogBuffer::resolve (BufferPosition position) const inline
Definition at line 42 of file log_buffer.hpp.
References foedus::snapshot::from_buffer_position().
Referenced by foedus::storage::array::compact_logs(), foedus::storage::hash::HashPartitioner::partition_batch(), foedus::storage::array::ArrayPartitioner::partition_batch(), foedus::storage::array::prepare_sort_entries(), foedus::storage::hash::prepare_sort_entries(), foedus::storage::masstree::prepare_sort_entries(), and foedus::storage::masstree::resolve_log().
{
     return reinterpret_cast<log::RecordLogType*>(
       base_address_ + from_buffer_position(position));
   }
Member Data Documentation
char* const foedus::snapshot::LogBuffer::base_address_
Definition at line 40 of file log_buffer.hpp.
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/snapshot/log_buffer.hpp