libfoedus-core: foedus::storage::sequential::SequentialAppendLogType Struct Reference
foedus::storage::sequential::SequentialAppendLogType Struct Reference
FOEDUS Components » Storage Manager » Array StorageFOEDUS Components » Log Manager » | Log Types
Log type of sequential-storage's append operation.
Detailed Description
Log type of sequential-storage's append operation.
This is the only record-level operation in sequential storage. It simply appends the the end with an atomic operation.
Definition at line 96 of file sequential_log_types.hpp.
#include <sequential_log_types.hpp>
Public Member Functions
SequentialAppendLogType ()=delete
SequentialAppendLogType (const SequentialAppendLogType &other)=delete
~SequentialAppendLogType ()=delete
void populate (StorageId storage_id, const void *payload, uint16_t payload_count) __attribute__((always_inline))
void apply_record (thread::Thread *context, StorageId storage_id, xct::RwLockableXctId *owner_id, char *payload) __attribute__((always_inline))
void assert_valid () __attribute__((always_inline))
Public Member Functions inherited from foedus::log::RecordLogType
bool is_engine_log () const
bool is_storage_log () const
bool is_record_log () const
void apply_engine (thread::Thread *)
void apply_storage (Engine *, storage::StorageId)
void assert_valid_generic () const __attribute__((always_inline))
Verifies the log contains essential fields set.
Static Public Member Functions
static uint16_t calculate_log_length (uint16_t payload_count) __attribute__((always_inline))
Public Attributes
uint16_t payload_count_
char payload_ [6]
Public Attributes inherited from foedus::log::BaseLogType
LogHeader header_
Friends
std::ostream & operator<< (std::ostream &o, const SequentialAppendLogType &v)
Constructor & Destructor Documentation
foedus::storage::sequential::SequentialAppendLogType::SequentialAppendLogType () delete
foedus::storage::sequential::SequentialAppendLogType::SequentialAppendLogType (const SequentialAppendLogType & other) delete
foedus::storage::sequential::SequentialAppendLogType::~SequentialAppendLogType () delete
Member Function Documentation
void foedus::storage::sequential::SequentialAppendLogType::apply_record (thread::Thread * context, StorageId storage_id, xct::RwLockableXctId * owner_id, char * payload) inline
Definition at line 116 of file sequential_log_types.hpp.
References foedus::storage::sequential::SequentialStorage::apply_append_record(), ASSERT_ND, CXX11_NULLPTR, foedus::Attachable< CONTROL_BLOCK >::get_engine(), foedus::storage::StorageManager::get_sequential(), and foedus::Engine::get_storage_manager().
{
     // It's a lock-free write set, so it doesn't have record info.
     ASSERT_ND(owner_id == CXX11_NULLPTR);
     ASSERT_ND(payload == CXX11_NULLPTR);
     SequentialStorage storage
       = context->get_engine()->get_storage_manager()->get_sequential(storage_id);
     storage.apply_append_record(context, this);
   }
void foedus::storage::sequential::SequentialAppendLogType::assert_valid () inline
Definition at line 129 of file sequential_log_types.hpp.
References ASSERT_ND, foedus::log::StorageLogType::assert_valid_generic(), foedus::log::LogHeader::get_type(), foedus::log::BaseLogType::header_, foedus::log::kLogCodeSequentialAppend, foedus::storage::sequential::kMaxPayload, and foedus::log::LogHeader::log_length_.
{
     assert_valid_generic();
     ASSERT_ND(header_.log_length_ == calculate_log_length(payload_count_));
     ASSERT_ND(payload_count_ < kMaxPayload);
     ASSERT_ND(header_.get_type() == log::kLogCodeSequentialAppend);
   }
static uint16_t foedus::storage::sequential::SequentialAppendLogType::calculate_log_length (uint16_t payload_count) inline static
Definition at line 101 of file sequential_log_types.hpp.
References foedus::assorted::align8().
Referenced by foedus::storage::sequential::SequentialStorage::append_record().
{
     // we pad to 8 bytes so that we always have a room for FillerLogType to align.
     return assorted::align8(18 + payload_count);
   }
void foedus::storage::sequential::SequentialAppendLogType::populate (StorageId storage_id, const void * payload, uint16_t payload_count) inline
Definition at line 106 of file sequential_log_types.hpp.
References foedus::log::BaseLogType::header_, foedus::log::kLogCodeSequentialAppend, foedus::log::LogHeader::log_length_, foedus::log::LogHeader::log_type_code_, and foedus::log::LogHeader::storage_id_.
Referenced by foedus::storage::sequential::SequentialStorage::append_record().
{
     header_.log_type_code_ = log::kLogCodeSequentialAppend;
     header_.log_length_ = calculate_log_length(payload_count);
     header_.storage_id_ = storage_id;
     payload_count_ = payload_count;
     std::memcpy(payload_, payload, payload_count);
   }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & o, const SequentialAppendLogType & v) friend
Definition at line 69 of file sequential_log_types.cpp.
{
   o << "<SequentialAppendLog>"
     << "<payload_count_>" << v.payload_count_ << "</payload_count_>";
   // show first few bytes
   o << "<data_>";
   for (uint16_t i = 0; i < std::min<uint16_t>(8, v.payload_count_); ++i) {
     o << i << ":" << static_cast<int>(v.payload_[i]) << " ";
   }
   o << "...</data_>";
   o << "</SequentialAppendLog>";
   return o;
 }
Member Data Documentation
char foedus::storage::sequential::SequentialAppendLogType::payload_[6]
Definition at line 99 of file sequential_log_types.hpp.
Referenced by foedus::storage::sequential::SequentialStorage::apply_append_record(), foedus::storage::sequential::operator<<(), and foedus::storage::sequential::StreamStatus::read_entry().
uint16_t foedus::storage::sequential::SequentialAppendLogType::payload_count_
Definition at line 98 of file sequential_log_types.hpp.
Referenced by foedus::storage::sequential::SequentialStorage::apply_append_record(), foedus::storage::sequential::SequentialComposer::compose(), and foedus::storage::sequential::operator<<().
The documentation for this struct was generated from the following file:
/home/shino/foedus_code/foedus-core/include/foedus/storage/sequential/sequential_log_types.hpp